#!/bin/sh

[ "${ACTION}" = "pressed" ] || exit 0

echo "$BUTTON button pressed for $SEEN seconds" > /dev/console

#system will only shut down gracfully if the button was pressed more the 2 consecutive seconds
#and less then 10 consecutive seconds(pressing longer will triger a hardware ungracful shutdown)
#the upper bound condition in the script means to prevent an unwanted shutdown while loading up the driver,
#because in load time the driver gets a button release notification with a large number of secends as time pressed argument.
if [[ "$SEEN" -gt 1  &&  "$SEEN" -lt 11 ]]
then
		echo "powering off system...." > /dev/console
		exec /sbin/poweroff
fi

return 0
