#!/bin/sh /etc/rc.common
# Copyright (C) 2011-2015 OpenWrt.org
# Copyright (C) 2018 Hikaru (i@rua.moe)

START=95
STOP=10
SERVICE_DAEMONIZE=1

start(){
	killall -q -9 bxc-main bxc-worker bxc-network
	sleep 1
	service_start /usr/share/bxc/bin/bxc-main
}

stop(){
	/usr/share/bxc/bin/bxc-main -k &
	killall -q -9 bxc-main bxc-worker bxc-network
}

restart(){
	stop
	sleep 1
	start
}