#!/bin/sh

[ ! -f /usr/bin/ip ] && ln -sf /sbin/ip /usr/bin/ip
(opkg list-installed | grep ip-full >/dev/null 2>&1)  && ln -sf /usr/sbin/ip /usr/bin/ip

/etc/init.d/shadowsocksr stop
/etc/init.d/shadowsocksr disable

rm -f /tmp/luci-indexcache
exit 0
