#!/bin/sh /etc/rc.common

START=99
STOP=80

start() {
	local enable value
	enable=$(uci get cpufreq.@cpufreq[0].enabled)
	value=$(uci get cpufreq.@cpufreq[0].use)
	if [ $enable -eq 1 ]; then
		cpufreq-set -f ${value}MHz
	fi
}

