#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@bonuscloud[-1]
	add ucitrack bonuscloud
	set ucitrack.@bonuscloud[-1].init=bonuscloud
	commit ucitrack
EOF

general=$(uci -q get bonuscloud.@general[-1])
if [ -z "$general" ]; then
	uci -q add bonuscloud general
fi
if [ "$general"x != "general"x ]; then
	uci -q batch <<-EOF >/dev/null
		rename bonuscloud.@general[-1]="general"
		commit bonuscloud
	EOF
fi

rm -rf /tmp/luci-indexcache /tmp/luci-modulecache
exit 0