O 1 FW
G 1 1 GLOBAL_GID_802_11_PROTOCOL
G 1 2 GLOBAL_AGER_EMULATOR
G 1 3 GLOBAL_GID_AGGREGATION_BUILDER
G 1 4 GLOBAL_GID_TX_HW_ACCELERATORS
G 1 5 GLOBAL_GID_BA_ANALYZER
G 1 6 GLOBAL_GID_HW_DRIVERS
G 1 7 GLOBAL_GID_BEACON_HANDLER
G 1 8 GLOBAL_GID_BSS
G 1 9 GLOBAL_GID_BSS_MANAGER
G 1 10 GLOBAL_GID_CHANNEL_SWITCH_MANAGER
G 1 11 GLOBAL_GID_COC
G 1 12 GLOBAL_GID_CSA_MANAGER
G 1 13 GLOBAL_GID_CTS_MANAGER
G 1 14 GLOBAL_GID_DATABASE
G 1 15 GLOBAL_GID_SECURITY_DEBRA
G 1 16 GLOBAL_GID_DEBUG_ENVIRONMENT
G 1 17 GLOBAL_GID_DMA_MANAGER
G 1 18 GLOBAL_GID_DUT
G 1 19 GLOBAL_GID_ERROR_HANDLER
G 1 20 GLOBAL_GID_EVENTS_MANAGER
G 1 21 GID_MTIDLPARSER
G 1 22 GID_LOG
G 1 23 GLOBAL_GID_GIDM_MANAGER
G 1 24 GLOBAL_GID_GROUP_DB
G 1 25 GLOBAL_GID_GROUP_MANAGER
G 1 26 GLOBAL_GID_HDK_CALIBRATIONS_1
G 1 27 GLOBAL_GID_CALIBRATIONS
G 1 28 GLOBAL_GID_HDK_MODULE
G 1 29 GLOBAL_GID_HDK_MODULE_1
G 1 30 GLOBAL_GID_GENRISCS_INTERFACE
G 1 31 GLOBAL_GID_HOST_IF
G 1 32 GLOBAL_GID_PAC
G 1 33 GLOBAL_GID_PAC_1
G 1 34 GLOBAL_GID_RX_QUEUES
G 1 35 GLOBAL_GID_TX_SELECTOR
G 1 36 GLOBAL_GID_UTILS
G 1 37 GLOBAL_GID_INTERFERER_DETECTION
G 1 38 GLOBAL_GID_SYS
G 1 39 GLOBAL_GID_IPC
G 1 40 GLOBAL_GID_KERNEL
G 1 41 GLOBAL_GID_LINK_ADAPTATION
G 1 42 GLOBAL_GID_LOCKER
G 1 43 GLOBAL_GID_LOGGER
G 1 44 GLOBAL_GID_LOWER_MAC
G 1 45 GLOBAL_GID_QUEUE_MGMT
G 1 46 GLOBAL_GID_LOWER_MAC_IF
G 1 47 GLOBAL_GID_MEMORY_MGMT
G 1 48 GLOBAL_GID_NDPA_MANAGER
G 1 49 GLOBAL_GID_PAC_MANAGER
G 1 50 GLOBAL_GID_PAUSER
G 1 51 GLOBAL_GID_PERIPHERALS
G 1 52 GLOBAL_GID_SECURITY
G 1 53 GLOBAL_GID_PROCESS_MANAGER
G 1 54 GLOBAL_GID_PROTECTED_DB_LOCK
G 1 55 GLOBAL_GID_PS_MANAGER
G 1 56 GLOBAL_GID_QOS
G 1 57 GLOBAL_GID_QS_MANAGER
G 1 58 GLOBAL_GID_REG_ACCESS
G 1 59 GLOBAL_GID_WAVE500
G 1 60 GLOBAL_GID_RX_CLASSIFIER
G 1 61 GLOBAL_GID_RX_DATA_PATH
G 1 62 GLOBAL_GID_RX_HANDLER
G 1 63 GLOBAL_GID_RX_LIBERATOR
G 1 64 GLOBAL_GID_RX_MANAGER
G 1 65 GLOBAL_GID_RX_POST_PROCESSING
G 1 66 GLOBAL_GID_RX_HW_ACCLERATORS
G 1 67 GLOBAL_GID_RSN
G 1 68 GLOBAL_GID_SENDER
G 1 69 GLOBAL_GID_SERVICES_HANDLER
G 1 70 GLOBAL_GID_SHARED_RAM
G 1 71 GLOBAL_GID_SMPS_MANAGER
G 1 72 GLOBAL_GID_STATION_DB
G 1 73 GID_STATISTICS_MANAGER
G 1 74 GLOBAL_GID_TX_APP
G 1 75 GLOBAL_GID_TINY_KERNEL
G 1 76 GID_TRAINING_MANAGER
G 1 77 GLOBAL_GID_TS_MANAGER
G 1 78 GLOBAL_GID_TX_DATA_PATH
G 1 79 GLOBAL_GID_TX_HANDLER
G 1 80 GLOBAL_GID_TX_MANAGER
G 1 81 GLOBAL_GID_TX
G 1 82 GLOBAL_GID_TX_SEQUENCER
G 1 83 GLOBAL_GID_UPPER_MAC_INTERFACE
G 1 84 GLOBAL_GID_CALENDAR_WHEEL
G 1 85 GLOBAL_GID_VAP_DB
S 1 1 1 117 Assert in file: "ieee_address.c" in line: 117
S 1 1 1 141 Assert in file: "ieee_address.c" in line: 141
S 1 1 1 166 Assert in file: "ieee_address.c" in line: 166
S 1 1 2 169 Assert in file: "Protocol_AirTimeAndDuration.c" in line: 169
S 1 1 2 198 Assert in file: "Protocol_AirTimeAndDuration.c" in line: 198
S 1 1 2 226 Assert in file: "Protocol_AirTimeAndDuration.c" in line: 226
S 1 1 2 255 Assert in file: "Protocol_AirTimeAndDuration.c" in line: 255
S 1 1 2 283 Assert in file: "Protocol_AirTimeAndDuration.c" in line: 283
S 1 1 2 310 Assert in file: "Protocol_AirTimeAndDuration.c" in line: 310
S 1 1 2 338 Assert in file: "Protocol_AirTimeAndDuration.c" in line: 338
S 1 2 1 200 Assert in file: "AgerEmulator.c" in line: 200
S 1 2 1 240 Assert in file: "AgerEmulator.c" in line: 240
S 1 2 1 276 Assert in file: "AgerEmulator.c" in line: 276
S 1 2 1 310 Assert in file: "AgerEmulator.c" in line: 310
S 1 2 1 312 Assert in file: "AgerEmulator.c" in line: 312
S 1 2 1 723 agerEmulatorHandlePeriodicTimer >>> Not performing check
S 1 2 1 1120 agerEmulatorSendConfirmToStationManager, Client %d, stationIndex %d
S 1 2 1 1788 agerEmulatorProcessQueue BAR TtlCount = %d , , retransmission = %d
S 1 2 1 1845 agerEmulatorProcessQueue MANAGEMENT  TtlCount = %d 
S 1 2 1 1880 agerEmulatorProcessQueue RETRANSMIT PDs 
S 1 2 1 1897 agerEmulatorProcessQueue RETRANSMIT PDs current = %x, amsdu tail = %x , ttlCount = %d , numberOfPdsInAmsdu %d 
S 1 2 1 1900 agerEmulatorProcessQueue RETRANSMIT DISCARD umacListHead = %x, umacListTail = %x 
S 1 2 1 1930 agerEmulatorProcessQueue RETRANSMIT NOT DISCARD locationInArray = %d, locationInBitmap = %d, locationInWord = %d 
S 1 2 1 1942 agerEmulatorProcessQueue NOT RETRANSMIT PDs TtlCount = %d
S 1 2 1 1959 agerEmulatorProcessQueue NOT RETRANSMIT DISCARD liberatorListHead = %x, liberatorListTail = %x
S 1 2 1 1990 agerEmulatorProcessQueue pHeadDesc = %x , pTailDesc = %x , numberOfDiscardedPds = %d 
S 1 2 1 2027 agerEmulatorProcessQueue AGER_EMULATOR_FIRST_PART_OF_BITMAP pdIndex = %d , currentPacketDescriptor = %x , amsduTail = %x , notDiscardedListHead = %x, notDiscardedListTail = %x
S 1 2 1 2055 agerEmulatorProcessQueue AGER_EMULATOR_FIRST_PART_OF_BITMAP pdIndex = %d , currentPacketDescriptor = %x , amsduTail = %x , notDiscardedListHead = %x, notDiscardedListTail = %x
S 1 2 1 2064 agerEmulatorProcessQueue NOT DISCARDED LIST notDiscardedListHead = %x, notDiscardedListTail = %x
S 1 2 1 2077 agerEmulatorProcessQueue LIBERATOR LIST liberatorListHead = %x, liberatorListTail = %x
S 1 2 1 2086 agerEmulatorProcessQueue UMAC LIST umacListHead = %x, umacListTail = %x
S 1 3 0 453 Assert in file: "AggregationBuilder.c" in line: 453
S 1 3 0 484 Assert in file: "AggregationBuilder.c" in line: 484
S 1 3 0 605 Assert in file: "AggregationBuilder.c" in line: 605
S 1 3 0 621 Assert in file: "AggregationBuilder.c" in line: 621
S 1 3 0 778 Assert in file: "AggregationBuilder.c" in line: 778
S 1 3 0 783 Assert in file: "AggregationBuilder.c" in line: 783
S 1 3 0 940 Assert in file: "AggregationBuilder.c" in line: 940
S 1 5 0 187 Assert in file: "BaAnalyzer.c" in line: 187
S 1 5 0 276 Assert in file: "BaAnalyzer.c" in line: 276
S 1 5 0 277 Assert in file: "BaAnalyzer.c" in line: 277
S 1 5 0 293 Fatal Error in file: "BaAnalyzer.c"; Fatal Print: baAnalyzerIllegalStdStatus
S 1 5 0 365 Assert in file: "BaAnalyzer.c" in line: 365
S 1 5 0 758 Assert in file: "BaAnalyzer.c" in line: 758
S 1 5 0 948 Assert in file: "BaAnalyzer.c" in line: 948
S 1 5 0 959 Assert in file: "BaAnalyzer.c" in line: 959
S 1 5 0 976 Assert in file: "BaAnalyzer.c" in line: 976
S 1 5 0 993 Assert in file: "BaAnalyzer.c" in line: 993
S 1 5 0 999 Assert in file: "BaAnalyzer.c" in line: 999
S 1 6 1 309 Assert in file: "BaAnalyzer.c" in line: 309
S 1 7 0 642 Assert in file: "BeaconHandler.c" in line: 642
S 1 7 0 668 Assert in file: "BeaconHandler.c" in line: 668
S 1 7 0 694 Assert in file: "BeaconHandler.c" in line: 694
S 1 7 0 722 beaconHandlerSendTemplateWasSetIndication for vap:%d
S 1 7 0 925 Assert in file: "BeaconHandler.c" in line: 925
S 1 7 0 926 Assert in file: "BeaconHandler.c" in line: 926
S 1 7 0 965 Assert in file: "BeaconHandler.c" in line: 965
S 1 7 0 977 Assert in file: "BeaconHandler.c" in line: 977
S 1 7 0 1046 Assert in file: "BeaconHandler.c" in line: 1046
S 1 7 0 1410 Assert in file: "BeaconHandler.c" in line: 1410
S 1 7 0 1590 Assert in file: "BeaconHandler.c" in line: 1590
S 1 7 0 1744 Assert in file: "BeaconHandler.c" in line: 1744
S 1 7 0 1823 Assert in file: "BeaconHandler.c" in line: 1823
S 1 7 0 1921 Assert in file: "BeaconHandler.c" in line: 1921
S 1 7 0 1999 Assert in file: "BeaconHandler.c" in line: 1999
S 1 7 0 2058 Assert in file: "BeaconHandler.c" in line: 2058
S 1 7 0 2246 Assert in file: "BeaconHandler.c" in line: 2246
S 1 7 0 2537 Assert in file: "BeaconHandler.c" in line: 2537
S 1 7 0 2581 Assert in file: "BeaconHandler.c" in line: 2581
S 1 7 0 2667 Assert in file: "BeaconHandler.c" in line: 2667
S 1 7 0 2710 Assert in file: "BeaconHandler.c" in line: 2710
S 1 7 0 2751 Assert in file: "BeaconHandler.c" in line: 2751
S 1 7 0 2977 Assert in file: "BeaconHandler.c" in line: 2977
S 1 7 0 3000 Assert in file: "BeaconHandler.c" in line: 3000
S 1 7 0 3023 Assert in file: "BeaconHandler.c" in line: 3023
S 1 7 0 3046 Assert in file: "BeaconHandler.c" in line: 3046
S 1 7 3 185 beaconHandlerDeactivateHw for vap:%d
S 1 7 3 217 beaconHandlerSendTemplateWasSetIndication for vap:%d
S 1 7 3 294 beaconHandlerUpdateIEsPdList for vap:%d
S 1 7 3 583 beaconHandlerUpdateIEsPdList Vap Id:%d is active so calling Locker
S 1 7 3 591 beaconHandlerUpdateIEsPdList Vap Id:%d is inactive sending template was set indication
S 1 7 3 625 BeaconHandler_AddVap for vap:%d
S 1 7 3 720 beaconHandlerDeactivateBeacon for vap:%d
S 1 7 3 919 Assert in file: "BeaconHandler.c" in line: 919
S 1 7 3 924 Assert in file: "BeaconHandler.c" in line: 924
S 1 7 3 929 Assert in file: "BeaconHandler.c" in line: 929
S 1 7 3 934 Assert in file: "BeaconHandler.c" in line: 934
S 1 7 3 1065 Assert in file: "BeaconHandler.c" in line: 1065
S 1 7 5 172 Beacon CSA Manager changed from %d to %d
S 1 7 5 312 Assert in file: "Beacon_CsaManager.c" in line: 312
S 1 7 5 394 Assert in file: "Beacon_CsaManager.c" in line: 394
S 1 7 5 654 Fatal Error in file: "Beacon_CsaManager.c"; Fatal Print: Beacon CSA Manager Fatal
S 1 7 5 686 Assert in file: "Beacon_CsaManager.c" in line: 686
S 1 7 5 717 Assert in file: "Beacon_CsaManager.c" in line: 717
S 1 8 0 225 vBSS_Initialize, send PAC_MANAGER_START_REQ
S 1 9 0 221 BssManager_StartActivateProcess
S 1 9 0 223 Assert in file: "BSSmanager.c" in line: 223
S 1 9 0 256 Assert in file: "BSSmanager.c" in line: 256
S 1 9 0 383 Assert in file: "BSSmanager.c" in line: 383
S 1 9 0 424 Assert in file: "BSSmanager.c" in line: 424
S 1 9 1 530 BSS Manager STA Manager, Station %d changed from %d to %d
S 1 9 1 567 Assert in file: "BssManager_StaManager.c" in line: 567
S 1 9 1 569 Assert in file: "BssManager_StaManager.c" in line: 569
S 1 9 1 571 Assert in file: "BssManager_StaManager.c" in line: 571
S 1 9 1 572 BSS MNG, STA MNG, Dispatch Reg %d, SID %d, num %d
S 1 9 1 587 BSS MNG, STA MNG, Dispatch Client %d, MsgId %d, TaskId %x
S 1 9 1 625 BSS MNG, STA MNG, Check Dispatcher, SID %d, state %d
S 1 9 1 628 Assert in file: "BssManager_StaManager.c" in line: 628
S 1 9 1 631 Assert in file: "BssManager_StaManager.c" in line: 631
S 1 9 1 634 Assert in file: "BssManager_StaManager.c" in line: 634
S 1 9 1 637 Assert in file: "BssManager_StaManager.c" in line: 637
S 1 9 1 707 BSS MNG, STA MNG, STA Open Done, SID %d
S 1 9 1 749 BSS MNG, STA MNG, Set Filter Done, SID %d
S 1 9 1 791 BSS MNG, STA MNG, Stop Traffic Done, SID %d
S 1 9 1 834 BSS MNG, STA MNG, STA Close Done, SID %d
S 1 9 1 868 BSS MNG, STA MNG, Check Confirm, SID %d, pending %d
S 1 9 1 878 Assert in file: "BssManager_StaManager.c" in line: 878
S 1 9 1 959 Fatal Error in file: "BssManager_StaManager.c"; Fatal Print: BSS Manager STA Manager Fatal
S 1 9 1 998 Assert in file: "BssManager_StaManager.c" in line: 998
S 1 9 1 1002 BSS MNG, STA MNG, Reg Confirm, SID %d, Client %d
S 1 9 1 1037 Assert in file: "BssManager_StaManager.c" in line: 1037
S 1 9 1 1040 Assert in file: "BssManager_StaManager.c" in line: 1040
S 1 9 1 1048 BSS MNG, STA MNG, ADD STA, SID %d
S 1 9 1 1085 Assert in file: "BssManager_StaManager.c" in line: 1085
S 1 9 1 1089 BSS MNG, STA MNG, Set Filter, SID %d
S 1 9 1 1126 Assert in file: "BssManager_StaManager.c" in line: 1126
S 1 9 1 1130 BSS MNG, STA MNG, Stop Traffic, SID %d
S 1 9 1 1167 Assert in file: "BssManager_StaManager.c" in line: 1167
S 1 9 1 1171 BSS MNG, STA MNG, Close STA, SID %d
S 1 9 2 175 BssManager_VapManager_SetState, vapId:%d, vapManagerNewState:%d
S 1 9 2 205 Assert in file: "BSSmanager_VapManager.c" in line: 205
S 1 9 2 207 BssManager_VapManager_AddVap of vapId:%d
S 1 9 2 266 BssManager_VapManager_StartAddVaptProcess of vapId:%d
S 1 9 2 315 Assert in file: "BSSmanager_VapManager.c" in line: 315
S 1 9 2 322 Assert in file: "BSSmanager_VapManager.c" in line: 322
S 1 9 2 357 Assert in file: "BSSmanager_VapManager.c" in line: 357
S 1 9 2 409 BssManager_VapManager_StartSetBssProcess of vapId:%d
S 1 9 2 419 Assert in file: "BSSmanager_VapManager.c" in line: 419
S 1 9 2 464 Assert in file: "BSSmanager_VapManager.c" in line: 464
S 1 9 2 473 Assert in file: "BSSmanager_VapManager.c" in line: 473
S 1 9 2 547 BssManager_VapManager_StartSetWmmParamsProcess of vapId:%d
S 1 9 2 561 Assert in file: "BSSmanager_VapManager.c" in line: 561
S 1 9 2 596 Assert in file: "BSSmanager_VapManager.c" in line: 596
S 1 9 2 601 BssManager_VapManager_FinalizeSetWmmParamsProcess of vapId:%d
S 1 9 2 700 BssManager_VapManager_StartRemoveVapProcess, vapId:%d
S 1 9 2 746 Assert in file: "BSSmanager_VapManager.c" in line: 746
S 1 9 2 751 BssManager_VapManager_FinalizeRemoveVapProcess of vapId:%d
S 1 9 2 756 Assert in file: "BSSmanager_VapManager.c" in line: 756
S 1 9 2 792 Assert in file: "BSSmanager_VapManager.c" in line: 792
S 1 9 2 835 Assert in file: "BSSmanager_VapManager.c" in line: 835
S 1 9 2 836 Assert in file: "BSSmanager_VapManager.c" in line: 836
S 1 9 2 872 BssManager_VapManager_EventHandlerConfirm, got cfm from taskID:%d
S 1 9 2 874 Assert in file: "BSSmanager_VapManager.c" in line: 874
S 1 9 2 875 Assert in file: "BSSmanager_VapManager.c" in line: 875
S 1 9 2 1100 Assert in file: "BSSmanager_VapManager.c" in line: 1100
S 1 9 2 1167 Assert in file: "BSSmanager_VapManager.c" in line: 1167
S 1 9 2 1173 Assert in file: "BSSmanager_VapManager.c" in line: 1173
S 1 9 2 1179 Assert in file: "BSSmanager_VapManager.c" in line: 1179
S 1 9 2 1185 Assert in file: "BSSmanager_VapManager.c" in line: 1185
S 1 9 2 1200 Assert in file: "BSSmanager_VapManager.c" in line: 1200
S 1 9 2 1206 Assert in file: "BSSmanager_VapManager.c" in line: 1206
S 1 9 2 1212 Assert in file: "BSSmanager_VapManager.c" in line: 1212
S 1 9 2 1214 Assert in file: "BSSmanager_VapManager.c" in line: 1214
S 1 9 2 1219 Assert in file: "BSSmanager_VapManager.c" in line: 1219
S 1 9 2 1225 Assert in file: "BSSmanager_VapManager.c" in line: 1225
S 1 9 2 1230 Assert in file: "BSSmanager_VapManager.c" in line: 1230
S 1 10 0 169 Assert in file: "ChannelSwitchManager.c" in line: 169
S 1 10 0 176 [channelSwitchManager_SetChannelRequest] CHANNEL_SWITCH_MANAGER_STATE_IDLE, channelSwitchManagerParams.pUmSetChannelParams->switch_type=%d
S 1 10 0 203 [channelSwitchManager_SetChannelRequest] in RSSI 0
S 1 10 0 234 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: illegal switch type
S 1 10 0 240 [channelSwitchManager_SetChannelRequest] in RSSI 1
S 1 10 0 304 Assert in file: "ChannelSwitchManager.c" in line: 304
S 1 10 0 317 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Channel Switch Manager: illegal type in current state
S 1 10 0 322 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Channel Switch Manager: illegal event in current state
S 1 10 0 354 [channelSwitchManager_ProcessStartConfirm] channelSwitchManagerParams.state = %d, channelSwitchManagerParams.pUmSetChannelParams->switch_type = %d
S 1 10 0 356 Assert in file: "ChannelSwitchManager.c" in line: 356
S 1 10 0 383 [channelSwitchManager_ProcessStartConfirm] send message to HDK
S 1 10 0 422 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: illegal switch type
S 1 10 0 426 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Channel Switch Manager: illegal event in current state
S 1 10 0 457 state: %d, event: Tx Queue Lock Confirm
S 1 10 0 529 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Channel Switch Manager: illegal event in current state
S 1 10 0 555 [channelSwitchManager_ProcessFinishConfirm] channelSwitchManagerParams.state = %d
S 1 10 0 568 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Channel Switch Manager: illegal event in current state
S 1 10 0 608 [channelSwitchManager_SetChannelConfirm] channelSwitchManagerParams.state = %d
S 1 10 0 617 [channelSwitchManager_SetChannelConfirm] CHANNEL_SWITCH_MANAGER_STATE_WAIT_FOR_SET_CHANNEL_CFM_FROM_HDK, channelSwitchManagerParams.pUmSetChannelParams->switch_type = %d
S 1 10 0 645 [channelSwitchManager_SetChannelConfirm] in ST_NORMAL_AFTER_RSSI
S 1 10 0 649 [channelSwitchManager_SetChannelConfirm] in ST_NORMAL_AFTER_RSSI, before Process Manager Resume all
S 1 10 0 662 [channelSwitchManager_SetChannelConfirm], pUmSetChannelParamsLocal->u16SID = %d
S 1 10 0 663 [channelSwitchManager_SetChannelConfirm] in ST_RSSI
S 1 10 0 716 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: illegal switch type
S 1 10 0 722 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Channel Switch Manager: illegal event in current state
S 1 10 0 749 state: %d, event: Tx Resume Confirm
S 1 10 0 768 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Channel Switch Manager: illegal event in current state
S 1 10 0 794 state: %d, event: Rx Resume Confirm
S 1 10 0 806 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Channel Switch Manager: illegal event in current state
S 1 10 0 833 state: %d, event: Tx Pause Confirm
S 1 10 0 866 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Channel Switch Manager: illegal event in current state
S 1 10 0 894 state: %d, event: TX Pause VAP Confirm
S 1 10 0 960 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Channel Switch Manager: illegal event in current state
S 1 10 0 986 state: %d, event: Rx Pause Confirm
S 1 10 0 1008 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Channel Switch Manager: illegal event in current state
S 1 10 0 1036 state: %d, event: Timer Expired
S 1 10 0 1067 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Channel Switch Manager: illegal event in current state
S 1 10 0 1096 state: %d, event: Beacon Add Csa Ie Confirm
S 1 10 0 1124 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Channel Switch Manager: illegal event in current state
S 1 10 0 1154 state: %d, event: CSA Beacon Done Indication
S 1 10 0 1212 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Channel Switch Manager: illegal event in current state
S 1 10 0 1241 state: %d, event: Stop CSA Beacons Confirm
S 1 10 0 1280 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Channel Switch Manager: illegal event in current state
S 1 10 0 1392 channelSwitchManager_VapManagerRegistrationEventAddVap, state: %d, event: Vap Manager Registration Event Add Vap
S 1 10 0 1394 Assert in file: "ChannelSwitchManager.c" in line: 1394
S 1 10 0 1432 state: %d, event: Vap Manager Registration Event Post Remove Vap
S 1 10 0 1434 Assert in file: "ChannelSwitchManager.c" in line: 1434
S 1 10 0 1472 state: %d, event: Csa Manager Start Tx Cfm
S 1 10 0 1533 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: channelSwitchManager_ProcessInterruptedIndication
S 1 10 0 1561 state: %d, event: Csa Manager Stop Tx Cfm
S 1 10 0 1640 [channelSwitchManager_SendConfirmationToHost] channelSwitchManagerParams.pUmSetChannelParams->rssi[%d] = %d
S 1 10 0 1647 [channelSwitchManager_SendConfirmationToHost] --------------------------end]
S 1 10 0 1686 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Utils_GetPrimaryChannel: 80+80 not supported
S 1 10 0 1689 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Utils_GetPrimaryChannel: Illegal rate
S 1 10 0 1737 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Utils_GetSecondayChannelOffset: 80+80 not supported
S 1 10 0 1740 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Utils_GetSecondayChannelOffset: Illegal rate
S 1 10 0 1780 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: ChannelSwitchManager_GetChannelWidth: not supported
S 1 10 0 1783 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: ChannelSwitchManager_GetChannelWidth: not supported
S 1 10 0 1786 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: ChannelSwitchManager_GetChannelWidth: Illegal channel width
S 1 10 0 1829 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: ChannelSwitchManager_GetCenterFreq0Idx: not supported
S 1 10 0 1832 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: ChannelSwitchManager_GetCenterFreq0Idx: not supported
S 1 10 0 1835 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: ChannelSwitchManager_GetCenterFreq0Idx: Illegal channel width
S 1 11 0 120 Assert in file: "CoC.c" in line: 120
S 1 11 0 121 Assert in file: "CoC.c" in line: 121
S 1 11 0 168 Assert in file: "CoC.c" in line: 168
S 1 11 0 169 Assert in file: "CoC.c" in line: 169
S 1 11 0 216 Assert in file: "CoC.c" in line: 216
S 1 11 0 217 Assert in file: "CoC.c" in line: 217
S 1 11 0 276 Assert in file: "CoC.c" in line: 276
S 1 11 0 354 Assert in file: "CoC.c" in line: 354
S 1 11 0 382 Assert in file: "CoC.c" in line: 382
S 1 11 0 416 Assert in file: "CoC.c" in line: 416
S 1 12 0 177 CSA Manager changed from %d to %d
S 1 12 0 428 Assert in file: "csaManager.c" in line: 428
S 1 12 0 612 Fatal Error in file: "csaManager.c"; Fatal Print: CSA Manager Fatal
S 1 12 1 341 CSA Manager STA Manager, STA %d changed from %d to %d
S 1 12 1 1742 Fatal Error in file: "CsaManager_StaManager.c"; Fatal Print: Csa Manager STA Manager Fatal
S 1 12 1 1779 Assert in file: "CsaManager_StaManager.c" in line: 1779
S 1 12 1 1817 Assert in file: "CsaManager_StaManager.c" in line: 1817
S 1 12 2 267 CSA Manager VAP Manager, VAP %d changed from %d to %d
S 1 12 2 1245 Assert in file: "CsaManager_VapManager.c" in line: 1245
S 1 12 2 1641 Fatal Error in file: "CsaManager_VapManager.c"; Fatal Print: CSA Manager VAP Manager Fatal
S 1 13 0 216 CTS Manager changed from %d to %d
S 1 13 0 747 Fatal Error in file: "CtsManager.c"; Fatal Print: CTS Manager Fatal
S 1 13 0 793 Assert in file: "CtsManager.c" in line: 793
S 1 14 0 142 Assert in file: "mib.c" in line: 142
S 1 14 0 200 Assert in file: "mib.c" in line: 200
S 1 14 0 436 u16MIB_PutValue: u16ID=%d 
S 1 14 0 480 Assert in file: "mib.c" in line: 480
S 1 15 0 269 Assert in file: "Debra.c" in line: 269
S 1 16 2 147 Assert in file: "StatisticsPhyHandler.c" in line: 147
S 1 16 2 155 [PhyStatistics_MetricsFifoNotEmpty], rdType = %d
S 1 16 2 174 [PhyStatistics_MetricsFifoNotEmpty], stationId = %d, isAmpdu = %d, packetLength = %d
S 1 16 2 313 [PhyStatistics_GetPhyStatusReq]
S 1 16 2 329 Assert in file: "StatisticsPhyHandler.c" in line: 329
S 1 16 2 377 PhyStatistics_ChannelLoadTimerExpired, phyStatisticDb.totalChannelLoadBssLoad:%d, currentTime:%d, phyStatisticDb.channelLoadMesStartTimeBssLoad:%d, channelUtilization:%d
S 1 16 2 522 [PhyStatistics_ChannelSwitchDone]
S 1 16 4 135 RX TH - WriteRxTh2Phy THval: %d
S 1 16 4 193 RX TH - SetRxThReq THval: %d
S 1 16 4 239 RX TH - WriteMinRssi2Phy regVal: %d minRssi: %d
S 1 16 4 291 RX TH - RxThRemoveSta staId: %d , rssiVal %d
S 1 16 4 294 Assert in file: "StatisticsHandler.c" in line: 294
S 1 16 4 363 RX TH - RxThUpdateRssi newRssi: %d oldRssi:%d
S 1 16 4 366 Assert in file: "StatisticsHandler.c" in line: 366
S 1 16 4 455 RX TH - RxThAddSta staId: %d rssiVal:%d
S 1 16 1 132 RX TH - WriteRxTh2Phy THval: %d
S 1 16 1 188 RX TH - SetRxThReq THval: %d
S 1 16 1 233 RX TH - WriteMinRssi2Phy regVal: %d minRssi: %d
S 1 16 1 283 RX TH - RxThRemoveSta staId: %d , rssiVal %d
S 1 16 1 286 Assert in file: "StatisticsHandler.c" in line: 286
S 1 16 1 354 RX TH - RxThUpdateRssi newRssi: %d oldRssi:%d
S 1 16 1 356 Assert in file: "StatisticsHandler.c" in line: 356
S 1 16 1 444 RX TH - RxThAddSta staId: %d rssiVal:%d
S 1 17 0 67 Assert in file: "DmaManager.c" in line: 67
S 1 17 0 69 Assert in file: "DmaManager.c" in line: 69
S 1 17 1 315 Assert in file: "DmaDriver.c" in line: 315
S 1 17 3 305 Assert in file: "DmaDriver.c" in line: 305
S 1 17 3 323 Assert in file: "DmaDriver.c" in line: 323
S 1 18 0 168 -------- DUT VAP ADDED --------
S 1 18 0 194 Assert in file: "Dut.c" in line: 194
S 1 18 0 200 -------- DUT VAP REMOVED--------
S 1 18 0 215 -------- DUT Dut_HandleSetFixedRateCfm--------
S 1 18 0 310 DUT_CfmToHost  DUT_CfmToHost  DUT_CfmToHost  DUT_CfmToHost
S 1 18 0 336 Dut_MsgCallBackFromProcess
S 1 18 0 412 Assert in file: "Dut.c" in line: 412
S 1 18 1 174 dutResetBb, calling PhyDrv_ResetBB()
S 1 18 1 185 dutStartBb, calling PhyDrv_ReActivateBB()
S 1 18 1 294 dutHwAccessSetDefaultAntenaSet, calling PhyDrv_SetRFMtype(MTLK_RF_MGMT_TYPE_OFF) 
S 1 18 1 361 dutHwAccessSetSpacelessTransmission, dutDB_p->spaceless:%d
S 1 18 1 404 DUT_SendModifyIfsParamsReq, spacing[usec]:%d
S 1 18 1 421 DUT_SendModifyIfsParamsReq
S 1 18 1 476 DUT_SetIfsValue, spacingUsec:%d, ifsn:%d, slotTimer:%d
S 1 18 1 570 Assert in file: "Dut_HwAccess.c" in line: 570
S 1 18 1 580 dutHwAccessGetTxPowerFeedbackReq, dutTxState NOT is DUT_TX_STATE_TRANSMITTING ! return to user
S 1 18 1 623 dutHwAccessGetRxGains, ant:%d, BBGain = %d
S 1 18 1 636 dutHwAccessGetRxGains, ant:%d, lnaActiveValue = %d %d
S 1 18 1 658 dutHwAccessGetRxGains, sysGain[%d] = 0x%x
S 1 18 1 670 dutHwAccessGetRxGains, backoffToDbmOffset = 0x%x
S 1 18 1 675 dutHwAccessGetRxGains, rxGains_p->antRxGains[%d].bbGain = 0x%x
S 1 18 1 768 Assert in file: "Dut_HwAccess.c" in line: 768
S 1 18 1 782 Assert in file: "Dut_HwAccess.c" in line: 782
S 1 18 1 806 Assert in file: "Dut_HwAccess.c" in line: 806
S 1 18 1 822 Assert in file: "Dut_HwAccess.c" in line: 822
S 1 18 1 851 Assert in file: "Dut_HwAccess.c" in line: 851
S 1 18 1 860 dutHwAccessReadTxPowerFeedBack, powerIndex:%x, validSamples:0x%x, txEnabledAntennas:0x%x, phyBw:%d
S 1 18 1 868 dutHwAccessReadTxPowerFeedBack, ant:%d, voltageMeasure:%d
S 1 18 1 877 voltageMeasure, voltageMeasure:%d , ant = %d
S 1 18 2 133 DUT API NOT SUPPORTED !!
S 1 18 2 334 Assert in file: "Dut_Managment.c" in line: 334
S 1 18 2 428 dutStartCalibration, abort request, calibration in process: %d
S 1 18 2 452 dutStartCalibration, start DUT_CALIBRATION_TYPE_ONLINE
S 1 18 2 461 dutStartCalibration, start DUT_CALIBRATION_TYPE_OFFLINE
S 1 18 2 466 Fatal Error in file: "Dut_Managment.c"; Fatal Print: DUT BROKEN
S 1 18 2 472 Assert in file: "Dut_Managment.c" in line: 472
S 1 18 2 494 Assert in file: "Dut_Managment.c" in line: 494
S 1 18 2 518 Assert in file: "Dut_Managment.c" in line: 518
S 1 18 2 539 DUT_HandleCalibDone, calibration type: %d ended
S 1 18 2 619 Assert in file: "Dut_Managment.c" in line: 619
S 1 18 2 755 Assert in file: "Dut_Managment.c" in line: 755
S 1 18 2 767 DUT_DebugDispatcher help: 1. get dutDB_t 2.Null 3. VapDB_GetRfPower 4. VapDb_GetVapDb(vapId) 5. TPC_getFixedPowerAndGain(ant, bw)
S 1 18 2 775 PhyCalDrv_GetDigitalGain, gain:%d
S 1 18 2 792 TPC_getPowerIndexValue, ant:%d, bw:%d, power:%d
S 1 18 2 796 Assert in file: "Dut_Managment.c" in line: 796
S 1 18 2 807 DUT_DebugDispatcher, dutAction: %d don't exists
S 1 18 3 159 Assert in file: "Dut_Tx.c" in line: 159
S 1 18 3 169 dutTxSetState, old state:%d, new state:%d
S 1 18 3 223 dutTxGetPowerVectorPerAnt, index:%d, measuredVoltagePerPower:%d
S 1 18 3 270 ----- dutTxStartTransmision ----
S 1 18 3 281 Error!, dutTxStartTransmision, isChannelSet:%d
S 1 18 3 292 dutTxStartTransmision, DUT_STATUS_TX_START_IS_ONGOING
S 1 18 3 296 dutTxStartTransmision, DUT_STATUS_TX_STOP_IS_ONGOING
S 1 18 3 300 Assert in file: "Dut_Tx.c" in line: 300
S 1 18 3 317 ----- dutTxStopTransmision ---- TxState = 0x%x
S 1 18 3 327 dutTxStopTransmision, packetsTransmitted:%d, packetsProcessed:%d
S 1 18 3 330 dutTxStopTransmision, DUT_STATUS_TX_ALREADY_STOPPED
S 1 18 3 334 dutTxStopTransmision, DUT_STATUS_TX_STOP_IS_ONGOING
S 1 18 3 338 Assert in file: "Dut_Tx.c" in line: 338
S 1 18 3 352 Assert in file: "Dut_Tx.c" in line: 352
S 1 18 3 406 dutTransmitPacketReq, dutDB_p->spaceless:%d
S 1 18 3 414 ---- dutTransmitPacketReq, no free desc
S 1 18 3 455 dutTransmitPacketReq, calling TxPacketsClassifier_SendManagementPacketFromFw, dutDB_p->m_DutTrafficParams.packetsProcessed:%d
S 1 18 3 482 Assert in file: "Dut_Tx.c" in line: 482
S 1 18 3 496 dutHandleCbInTransmittingState transmitPowerVector.numOfTransmitionPerPower[PVpowerToTransmitIndex]:%d
S 1 18 3 515 dutHandleCbInTransmittingState SET NEW POWER AND LENGTH
S 1 18 3 519 dutHandleCbInTransmittingState packetLength:%d
S 1 18 3 520 dutHandleCbInTransmittingState dutPowerAndPacketLength.txPower:%d
S 1 18 3 540 dutHandleCbInTransmittingState, calling TxPacketsClassifier_SendManagementPacketFromFw, m_DutTrafficParams_p->packetsProcessed:%d
S 1 18 3 557 dutHandleTxActionPublicFrameCb, DUT_TX_STATE_TRANSMITTING -> DUT_TX_STATE_IDLE, calling ResourceManager_ReleaseDescriptor
S 1 18 3 593 dutHandleTxActionPublicFrameCb, m_DutTrafficParams_p->trafficState:%d, m_DutTrafficParams_p->txPacketIsOngoing:%d, packetsTransmitted:%d
S 1 18 3 615 Assert in file: "Dut_Tx.c" in line: 615
S 1 19 0 236 vAPP_Assert assertGroupId=%d assertFileId=%d assertLine=%d
S 1 19 0 286 vAPP_Assert last PCs: Tx Sender 0x%04x, Rx Handler 0x%04x, Host I/F 0x%04x
S 1 19 0 653 Fatal Error in file: "ErrorHandler.c"; Fatal Print: Lower MAC Assertion
S 1 19 0 678 Assert in file: "ErrorHandler.c" in line: 678
S 1 19 0 710 Fatal Error in file: "ErrorHandler.c"; Fatal Print: Assert Requested by the Host
S 1 19 0 886 Assert in file: "ErrorHandler.c" in line: 886
S 1 20 0 184 Assert in file: "eventsManager.c" in line: 184
S 1 20 0 201 Fatal Error in file: "eventsManager.c"; Fatal Print: EventManager_MaskHwEvent
S 1 20 0 206 Fatal Error in file: "eventsManager.c"; Fatal Print: HwEvents_UnMaskEvent
S 1 20 0 225 Assert in file: "eventsManager.c" in line: 225
S 1 20 0 232 Assert in file: "eventsManager.c" in line: 232
S 1 20 2 202 Assert in file: "eventsManager.c" in line: 202
S 1 20 2 212 Assert in file: "eventsManager.c" in line: 212
S 1 20 2 243 Assert in file: "eventsManager.c" in line: 243
S 1 20 2 253 Assert in file: "eventsManager.c" in line: 253
S 1 23 0 162 Assert in file: "GidmManager.c" in line: 162
S 1 23 0 175 GidmManager_RunStateMachine: Sta = %d, CurrentState = %d, event = %d
S 1 23 0 183 GidmManager_ChangeState: staIndex = %d, newState = %d
S 1 23 0 190 Fatal Error in file: "GidmManager.c"; Fatal Print: GidmManager_IllegalEvent
S 1 23 0 326 Assert in file: "GidmManager.c" in line: 326
S 1 23 0 347 Assert in file: "GidmManager.c" in line: 347
S 1 23 0 351 Assert in file: "GidmManager.c" in line: 351
S 1 23 0 383 Assert in file: "GidmManager.c" in line: 383
S 1 24 0 120 GroupDb_FillGroupParams: groupIndex is %x. SIDs in group (%d, %d, %d, %d)
S 1 24 0 360 Assert in file: "GroupDatabase.c" in line: 360
S 1 24 0 361 Assert in file: "GroupDatabase.c" in line: 361
S 1 24 0 362 Assert in file: "GroupDatabase.c" in line: 362
S 1 24 0 363 Assert in file: "GroupDatabase.c" in line: 363
S 1 24 0 370 Assert in file: "GroupDatabase.c" in line: 370
S 1 24 0 375 Fatal Error in file: "GroupDatabase.c"; Fatal Print: GroupDb_UpdateMuGroupAttributes invalid option
S 1 24 0 415 GroupDb_ResetGroupEntry: groupIndex is %X
S 1 24 0 449 GroupDB_Init
S 1 25 0 1018 Assert in file: "GroupManager.c" in line: 1018
S 1 25 0 1039 groupManagerAddStation: Adding station %d
S 1 25 0 1048 groupManagerAddStation: station id %d is not allowed
S 1 25 0 1091 groupManagerRemoveStation: received on SID %d
S 1 25 0 1140 groupManagerTrainingTimer: stations timer event, handle index %d
S 1 25 0 1158 groupManagerTrainingTimer: groups timer event, handle index %d
S 1 25 0 1348 groupManagerGroupsMarksReceived: word in Bitmap %d, stations waiting for group marks in this word 0x%x
S 1 25 0 1362 Assert in file: "GroupManager.c" in line: 1362
S 1 25 0 1452 groupManagerStationNssHasChanged: station index %d. New nss %d. virtual group removed %d
S 1 25 0 1469 groupManagerStationNssHasChanged: station index %d. New nss %d. active group removed %d
S 1 25 0 1511 groupManagerAddGroupConfirmation - groupIdx %d
S 1 25 0 1601 groupManagerRemovedGroupConfirmation: from LA on group index %d. group state %d
S 1 25 0 1643 groupManagerGroupsHasFailed: group index %d
S 1 25 0 1733 Fatal Error in file: "GroupManager.c"; Fatal Print: groupManagerResetMultiUserOperation
S 1 25 0 1749 Fatal Error in file: "GroupManager.c"; Fatal Print: groupManagerResetMultiUserOperation
S 1 25 0 1796 Fatal Error in file: "GroupManager.c"; Fatal Print: groupManagerSetMultiUserOperationCfm
S 1 25 0 1834 Assert in file: "GroupManager.c" in line: 1834
S 1 25 0 1835 Assert in file: "GroupManager.c" in line: 1835
S 1 25 0 1882 groupManagerSetMultiUserOperation: current MU state = %d
S 1 25 0 1897 groupManagerSetMultiUserOperation: MU is already active
S 1 25 0 1919 groupManagerSetMultiUserOperation: MU is already deactivated
S 1 25 0 1950 groupManagerSetMuFixedRate: isFixedRate %d
S 1 25 0 2150 Assert in file: "GroupManager.c" in line: 2150
S 1 25 0 2226 Assert in file: "GroupManager.c" in line: 2226
S 1 25 0 2379 groupManagerStationEventRemoveStationInActiveOrTempActive: on station index %d
S 1 25 0 2660 groupManagerStationEventRemoveGroupDueToStationInNotifying: group index %d, station index %d
S 1 25 0 2729 groupManagerStationEventRemoveGroupDueToStationInProbing: group index %d, station index %d. Configure station for selector as SU.
S 1 25 0 2744 groupManagerStationEventRemoveGroupDueToStationInProbing: group index %d, station index %d. Station is only a member in notifying groups
S 1 25 0 2755 groupManagerStationEventRemoveGroupDueToStationInProbing: group index %d, station index %d. Station is only a member in virtual groups
S 1 25 0 2765 groupManagerStationEventRemoveGroupDueToStationInProbing: group index %d, station index %d. Station is not a member of any group. Moving to HALT
S 1 25 0 2828 groupManagerStationEventRemoveGroupInTempActive: Removing groupIndex %d. stationIndex %d is tempActive of the group
S 1 25 0 2860 groupManagerStationEventRemoveGroupInTempActive: Removing groupIndex %d which is primary group of stationIndex %d. station is tempActive of another group and part of more active groups
S 1 25 0 2873 groupManagerStationEventRemoveGroupInTempActive: Removing groupIndex %d which is primary group of stationIndex %d. station is tempActive and member of only probing groups
S 1 25 0 2982 groupManagerStationEventRemoveGroupDueToStationInSuValWaitingLa: groupIndex %d, station index %d
S 1 25 0 2988 groupManagerStationEventRemoveGroupDueToStationInSuValWaitingLa: the primary group of station waiting to start SU val is removed, cancel SU val
S 1 25 0 3030 groupManagerStationEventRemoveGroupDueToStationInSingleUserValidation: group index %d, station index %d, primary group index = %d
S 1 25 0 3118 groupManagerStationEventRemoveGroupInNotifying: groupIndex %d, stationIndex %d
S 1 25 0 3170 groupManagerStationEventRemoveGroupInProbing: Station %d is primary of probing group %d which is beeing removed. configure station in selector to SU
S 1 25 0 3186 groupManagerStationEventRemoveGroupInProbing: Station %d remains member of only notify groups
S 1 25 0 3194 groupManagerStationEventRemoveGroupInProbing: Station %d is not a member of any active/probing/notify group
S 1 25 0 3549 groupManagerStationEventActivateGroupInProbing: group idx %d, SID %d 
S 1 25 0 3566 groupManagerStationEventActivateGroupInProbing: tempPrimaryGroup before activation is %d 
S 1 25 0 3933 groupManagerStationEventActivateGroupInSingleUserValidationEnded: SID %d, configured to be primary of group %d
S 1 25 0 4123 groupManagerStationEventSuValStartCfmInSuValWaitingLa: SID %d configured to SU mode
S 1 25 0 4269 groupManagerStationEventSuValEndCfmInSuValSucceeded: SID %d, configured to work in MU mode, primary for group %d
S 1 25 0 4574 Assert station %d state: %d
S 1 25 0 4576 Fatal Error in file: "GroupManager.c"; Fatal Print: Assert in group manager station event
S 1 25 0 4606 Ingore event station %d state: %d
S 1 25 0 4638 Remove Group event update station bitmap station %d state: %d group %d
S 1 25 0 4673 Add Group event update station bitmap station %d state: %d group %d
S 1 25 0 4754 groupManagerRunStationStateMachine station %d state: %d event %d
S 1 25 0 4768 Assert in file: "GroupManager.c" in line: 4768
S 1 25 0 4808 groupManagerChangeStationState: Change station %d state: old state %d new state %d
S 1 25 0 4858 group manager, Send Confirmation, Client %d, stationIndex %d
S 1 25 0 4896 groupManagerRemoveAllStationVirtualGroups: SID %d, virtualGroupsBitmap 0x%x
S 1 25 0 5003 Fatal Error in file: "GroupManager.c"; Fatal Print: Station was not found in virtual group
S 1 25 0 5050 Fatal Error in file: "GroupManager.c"; Fatal Print: Station was not found in group
S 1 25 0 5096 groupManagerSetStationPrimaryBitInGroupsDb: stationIndex %d, groupIndex %d, primary stations bitmap after adding new primary 0x%x
S 1 25 0 5131 groupManagerConfigureStationAsPrimaryInGroup: station index %d configured primary for selector with group index %d
S 1 25 0 5208 groupManagerClearStationPrimaryInGroup: station index %d, group index %d, primaryStationsbitmap for this group 0x%x
S 1 25 0 5230 Fatal Error in file: "GroupManager.c"; Fatal Print: Trying to delete staticGroup !
S 1 25 0 5268 groupManagerSendEndSingleUserValidationMessage: to LA on SID %d
S 1 25 0 5304 groupManagerTriggerRemoveStationInTraining: sent to Training mng on SID %d
S 1 25 0 5434 groupManagerFindBestGroup: group with best mark  is %d
S 1 25 0 5515 groupManagerRemoveGroupInActive: group index: %d, haltNeeded: %d 
S 1 25 0 5524 groupManagerRemoveGroupInActive: station has more active groups. bitmap of groups 0x%x
S 1 25 0 5698 groupManagerTryToStartNewSingleUserValidation: Single User Validation bitmap %d, SID %d
S 1 25 0 5703 groupManagerTryToStartNewSingleUserValidation: Single User Validation bitmap after adding new one %d, SID %d
S 1 25 0 5713 groupManagerTryToStartNewSingleUserValidation: start single user val on SID %d
S 1 25 0 5749 groupManagerSendGroupsMarksMessage
S 1 25 0 5802 groupManagerStationExitActiveState: station has more probing groups
S 1 25 0 5815 groupManagerStationExitActiveState: station has more notifying groups
S 1 25 0 5826 groupManagerStationExitActiveState: can remain in single user state. isHaltNeeded %d, virtual groups bitmap 0x%x
S 1 25 0 5834 groupManagerStationExitActiveState: station is moving to HALT
S 1 25 0 5886 groupManagerStartNewSingleUserValidation: all stations candidates for su validation bitmap 0x%x
S 1 25 0 5892 groupManagerStartNewSingleUserValidation: SID %d chosen next for SU validation, moving to Su val pending
S 1 25 0 5899 groupManagerStartNewSingleUserValidation: no candidates for su val found
S 1 25 0 5971 groupManagerConfigureNewGroupForSelector: numOfStations %d
S 1 25 0 5974 groupManagerConfigureNewGroupForSelector: sid %d
S 1 25 0 5983 groupManagerConfigureNewGroupForSelector: Configure primary SID %d for group %d in Selector
S 1 25 0 6169 Assert in file: "GroupManager.c" in line: 6169
S 1 25 0 6171 groupManagerGroupEventStartNotifying: group index for notification %d, virtual group index %d
S 1 25 0 6215 groupManagerGroupEventStartNotifying: station index %d, group index %d, uspVector 0x%x
S 1 25 0 6345 groupManagerGroupEventRemoveGroupInProbing: group %d
S 1 25 0 6385 groupManagerGroupEventRemoveGroupInActive: group %d
S 1 25 0 6438 groupManagerGroupEventNotificationCfmInProbingNotifying: on SID %d, groupIdx %d, notifStatus %d
S 1 25 0 6460 groupManagerGroupEventNotificationCfmInProbingNotifying: All notifications arrived successfully
S 1 25 0 6490 groupManagerGroupEventNotificationCfmInProbingNotifying: timer started after static group generation
S 1 25 0 6514 groupManagerGroupEventNotificationCfmInProbingNotifying: All notifications arrived - last FAILED
S 1 25 0 6546 groupManagerGroupEventNotificationCfmInProbingNotifying: one of notification failed, more notifications will arrive - start remove group now
S 1 25 0 6951 groupManagerGroupEventRemoveGroupCfmInRemovingWaitingForLaCfm
S 1 25 0 7003 groupManagerGroupEventProbingResultsAreReadyInProbing: group Idx %d, group mark %d, states (%d, %d, %d, %d)
S 1 25 0 7026 groupManagerGroupEventProbingResultsAreReadyInProbing: for group %d station %d mark is below threshold! (%d, %d, %d, %d)
S 1 25 0 7042 groupManagerGroupEventProbingResultsAreReadyInProbing: Group mark is below threshold!!!
S 1 25 0 7049 groupManagerGroupEventProbingResultsAreReadyInProbing: num of active groups %d, num of removing active groups %d
S 1 25 0 7072 groupManagerGroupEventProbingResultsAreReadyInProbing: active groups are full. Worth active group index %d, group mark %d, probing grop mark %d
S 1 25 0 7090 groupManagerGroupEventProbingResultsAreReadyInProbing: Send activateGroup event to SID %d
S 1 25 0 7117 groupManagerGroupEventProbingResultsAreReadyInProbing: Valid probing group found. Group idx %d. will be active
S 1 25 0 7147 groupManagerGroupEventProbingResultsAreReadyInProbing: Probing group idx %d is not valid. No primary station availabe for it. Will be removed
S 1 25 0 7199 Ignore 'probing results ready event' for group %d (static group) in state: %d
S 1 25 0 7205 Assert group %d state: %d on probing results ready event
S 1 25 0 7207 Fatal Error in file: "GroupManager.c"; Fatal Print: Assert in group manager group event
S 1 25 0 7335 Assert group %d state: %d
S 1 25 0 7337 Fatal Error in file: "GroupManager.c"; Fatal Print: Assert in group manager group event
S 1 25 0 7368 Ignore event group %d state: %d
S 1 25 0 7406 groupManagerRunGroupStateMachine group %d state: %d event %d
S 1 25 0 7435 groupManagerChangeGlobalState: current state: %d, new state %d
S 1 25 0 7469 groupManagerChangeGroupState: Change group %d state: old state %d new state %d
S 1 25 0 7511 groupManagerSendRemoveGroupMessage: groupIndex %d
S 1 25 0 7556 groupManagerSendAddGroupMessage: send add group to LA
S 1 25 0 7594 groupManagerLockGroup: sending lock request to Locker on group %d
S 1 25 0 7607 groupManagerLockGroup: lock was already sent. Adding group %d to waiting list. waitingLock bitmap 0x%x
S 1 25 0 7667 groupManagerGroupRemoveGroupInProbingNotifying: station %d is removed during probing, send stopTx to GIDM Mng
S 1 25 0 7681 groupManagerGroupRemoveGroupInProbingNotifying: send stopTx on station %d to GIDM Mng, notification cancelled
S 1 25 0 7697 groupManagerGroupRemoveGroupInProbingNotifying: station index received %d. notification status of the group (%d, %d, %d, %d)
S 1 25 0 7752 groupManagerHandleNextGroupWaitingForLock: group  %d
S 1 25 0 7790 groupManagerFinishGroupRemovalProcess: group idx %d, removingGroupsBitmap 0x%x, occupiedGroupsBitmap 0x%x, numberOfOccupiedGroups %d, activeGroupsBitmap 0x%x, probingGroupsBitmap 0x%x
S 1 25 0 7806 groupManagerFinishGroupRemovalProcess: group was in active state. After clear bits: activeGroupsBitmap 0x%x, numberOfActiveGroups %d, num of removing groups in active %d
S 1 25 0 7815 groupManagerFinishGroupRemovalProcess: group was in probing state. After clear bits: probingGroupsBitmap 0x%x, numberOfProbingGroups %d
S 1 25 0 7835 groupManagerFinishGroupRemovalProcess: group failed
S 1 25 0 7847 groupManagerFinishGroupRemovalProcess: group not failed
S 1 25 0 7897 groupManagerFinishGlobalRemovalProcess: sending multi user operation setting cfm
S 1 25 0 7908 groupManagerFinishGlobalRemovalProcess: starting static group generation
S 1 25 0 7952 groupManagerTryToFindNewGroupForProbing: probing groups %d, occupied groups %d
S 1 25 0 7965 groupManagerTryToFindNewGroupForProbing: virtuals db bitmap 0x%x
S 1 25 0 8033 groupManagerTryToFindNewGroupForProbing: virtual groups bitmap candidates for probing 0x%x
S 1 25 0 8049 groupManagerTryToFindNewGroupForProbing: found best virtual group index for probing %d
S 1 25 0 8387 GroupManager_TrainingWasStoppedConfirmation
S 1 25 0 8410 GroupManager_TrainingWasStoppedConfirmation: send multi user operation setting cfm
S 1 25 0 8428 GroupManager_TrainingWasStoppedConfirmation: Starting To create static group
S 1 25 0 8448 Fatal Error in file: "GroupManager.c"; Fatal Print: Assert in GroupManager_TrainingWasStoppedConfirmation
S 1 25 0 8547 GroupManager_TrainingResultsWereReceived: entry num %d
S 1 25 0 8553 GroupManager_TrainingResultsWereReceived: invalid  StaIdx %d
S 1 25 0 8561 GroupManager_TrainingResultsWereReceived: staIdx %d, invalid combination. 
S 1 25 0 8590 GroupManager_TrainingResultsWereReceived: staId %d - (%d, %d, %d, %d).
S 1 25 0 8592 GroupManager_TrainingResultsWereReceived: MCS - (%d, %d, %d, %d)
S 1 25 0 8594 GroupManager_TrainingResultsWereReceived: groupGrade - %d, singleNsts %d, doubleNsts %d
S 1 25 0 8627 GroupManager_TrainingResultsWereReceived: Nss bitmap: 0x%x
S 1 25 0 8640 GroupManager_TrainingResultsWereReceived:occupied groupId %d, groupStations (%d,%d,%d,%d)
S 1 25 0 8652 GroupManager_TrainingResultsWereReceived: Group Exists in occupied DB: EntryIdx %d, staId %d, groupIndex %d
S 1 25 0 8674 GroupManager_TrainingResultsWereReceived: virtualGroupId %d, groupStations (%d,%d,%d,%d)
S 1 25 0 8694 GroupManager_TrainingResultsWereReceived: Group Exists in VIRTUAL DB: EntryIdx %d, staId %d, virtualGroupIdx %d
S 1 25 0 8712 GroupManager_TrainingResultsWereReceived: Found free spot %d in virtual DB
S 1 25 0 8723 GroupManager_TrainingResultsWereReceived: Virtual DB is full!
S 1 25 0 8739 GroupManager_TrainingResultsWereReceived: new group will overwrite groupIdx %d in virtual DB. Prev group grade %d, new group grade %d
S 1 25 0 8887 GroupManager_GidmNotificationConfirmation: SID %d, notify group idx %d
S 1 25 0 9380 groupManagerCreateMuStaticGroup: preparing for static group generation
S 1 25 0 9415 groupManagerDeleteMuStaticGroup
S 1 26 0 164 AfePhase: Executing Calibration
S 1 26 0 171 AfePhase: run time =%d
S 1 26 0 215 AfePhase: initCalibration() nCB mode
S 1 26 0 224 AfePhase: initCalibration() CB mode
S 1 26 0 290 AfePhase: AfePhase_Logic() initValue[%d] = h%x
S 1 26 0 317 Calibration Step delay[0] = h%x delay[1] = h%x delay[2] = h%x
S 1 26 0 318 Tx: res[0] = h%x res[1] = h%x res[2] = h%x
S 1 26 0 319 Rx: res[0] = h%x res[1] = h%x res[2] = h%x
S 1 26 0 386 Assert in file: "AfePhaseClbrHndlr.c" in line: 386
S 1 26 0 399 ant1equal = %d times, ant2equal= %d
S 1 26 0 452 Assert in file: "AfePhaseClbrHndlr.c" in line: 452
S 1 26 0 458 diff_array_rx[%d] = %d rxDelay = %d
S 1 26 0 459 diff_array_tx[%d] = %d 
S 1 26 3 568 START AFE CALIBRATION
S 1 26 3 597 retVal=%d, packetMod=%d
S 1 26 3 602 packetMod=%d,pElements->results.offlineModulationType=%d 
S 1 26 3 606 exit ALB mode, calibration end!
S 1 26 3 613 LastClRunTime: %d
S 1 26 3 673 QBF calibration finished
S 1 26 3 701 Setting TPC: %d, for extPa = %d
S 1 26 3 816 Assert in file: "BeamFormingClbrHndlr.c" in line: 816
S 1 26 3 823 agcGains(ant %d). lnaIndx = %d pgc1Indx = %d pgc2Indx = %d pgc3Indx = %d
S 1 26 3 833 Send packet %d => %d
S 1 26 3 849 Packet sent from ant %d to ant %d
S 1 26 3 868 BM calibration fail! number of recorded bins from sessions not identical
S 1 26 3 893 StopRisc called
S 1 26 3 930 Assert in file: "BeamFormingClbrHndlr.c" in line: 930
S 1 26 3 940 StartRisc called
S 1 26 3 979 TRSW: %x %x %x
S 1 26 3 1068 Assert in file: "BeamFormingClbrHndlr.c" in line: 1068
S 1 26 3 1092 Assert in file: "BeamFormingClbrHndlr.c" in line: 1092
S 1 26 3 1141 Registers values were not saved, cannot restore them
S 1 26 3 1142 Assert in file: "BeamFormingClbrHndlr.c" in line: 1142
S 1 26 3 1147 Stop risc
S 1 26 3 1163 Run risc
S 1 26 3 1209 Assert in file: "BeamFormingClbrHndlr.c" in line: 1209
S 1 26 3 1258 BF Calibration Failed!! could not achieve a good channel
S 1 26 3 1274 triggerTB
S 1 26 3 1336 Record Channel Failed !! packet did not arrive in time
S 1 26 3 1348 Record Channel Failed!! wrong channel size, CB: %d, numOfBins:%d
S 1 26 3 1359 Record Channel Failed!! Wrong Packet received with length %d
S 1 26 3 1373 Record channel failed!!! CRC error
S 1 26 3 1424 Assert in file: "BeamFormingClbrHndlr.c" in line: 1424
S 1 26 3 1430 Record %d bins
S 1 26 3 1578 CaluclateCalResult, calPair=%d
S 1 26 3 1580 Assert in file: "BeamFormingClbrHndlr.c" in line: 1580
S 1 26 3 1642 NCB mode: Start checking phase jump
S 1 26 3 1651 PhaseDiff = %d
S 1 26 3 1660 Phase jump found! correcting K calibration
S 1 26 3 1685 Phase jump not found
S 1 26 3 1768 Assert in file: "BeamFormingClbrHndlr.c" in line: 1768
S 1 26 3 1857 Assert in file: "BeamFormingClbrHndlr.c" in line: 1857
S 1 26 3 1873 START AGC GAINS CALIBRATION
S 1 26 3 1884 START K CALIBRATION
S 1 26 3 1908 START AGC OFFSET CALIBRATION
S 1 26 3 1916 START TX OFFSET CALIBRATION
S 1 26 3 1923 exit ALB mode, calibration end!, calStatus = %X
S 1 26 3 1953 Start K%d calibration, CB=%d
S 1 26 3 1991 extGainDb = %d, extGain = %d, trAttenDb = %d
S 1 26 3 2069 relative gain = %d
S 1 26 3 2094 Assert in file: "BeamFormingClbrHndlr.c" in line: 2094
S 1 26 3 2110 Warning: working at %d instead of 15 dB backoff
S 1 26 3 2118 BF Calibration Failed !! Attenuation between antennas too high:%d
S 1 26 3 2143 Send packet: Ant%d->Ant%d
S 1 26 3 2144 trSwTxAnt: %d
S 1 26 3 2316 Assert in file: "BeamFormingClbrHndlr.c" in line: 2316
S 1 26 3 2357 digital gain %d
S 1 26 3 2368 running for gains : LnaIndex %d, pgc1Index %d, pgc2Index %d,pgc3Index %d
S 1 26 3 2616 Assert in file: "BeamFormingClbrHndlr.c" in line: 2616
S 1 26 3 2798 Assert in file: "BeamFormingClbrHndlr.c" in line: 2798
S 1 26 3 2848 BF Calibration Failed!! could not achieve a good channel
S 1 26 3 2873 DisTxCancel
S 1 26 3 2880 EnTxCancel
S 1 26 5 647 START AFE CALIBRATION
S 1 26 5 676 retVal=%d, packetMod=%d
S 1 26 5 686 packetMod=%d,pElements->results.offlineModulationType=%d 
S 1 26 5 690 exit ALB mode, calibration end!
S 1 26 5 697 LastClRunTime: %d
S 1 26 5 757 QBF calibration finished
S 1 26 5 788 Setting TPC: %d, for extPa = %d
S 1 26 5 881 Assert in file: "BeamFormingClbrHndlr.c" in line: 881
S 1 26 5 884 agcGains(ant %d). lnaIndx = %d pgc1Indx = %d pgc2Indx = %d pgc3Indx = %d
S 1 26 5 896 Send packet %d => %d
S 1 26 5 909 Packet sent from ant %d to ant %d
S 1 26 5 920 BM calibration fail! number of recorded bins from sessions not identical
S 1 26 5 942 StopRisc called
S 1 26 5 998 StartRisc called
S 1 26 5 1052 TRSW: %x %x %x
S 1 26 5 1202 Registers values were not saved, cannot restore them
S 1 26 5 1203 Assert in file: "BeamFormingClbrHndlr.c" in line: 1203
S 1 26 5 1208 Stop risc
S 1 26 5 1230 Run risc
S 1 26 5 1275 Assert in file: "BeamFormingClbrHndlr.c" in line: 1275
S 1 26 5 1329 BF Calibration Failed!! could not achieve a good channel
S 1 26 5 1349 triggerTB
S 1 26 5 1429 Record channel failed!!! CRC error
S 1 26 5 1539 Assert in file: "BeamFormingClbrHndlr.c" in line: 1539
S 1 26 5 1546 Record %d bins
S 1 26 5 1907 Assert in file: "BeamFormingClbrHndlr.c" in line: 1907
S 1 26 5 1997 Assert in file: "BeamFormingClbrHndlr.c" in line: 1997
S 1 26 5 2018 START AGC GAINS CALIBRATION
S 1 26 5 2031 START K CALIBRATION
S 1 26 5 2059 START AGC OFFSET CALIBRATION
S 1 26 5 2069 START TX OFFSET CALIBRATION
S 1 26 5 2084 exit ALB mode, calibration end!, calStatus = %X
S 1 26 5 2114 Start K%d calibration, CB=%d
S 1 26 5 2216 relative gain = %d
S 1 26 5 2241 Assert in file: "BeamFormingClbrHndlr.c" in line: 2241
S 1 26 5 2256 Warning: working at %d instead of 15 dB backoff
S 1 26 5 2264 BF Calibration Failed !! Attenuation between antennas too high:%d
S 1 26 5 2305 Send packet: Ant%d->Ant%d
S 1 26 5 2306 trSwTxAnt: %d
S 1 26 5 2504 Assert in file: "BeamFormingClbrHndlr.c" in line: 2504
S 1 26 5 2571 digital gain %d
S 1 26 5 2584 running for gains : LnaIndex %d, pgc1Index %d, pgc2Index %d,pgc3Index %d
S 1 26 5 2838 Assert in file: "BeamFormingClbrHndlr.c" in line: 2838
S 1 26 5 3038 Assert in file: "BeamFormingClbrHndlr.c" in line: 3038
S 1 26 5 3088 BF Calibration Failed!! could not achieve a good channel
S 1 26 5 3164 DisTxCancel
S 1 26 5 3171 EnTxCancel
S 1 26 9 645 START AFE CALIBRATION
S 1 26 9 674 retVal=%d, packetMod=%d
S 1 26 9 684 packetMod=%d,pElements->results.offlineModulationType=%d 
S 1 26 9 688 exit ALB mode, calibration end!
S 1 26 9 695 LastClRunTime: %d
S 1 26 9 755 QBF calibration finished
S 1 26 9 786 Setting TPC: %d, for extPa = %d
S 1 26 9 879 Assert in file: "BeamFormingClbrHndlr.c" in line: 879
S 1 26 9 882 agcGains(ant %d). lnaIndx = %d pgc1Indx = %d pgc2Indx = %d pgc3Indx = %d
S 1 26 9 894 Send packet %d => %d
S 1 26 9 907 Packet sent from ant %d to ant %d
S 1 26 9 918 BM calibration fail! number of recorded bins from sessions not identical
S 1 26 9 940 StopRisc called
S 1 26 9 996 StartRisc called
S 1 26 9 1050 TRSW: %x %x %x
S 1 26 9 1200 Registers values were not saved, cannot restore them
S 1 26 9 1201 Assert in file: "BeamFormingClbrHndlr.c" in line: 1201
S 1 26 9 1206 Stop risc
S 1 26 9 1228 Run risc
S 1 26 9 1273 Assert in file: "BeamFormingClbrHndlr.c" in line: 1273
S 1 26 9 1327 BF Calibration Failed!! could not achieve a good channel
S 1 26 9 1347 triggerTB
S 1 26 9 1429 Record channel failed!!! CRC error
S 1 26 9 1537 Assert in file: "BeamFormingClbrHndlr.c" in line: 1537
S 1 26 9 1543 Record %d bins
S 1 26 9 1898 Assert in file: "BeamFormingClbrHndlr.c" in line: 1898
S 1 26 9 1989 Assert in file: "BeamFormingClbrHndlr.c" in line: 1989
S 1 26 9 2010 START AGC GAINS CALIBRATION
S 1 26 9 2023 START K CALIBRATION
S 1 26 9 2051 START AGC OFFSET CALIBRATION
S 1 26 9 2061 START TX OFFSET CALIBRATION
S 1 26 9 2076 exit ALB mode, calibration end!, calStatus = %X
S 1 26 9 2106 Start K%d calibration, CB=%d
S 1 26 9 2208 relative gain = %d
S 1 26 9 2233 Assert in file: "BeamFormingClbrHndlr.c" in line: 2233
S 1 26 9 2248 Warning: working at %d instead of 15 dB backoff
S 1 26 9 2256 BF Calibration Failed !! Attenuation between antennas too high:%d
S 1 26 9 2297 Send packet: Ant%d->Ant%d
S 1 26 9 2298 trSwTxAnt: %d
S 1 26 9 2496 Assert in file: "BeamFormingClbrHndlr.c" in line: 2496
S 1 26 9 2563 digital gain %d
S 1 26 9 2576 running for gains : LnaIndex %d, pgc1Index %d, pgc2Index %d,pgc3Index %d
S 1 26 9 2830 Assert in file: "BeamFormingClbrHndlr.c" in line: 2830
S 1 26 9 3030 Assert in file: "BeamFormingClbrHndlr.c" in line: 3030
S 1 26 9 3080 BF Calibration Failed!! could not achieve a good channel
S 1 26 9 3156 DisTxCancel
S 1 26 9 3163 EnTxCancel
S 1 27 0 178 LPF: Executing Calibration.
S 1 27 0 190 LPF: Finished Calibration. Ret Val = %d, Run Time = %d
S 1 27 0 216 LPF_LoadResults(): Ant %u lpfI=%u lpfQ=%u
S 1 27 1 124 Assert in file: "LpfClbrUtils.c" in line: 124
S 1 27 5 140 MsSsiAdc: Executing Calibration
S 1 27 5 442 MsSsiAdc verifyCalibrationResults: antNum = %d Status = %d
S 1 27 5 443 MsSsiAdc verifyCalibrationResults: statusGain = %d gainDist = %d
S 1 27 5 444 MsSsiAdc verifyCalibrationResults: statusOffset = %d offsetDist = %d
S 1 27 6 114 RficBias: Executing Calibration
S 1 27 6 143 RficBias: status = %d, statusRpos = %d, statusRneg = %d
S 1 27 6 144 RficBias: Rint = %d Rpos = %d, Rneg = %d
S 1 27 6 154 RficBias: Finished Calibration. Run Time = %d
S 1 27 6 215 RficBias_calibrateRpos:Failed to reach comparator SUCCESS
S 1 27 6 276 RficBias_calibrateRneg:Failed to reach comparator SUCCESS
S 1 27 6 394 RficBias_LoadResults(): Rint=%d
S 1 27 7 127 RssiDcOffset: Executing Calibration
S 1 27 7 349 RssiDcOffset min_search !!! DEBUG !!!: delta=0: antenna %d
S 1 27 7 445 RssiDcOffset: Finished Calibration. Ret Code = %d, Run Time = %d
S 1 27 7 453 RssiDcOffset: AntNum = %d Status = %d
S 1 27 7 461 RssiDcOffset OFFSETS: I1 = %d I2 = %d I3 = %d
S 1 27 7 462 RssiDcOffset OFFSETS: I4 = %d I5 = %d
S 1 27 7 463 RssiDcOffset OFFSETS: Q1 = %d Q2 = %d Q3 = %d
S 1 27 7 464 RssiDcOffset OFFSETS: Q4 = %d Q5 = %d
S 1 27 7 472 RssiDcOffset DATA OUT OFFSETS: I1 = %d I2 = %d I3 = %d
S 1 27 7 473 RssiDcOffset DATA OUT OFFSETS: I4 = %d I5 = %d
S 1 27 7 474 RssiDcOffset DATA OUT OFFSETS: Q1 = %d Q2 = %d Q3 = %d
S 1 27 7 475 RssiDcOffset DATA OUT OFFSETS: Q4 = %d Q5 = %d
S 1 27 8 123 RSSI Path: Executing Calibration
S 1 27 8 153 RSSI Path Calibration:Antenna %d status %d
S 1 27 8 170 RSSI Path Calibration:Finished Calibration. ret = %d, Run Time = %d
S 1 27 8 210 RSSI Path calibrateSingleAntenna(): Antenna %d
S 1 27 8 222 Assert in file: "RssiPathClbrHndlr.c" in line: 222
S 1 27 8 244 RSSI Path calibrateSingleAntenna:Rssi = %d
S 1 27 8 283 RSSI Path calibrateSingleAntenna():Index = %d,Rssi = %d
S 1 27 8 308 RSSI Path calibrateSingleAntenna:Partitioned Section =%d Index = %d,Rssi = %d
S 1 27 8 468 Assert in file: "RssiPathClbrHndlr.c" in line: 468
S 1 27 8 512 RSSI Path measureRssi: measureRssi() time = %d
S 1 27 8 588 Assert in file: "RssiPathClbrHndlr.c" in line: 588
S 1 27 8 602 RSSI CalcDerivative: section=%d a=%d b=%d
S 1 27 8 618 RSSI Path calcDerivative(): time = %d
S 1 27 8 760 GenerateRssiTable:Dynamic Range low =%d high %d
S 1 27 8 761 GenerateRssiTable:First Calibrated Power In Dynamic Range: %d
S 1 27 8 762 GenerateRssiTable:Last Calibrated Power In Dynamic Range: %d
S 1 27 8 804 Assert in file: "RssiPathClbrHndlr.c" in line: 804
S 1 27 8 849 Assert in file: "RssiPathClbrHndlr.c" in line: 849
S 1 27 8 902 RSSI path VerifyResult: AntNum %d
S 1 27 8 938 RSSI path VerifyResult: transmit power %d  meaured rssi %d  calibrated power %d
S 1 27 8 963 RSSI path VerifyResult: Dynamic range %d low_power %d high_power %d
S 1 27 8 972 RSSI path VerifyResult: Status Fail, dynamicRange below minimum allowed %d
S 1 27 8 981 RSSI path VerifyResult: rssiPowerDiff %d maxDiffIsInPower %d
S 1 27 8 990 RSSI path VerifyResult: Status Fail, rssiPowerDiff exceeds maximum allowed %d
S 1 27 8 1005 RSSI path VerifyResult: measurementVariation %d min_measure %d max_measure %d
S 1 27 8 1014 RSSI path VerifyResult: Status Fail, measurementVariation exceeds maximum allowed %d
S 1 27 8 1030 RSSI Path VerifyResult(): ret %d status %d
S 1 27 8 1038 RSSI Path VerifyResult(): verify run time %d
S 1 27 8 1055 Assert in file: "RssiPathClbrHndlr.c" in line: 1055
S 1 27 28 279 RSSI Path: Executing Calibration
S 1 27 28 290 Assert in file: "RssiPathClbrHndlr.c" in line: 290
S 1 27 28 596 Assert in file: "RssiPathClbrHndlr.c" in line: 596
S 1 27 28 628 Assert in file: "RssiPathClbrHndlr.c" in line: 628
S 1 27 28 646 Assert in file: "RssiPathClbrHndlr.c" in line: 646
S 1 27 29 280 RSSI Path: Executing Calibration
S 1 27 29 291 Assert in file: "RssiPathClbrHndlr.c" in line: 291
S 1 27 29 597 Assert in file: "RssiPathClbrHndlr.c" in line: 597
S 1 27 29 629 Assert in file: "RssiPathClbrHndlr.c" in line: 629
S 1 27 29 647 Assert in file: "RssiPathClbrHndlr.c" in line: 647
S 1 27 9 349 Assert in file: "RxDcOffsetClbrHndlr.c" in line: 349
S 1 27 9 655 Assert in file: "RxDcOffsetClbrHndlr.c" in line: 655
S 1 27 9 669 Assert in file: "RxDcOffsetClbrHndlr.c" in line: 669
S 1 27 10 132 Rx IQ: Executing Calibration
S 1 27 10 222 RxIQ ALGO:Finished Calibration. Ret Code = %d, Run Time = %d
S 1 27 10 255 Rx IQ: Restore Done. Duration = %d
S 1 27 10 310 Rx IQ: Init Done. Duration = %d
S 1 27 10 464 RxIQ error verification for ANTENNA %d  w1 = %d w2 = %d
S 1 27 10 465 RxIQ error verification II = %d QQ = %d IQ = %d
S 1 27 10 482 RxIQ verifyCalibrationResults: error verification Status = %d w1_Error= %d w2_Error= %d
S 1 27 11 548 Assert in file: "TpcClbrHndlr.c" in line: 548
S 1 27 11 569 Assert in file: "TpcClbrHndlr.c" in line: 569
S 1 27 11 756 Assert in file: "TpcClbrHndlr.c" in line: 756
S 1 27 11 1086 Assert in file: "TpcClbrHndlr.c" in line: 1086
S 1 27 11 1134 ===================== Calibrate index %d, ant %d, bw %d ==============================
S 1 27 11 1183 -------- feedback %d, measured %d, target %d -----------
S 1 27 11 1207 old %d, new %d, steps %d
S 1 27 11 1418 Assert in file: "TpcClbrHndlr.c" in line: 1418
S 1 27 11 1429 Assert in file: "TpcClbrHndlr.c" in line: 1429
S 1 27 11 1430 Assert in file: "TpcClbrHndlr.c" in line: 1430
S 1 27 13 639 Assert in file: "TpcClbrHndlr.c" in line: 639
S 1 27 13 640 Assert in file: "TpcClbrHndlr.c" in line: 640
S 1 27 14 131 use ssb loop %d
S 1 27 14 188 Tx IQ: Finished Calibration. Ret Code = %d, Run Time = %d
S 1 27 14 270 Tx IQ initAntennaOnlineIterationDetails: last antenna = %d
S 1 27 14 380 TXIQ calibrateSingleAntenna:RF Ant %d,LoopBackRxAnt %d, LoopBackTxAnt %d
S 1 27 14 442 Tx IQ calibrateSingleAntenna(): Restore Hw Registers Run Time = %d
S 1 27 14 499 amplitude: %d digital gain: %d
S 1 27 14 500 Tx IQ: Init Done. Duration = %d
S 1 27 14 528 Tx IQ: Restore Done. Duration = %d
S 1 27 14 593 setTxIqAdaptiveGain. acc result(II) = %d. accumNorm = %d
S 1 27 14 612 Accumulator measurement is low - increase gain. course = %d
S 1 27 14 624 Accumulator measurement is high - decrease gain. course = %d
S 1 27 14 645 old Amp: %d new Amp: %d old digital: %d new digital: %d
S 1 27 14 666 Assert in file: "TxIQMismatchClbrHndlr.c" in line: 666
S 1 27 14 683 a: %d phiSquared: %d IMR: %d
S 1 27 14 817 Tx IQ calibrateAndVerifySingleBin:Bin %d
S 1 27 14 837 Reference energy (bin %d - %d): %d
S 1 27 14 889 Tx IQ calibrateAndVerifySingleBin(): Run Time = %d
S 1 27 14 948 tx ant: %d. rx ant: %d. II: %d QQ: %d IQ: %d
S 1 27 14 952 Tx IQ calcMinimumCoeffcientsValue(): a energy x0=%d x1=%d x2=%d
S 1 27 14 953 Tx IQ calcMinimumCoeffcientsValue(): a energy x3=%d x4=%d x5=%d
S 1 27 14 954 Tx IQ calcMinimumCoeffcientsValue(): a energy x6=%d x7=%d x8=%d
S 1 27 14 973 tx ant: %d. rx ant: %d. II: %d QQ: %d IQ: %d
S 1 27 14 977 Tx IQ calcMinimumCoeffcientsValue(): b energy x0=%d x1=%d x2=%d
S 1 27 14 978 Tx IQ calcMinimumCoeffcientsValue(): b energy x3=%d x4=%d x5=%d
S 1 27 14 979 Tx IQ calcMinimumCoeffcientsValue(): b energy x6=%d x7=%d x8=%d
S 1 27 14 988 Tx IQ calcMinCoeffcientValues(): a=%d, b=%d
S 1 27 14 1178 Assert in file: "TxIQMismatchClbrHndlr.c" in line: 1178
S 1 27 14 1201 Tx IQ VerifyCalibrationResults(): Energy(log) = %d
S 1 27 14 1214 Tx IQ verifyCalibrationResults():Energy exceeds max TH = %d status = %d
S 1 27 14 1231 Tx IQ verifyCalibrationResults(): Single bin verify Run Time = %d
S 1 27 14 1256 Assert in file: "TxIQMismatchClbrHndlr.c" in line: 1256
S 1 27 14 1260 Verify. a = %d b = %d
S 1 27 14 1264 Verify. tx ant: %d. rx ant: %d. II: %d QQ: %d IQ: %d
S 1 27 14 1271 Verify. IMR(dB) = %d
S 1 27 14 1284 Tx IQ verifyCalibrationResults():Energy exceeds max TH = %d status = %d
S 1 27 14 1301 Tx IQ verifyCalibrationResults(): Single bin verify Run Time = %d
S 1 27 14 1440 Tx IQ fixFailedBins(): Can't fix bins - calibration of all bins in range failed !!!
S 1 27 14 1456 Tx IQ fixFailedBins():Minimal Coefficient Values: bin=%d a=%d, b=%d
S 1 27 14 1467 Tx IQ fixFailedBins(): Failed bins %d, Fixed bins %d
S 1 27 14 1487 Tx IQ fixFailedBins(): Range sign %d, Run Time = %d
S 1 27 14 1601 Tx IQ calcInterpolatedCoefficients(): Interpolation between 2 bins [0,1] Run Time = %d
S 1 27 14 1644 Assert in file: "TxIQMismatchClbrHndlr.c" in line: 1644
S 1 27 14 1751 TxIQClbr_StoreResults(): CB mode %d
S 1 27 14 1772 TxIQClbr_StoreResults(): binIndex %d a=%d b=%d
S 1 27 14 1784 TxIQClbr_StoreResults(): binIndex %d a=%d b=%d
S 1 27 14 1929 Assert in file: "TxIQMismatchClbrHndlr.c" in line: 1929
S 1 27 14 1952 Assert in file: "TxIQMismatchClbrHndlr.c" in line: 1952
S 1 27 14 1970 ant: %d bin: %d a_k: %d b_k: %d
S 1 27 14 1985 x: %d, p/2: %d, e: %d
S 1 27 14 2000 F00: %d, F01: %d, F10: %d, F11: %d
S 1 27 14 2017 e %d sqrte %d ret %d
S 1 27 15 142 Tx Lo: Executing Calibration: CalibType(offline(1)/online(2)) = %d,
S 1 27 15 182 Tx Lo: Finished Calibration. Ret Code = %d, Run Time = %d
S 1 27 15 357 TXLo calibrateSingleAntenna:RF Ant %d,LoopBackRxAnt %d, LoopBackTxAnt %d
S 1 27 15 372 TxLo calibrateSingleAntenna(): Restore Hw Registers Run Time = %d
S 1 27 15 643 TxLo calibrateAndVerifySingleTpc: TPC %d
S 1 27 15 681 Tx Lo calibrateAndVerifySingleTpc(): Verify reference Energy(log) = %d
S 1 27 15 746 TxLo doAxisIteration(). Iteration = %d, I = %d
S 1 27 15 756 TxLo doAxisIteration(). Iteration = %d, Q = %d
S 1 27 15 769 TxLo calibrateAndVerifySingleTpc digitalDacI = %d, digitalDacQ = %d
S 1 27 15 777 TxLo calibrateAndVerifySingleTpc dacI = %d, dacQ = %d
S 1 27 15 788 TxLo calibrateAndVerifySingleTpc(): Run Time = %d
S 1 27 15 848 ant: %d. inHi: %d inLow %d energy high %d energy low: %d
S 1 27 15 888 ant: %d. inHi: %d inLow %d energy high %d energy low: %d
S 1 27 15 985 TxLo digitalDacUpdateRequired() DAC  %d exceeds allowed range but digital DAC max iterations %d exceeded
S 1 27 15 1140 Tx Lo VerifyCalibrationResults(): TPC Energy(log) = %d Diff from Ref %d
S 1 27 15 1150 Tx Lo verifyCalibrationResults():Energy diff from ref %d below TH = %d status = %d
S 1 27 15 1158 TxLo verifyCalibrationResults status = %d
S 1 27 15 1165 TxLo verifyCalibrationResults(): Single TPC verify Run Time = %d
S 1 27 15 1320 TxLo updateTpcsToNextCalibTpc: next TPC = %d
S 1 27 15 1412 Assert in file: "TxLOLeakageClbrHndlr.c" in line: 1412
S 1 27 15 1461 TxLoLeakage_StoreResults(): Ant %d Digital DAC: I=%d Q=%d
S 1 27 15 1469 TxLoLeakage_StoreResults(): Ant %d Num Calibrated TPCs=%d
S 1 27 15 1480 TxLoLeakage_StoreResults(): Ant %d TPC %d DAC: I=%d Q=%d
S 1 27 16 343 Assert in file: "CalibrationHandler.c" in line: 343
S 1 27 16 351 Assert in file: "CalibrationHandler.c" in line: 351
S 1 27 16 374 Calibrating...
S 1 27 16 535 Assert in file: "CalibrationHandler.c" in line: 535
S 1 27 16 550 runCalibration. clbrType: %d dataStoreState: %d
S 1 27 16 569 runCalibration. proc %d
S 1 27 16 572 Assert in file: "CalibrationHandler.c" in line: 572
S 1 27 16 585 Calibrations fragmented
S 1 27 16 589 Finished Calibrations
S 1 27 16 689 CalibrationHandler getUpdateOfflineStatus(). StatusVector = 0x%x %d
S 1 27 17 34 Assert in file: "CalibrationHandlerUtils.c" in line: 34
S 1 27 18 345 Load Store event: LOAD_STORE_EVENT_TRIGGER_LOAD. current state: %d
S 1 27 18 354 Load Store event: LOAD_STORE_EVENT_DMA_DONE. current state: %d
S 1 27 18 363 Load Store event: LOAD_STORE_EVENT_TRIGGER_STORE. current state: %d
S 1 27 18 416 Assert in file: "CalibrationManager.c" in line: 416
S 1 27 18 431 setLoadStoreSmState. state: %d
S 1 27 18 541 ClbrMngr_RunOnlineCalibration
S 1 27 18 544 Assert in file: "CalibrationManager.c" in line: 544
S 1 27 18 562 ClbrMngr_RunOfflineCalibration
S 1 27 18 597 Assert in file: "CalibrationManager.c" in line: 597
S 1 27 18 636 Assert in file: "CalibrationManager.c" in line: 636
S 1 27 18 655 CM_STATISTICS_ONLINE_CAL_NET_DURATION %d proc %d
S 1 27 18 657 Assert in file: "CalibrationManager.c" in line: 657
S 1 27 18 747 ClbrMngr_HandleCalibrateProcessStart
S 1 27 18 797 ClbrMngr_CalibrateChannelDone
S 1 27 18 825 Fatal Error in file: "CalibrationManager.c"; Fatal Print: Calibration WD Timer Expired
S 1 28 0 1098 Assert in file: "Afe.c" in line: 1098
S 1 28 0 1131 Assert in file: "Afe.c" in line: 1131
S 1 28 0 1293 Assert in file: "Afe.c" in line: 1293
S 1 28 0 1438 Assert in file: "Afe.c" in line: 1438
S 1 28 4 854 Assert in file: "Afe.c" in line: 854
S 1 28 4 1377 Assert in file: "Afe.c" in line: 1377
S 1 28 4 1516 Assert in file: "Afe.c" in line: 1516
S 1 29 4 852 Assert in file: "Afe.c" in line: 852
S 1 29 4 1372 Assert in file: "Afe.c" in line: 1372
S 1 29 4 1511 Assert in file: "Afe.c" in line: 1511
S 1 29 1 61 Assert in file: "efuseAccess.c" in line: 61
S 1 29 1 62 Assert in file: "efuseAccess.c" in line: 62
S 1 29 1 110 Assert in file: "efuseAccess.c" in line: 110
S 1 28 5 256 Assert in file: "IndirectAccess.c" in line: 256
S 1 28 6 639 Assert in file: "PhyCalDriver.c" in line: 639
S 1 28 6 1069 Assert in file: "PhyCalDriver.c" in line: 1069
S 1 28 6 1299 Assert in file: "PhyCalDriver.c" in line: 1299
S 1 28 8 780 Assert in file: "PhyCalDriver.c" in line: 780
S 1 28 8 781 Assert in file: "PhyCalDriver.c" in line: 781
S 1 28 8 812 Assert in file: "PhyCalDriver.c" in line: 812
S 1 28 8 866 Assert in file: "PhyCalDriver.c" in line: 866
S 1 28 8 1349 Assert in file: "PhyCalDriver.c" in line: 1349
S 1 28 8 1641 Assert in file: "PhyCalDriver.c" in line: 1641
S 1 28 9 281 Fatal Error in file: "mt_phy_dummy.c"; Fatal Print: Bad PHY mdoe
S 1 28 9 351 Assert in file: "mt_phy_dummy.c" in line: 351
S 1 28 10 449 Assert in file: "PhyDriver.c" in line: 449
S 1 28 10 506 Assert in file: "PhyDriver.c" in line: 506
S 1 28 10 515 Assert in file: "PhyDriver.c" in line: 515
S 1 28 10 614 Assert in file: "PhyDriver.c" in line: 614
S 1 28 10 654 Assert in file: "PhyDriver.c" in line: 654
S 1 28 10 661 Assert in file: "PhyDriver.c" in line: 661
S 1 28 10 801 PhyDrv_DisableBB, %u
S 1 28 10 814 PhyDrv_EnableBB, %u
S 1 28 10 1078 Assert in file: "PhyDriver.c" in line: 1078
S 1 28 10 1103 Assert in file: "PhyDriver.c" in line: 1103
S 1 28 10 1129 Assert in file: "PhyDriver.c" in line: 1129
S 1 28 10 1164 Assert in file: "PhyDriver.c" in line: 1164
S 1 28 10 1325 Assert in file: "PhyDriver.c" in line: 1325
S 1 28 10 1369 Assert in file: "PhyDriver.c" in line: 1369
S 1 28 10 1370 Assert in file: "PhyDriver.c" in line: 1370
S 1 28 10 1395 Fatal Error in file: "PhyDriver.c"; Fatal Print: WD(phy) interrupt occured
S 1 28 10 1528 Assert in file: "PhyDriver.c" in line: 1528
S 1 28 10 1563 1continuousInterfererSample   = %d
S 1 28 13 459 PhyDrv_DisableBB
S 1 28 13 470 PhyDrv_EnableBB
S 1 28 13 619 Assert in file: "PhyDriver.c" in line: 619
S 1 28 13 647 Fatal Error in file: "PhyDriver.c"; Fatal Print: PHY DRV Get TCR All
S 1 28 13 733 ERROR 1 !!! DUT_SetIfsValue, spacingUsec:%d, m_phyDelays[PHY_DID_TIM_SLOT_TIMER]:%d, m_phyDelays[PHY_DID_SIFS]:%d
S 1 28 13 739 ERROR 2 !!! DUT_SetIfsValue, spacingUsec:%d, m_phyDelays[PHY_DID_SIFS]:%d
S 1 28 13 801 Assert in file: "PhyDriver.c" in line: 801
S 1 28 13 888 Assert in file: "PhyDriver.c" in line: 888
S 1 28 13 890 Assert in file: "PhyDriver.c" in line: 890
S 1 28 13 891 Assert in file: "PhyDriver.c" in line: 891
S 1 28 13 901 Fatal Error in file: "PhyDriver.c"; Fatal Print: WD(phy) interrupt occured
S 1 28 13 908 Fatal Error in file: "PhyDriver.c"; Fatal Print: Tx packet interrupt
S 1 28 14 334 Assert in file: "PhyDriver.c" in line: 334
S 1 28 14 344 Fatal Error in file: "PhyDriver.c"; Fatal Print: MIPS halt done
S 1 28 14 465 PhyDrv_ReleaseSWreset
S 1 28 14 654 PhyDrv_DisableBB
S 1 28 14 661 PhyDrv_EnableBB
S 1 28 14 736 Assert in file: "PhyDriver.c" in line: 736
S 1 28 14 760 Fatal Error in file: "PhyDriver.c"; Fatal Print: PHY DRV Get TCR All
S 1 28 14 810 Assert in file: "PhyDriver.c" in line: 810
S 1 28 14 841 Assert in file: "PhyDriver.c" in line: 841
S 1 28 14 888 Assert in file: "PhyDriver.c" in line: 888
S 1 28 14 990 ERROR 1 !!! DUT_SetIfsValue, spacingUsec:%d, m_phyDelays[PHY_DID_TIM_SLOT_TIMER]:%d, m_phyDelays[PHY_DID_SIFS]:%d
S 1 28 14 995 ERROR 2 !!! DUT_SetIfsValue, spacingUsec:%d, m_phyDelays[PHY_DID_SIFS]:%d
S 1 28 14 1054 Assert in file: "PhyDriver.c" in line: 1054
S 1 28 14 1150 Assert in file: "PhyDriver.c" in line: 1150
S 1 28 14 1151 Assert in file: "PhyDriver.c" in line: 1151
S 1 28 14 1159 Assert in file: "PhyDriver.c" in line: 1159
S 1 28 14 1160 Assert in file: "PhyDriver.c" in line: 1160
S 1 28 14 1188 Fatal Error in file: "PhyDriver.c"; Fatal Print: WD(phy) interrupt occured
S 1 28 14 1329 Assert in file: "PhyDriver.c" in line: 1329
S 1 28 14 1402 Assert in file: "PhyDriver.c" in line: 1402
S 1 28 14 1436 PhyDrvInterfererDetection_FlushContinuousInterfererDetectionFifo index = %d continuousInterfererSample = %d 
S 1 28 14 1536 PhyDrv_SetCcaTh  params->midPktSecondary20CCA  =%d
S 1 28 14 1537 PhyDrv_SetCcaTh  params->midPktSecondary40CCA  =%d
S 1 28 14 1538 PhyDrv_SetCcaTh  params->midPktPrimaryCCA  =%d
S 1 28 14 1539 PhyDrv_SetCcaTh  params->primaryChCCA  =%d
S 1 28 14 1540 PhyDrv_SetCcaTh  params->secondaryChCCA  =%d
S 1 28 14 1569 PhyDrv_getCcaTh  params->midPktSecondary20CCA  =%d
S 1 28 14 1570 PhyDrv_getCcaTh  params->midPktSecondary40CCA  =%d
S 1 28 14 1571 PhyDrv_getCcaTh  params->midPktPrimaryCCA  =%d
S 1 28 14 1572 PhyDrv_getCcaTh  params->primaryChCCA  =%d
S 1 28 14 1573 PhyDrv_getCcaTh  params->secondaryChCCA  =%d
S 1 28 14 1618 Assert in file: "PhyDriver.c" in line: 1618
S 1 28 14 1649 Assert in file: "PhyDriver.c" in line: 1649
S 1 28 14 1678 Assert in file: "PhyDriver.c" in line: 1678
S 1 28 15 121 Assert in file: "PhyTestBus.c" in line: 121
S 1 28 15 141 Assert in file: "PhyTestBus.c" in line: 141
S 1 28 15 165 Fatal Error in file: "PhyTestBus.c"; Fatal Print: PhyTestBus_Read, illegal case
S 1 28 16 701 Assert in file: "RficDriver.c" in line: 701
S 1 28 16 748 Assert in file: "RficDriver.c" in line: 748
S 1 28 16 793 Assert in file: "RficDriver.c" in line: 793
S 1 28 16 1033 Assert in file: "RficDriver.c" in line: 1033
S 1 28 16 1152 Assert in file: "RficDriver.c" in line: 1152
S 1 28 16 1153 Assert in file: "RficDriver.c" in line: 1153
S 1 28 16 1154 Assert in file: "RficDriver.c" in line: 1154
S 1 28 16 1230 Assert in file: "RficDriver.c" in line: 1230
S 1 28 16 1342 Assert in file: "RficDriver.c" in line: 1342
S 1 28 16 1404 Assert in file: "RficDriver.c" in line: 1404
S 1 28 16 1452 Assert in file: "RficDriver.c" in line: 1452
S 1 28 16 1493 Assert in file: "RficDriver.c" in line: 1493
S 1 28 16 1537 Assert in file: "RficDriver.c" in line: 1537
S 1 28 16 1577 Assert in file: "RficDriver.c" in line: 1577
S 1 28 16 1682 Assert in file: "RficDriver.c" in line: 1682
S 1 28 16 1760 Assert in file: "RficDriver.c" in line: 1760
S 1 28 16 1775 Assert in file: "RficDriver.c" in line: 1775
S 1 28 16 1842 Assert in file: "RficDriver.c" in line: 1842
S 1 28 16 1928 RficDriver_SetFrequency
S 1 28 16 1955 [RficDriver_SetFrequency], Flo = %d
S 1 28 16 2114 Assert in file: "RficDriver.c" in line: 2114
S 1 28 16 2228 Assert in file: "RficDriver.c" in line: 2228
S 1 28 16 2328 Assert in file: "RficDriver.c" in line: 2328
S 1 28 16 2386 Assert in file: "RficDriver.c" in line: 2386
S 1 28 16 2469 Assert in file: "RficDriver.c" in line: 2469
S 1 28 16 2470 Assert in file: "RficDriver.c" in line: 2470
S 1 28 16 2510 Assert in file: "RficDriver.c" in line: 2510
S 1 28 16 2511 Assert in file: "RficDriver.c" in line: 2511
S 1 28 16 2587 Assert in file: "RficDriver.c" in line: 2587
S 1 28 16 2627 Assert in file: "RficDriver.c" in line: 2627
S 1 28 16 2760 Assert in file: "RficDriver.c" in line: 2760
S 1 28 20 705 Assert in file: "RficDriver.c" in line: 705
S 1 28 20 752 Assert in file: "RficDriver.c" in line: 752
S 1 28 20 929 Assert in file: "RficDriver.c" in line: 929
S 1 28 20 1025 Assert in file: "RficDriver.c" in line: 1025
S 1 28 20 1085 Assert in file: "RficDriver.c" in line: 1085
S 1 28 20 1334 Assert in file: "RficDriver.c" in line: 1334
S 1 28 20 1349 Assert in file: "RficDriver.c" in line: 1349
S 1 28 20 1416 Assert in file: "RficDriver.c" in line: 1416
S 1 28 20 1509 RficDriver_SetFrequency freq = %d, bw = %d
S 1 28 20 1858 Assert in file: "RficDriver.c" in line: 1858
S 1 28 20 1916 Assert in file: "RficDriver.c" in line: 1916
S 1 28 20 1988 Assert in file: "RficDriver.c" in line: 1988
S 1 28 20 2026 Assert in file: "RficDriver.c" in line: 2026
S 1 28 20 2101 Assert in file: "RficDriver.c" in line: 2101
S 1 28 20 2115 Assert in file: "RficDriver.c" in line: 2115
S 1 28 20 2194 Assert in file: "RficDriver.c" in line: 2194
S 1 28 20 2229 Assert in file: "RficDriver.c" in line: 2229
S 1 28 20 2890 Assert in file: "RficDriver.c" in line: 2890
S 1 28 20 2901 Assert in file: "RficDriver.c" in line: 2901
S 1 29 2 705 Assert in file: "RficDriver.c" in line: 705
S 1 29 2 752 Assert in file: "RficDriver.c" in line: 752
S 1 29 2 1036 Assert in file: "RficDriver.c" in line: 1036
S 1 29 2 1132 Assert in file: "RficDriver.c" in line: 1132
S 1 29 2 1192 Assert in file: "RficDriver.c" in line: 1192
S 1 29 2 1254 Assert in file: "RficDriver.c" in line: 1254
S 1 29 2 1302 Assert in file: "RficDriver.c" in line: 1302
S 1 29 2 1343 Assert in file: "RficDriver.c" in line: 1343
S 1 29 2 1387 Assert in file: "RficDriver.c" in line: 1387
S 1 29 2 1427 Assert in file: "RficDriver.c" in line: 1427
S 1 29 2 1529 Assert in file: "RficDriver.c" in line: 1529
S 1 29 2 1607 Assert in file: "RficDriver.c" in line: 1607
S 1 29 2 1622 Assert in file: "RficDriver.c" in line: 1622
S 1 29 2 1689 Assert in file: "RficDriver.c" in line: 1689
S 1 29 2 1793 RficDriver_SetFrequency freq = %d, bw = %d
S 1 29 2 1949 Assert in file: "RficDriver.c" in line: 1949
S 1 29 2 2149 Assert in file: "RficDriver.c" in line: 2149
S 1 29 2 2207 Assert in file: "RficDriver.c" in line: 2207
S 1 29 2 2279 Assert in file: "RficDriver.c" in line: 2279
S 1 29 2 2321 Assert in file: "RficDriver.c" in line: 2321
S 1 29 2 2528 Assert in file: "RficDriver.c" in line: 2528
S 1 29 2 2563 Assert in file: "RficDriver.c" in line: 2563
S 1 28 22 217 Assert in file: "PSD.c" in line: 217
S 1 28 22 292 Assert in file: "PSD.c" in line: 292
S 1 28 22 303 Assert in file: "PSD.c" in line: 303
S 1 28 22 395 Assert in file: "PSD.c" in line: 395
S 1 28 22 431 Assert in file: "PSD.c" in line: 431
S 1 28 22 472 Assert in file: "PSD.c" in line: 472
S 1 28 22 512 Assert in file: "PSD.c" in line: 512
S 1 28 22 591 Assert in file: "PSD.c" in line: 591
S 1 28 22 592 Assert in file: "PSD.c" in line: 592
S 1 28 22 630 Assert in file: "PSD.c" in line: 630
S 1 28 22 677 Assert in file: "PSD.c" in line: 677
S 1 28 22 1048 Assert in file: "PSD.c" in line: 1048
S 1 28 24 103 LmHdk_init
S 1 30 5 176 Fatal Error in file: "HostGenRiscInterface.c"; Fatal Print: Host Interface 2 MIPS Error Start
S 1 30 5 192 Fatal Error in file: "HostGenRiscInterface.c"; Fatal Print: Unsupported Message ID
S 1 30 5 217 Fatal Error in file: "HostGenRiscInterface.c"; Fatal Print: Unsupported Message ID
S 1 30 5 229 Fatal Error in file: "HostGenRiscInterface.c"; Fatal Print: Host Interface 2 MIPS Unknown event
S 1 30 5 412 Assert in file: "HostGenRiscInterface.c" in line: 412
S 1 30 5 443 Assert in file: "HostGenRiscInterface.c" in line: 443
S 1 30 5 494 Assert in file: "HostGenRiscInterface.c" in line: 494
S 1 31 0 489 Assert in file: "HostInterface.c" in line: 489
S 1 31 0 518 Fatal Error in file: "HostInterface.c"; Fatal Print: Error buffer descriptor in FIFO!
S 1 31 0 540 Assert in file: "HostInterface.c" in line: 540
S 1 31 0 619 Ts Manager, Send Confirmation, Client %d, SID %d
S 1 31 0 736 Assert in file: "HostInterface.c" in line: 736
S 1 31 0 739 Assert in file: "HostInterface.c" in line: 739
S 1 31 0 751 Assert in file: "HostInterface.c" in line: 751
S 1 31 0 1009 Assert in file: "HostInterface.c" in line: 1009
S 1 31 0 1018 Assert in file: "HostInterface.c" in line: 1018
S 1 31 0 1053 Fatal Error in file: "HostInterface.c"; Fatal Print: Error buffer descriptor in FIFO!
S 1 31 0 1139 Assert in file: "HostInterface.c" in line: 1139
S 1 31 0 1178 Assert in file: "HostInterface.c" in line: 1178
S 1 31 1 339 Assert in file: "HostInterfaceRings.c" in line: 339
S 1 31 1 387 Assert in file: "HostInterfaceRings.c" in line: 387
S 1 31 1 395 Assert in file: "HostInterfaceRings.c" in line: 395
S 1 31 1 396 Assert in file: "HostInterfaceRings.c" in line: 396
S 1 31 1 424 Assert in file: "HostInterfaceRings.c" in line: 424
S 1 31 1 434 Assert in file: "HostInterfaceRings.c" in line: 434
S 1 31 1 676 Assert in file: "HostInterfaceRings.c" in line: 676
S 1 31 1 905 Assert in file: "HostInterfaceRings.c" in line: 905
S 1 31 1 934 Assert in file: "HostInterfaceRings.c" in line: 934
S 1 31 1 935 Assert in file: "HostInterfaceRings.c" in line: 935
S 1 31 1 968 Assert in file: "HostInterfaceRings.c" in line: 968
S 1 31 1 969 Assert in file: "HostInterfaceRings.c" in line: 969
S 1 31 3 67 Assert in file: "HostInterfaceAcc.c" in line: 67
S 1 31 3 73 Assert in file: "HostInterfaceAcc.c" in line: 73
S 1 31 3 156 Assert in file: "HostInterfaceAcc.c" in line: 156
S 1 31 3 240 HostIfAcc_SetPdThreshold - %d
S 1 31 2 440 HostIfAcc_SetPdThreshold - %d
S 1 32 4 83 [Pac_DurEnableNavInitMode] - WAVE400------------------------------------end]
S 1 32 5 299 [Pac_RxcEnableRssiAbort]--WAVE400
S 1 32 5 323 [Pac_RxcDisableRssiAbort]--WAVE400
S 1 32 6 588 [Pac_RxdConfigureRssiMode]---WAVE400------------------------end]
S 1 32 7 274 Assert in file: "PacRxf.c" in line: 274
S 1 32 7 277 [Pac_RxfSetMACAddressfilter] before, sRXF.asLFCs[0].u32Ref1 = %x, sRXF.asLFCs[0].u32Ref2 = %x, sRXF.asLFCs[0].u32Control = %x
S 1 32 7 284 Assert in file: "PacRxf.c" in line: 284
S 1 32 7 332 [Pac_RxfSetMACAddressfilter] after, sRXF.asLFCs[0].u32Ref1 = %x, sRXF.asLFCs[0].u32Ref2 = %x, sRXF.asLFCs[0].u32Control = %x
S 1 32 7 336 [Pac_RxfSetMACAddressfilter]---WAVE400----------------------end]
S 1 32 7 352 Assert in file: "PacRxf.c" in line: 352
S 1 32 7 381 [Pac_RxfUseFixedVapId] - WAVE400------------------------------------end]
S 1 32 7 419 [Pac_RxfNormalVapId]---WAVE400------------------------------end]
S 1 32 8 148 Assert in file: "PacTim.c" in line: 148
S 1 32 9 291 LmUtil_setIfsValue, ifsValue[ifs resolution]:%d, spacingUsec:%d, PhyDrv_GetDelayValue(PHY_DID_PIFS):%d
S 1 32 20 134 Assert in file: "Pac.c" in line: 134
S 1 32 23 143 Assert in file: "PacDeliniator.c" in line: 143
S 1 32 24 149 Assert in file: "PacDur.c" in line: 149
S 1 32 26 489 Fatal Error in file: "PacRxd.c"; Fatal Print: Pac_RxdConfigureScanMode
S 1 32 27 255 Assert in file: "PacRxf.c" in line: 255
S 1 32 27 371 Assert in file: "PacRxf.c" in line: 371
S 1 32 27 593 Assert in file: "PacRxf.c" in line: 593
S 1 32 27 603 Assert in file: "PacRxf.c" in line: 603
S 1 32 27 610 [Pac_RxfSetMACAddressfilter], PacManagerGlobalParameters->longFilter0Ref1RegNormal = %x
S 1 32 27 611 [Pac_RxfSetMACAddressfilter], PacManagerGlobalParameters->longFilter0Ref2RegNormal = %x
S 1 32 27 645 [Pac_RxfSetMACAddressfilter], longFilterRef1Address = %x
S 1 32 27 646 [Pac_RxfSetMACAddressfilter], longFilter0Ref1Reg.val = %x
S 1 32 27 647 [Pac_RxfSetMACAddressfilter], longFilterRef2Address = %x
S 1 32 27 648 [Pac_RxfSetMACAddressfilter], longFilter0Ref2Reg.val = %x
S 1 32 27 668 Assert in file: "PacRxf.c" in line: 668
S 1 32 27 743 [Pac_RxfNormalVapId], pLocalPacManagerGlobalParameters->vapIdBitMap = %d
S 1 32 27 744 [Pac_RxfNormalVapId], longFilterRef1Address = %x
S 1 32 27 745 [Pac_RxfNormalVapId], pLocalPacManagerGlobalParameters->longFilter0Ref1RegNormal = %x
S 1 32 27 746 [Pac_RxfNormalVapId], longFilterRef2Address = %x
S 1 32 27 747 [Pac_RxfNormalVapId], pLocalPacManagerGlobalParameters->longFilter0Ref2RegNormal = %x
S 1 6 3 171 Assert in file: "HwErrors.c" in line: 171
S 1 6 3 191 hwErrorsRxcRxBufferOverflow rxBufferOverflowDroppedMpdus = %d
S 1 6 3 245 Assert in file: "HwErrors.c" in line: 245
S 1 6 3 264 Assert in file: "HwErrors.c" in line: 264
S 1 6 3 279 Assert in file: "HwErrors.c" in line: 279
S 1 6 3 367 Fatal Error in file: "HwErrors.c"; Fatal Print: hwErrorsRxEof
S 1 6 3 407 Fatal Error in file: "HwErrors.c"; Fatal Print: hwErrorsRxAggr
S 1 6 3 450 Assert in file: "HwErrors.c" in line: 450
S 1 6 3 477 Fatal Error in file: "HwErrors.c"; Fatal Print: hwErrorsTxSelector
S 1 6 3 495 Fatal Error in file: "HwErrors.c"; Fatal Print: hwErrorsTxSelector
S 1 6 3 513 Assert in file: "HwErrors.c" in line: 513
S 1 6 3 536 Assert in file: "HwErrors.c" in line: 536
S 1 6 3 551 Assert in file: "HwErrors.c" in line: 551
S 1 6 3 565 Assert in file: "HwErrors.c" in line: 565
S 1 6 3 579 Assert in file: "HwErrors.c" in line: 579
S 1 6 3 592 Assert in file: "HwErrors.c" in line: 592
S 1 6 3 606 Assert in file: "HwErrors.c" in line: 606
S 1 6 3 627 Fatal Error in file: "HwErrors.c"; Fatal Print: hwErrorsDelineatorFifoOverflow
S 1 6 3 721 Assert in file: "HwErrors.c" in line: 721
S 1 6 3 729 isr_HwErrors errorIndex %d num of errors %d
S 1 6 4 162 Assert in file: "HwEvents.c" in line: 162
S 1 6 4 254 Fatal Error in file: "HwEvents.c"; Fatal Print: hwEventsRxClassifierRekey
S 1 6 5 273 Assert in file: "HwLogger.c" in line: 273
S 1 6 5 355 Assert in file: "HwLogger.c" in line: 355
S 1 6 5 356 Assert in file: "HwLogger.c" in line: 356
S 1 6 5 387 Assert in file: "HwLogger.c" in line: 387
S 1 6 5 570 Assert in file: "HwLogger.c" in line: 570
S 1 6 5 586 Assert in file: "HwLogger.c" in line: 586
S 1 6 5 806 Assert in file: "HwLogger.c" in line: 806
S 1 6 5 863 Assert in file: "HwLogger.c" in line: 863
S 1 6 5 2238 Fatal Error in file: "HwLogger.c"; Fatal Print: hwLoggerEnableDisableUnknown
S 1 6 5 2269 Fatal Error in file: "HwLogger.c"; Fatal Print: hwLoggerEnableDisableMuLockerLogs
S 1 6 5 2274 Fatal Error in file: "HwLogger.c"; Fatal Print: hwLoggerEnableDisablePacExtraLogs
S 1 6 5 2279 Fatal Error in file: "HwLogger.c"; Fatal Print: hwLoggerEnableDisableMuBfLogs
S 1 6 5 2284 Fatal Error in file: "HwLogger.c"; Fatal Print: hwLoggerEnableDisableMuBitmapSelectLogs
S 1 6 6 371 Assert in file: "HwQManager.c" in line: 371
S 1 6 6 399 Assert in file: "HwQManager.c" in line: 399
S 1 6 6 429 Assert in file: "HwQManager.c" in line: 429
S 1 6 6 458 Assert in file: "HwQManager.c" in line: 458
S 1 6 6 487 Assert in file: "HwQManager.c" in line: 487
S 1 6 6 516 Assert in file: "HwQManager.c" in line: 516
S 1 6 6 546 Assert in file: "HwQManager.c" in line: 546
S 1 6 6 574 Assert in file: "HwQManager.c" in line: 574
S 1 34 0 548 Assert in file: "RxQueues.c" in line: 548
S 1 34 0 591 Assert in file: "RxQueues.c" in line: 591
S 1 34 0 599 Assert in file: "RxQueues.c" in line: 599
S 1 34 0 607 Assert in file: "RxQueues.c" in line: 607
S 1 34 0 766 Assert in file: "RxQueues.c" in line: 766
S 1 34 0 788 Assert in file: "RxQueues.c" in line: 788
S 1 6 8 191 Assert in file: "HwQManager.c" in line: 191
S 1 6 8 194 Assert in file: "HwQManager.c" in line: 194
S 1 6 8 200 Assert in file: "HwQManager.c" in line: 200
S 1 6 8 262 Assert in file: "HwQManager.c" in line: 262
S 1 6 8 684 HwQManager_ErrorEvent: 0x%X 
S 1 6 8 686 Fatal Error in file: "HwQManager.c"; Fatal Print: HW Q Manager Error Event
S 1 6 8 713 Assert in file: "HwQManager.c" in line: 713
S 1 6 8 744 Assert in file: "HwQManager.c" in line: 744
S 1 6 8 778 Assert in file: "HwQManager.c" in line: 778
S 1 37 2 116 ContinuousInterfererDetectionGlobalParameters.maxMeasuremenet = %d continuousInterfererMessageParameters.channel: %d
S 1 37 2 205 continuousInterfererMessageParameters.maximumValue = %d continuousInterfererMessageParameters.channel: %d
S 1 37 1 144 Assert in file: "RadarDetection.c" in line: 144
S 1 37 1 192 Assert in file: "RadarDetection.c" in line: 192
S 1 37 1 235 Assert in file: "RadarDetection.c" in line: 235
S 1 37 1 269 Assert in file: "RadarDetection.c" in line: 269
S 1 37 1 313 Assert in file: "RadarDetection.c" in line: 313
S 1 37 1 388 Assert in file: "RadarDetection.c" in line: 388
S 1 37 1 393 Assert in file: "RadarDetection.c" in line: 393
S 1 37 1 446 Assert in file: "RadarDetection.c" in line: 446
S 1 37 1 532 Assert in file: "RadarDetection.c" in line: 532
S 1 37 1 555 Assert in file: "RadarDetection.c" in line: 555
S 1 37 1 659 Assert in file: "RadarDetection.c" in line: 659
S 1 37 1 660 Assert in file: "RadarDetection.c" in line: 660
S 1 37 1 668 Assert in file: "RadarDetection.c" in line: 668
S 1 37 1 672 Assert in file: "RadarDetection.c" in line: 672
S 1 37 1 735 Assert in file: "RadarDetection.c" in line: 735
S 1 37 1 905 Assert in file: "RadarDetection.c" in line: 905
S 1 37 1 906 Assert in file: "RadarDetection.c" in line: 906
S 1 38 0 437 Fatal Error in file: "InterruptManager.c"; Fatal Print: Spurious Interrupt
S 1 38 0 471 Assert in file: "InterruptManager.c" in line: 471
S 1 38 0 477 Assert in file: "InterruptManager.c" in line: 477
S 1 38 0 519 Assert in file: "InterruptManager.c" in line: 519
S 1 38 0 523 Assert in file: "InterruptManager.c" in line: 523
S 1 38 0 681 Assert in file: "InterruptManager.c" in line: 681
S 1 39 0 78 IPC UM Debug - MSG from other core: %d : MsgType: 0x%x
S 1 39 0 80 IPC LM Debug - MSG from other core: %d : MsgType: 0x%x
S 1 39 0 137 Assert in file: "ipc.c" in line: 137
S 1 39 0 269 Assert in file: "ipc.c" in line: 269
S 1 40 0 183 Fatal Error in file: "kccmsg.c"; Fatal Print: pre-allocated message space insufficient
S 1 40 0 200 Assert in file: "kccmsg.c" in line: 200
S 1 40 0 201 Assert in file: "kccmsg.c" in line: 201
S 1 40 0 202 Assert in file: "kccmsg.c" in line: 202
S 1 40 0 203 Assert in file: "kccmsg.c" in line: 203
S 1 40 0 217 Assert in file: "kccmsg.c" in line: 217
S 1 40 0 253 Fatal Error in file: "kccmsg.c"; Fatal Print: Tried to increase a reference count past limit
S 1 41 0 145 AntennaSelectionAddSta. ActivatedAntennasCount %d antSelMask %d
S 1 41 0 193 AntennaSelectionSetNextProbingPoint
S 1 41 0 205 AntennaSelectionSetNextProbingPoint. nextprobingMask 0x%x
S 1 41 0 261 AntennaSelectionProcessFeedback
S 1 41 0 304 AntennaSelectionProcessFeedback. PB is better than WP - change WP!
S 1 41 0 332 AntennaSelectionProcessFeedback - SET RATE + 1
S 1 41 0 482 setAntSelParams. numOfAntennas %d isLimitingState %d validAntennas %d 
S 1 41 0 507 getPermutation. antennasIndex %d permutationIndex %d 
S 1 41 0 509 Assert in file: "AntennaSelection.c" in line: 509
S 1 41 0 510 Assert in file: "AntennaSelection.c" in line: 510
S 1 41 0 552 increaseAntSelectionProbingIndices. nextPermutation 0x%x antennaIndex %d permutationIndex %d 
S 1 41 0 600 increaseAntSelectionProbingIndices. validPermutationFound %d ActivatedAntennasBitmap 0x%x 
S 1 41 0 635 Assert in file: "AntennaSelection.c" in line: 635
S 1 41 0 684 Assert in file: "AntennaSelection.c" in line: 684
S 1 41 0 766 Assert in file: "AntennaSelection.c" in line: 766
S 1 41 0 848 Assert in file: "AntennaSelection.c" in line: 848
S 1 41 0 1114 setAntSelectionInStaTcr 0x%x isProbing: %d
S 1 41 0 1148 AntSelectionModificationFunc.numOfAntsPp %d, change also CDD
S 1 41 0 1259 AntennaSelectionBfModeIsChanged. newBfMode %d
S 1 41 17 376 Assert in file: "Beamforming.c" in line: 376
S 1 41 17 920 linkAdaptationHandleAgingTimerEvent
S 1 41 2 230 Assert in file: "BwAdaptation.c" in line: 230
S 1 41 2 259 Assert in file: "BwAdaptation.c" in line: 259
S 1 41 2 362 Fatal Error in file: "BwAdaptation.c"; Fatal Print: BwSetNextProbingPoint
S 1 41 2 372 Assert in file: "BwAdaptation.c" in line: 372
S 1 41 2 392 Fatal Error in file: "BwAdaptation.c"; Fatal Print: BwSetNextProbingPoint - No probing should be done if BW loop is not activate
S 1 41 18 95 CddAddSta: %d cddIndex: %d
S 1 41 18 135 non effective loop
S 1 41 18 191 CddProcessFeedback, workingPointPer = %d, slowProbingPointPer = %d
S 1 41 18 217 PB is better than WP - change WP!
S 1 41 18 245 CddProcessFeedback - SET RATE + 1
S 1 41 18 300 validRate: %d antennaCount: %d stbc: %d
S 1 41 18 320 CddStaNumOfAntsIsChanged: antCount %d
S 1 41 18 389 nextPermutation: 0x%x
S 1 41 18 397 cddIndex: %d
S 1 41 18 444 setCddInStaTcr. cddAnt1: %d cddAnt2: %d cddAnt3: %d
S 1 41 18 468 setCddValues. cddAnt1 %d, cddAnt2 %d cddAnt3 %d
S 1 41 18 483 setCddFixedValues. cddAnt1 %d, cddAnt2 %d cddAnt3 %d
S 1 41 18 494 getPermutation. antCount%d
S 1 41 18 496 Assert in file: "CDD.c" in line: 496
S 1 41 18 497 Assert in file: "CDD.c" in line: 497
S 1 41 18 519 tcrCddAnt1: %d tcrCddAnt2: %d tcrCddAnt3: %d
S 1 41 18 528 sameAsWorkingPoint = %d
S 1 41 3 305 CyclicPrefixSetNextProbingPoint, tcrCpTable[%d] = %d
S 1 41 3 394 Assert in file: "CyclicPrefix.c" in line: 394
S 1 41 3 444 CyclicPrefixProcessFeedback,workingPointPer = %d,slowProbingPointPer = %d, effectiveTpWp = %d,  effectiveTpProbing = %d
S 1 41 3 456 CyclicPrefixProcessFeedback, Chane WP, tcrCpTable[%d] = =%d
S 1 41 3 492 Assert in file: "CyclicPrefix.c" in line: 492
S 1 41 3 496 CyclicPrefix - SET RATE + 1
S 1 41 3 573 Assert in file: "CyclicPrefix.c" in line: 573
S 1 41 4 423 estimatorsResetFastProbingFilters
S 1 41 4 782 Assert in file: "Estimators.c" in line: 782
S 1 41 4 825 Assert in file: "Estimators.c" in line: 825
S 1 41 4 834 Assert in file: "Estimators.c" in line: 834
S 1 41 4 1009 Assert in file: "Estimators.c" in line: 1009
S 1 41 4 1081 Assert in file: "Estimators.c" in line: 1081
S 1 41 4 1171 Assert in file: "Estimators.c" in line: 1171
S 1 41 4 1201 estimatorsProcessBaaReport, rate changed, new rate = %d
S 1 41 4 1345 Assert in file: "Estimators.c" in line: 1345
S 1 41 4 1629 estimatorsSlowProbingDbUpdate av per,RateIndex = %d,bandwidth = %d,filterinput = %d, filterResult = %d, alpha = %d
S 1 41 4 1679 calculatePer, resWeighted = %d, resMPduNum = %d, resLength = %d
S 1 41 4 1683 Assert in file: "Estimators.c" in line: 1683
S 1 41 4 1740 Assert in file: "Estimators.c" in line: 1740
S 1 41 4 1765 Assert in file: "Estimators.c" in line: 1765
S 1 41 4 1797 Assert in file: "Estimators.c" in line: 1797
S 1 41 4 1856 estimatorsProbingValidationCriteria,currentPacketTsf = %d, probeIsValid = %d, currentTsfMod = %d, tsfDiff = %d, validationCounter = %d
S 1 41 4 1944 estimatorsAgingCheck, staId = %d, Station's grade is - %d
S 1 41 4 1995 Fatal Error in file: "Estimators.c"; Fatal Print: estimatorsSetSlowProbingPointRateIndex
S 1 41 4 2065 Assert in file: "Estimators.c" in line: 2065
S 1 41 4 2110 Assert in file: "Estimators.c" in line: 2110
S 1 41 4 2156 Assert in file: "Estimators.c" in line: 2156
S 1 41 4 2195 estimatorsProcessSequencerReport, staId = %d, Station's grade is - %d
S 1 41 4 2222 Sequencer estimaror processing - goodput update, current totalgroup's avgGoodput = %d, normAvgGoodput %d, groupId %d
S 1 41 4 2268 estimatorsProcessSequencerReport recovery
S 1 41 4 2296 estimatorsProcessSequencerReport, rate changed, new rate = %d
S 1 41 4 2505 Assert in file: "Estimators.c" in line: 2505
S 1 41 4 2666 Assert in file: "Estimators.c" in line: 2666
S 1 41 4 2668 fastDropEstimator, windowFailedPacketBitmap = %d, numberOfFailedPacketInWindow = %d,  consFailMask = %d, numbOfFailsinWind = %d, consequtiveFailsCondition = %d, FailIndication = %d
S 1 41 4 2725 Assert in file: "Estimators.c" in line: 2725
S 1 41 4 2744 estimatorsFastProbingSearchMaxEffTp, AvPerFilter: filetrResult = %d, alpha = %d, Last TSF = %d
S 1 41 4 2818 Assert in file: "Estimators.c" in line: 2818
S 1 41 4 2861 Assert in file: "Estimators.c" in line: 2861
S 1 41 4 2906 Assert in file: "Estimators.c" in line: 2906
S 1 41 4 2913 Assert in file: "Estimators.c" in line: 2913
S 1 41 4 2917 Assert in file: "Estimators.c" in line: 2917
S 1 41 4 2950 linkAdaptationCalcMuCandidacyGrade - stationInPsWithinAwindowCount =%d 
S 1 41 4 2951 linkAdaptationCalcMuCandidacyGrade - lowFrameRateCounter =%d 
S 1 41 4 2952 linkAdaptationCalcMuCandidacyGrade - wpAverageGoodPut =%d 
S 1 41 13 662 Assert in file: "PowerAdaptation.c" in line: 662
S 1 41 13 816 PowerSetNextProbingPointAndIndications,wpPower = %d, newProbingPower = %d
S 1 41 13 835 PowerSetNextProbingPointAndIndications,probingPower = %d, newProbingPower = %d
S 1 41 13 841 PowerSetNextProbingPointAndIndications, Bw %d, newPower = %d
S 1 41 13 987 PowerProcessFeedback, workingPointPer = %d, slowProbingPointPer = %d
S 1 41 13 1047 PowerProcessFeedback, Change power working point, BW %d, newPower = %d
S 1 41 13 1061 PowerProcessFeedback - SET RATE + 1
S 1 41 13 1131 powerStepTemp %d
S 1 41 13 1159 powerStepTemp %d
S 1 41 13 1179 *pAdditionalStep %d minAbsPowerStep %d
S 1 41 13 1195 nextStepTemp %d
S 1 41 13 1208 *pAdditionalStep %d
S 1 41 13 1265 CalcLimitsAndGetStaTcrPowerVal, Bw = %d, rateIndex = %d, powerVal = %d, newPower = %d, newTcrPowerVal = %d
S 1 41 13 1377 Assert in file: "PowerAdaptation.c" in line: 1377
S 1 41 13 1536 Assert in file: "PowerAdaptation.c" in line: 1536
S 1 41 13 1676 Assert in file: "PowerAdaptation.c" in line: 1676
S 1 41 13 1789 mcs:%d, mss:%d
S 1 41 13 1798 Assert in file: "PowerAdaptation.c" in line: 1798
S 1 41 13 1830 Assert in file: "PowerAdaptation.c" in line: 1830
S 1 41 13 1837 Assert in file: "PowerAdaptation.c" in line: 1837
S 1 41 13 1883 Assert in file: "PowerAdaptation.c" in line: 1883
S 1 41 13 1945 calcInternalLowerLimit, Limit = %d
S 1 41 13 1974 calcExternalLowerLimit, BW %d, Limit = %d
S 1 41 13 2013 calcExternalUpperLimit, BW %d, Limit = %d
S 1 41 13 2199 PowerAdaptationCalcPowerInStaLimits, newPower = %d, isPowerBlocked = %d
S 1 41 13 2527 Assert in file: "PowerAdaptation.c" in line: 2527
S 1 41 13 2553 Assert in file: "PowerAdaptation.c" in line: 2553
S 1 41 13 2555 GetInitialRateAccordingToRssi,rssiVal = %d,  phyMode = %d, initialRateIndex = %d
S 1 41 6 311 Assert in file: "LinkAdaptationPhyDriver.c" in line: 311
S 1 41 6 335 Assert in file: "LinkAdaptationPhyDriver.c" in line: 335
S 1 41 6 341 pDataTcr1->tcr1TxPower = %d
S 1 41 6 432 Assert in file: "LinkAdaptationPhyDriver.c" in line: 432
S 1 41 6 505 Assert in file: "LinkAdaptationPhyDriver.c" in line: 505
S 1 41 6 853 Assert in file: "LinkAdaptationPhyDriver.c" in line: 853
S 1 41 6 868 Assert in file: "LinkAdaptationPhyDriver.c" in line: 868
S 1 41 6 1285 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1285
S 1 41 6 1507 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1507
S 1 41 6 1532 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1532
S 1 41 6 1646 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1646
S 1 41 6 1754 bwAdaptationSetStationBwLimit, laDatabase->bwAdaptationDb.maxSupportedBw = %d
S 1 41 6 1802 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1802
S 1 41 6 1824 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1824
S 1 41 6 1911 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1911
S 1 41 6 2067 Assert in file: "LinkAdaptationPhyDriver.c" in line: 2067
S 1 41 6 2208 Assert in file: "LinkAdaptationPhyDriver.c" in line: 2208
S 1 41 6 2210 Assert in file: "LinkAdaptationPhyDriver.c" in line: 2210
S 1 41 6 2245 Assert in file: "LinkAdaptationPhyDriver.c" in line: 2245
S 1 41 9 115 Assert in file: "LinkAdaptationProductAdjustment.c" in line: 115
S 1 41 11 76 [LinkAdaptation_QAMplusInit] Wave500B, QAMplusEnableFromLm = %d
S 1 41 14 219 Assert in file: "ProtectionAdaptation.c" in line: 219
S 1 41 14 244 Assert in file: "ProtectionAdaptation.c" in line: 244
S 1 41 14 307 Assert in file: "ProtectionAdaptation.c" in line: 307
S 1 41 14 335 Assert in file: "ProtectionAdaptation.c" in line: 335
S 1 41 14 337 Assert in file: "ProtectionAdaptation.c" in line: 337
S 1 41 14 382 Assert in file: "ProtectionAdaptation.c" in line: 382
S 1 41 14 412 ProtectionAdaptation_VapSm - vapCollisionTotalRatio is very high : %d, Ackbitmap:%d, Ctsbitmap:%d
S 1 41 14 421 ProtectionAdaptation_VapSm -got indication for invalid VAP 
S 1 41 14 434 ProtectionAdaptation_VapSm -VAP in PROTECTION_NONE_STATE collsion Count : %d
S 1 41 14 439 ProtectionAdaptation_VapSm -Transition to threshold - collsion Count : %d
S 1 41 14 449 Assert in file: "ProtectionAdaptation.c" in line: 449
S 1 41 14 461 ProtectionAdaptation_VapSm - VAP state:  VAP_PROTECTION_THRESHOLD_STATE
S 1 41 14 476 ProtectionAdaptation_VapSm - Transition to  VAP_PROTECTION_NONE_STATE
S 1 41 14 496 ProtectionAdaptation_VapSm - Transition to  VAP_PROTECTION_NONE_STATE - protection doen't improve
S 1 41 14 510 Assert in file: "ProtectionAdaptation.c" in line: 510
S 1 41 14 515 ProtectionAdaptation_VapSm -VAP state: VAP_PROTECTION_FORCED_STATE
S 1 41 14 520 ProtectionAdaptation_VapSm -transition to VAP_PROTECTION_NONE_STATE
S 1 41 14 532 Assert in file: "ProtectionAdaptation.c" in line: 532
S 1 41 14 564 protectionAdaptationStaSm - staCollisionCount : %d, Ackbitmap:%d, Ctsbitmap:%d
S 1 41 14 566 protectionAdaptationStaSm - staCollisionCount is very high
S 1 41 14 575 protectionAdaptationStaSm -statino state: STA_PROTECTION_NONE_STATE
S 1 41 14 581 protectionAdaptationStaSm -transition to STA_THRESHOLD_MODE vapStaCollisionDelta = %d
S 1 41 14 590 protectionAdaptationStaSm -statino state: STA_PROTECTION_THRESHOLD_STATE  vapStaCollisionDelta = %d
S 1 41 14 595 protectionAdaptationStaSm -transition to STA_FORCE_PROTECTION_MODE vapStaCollisionDelta = %d
S 1 41 14 608 protectionAdaptationStaSm -transition to STA_NO_PROTECTION_MODE vapStaCollisionDelta = %d
S 1 41 14 618 protectionAdaptationStaSm -transition to STA_NO_PROTECTION_MODE vapStaCollisionDelta = %d
S 1 41 14 629 protectionAdaptationStaSm -statino state: STA_PROTECTION_FORCE_STATE vapStaCollisionDelta = %d
S 1 41 14 634 protectionAdaptationStaSm -transition to STA_THRESHOLD_MODE - delta exceed threshold, delta = %d
S 1 41 14 649 protectionAdaptationStaSm -transition to STA_NO_PROTECTION_MODE - No improvement with protection vapStaCollisionDelta = %d
S 1 41 14 671 protectionAdaptationStaSm -BAA report arrived to a non-valid station!
S 1 41 14 675 Assert in file: "ProtectionAdaptation.c" in line: 675
S 1 41 14 687 Fatal Error in file: "ProtectionAdaptation.c"; Fatal Print: ProtectionAdaptation_Handler - BAA report associated with inactive VAP recieved 
S 1 41 14 699 Assert in file: "ProtectionAdaptation.c" in line: 699
S 1 41 14 736 ProtectionAdaptation_WlanTimerEventHandler -collosionRatio == %d
S 1 41 19 144 [QAMplus_ResetCounters]
S 1 41 19 185 [QAMplus_ResetParams]
S 1 41 19 232 [QAMplus_SupportedState], LA in steadyState
S 1 41 19 294 [QAMplus_TrialState] pBaaReport->successMpdu = %d, pBaaReport->MpduCnt = %d
S 1 41 19 311 Assert in file: "QAMplus.c" in line: 311
S 1 41 19 353 [QAMplus_TrialState] pQAMplusDatabase->lastRSSIdB = %d
S 1 41 19 396 Assert in file: "QAMplus.c" in line: 396
S 1 41 19 405 [QAMplus_NewBAReport] start
S 1 41 19 433 [QAMplus_NewBAReport] start, isWorkingPoint = %d, highestRateIndex = %d
S 1 41 19 434 [QAMplus_NewBAReport] start, rateIndexFromCurrentBA = %d
S 1 41 19 435 [QAMplus_NewBAReport] QAM_PLUS_STATE_SUPPORTED start, pQAMplusDatabase->successHighestRateWPCounter = %d
S 1 41 19 436 [QAMplus_NewBAReport] QAM_PLUS_STATE_SUPPORTED start, pBaaReport->successMpdu = %d
S 1 41 19 441 [QAMplus_NewBAReport] QAM_PLUS_STATE_SUPPORTED end, pQAMplusDatabase->successHighestRateWPCounter = %d
S 1 41 19 449 [QAMplus_NewBAReport] QAM_PLUS_STATE_TRIAL start, pBaaReport->phyMode = %d, rateIndexFromCurrentBA = %d, RatesTable[rateIndexFromCurrentBA].vhtMcs = %d
S 1 41 19 463 [QAMplus_NewBAReport] end
S 1 41 19 493 [QAMplus_AddStationReq]  QAMplusEnableFromDriver = %d, QAMplusEnable = %d
S 1 41 19 502 [QAMplus_AddStationReq]  QAMplus_GetState = %d
S 1 41 19 513 [QAMplus_AddStationReq] stationId = %d
S 1 41 19 548 [QAMplus_compareRSSI], start 
S 1 41 19 560 [QAMplus_compareRSSI], end newRSSILarger = %d, pQAMplusDatabase->lastRSSIdB = %d, maxCurrentRssidB = %d
S 1 41 19 602 [QAMplus_findMaxRssi], maxCurrentRssidB = %d
S 1 41 19 630 [QAMplus_SetState] QAMplus_GetState = %d
S 1 41 19 704 [QAMplus_SetSupportedThresh], pQAMplusDatabase->supportedThresh = %d
S 1 41 19 741 [QAMplus_GetMaxNssInMask], MaxNss = %d, indexNss = %d, localRateMask[0] = %d, localRateMask[1] = %d
S 1 41 19 751 Assert in file: "QAMplus.c" in line: 751
S 1 41 19 787 [QAMplus_UpdateLaRateMask] before update
S 1 41 19 797 Assert in file: "QAMplus.c" in line: 797
S 1 41 19 811 [QAMplus_UpdateLaRateMask], maxNss according to raIndexMask= %d
S 1 41 19 812 [QAMplus_UpdateLaRateMask], maxNss according to raIndexMaskOrg= %d
S 1 41 19 816 Assert in file: "QAMplus.c" in line: 816
S 1 41 19 817 Assert in file: "QAMplus.c" in line: 817
S 1 41 19 831 [QAMplus_UpdateLaRateMask] after update
S 1 41 19 868 [QAMplus_SetThresh]
S 1 41 19 897 [QAMplus_Enable], QAMplusEnableFromDriver = %d
S 1 41 19 928 [QAMplus_SetSupportedThresh]
S 1 41 19 960 [QAMplus_GetThresh], pQAMplusConfigParams->trialThresh=%d, pQAMplusConfigParams->inactiveTrialThresh = %d, pQAMplusDatabase->supportedThresh = %d
S 1 41 19 989 [QAMplus_GetCounters] stationId = %d: failureCounter = %d, numberTrialsCounter = %d, successHighestRateWPCounter = %d
S 1 41 5 679 Assert in file: "LinkAdaptation.c" in line: 679
S 1 41 5 683 linkAdaptationSetTransmissionTimeLimit staId: %d transmission time: %d
S 1 41 5 753 Assert in file: "LinkAdaptation.c" in line: 753
S 1 41 5 888 Assert in file: "LinkAdaptation.c" in line: 888
S 1 41 5 1158 Assert in file: "LinkAdaptation.c" in line: 1158
S 1 41 5 1162 Assert in file: "LinkAdaptation.c" in line: 1162
S 1 41 5 1393 MU-Group Fixed rate state, changed to == %d
S 1 41 5 1432 linkAdaptationSetFixedPower FixedPowerParameters.powerVal : %d
S 1 41 5 1620 Assert in file: "LinkAdaptation.c" in line: 1620
S 1 41 5 1630 Assert in file: "LinkAdaptation.c" in line: 1630
S 1 41 5 1812 linkAdaptationHandleAgingTimerEvent
S 1 41 5 1824 Assert in file: "LinkAdaptation.c" in line: 1824
S 1 41 5 1828 Assert in file: "LinkAdaptation.c" in line: 1828
S 1 41 5 1879 [OMN][linkAdaptationOpertingModeNotificationSimulateActionFrameBeforeAddSta] channelWidth = OMN_BW_20_MHZ rxNss = OMN_RX_NSS_1
S 1 41 5 2059 [linkAdaptationAddStationReq], staPHYmode = %d
S 1 41 5 2211 Assert in file: "LinkAdaptation.c" in line: 2211
S 1 41 5 2225 LA add group, GroupId ==%d, UsPIndex == %d,initialTcrRate ==%d 
S 1 41 5 2442 SINGLEUSER PROBING HANDLER - sup count == %d 
S 1 41 5 2450 SINGLEUSER PROBING END - station's grade == %d
S 1 41 5 2494 linkAdaptationMuPreliminaryHandler - groupIndex = %d, probing count = %d 
S 1 41 5 2510 linkAdaptationMuPreliminaryHandler,  PROBING END - groupIndex = %d, grade = %d
S 1 41 5 2563 linkAdaptationGetGroupsMarks,	groupId -%d , group's grade == %d
S 1 41 5 2592 Assert in file: "LinkAdaptation.c" in line: 2592
S 1 41 5 2733 Assert in file: "LinkAdaptation.c" in line: 2733
S 1 41 5 2960 [setLinkAdaptationRatesMask], pLmStaDbSwinfo->supportedRates = %d
S 1 41 5 2997 [setLinkAdaptationRatesMask] pLinkAdaptationDb->laStaUspCommon.raIndexMask.raIndexMask64bit[0] = %d
S 1 41 5 2998 [setLinkAdaptationRatesMask] pLinkAdaptationDb->laStaUspCommon.raIndexMask.raIndexMask64bit[1] = %d
S 1 41 5 3247 Assert in file: "LinkAdaptation.c" in line: 3247
S 1 41 5 3296 Assert in file: "LinkAdaptation.c" in line: 3296
S 1 41 5 3428 Assert in file: "LinkAdaptation.c" in line: 3428
S 1 41 5 3605 Assert in file: "LinkAdaptation.c" in line: 3605
S 1 41 5 3716 Assert in file: "LinkAdaptation.c" in line: 3716
S 1 41 5 3721 Assert in file: "LinkAdaptation.c" in line: 3721
S 1 41 5 3735 Assert in file: "LinkAdaptation.c" in line: 3735
S 1 41 5 3838 Assert in file: "LinkAdaptation.c" in line: 3838
S 1 41 5 3860 Assert in file: "LinkAdaptation.c" in line: 3860
S 1 41 5 3875 Assert in file: "LinkAdaptation.c" in line: 3875
S 1 41 5 3950 [linkAdaptationSetAggRateLimit] agg limit mode: %d agg limit max rate: %d
S 1 41 5 4005 Assert in file: "LinkAdaptation.c" in line: 4005
S 1 41 5 4037 Assert in file: "LinkAdaptation.c" in line: 4037
S 1 41 5 4067 Assert in file: "LinkAdaptation.c" in line: 4067
S 1 41 5 4383 [updateTransmissionTimeParams] rate is above threshold: %d
S 1 41 5 4389 [updateTransmissionTimeParams] rate is below threshold: %d. limit transmission time
S 1 41 5 4427 clientIsolationRateIsChanged oldPhyRate: %d newPhyRate: %d oldPhymode %d newPhyMode %d
S 1 41 5 4515 Assert in file: "LinkAdaptation.c" in line: 4515
S 1 41 5 4636 Assert in file: "LinkAdaptation.c" in line: 4636
S 1 41 5 4655 pTcrPowerModified = %d
S 1 41 5 4780 Assert in file: "LinkAdaptation.c" in line: 4780
S 1 41 5 4790 Assert in file: "LinkAdaptation.c" in line: 4790
S 1 41 5 4797 Fatal Error in file: "LinkAdaptation.c"; Fatal Print: linkAdaptationProcessCurrentBaaReport
S 1 41 5 4838 linkAdaptationSetPowerAdaptationPsdTables, tableType = %d cols %d rows %d
S 1 41 5 4839 Assert in file: "LinkAdaptation.c" in line: 4839
S 1 41 5 4972 Fatal Error in file: "LinkAdaptation.c"; Fatal Print: [Lmmain_HandleGenericReq] Unknown message type
S 1 41 5 5066 Assert in file: "LinkAdaptation.c" in line: 5066
S 1 41 5 5105 [ChangeStaToSteadyStateConfigurationParams]
S 1 41 5 5142 Assert in file: "LinkAdaptation.c" in line: 5142
S 1 41 5 5150 Fatal Error in file: "LinkAdaptation.c"; Fatal Print: updateLaDbDistributionParam
S 1 41 5 5252 Assert in file: "LinkAdaptation.c" in line: 5252
S 1 41 5 5327 Assert in file: "LinkAdaptation.c" in line: 5327
S 1 41 5 5363 Assert in file: "LinkAdaptation.c" in line: 5363
S 1 41 5 5390 Assert in file: "LinkAdaptation.c" in line: 5390
S 1 41 12 120 Assert in file: "LinkAdaptation_Tests.c" in line: 120
S 1 41 12 230 Assert in file: "LinkAdaptation_Tests.c" in line: 230
S 1 41 12 302 Assert in file: "LinkAdaptation_Tests.c" in line: 302
S 1 41 12 359 Assert in file: "LinkAdaptation_Tests.c" in line: 359
S 1 42 0 174 lockerScheduleRequest  lockRequesterParams= %x 
S 1 42 0 178 Assert in file: "Locker.c" in line: 178
S 1 42 0 231 lockerScheduleGroupRequest  lockRequesterParams=0x %x 
S 1 42 0 235 Assert in file: "Locker.c" in line: 235
S 1 42 0 302 Locker_LockRequestServiced  stationOrVapNum= %x tid = %x callerContext = %x
S 1 42 0 356 Locker_LockGroupRequestServiced status= %d
S 1 42 0 474 Locker_EnableStaQueues queueType= %d, stationOrVapId= %d
S 1 43 0 309 Assert in file: "logger.c" in line: 309
S 1 43 0 497 Assert in file: "logger.c" in line: 497
S 1 43 0 501 Assert in file: "logger.c" in line: 501
S 1 43 0 523 Assert in file: "logger.c" in line: 523
S 1 43 0 524 Assert in file: "logger.c" in line: 524
S 1 43 0 622 Assert in file: "logger.c" in line: 622
S 1 43 0 884 Assert in file: "logger.c" in line: 884
S 1 43 0 929 Assert in file: "logger.c" in line: 929
S 1 43 0 1039 Assert in file: "logger.c" in line: 1039
S 1 43 0 1232 Assert in file: "logger.c" in line: 1232
S 1 43 0 1287 Assert in file: "logger.c" in line: 1287
S 1 43 0 1291 Assert in file: "logger.c" in line: 1291
S 1 43 0 1313 ** missed logs: lack of buffers: %d, lack of BD: %d
S 1 43 0 1355 Assert in file: "logger.c" in line: 1355
S 1 43 0 1393 Assert in file: "logger.c" in line: 1393
S 1 43 0 1409 Assert in file: "logger.c" in line: 1409
S 1 43 0 1432 Assert in file: "logger.c" in line: 1432
S 1 43 0 1452 Assert in file: "logger.c" in line: 1452
S 1 43 2 208 LoggerApi_SetSeverity, level:%d, targetCPU:%d
S 1 43 2 214 Logger severity request is out of range:%d ! (should be [%d, %d]
S 1 43 2 277 Assert in file: "loggerAPI.c" in line: 277
S 1 43 2 299 Assert in file: "loggerAPI.c" in line: 299
S 1 43 2 399 Assert in file: "loggerAPI.c" in line: 399
S 1 43 2 582 Assert in file: "loggerAPI.c" in line: 582
S 1 43 2 592 Assert in file: "loggerAPI.c" in line: 592
S 1 44 2 197 Fatal Error in file: "lmint.c"; Fatal Print: Status FIFO has overflowed
S 1 44 2 244 Fatal Error in file: "lmint.c"; Fatal Print: Unused TSF timer
S 1 44 2 502 INT_GP_TIMER_2_ISR in OPERATION_MODE_DUT, calling LowerSenderDutTxEndHandler
S 1 44 2 571 Assert in file: "lmint.c" in line: 571
S 1 44 2 572 Assert in file: "lmint.c" in line: 572
S 1 44 3 321 [lmmain_HwSemaphoreTest 2] got the lock
S 1 44 3 333 [lmmain_HwSemaphoreTest 3] try to free
S 1 44 3 339 [lmmain_HwSemaphoreTest 4] lock is free
S 1 44 3 349 [1] Try to get the lock. Lock status is %d
S 1 44 3 353 [2] I got the lock. Lock status is %d
S 1 44 3 357 [3] I freed the lock. lock status is %d
S 1 44 5 253 Assert in file: "lmtimerUtility.c" in line: 253
S 1 44 7 210 Assert in file: "lmwmertns.c" in line: 210
S 1 44 7 223 Assert in file: "lmwmertns.c" in line: 223
S 1 44 7 225 Assert in file: "lmwmertns.c" in line: 225
S 1 44 7 255 Assert in file: "lmwmertns.c" in line: 255
S 1 44 8 238 Assert in file: "lm_StaDatabase.c" in line: 238
S 1 44 8 276 Assert in file: "lm_StaDatabase.c" in line: 276
S 1 44 8 308 Assert in file: "lm_StaDatabase.c" in line: 308
S 1 44 8 335 Assert in file: "lm_StaDatabase.c" in line: 335
S 1 44 9 183 Assert in file: "lm_VapDatabase.c" in line: 183
S 1 45 0 83 Assert in file: "lmi_queue.c" in line: 83
S 1 46 0 201 Assert in file: "lm_interface_task.c" in line: 201
S 1 46 0 213 Assert in file: "lm_interface_task.c" in line: 213
S 1 46 0 214 Assert in file: "lm_interface_task.c" in line: 214
S 1 46 0 215 Assert in file: "lm_interface_task.c" in line: 215
S 1 46 0 216 Assert in file: "lm_interface_task.c" in line: 216
S 1 46 0 220 Assert in file: "lm_interface_task.c" in line: 220
S 1 46 0 396 Assert in file: "lm_interface_task.c" in line: 396
S 1 46 0 397 Assert in file: "lm_interface_task.c" in line: 397
S 1 6 10 118 Assert in file: "Mac2index.c" in line: 118
S 1 6 10 121 Assert in file: "Mac2index.c" in line: 121
S 1 6 10 269 Assert in file: "Mac2index.c" in line: 269
S 1 6 10 272 Assert in file: "Mac2index.c" in line: 272
S 1 47 0 81 Assert in file: "init_ifmsg.c" in line: 81
S 1 47 0 83 Assert in file: "init_ifmsg.c" in line: 83
S 1 47 0 133 Assert in file: "init_ifmsg.c" in line: 133
S 1 47 0 139 Assert in file: "init_ifmsg.c" in line: 139
S 1 47 1 64 Assert in file: "MT_NSSMemoryPool.c" in line: 64
S 1 47 1 77 Assert in file: "MT_NSSMemoryPool.c" in line: 77
S 1 47 1 83 Assert in file: "MT_NSSMemoryPool.c" in line: 83
S 1 47 1 130 Assert in file: "MT_NSSMemoryPool.c" in line: 130
S 1 47 1 138 Assert in file: "MT_NSSMemoryPool.c" in line: 138
S 1 47 1 169 Assert in file: "MT_NSSMemoryPool.c" in line: 169
S 1 47 1 177 Assert in file: "MT_NSSMemoryPool.c" in line: 177
S 1 47 1 190 Assert in file: "MT_NSSMemoryPool.c" in line: 190
S 1 47 2 182 Assert in file: "PacketDescriptorsPool.c" in line: 182
S 1 47 2 214 Assert in file: "PacketDescriptorsPool.c" in line: 214
S 1 48 0 199 Fatal Error in file: "NdpaManager.c"; Fatal Print: ndpaManagerIllegalEvent
S 1 48 0 204 ndpaManagerChangeState: newState = %d
S 1 48 0 211 Assert in file: "NdpaManager.c" in line: 211
S 1 48 0 213 ndpaManagerRunStateMachine: CurrentState = %d, event = %d
S 1 48 0 226 Assert in file: "NdpaManager.c" in line: 226
S 1 48 0 228 ndpaManagerStartTxReq: received NdpaStartTx !!!
S 1 48 0 276 ndpaManagerStopTxReq: received NdpaStoptTx !!!
S 1 48 0 298 Assert in file: "NdpaManager.c" in line: 298
S 1 48 0 330 Assert in file: "NdpaManager.c" in line: 330
S 1 48 0 345 Assert in file: "NdpaManager.c" in line: 345
S 1 48 0 383 ndpaManagerIgnoreEvent: CurrentState = %d
S 1 48 0 394 ndpaManagerLaBfReportIndPdReleased: status = %d
S 1 48 0 402 ndpaManagerLaBfReportIndPdNotReleased: status = %d
S 1 48 0 412 ndpaManagerLaBfReportIndWaitForLock: status = %d
S 1 48 0 453 Assert in file: "NdpaManager.c" in line: 453
S 1 48 0 455 ndpaManagerLockCfmInWaitForLock: Lock status %d
S 1 48 0 491 Assert in file: "NdpaManager.c" in line: 491
S 1 48 0 523 Assert in file: "NdpaManager.c" in line: 523
S 1 49 0 202 Assert in file: "PacManager.c" in line: 202
S 1 49 0 253 PacManager_RxError state = %d rxErrorReason = %d rxErrorBitmap = %x
S 1 49 0 310 Fatal Error in file: "PacManager.c"; Fatal Print: PacManager_RxError: Ilegall State
S 1 49 0 373 [PacManagerSetRxd]---WAVE400--------------------------------end]
S 1 49 0 483 [PacManagerNormalActivation] -------------------------------------------end]
S 1 49 0 525 [PacManagerRssiActivation]----------------------------------end]
S 1 49 0 571 -------- RXF configured for Sniffer --------
S 1 49 0 578 -------- RXD configured for Sniffer --------
S 1 49 0 586 -------- RXC reserved storage size configured for Sniffer --------
S 1 49 0 593 -------- RXC Rssi abort disabled for Sniffer --------
S 1 49 0 598 Assert in file: "PacManager.c" in line: 598
S 1 49 0 601 -------- RXC configured correctly --------
S 1 49 0 741 Assert in file: "PacManager.c" in line: 741
S 1 49 0 807 Assert in file: "PacManager.c" in line: 807
S 1 49 0 830 Assert in file: "PacManager.c" in line: 830
S 1 49 0 868 PacManagerStartRxErrorProcess rxErrorState = %d
S 1 49 0 877 Assert in file: "PacManager.c" in line: 877
S 1 49 0 888 Fatal Error in file: "PacManager.c"; Fatal Print: PAC Manager Start RX Error Process Rejected
S 1 49 0 913 PacManagerFinalizeRxErrorProcess rxErrorState = %d
S 1 49 0 940 Assert in file: "PacManager.c" in line: 940
S 1 50 0 134 Assert in file: "TxPauser.c" in line: 134
S 1 50 0 495 Assert in file: "TxPauser.c" in line: 495
S 1 50 2 193 Assert in file: "TxPauser.c" in line: 193
S 1 50 2 209 Assert in file: "TxPauser.c" in line: 209
S 1 50 2 224 Assert in file: "TxPauser.c" in line: 224
S 1 50 2 240 Assert in file: "TxPauser.c" in line: 240
S 1 50 2 257 Assert in file: "TxPauser.c" in line: 257
S 1 50 2 272 Assert in file: "TxPauser.c" in line: 272
S 1 50 2 312 Assert in file: "TxPauser.c" in line: 312
S 1 51 0 151 Assert in file: "mt_addr_sharing.c" in line: 151
S 1 51 0 203 Assert in file: "mt_addr_sharing.c" in line: 203
S 1 55 0 107 Assert in file: "PsManager.c" in line: 107
S 1 55 0 629 Assert in file: "PsManager.c" in line: 629
S 1 55 2 129 Assert in file: "PsManager.c" in line: 129
S 1 56 0 219 Assert in file: "Qos.c" in line: 219
S 1 56 0 303 [qosFreePdsThresholdEvent], currentNumberOfFreePds = %d, numberOfFreePdsNeeded = %d
S 1 56 0 776 [qosSingleCheckDone]
S 1 56 0 807 [qosSingleCheckDone], numberOfFreePdsNeeded = %d, currentNumberOfFreePds = %d
S 1 56 0 814 [qosSingleCheckDone], QosAgerSingleCheckConfigurationParameters.maximumPdsToDiscard = %d, QosSingleCheckParameters.currentPdLimitIndex = %d
S 1 56 0 821 [qosSingleCheckDone], QosSingleCheckParameters.currentTtl = %d
S 1 56 0 864 [qosSingleCheckDone] stop single check
S 1 56 0 1229 Assert in file: "Qos.c" in line: 1229
S 1 56 0 1283 Assert in file: "Qos.c" in line: 1283
S 1 56 0 1451 Qos, Send Confirmation, Client %d, stationIndex %d
S 1 56 0 1515 Assert in file: "Qos.c" in line: 1515
S 1 56 0 1659 Assert in file: "Qos.c" in line: 1659
S 1 45 1 85 Assert in file: "GeneralQ.c" in line: 85
S 1 45 2 123 Assert in file: "MT_FifoQ.c" in line: 123
S 1 45 2 174 Assert in file: "MT_FifoQ.c" in line: 174
S 1 45 2 179 Assert in file: "MT_FifoQ.c" in line: 179
S 1 45 2 192 Assert in file: "MT_FifoQ.c" in line: 192
S 1 45 2 222 Assert in file: "MT_FifoQ.c" in line: 222
S 1 45 2 227 Assert in file: "MT_FifoQ.c" in line: 227
S 1 45 2 255 Assert in file: "MT_FifoQ.c" in line: 255
S 1 45 2 289 Assert in file: "MT_FifoQ.c" in line: 289
S 1 45 2 294 Assert in file: "MT_FifoQ.c" in line: 294
S 1 45 2 305 Assert in file: "MT_FifoQ.c" in line: 305
S 1 57 0 80 Assert in file: "QSmanager.c" in line: 80
S 1 58 0 188 Fatal Error in file: "RegAccess.c"; Fatal Print: REG Access Write Secured
S 1 59 0 260 Assert in file: "ResourceManager.c" in line: 260
S 1 59 0 295 Assert in file: "ResourceManager.c" in line: 295
S 1 59 0 299 Assert in file: "ResourceManager.c" in line: 299
S 1 59 0 303 Assert in file: "ResourceManager.c" in line: 303
S 1 59 0 310 Assert in file: "ResourceManager.c" in line: 310
S 1 59 0 570 Resource Manager - no ID available for pool type %d, return msg %d, return task %d, context %d
S 1 59 0 613 Assert in file: "ResourceManager.c" in line: 613
S 1 59 0 614 Assert in file: "ResourceManager.c" in line: 614
S 1 59 0 657 Assert in file: "ResourceManager.c" in line: 657
S 1 59 0 691 Assert in file: "ResourceManager.c" in line: 691
S 1 59 0 696 Assert in file: "ResourceManager.c" in line: 696
S 1 59 0 739 Assert in file: "ResourceManager.c" in line: 739
S 1 59 0 775 Assert in file: "ResourceManager.c" in line: 775
S 1 60 0 925 Assert in file: "RxClassifier.c" in line: 925
S 1 60 0 983 [RxClassifier_FillRtd], staIndex = %d
S 1 60 0 1003 [RxClassifier_FillRtd], rssiTypeFlag = %d, isMulticastOrBroadcast = %d, isStaIndexValid = %d
S 1 60 0 1017 Assert in file: "RxClassifier.c" in line: 1017
S 1 60 0 1388 RxClassifier_RxFilters drop sn %d
S 1 60 0 1762 Assert in file: "RxClassifier.c" in line: 1762
S 1 60 0 1786 Assert in file: "RxClassifier.c" in line: 1786
S 1 60 0 1810 Assert in file: "RxClassifier.c" in line: 1810
S 1 60 0 1837 Assert in file: "RxClassifier.c" in line: 1837
S 1 60 0 1865 Assert in file: "RxClassifier.c" in line: 1865
S 1 60 0 1894 Assert in file: "RxClassifier.c" in line: 1894
S 1 60 0 1923 Assert in file: "RxClassifier.c" in line: 1923
S 1 60 0 1957 Assert in file: "RxClassifier.c" in line: 1957
S 1 60 0 2020 Assert in file: "RxClassifier.c" in line: 2020
S 1 60 0 2110 Assert in file: "RxClassifier.c" in line: 2110
S 1 60 0 2139 Assert in file: "RxClassifier.c" in line: 2139
S 1 60 0 2165 Assert in file: "RxClassifier.c" in line: 2165
S 1 60 0 2188 Assert in file: "RxClassifier.c" in line: 2188
S 1 60 0 2211 Assert in file: "RxClassifier.c" in line: 2211
S 1 60 0 2234 Assert in file: "RxClassifier.c" in line: 2234
S 1 60 0 2257 Assert in file: "RxClassifier.c" in line: 2257
S 1 60 0 2368 Assert in file: "RxClassifier.c" in line: 2368
S 1 60 0 2396 Assert in file: "RxClassifier.c" in line: 2396
S 1 60 0 2522 -------- Rx Classifier configured for Sniffer --------
S 1 60 0 2615 [RxClassifier_ConfigureNormalMode] - WAVE400------------------end]
S 1 60 0 2642 [RxClassifier_ConfigureRssiMode]-------- Rx Classifier configured for RSSI -WAVE400------- RxClassifierDb.rssiTypeFlag = %d
S 1 6 12 602 Assert in file: "RxClassifier.c" in line: 602
S 1 6 12 714 Assert in file: "RxClassifier.c" in line: 714
S 1 6 12 761 Assert in file: "RxClassifier.c" in line: 761
S 1 6 12 882 Assert in file: "RxClassifier.c" in line: 882
S 1 6 12 935 Assert in file: "RxClassifier.c" in line: 935
S 1 6 12 1081 [RxClassifier_ConfigureNormalMode]-------- Rx Classifier RAM configured for NORMAL_AFTER_RSSI --------
S 1 6 12 1090 [RxClassifier_ConfigureNormalMode]--------------------------end
S 1 6 12 1125 [RxClassifier_ConfigureRssiMode]-------- Rx Classifier RAM configured for RSSI --------
S 1 6 12 1132 [RxClassifier_ConfigureRssiMode], StaDB_IsDataEncrypted(%d) = %d, StaDB_IsManagementEncrypted(%d) = %d
S 1 6 12 1140 [RxClassifier_ConfigureRssiMode]------------------------------------end]
S 1 6 12 1206 -------- Rx Classifier configured for Sniffer --------
S 1 61 0 445 Assert in file: "RxDataPath.c" in line: 445
S 1 61 0 470 Assert in file: "RxDataPath.c" in line: 470
S 1 62 0 220 Assert in file: "RxHandler.c" in line: 220
S 1 62 0 257 Assert in file: "RxHandler.c" in line: 257
S 1 62 0 325 Assert in file: "RxHandler.c" in line: 325
S 1 62 0 432 Assert in file: "RxHandler.c" in line: 432
S 1 62 0 550 Frame is bigger than Max sniffer payload size (1600 bytes) and has been reduces!! Sniffer original payload size is %d
S 1 62 0 689 Assert in file: "RxHandler.c" in line: 689
S 1 62 0 880 Assert in file: "RxHandler.c" in line: 880
S 1 62 0 1505 Assert in file: "RxHandler.c" in line: 1505
S 1 62 0 1509 Assert in file: "RxHandler.c" in line: 1509
S 1 62 0 1737 Assert in file: "RxHandler.c" in line: 1737
S 1 62 0 2045 [RxHandler_CopyMetricsToMetricsFifo] trigger SW event EVENT_ID_METRICS_FIFO_NOT_EMPTY, pFifoEntry->rxPhyMetrics.geriscSpare2 = %d
S 1 62 1 1042 Assert in file: "RxHandler_Decryption.c" in line: 1042
S 1 62 1 1102 Assert in file: "RxHandler_Decryption.c" in line: 1102
S 1 62 1 1325 Assert in file: "RxHandler_Decryption.c" in line: 1325
S 1 62 2 243 Assert in file: "RxHandler_Rtd.c" in line: 243
S 1 62 2 278 Assert in file: "RxHandler_Rtd.c" in line: 278
S 1 30 2 162 Fatal Error in file: "RxHandler.c"; Fatal Print: RX Handler Error Start
S 1 30 2 178 Fatal Error in file: "RxHandler.c"; Fatal Print: Unsupported Message ID
S 1 30 2 203 Fatal Error in file: "RxHandler.c"; Fatal Print: Unsupported Message ID
S 1 30 2 215 Fatal Error in file: "RxHandler.c"; Fatal Print: RX Handler Unknown Event
S 1 30 2 385 Assert in file: "RxHandler.c" in line: 385
S 1 30 2 416 Assert in file: "RxHandler.c" in line: 416
S 1 30 2 467 Assert in file: "RxHandler.c" in line: 467
S 1 64 0 347 Assert in file: "RxManager.c" in line: 347
S 1 64 0 352 Assert in file: "RxManager.c" in line: 352
S 1 64 0 353 Assert in file: "RxManager.c" in line: 353
S 1 64 0 524 Fatal Error in file: "RxManager.c"; Fatal Print: RX Manager Timer Unknown Type
S 1 64 0 647 Fatal Error in file: "RxManager.c"; Fatal Print: RX Manager Classifier Resource Timeout
S 1 64 0 681 [rxManagerClassifierConfigureNormalMode]---WAVE400------------end]
S 1 64 0 717 [rxManagerClassifierConfigureRssiMode]----------------------end]
S 1 64 0 767 [rxManagerConfigureNormalMode]------------------------------end]
S 1 64 0 816 [rxManagerConfigureRssiMode]--------------------------------end]
S 1 64 0 865 Assert in file: "RxManager.c" in line: 865
S 1 64 0 883 Assert in file: "RxManager.c" in line: 883
S 1 64 0 907 Assert in file: "RxManager.c" in line: 907
S 1 64 0 908 Assert in file: "RxManager.c" in line: 908
S 1 64 0 1207 Assert in file: "RxManager.c" in line: 1207
S 1 64 0 1311 rxManagerPsSettingsFifoNotEmpty %x
S 1 64 0 1324 Assert in file: "RxManager.c" in line: 1324
S 1 64 0 1329 rxManagerPsSettingsFifoNotEmpty  Station Changed Ps Mode Set Ps Status %x Clear Ps Status %x
S 1 64 0 1422 [ARP][rxManagerDebugRdsListHandler] SN = %d
S 1 64 0 1702 Reached rxManagerManagementRdsListHandler
S 1 64 0 1755 Fatal Error in file: "RxManager.c"; Fatal Print: RX Manager RD Handler
S 1 64 0 1820 Assert in file: "RxManager.c" in line: 1820
S 1 64 0 1877 Assert in file: "RxManager.c" in line: 1877
S 1 64 0 2016 Assert in file: "RxManager.c" in line: 2016
S 1 64 0 2410 rxManagerHandleValidActionFrame_1
S 1 64 0 2428 rxManagerHandleValidActionFrame_2
S 1 64 0 2850 Assert in file: "RxManager.c" in line: 2850
S 1 64 0 3075 RX Manager, Send Confirmation, Client %d, SID %d
S 1 64 0 3115 Assert in file: "RxManager.c" in line: 3115
S 1 64 0 3387 Assert in file: "RxManager.c" in line: 3387
S 1 64 0 3388 Assert in file: "RxManager.c" in line: 3388
S 1 64 0 3389 Assert in file: "RxManager.c" in line: 3389
S 1 64 0 3390 Assert in file: "RxManager.c" in line: 3390
S 1 65 0 284 Assert in file: "Reordering.c" in line: 284
S 1 65 0 823 Assert in file: "Reordering.c" in line: 823
S 1 65 0 931 Assert in file: "Reordering.c" in line: 931
S 1 65 2 167 Assert in file: "RxPp.c" in line: 167
S 1 65 2 187 Assert in file: "RxPp.c" in line: 187
S 1 65 2 859 Assert in file: "RxPp.c" in line: 859
S 1 66 1 177 Assert in file: "RxPp.c" in line: 177
S 1 66 1 466 Assert in file: "RxPp.c" in line: 466
S 1 66 1 467 Assert in file: "RxPp.c" in line: 467
S 1 66 1 515 Assert in file: "RxPp.c" in line: 515
S 1 66 1 652 Assert in file: "RxPp.c" in line: 652
S 1 66 1 1079 Assert in file: "RxPp.c" in line: 1079
S 1 52 5 96 Assert in file: "cipher_shared_ram_db.c" in line: 96
S 1 52 5 97 Assert in file: "cipher_shared_ram_db.c" in line: 97
S 1 52 5 136 Assert in file: "cipher_shared_ram_db.c" in line: 136
S 1 52 5 138 Assert in file: "cipher_shared_ram_db.c" in line: 138
S 1 52 5 170 Assert in file: "cipher_shared_ram_db.c" in line: 170
S 1 52 5 171 Assert in file: "cipher_shared_ram_db.c" in line: 171
S 1 52 5 173 Assert in file: "cipher_shared_ram_db.c" in line: 173
S 1 52 5 202 Assert in file: "cipher_shared_ram_db.c" in line: 202
S 1 52 6 163 Assert in file: "cipher_suite.c" in line: 163
S 1 52 6 189 Assert in file: "cipher_suite.c" in line: 189
S 1 52 6 215 Assert in file: "cipher_suite.c" in line: 215
S 1 52 6 217 Assert in file: "cipher_suite.c" in line: 217
S 1 52 7 98 Assert in file: "cipher_suite_ccmp.c" in line: 98
S 1 52 8 97 Assert in file: "cipher_suite_wep.c" in line: 97
S 1 52 8 123 Assert in file: "cipher_suite_wep.c" in line: 123
S 1 52 8 154 Assert in file: "cipher_suite_wep.c" in line: 154
S 1 52 1 94 Assert in file: "key_manager.c" in line: 94
S 1 52 2 227 Sec Manager, Send Confirmation, Client %d, SID %d
S 1 52 2 258 SEC Manager STA Manager, Station %d changed from %d to %d
S 1 52 2 925 Fatal Error in file: "secManager_StaManager.c"; Fatal Print: SEC Manager STA Manager Fatal
S 1 52 2 965 Assert in file: "secManager_StaManager.c" in line: 965
S 1 52 2 1067 Assert in file: "secManager_StaManager.c" in line: 1067
S 1 52 2 1107 Assert in file: "secManager_StaManager.c" in line: 1107
S 1 52 2 1148 Assert in file: "secManager_StaManager.c" in line: 1148
S 1 52 2 1188 Assert in file: "secManager_StaManager.c" in line: 1188
S 1 52 3 168 SEC Manager VAP Manager, Vap %d changed from %d to %d
S 1 52 3 236 vUM_MAN_SET_KEY_REQ: u16Status:%d psMsg->header.vapId:%d
S 1 52 3 342 Assert in file: "secManager_VapManager.c" in line: 342
S 1 52 3 419 Assert in file: "secManager_VapManager.c" in line: 419
S 1 52 3 553 Fatal Error in file: "secManager_VapManager.c"; Fatal Print: SEC Manager STA Manager Fatal
S 1 52 3 621 Assert in file: "secManager_VapManager.c" in line: 621
S 1 52 3 693 Assert in file: "secManager_VapManager.c" in line: 693
S 1 52 3 731 Assert in file: "secManager_VapManager.c" in line: 731
S 1 52 3 771 Assert in file: "secManager_VapManager.c" in line: 771
S 1 52 3 774 secManager_VapManagerRemoveVap
S 1 68 0 336 Assert in file: "LowerSender.c" in line: 336
S 1 68 0 446 Assert in file: "LowerSender.c" in line: 446
S 1 68 0 477 Assert in file: "LowerSender.c" in line: 477
S 1 68 0 482 Assert in file: "LowerSender.c" in line: 482
S 1 68 0 492 Assert in file: "LowerSender.c" in line: 492
S 1 68 0 589 Assert in file: "LowerSender.c" in line: 589
S 1 68 0 649 LowerSenderDutTxEndHandler, DUT_TX_STATE_STOPPING, toStop == TRUE
S 1 68 0 655 Assert in file: "LowerSender.c" in line: 655
S 1 68 0 665 Assert in file: "LowerSender.c" in line: 665
S 1 68 0 673 LowerSenderDutTxAbortHandler
S 1 68 0 891 Assert in file: "LowerSender.c" in line: 891
S 1 68 0 1034 Assert in file: "LowerSender.c" in line: 1034
S 1 68 0 1151 LowerSender_DutConfig
S 1 68 0 1175 LowerSender_UpdateStdWithDutParams, alloctedStd_p:0x%x, current std:0x%x
S 1 68 1 99 Assert in file: "LowerSenderTxCancel.c" in line: 99
S 1 68 1 106 Assert in file: "LowerSenderTxCancel.c" in line: 106
S 1 68 1 121 Assert in file: "LowerSenderTxCancel.c" in line: 121
S 1 68 1 135 Assert in file: "LowerSenderTxCancel.c" in line: 135
S 1 68 1 147 Assert in file: "LowerSenderTxCancel.c" in line: 147
S 1 68 2 294 Assert in file: "UpperSender.c" in line: 294
S 1 68 2 296 Assert in file: "UpperSender.c" in line: 296
S 1 68 2 298 Assert in file: "UpperSender.c" in line: 298
S 1 68 2 645 Assert in file: "UpperSender.c" in line: 645
S 1 68 2 683 Assert in file: "UpperSender.c" in line: 683
S 1 68 2 745 Assert in file: "UpperSender.c" in line: 745
S 1 68 2 746 Assert in file: "UpperSender.c" in line: 746
S 1 68 3 109 Assert in file: "UpperSender_Encryption.c" in line: 109
S 1 30 4 163 Sender Error: file ID %d, line %d, state %d
S 1 30 4 164 Fatal Error in file: "SenderInterface.c"; Fatal Print: Sender Error Start
S 1 30 4 180 Fatal Error in file: "SenderInterface.c"; Fatal Print: Unsupported Message ID
S 1 30 4 206 Fatal Error in file: "SenderInterface.c"; Fatal Print: Unsupported Message ID
S 1 30 4 218 Fatal Error in file: "SenderInterface.c"; Fatal Print: Sender Unknown Event
S 1 30 4 354 Assert in file: "SenderInterface.c" in line: 354
S 1 30 4 450 Assert in file: "SenderInterface.c" in line: 450
S 1 69 0 448 [servicesHandlerSendCTS2Self], ctsParams->duration = %d, servicesHandlerParams.currentRunningServiceData = %d
S 1 69 0 476 Fatal Error in file: "ServicesHandler.c"; Fatal Print: servicesHandlerError
S 1 69 0 535 ServicesHandler_RunService:Service Id %d
S 1 69 0 543 Assert in file: "ServicesHandler.c" in line: 543
S 1 69 0 635 ServicesHandler_PauseRxTimerExpired
S 1 69 0 641 ServicesHandler_PauseRxTimerExpired:PauseOrResume Done
S 1 70 0 58 Assert in file: "shram_interruptSection.c" in line: 58
S 1 70 0 63 Assert in file: "shram_interruptSection.c" in line: 63
S 1 71 0 281 Smps Manager STA Manager, STA %d changed from %d to %d
S 1 71 0 1346 Assert in file: "SmpsManager_StaManager.c" in line: 1346
S 1 71 0 1522 Assert in file: "SmpsManager_StaManager.c" in line: 1522
S 1 71 0 1560 Assert in file: "SmpsManager_StaManager.c" in line: 1560
S 1 72 0 158 Assert in file: "StaDatabase.c" in line: 158
S 1 72 0 165 Assert in file: "StaDatabase.c" in line: 165
S 1 72 0 175 Assert in file: "StaDatabase.c" in line: 175
S 1 72 0 182 Assert in file: "StaDatabase.c" in line: 182
S 1 72 0 371 StaDb_RemoveStationFromDB %X
S 1 72 0 480 Assert in file: "StaDatabase.c" in line: 480
S 1 72 0 517 Assert in file: "StaDatabase.c" in line: 517
S 1 72 0 669 Assert in file: "StaDatabase.c" in line: 669
S 1 72 0 1065 Assert in file: "StaDatabase.c" in line: 1065
S 1 72 0 1066 Assert in file: "StaDatabase.c" in line: 1066
S 1 72 0 1100 Assert in file: "StaDatabase.c" in line: 1100
S 1 72 0 1101 Assert in file: "StaDatabase.c" in line: 1101
S 1 72 0 1159 Assert in file: "StaDatabase.c" in line: 1159
S 1 72 0 1442 Assert in file: "StaDatabase.c" in line: 1442
S 1 72 0 1469 Assert in file: "StaDatabase.c" in line: 1469
S 1 72 0 1490 Assert in file: "StaDatabase.c" in line: 1490
S 1 72 0 1491 Assert in file: "StaDatabase.c" in line: 1491
S 1 72 0 1513 Assert in file: "StaDatabase.c" in line: 1513
S 1 73 0 300 Statistics Manager, Send Confirmation, Client %d, SID %d
S 1 73 0 331 Statistics Manager, Send Confirmation, VapId %d
S 1 73 0 442 statisticsManagerIncrease %d %d %d %d
S 1 73 0 463 statisticsManagerDecrease %d %d %d %d
S 1 73 0 492 Fatal Error in file: "StatisticsManager.c"; Fatal Print: statisticsManagerArithmetic
S 1 73 0 540 Fatal Error in file: "StatisticsManager.c"; Fatal Print: statisticsManagerSet
S 1 73 0 607 Fatal Error in file: "StatisticsManager.c"; Fatal Print: statisticsManagerSet
S 1 73 0 892 Assert in file: "StatisticsManager.c" in line: 892
S 1 73 0 896 Assert in file: "StatisticsManager.c" in line: 896
S 1 73 0 997 Assert in file: "StatisticsManager.c" in line: 997
S 1 73 0 1002 Assert in file: "StatisticsManager.c" in line: 1002
S 1 73 0 1003 Assert in file: "StatisticsManager.c" in line: 1003
S 1 73 0 1033 Assert in file: "StatisticsManager.c" in line: 1033
S 1 73 0 1034 Assert in file: "StatisticsManager.c" in line: 1034
S 1 73 0 1096 Assert in file: "StatisticsManager.c" in line: 1096
S 1 73 0 1097 Assert in file: "StatisticsManager.c" in line: 1097
S 1 73 0 1130 Fatal Error in file: "StatisticsManager.c"; Fatal Print: Current implementation: table stored in IRAM
S 1 73 0 1567 Assert in file: "StatisticsManager.c" in line: 1567
S 1 73 0 1602 Assert in file: "StatisticsManager.c" in line: 1602
S 1 73 0 1762 pGetAocsInfo->dynamicBW20MHz, %d
S 1 73 0 1763 pGetAocsInfo->dynamicBW40MHz, %d
S 1 73 0 1764 pGetAocsInfo->dynamicBW80MHz, %d
S 1 73 0 1765 pGetAocsInfo->extStaRx, %d
S 1 73 0 1766 pGetAocsInfo->noiseFloor, %d
S 1 73 0 1767 pGetAocsInfo->TxPower, %d
S 1 73 0 1768 pGetAocsInfo->channelLoad, %d
S 1 73 0 1769 pGetAocsInfo->CWIvalue, %d
S 1 73 0 1770 numOfStationCounter, %d
S 1 73 0 1771 averageRssi, %d
S 1 73 0 1772 pGetAocsInfo->RSSI, %d
S 1 73 0 1773 pGetAocsInfo->SNR, %d
S 1 73 0 1774 phyRxStatusDb.devicePhyRxStatus.rf_gain[ant], %d
S 1 73 0 1842 Assert in file: "StatisticsManager.c" in line: 1842
S 1 73 0 1985 Assert in file: "StatisticsManager.c" in line: 1985
S 1 73 0 1994 Assert in file: "StatisticsManager.c" in line: 1994
S 1 73 0 2063 Assert in file: "StatisticsManager.c" in line: 2063
S 1 73 0 2069 Assert in file: "StatisticsManager.c" in line: 2069
S 1 73 0 2070 Assert in file: "StatisticsManager.c" in line: 2070
S 1 73 0 2183 %d %d
S 1 38 1 131 Fatal Error in file: "System_Configuration.c"; Fatal Print: System_ConvertUsToSystemClk
S 1 38 2 433 Fatal Error in file: "System_MipsTimers.c"; Fatal Print: Rx Pasue Timer isn't used in Wave500B
S 1 38 2 526 Assert in file: "System_MipsTimers.c" in line: 526
S 1 38 2 550 Assert in file: "System_MipsTimers.c" in line: 550
S 1 74 1 117 Assert in file: "tx_application_define.c" in line: 117
S 1 74 1 125 Assert in file: "tx_application_define.c" in line: 125
S 1 74 1 142 Assert in file: "tx_application_define.c" in line: 142
S 1 74 1 154 Assert in file: "tx_application_define.c" in line: 154
S 1 74 1 174 Assert in file: "tx_application_define.c" in line: 174
S 1 74 1 210 Assert in file: "tx_application_define.c" in line: 210
S 1 74 2 59 Assert in file: "tx_application_entry_func.c" in line: 59
S 1 74 2 62 Thread : %d  Entry func, recieved message 
S 1 74 2 63 Assert in file: "tx_application_entry_func.c" in line: 63
S 1 74 2 67 Assert in file: "tx_application_entry_func.c" in line: 67
S 1 74 3 96 Assert in file: "tx_application_func.c" in line: 96
S 1 74 3 113 Assert in file: "tx_application_func.c" in line: 113
S 1 74 3 123 Assert in file: "tx_application_func.c" in line: 123
S 1 74 3 151 Assert in file: "tx_application_func.c" in line: 151
S 1 74 3 197 Assert in file: "tx_application_func.c" in line: 197
S 1 74 3 216 Assert in file: "tx_application_func.c" in line: 216
S 1 74 3 237 Assert in file: "tx_application_func.c" in line: 237
S 1 74 3 290 Assert in file: "tx_application_func.c" in line: 290
S 1 74 3 309 Assert in file: "tx_application_func.c" in line: 309
S 1 74 3 310 Assert in file: "tx_application_func.c" in line: 310
S 1 74 3 331 Assert in file: "tx_application_func.c" in line: 331
S 1 74 3 405 Assert in file: "tx_application_func.c" in line: 405
S 1 74 3 410 Assert in file: "tx_application_func.c" in line: 410
S 1 74 5 46 Assert in file: "tx_application_msg_pool.c" in line: 46
S 1 74 5 87 Assert in file: "tx_application_msg_pool.c" in line: 87
S 1 74 5 108 Assert in file: "tx_application_msg_pool.c" in line: 108
S 1 74 5 113 Assert in file: "tx_application_msg_pool.c" in line: 113
S 1 74 5 138 Assert in file: "tx_application_msg_pool.c" in line: 138
S 1 74 5 142 Assert in file: "tx_application_msg_pool.c" in line: 142
S 1 74 5 198 Assert in file: "tx_application_msg_pool.c" in line: 198
S 1 74 5 214 Fatal Error in file: "tx_application_msg_pool.c"; Fatal Print: attempt to release a non allocated message
S 1 74 5 253 Fatal Error in file: "tx_application_msg_pool.c"; Fatal Print: Tried to decrease a reference count past zero
S 1 74 6 116 Assert in file: "tx_application_timer.c" in line: 116
S 1 75 0 112 Assert in file: "TinyKernel_Messages.c" in line: 112
S 1 75 0 139 Assert in file: "TinyKernel_Messages.c" in line: 139
S 1 75 0 148 Assert in file: "TinyKernel_Messages.c" in line: 148
S 1 75 0 152 Assert in file: "TinyKernel_Messages.c" in line: 152
S 1 75 0 205 Assert in file: "TinyKernel_Messages.c" in line: 205
S 1 75 0 226 Assert in file: "TinyKernel_Messages.c" in line: 226
S 1 75 0 227 Assert in file: "TinyKernel_Messages.c" in line: 227
S 1 75 0 250 Assert in file: "TinyKernel_Messages.c" in line: 250
S 1 75 0 264 Assert in file: "TinyKernel_Messages.c" in line: 264
S 1 75 0 413 Assert in file: "TinyKernel_Messages.c" in line: 413
S 1 75 0 444 Assert in file: "TinyKernel_Messages.c" in line: 444
S 1 76 0 235 Assert in file: "TrainingManager.c" in line: 235
S 1 76 0 242 TrainingManager_RunStateMachine: CurrentState = %d, event = %d
S 1 76 0 252 TrainingManager_ChangeState: newState = %d
S 1 76 0 312 Fatal Error in file: "TrainingManager.c"; Fatal Print: TrainingManager_IllegalEvent
S 1 76 0 339 TrainingManager_SendLaInfoReq, muActiveVapBitmap = 0x%04X
S 1 76 0 391 TrainingManager_CheckNdpaConfirmationStatus, Status = %d
S 1 76 0 419 Group Manager result BW = %d
S 1 76 0 453 TrainingManager_StopTrainingDuringTraining
S 1 76 0 484 TrainingManager_StopTrainingDuringWaitingForLaInfo
S 1 76 0 523 TrainingManager_AddVap, new VAP id = %d
S 1 76 0 664 TrainingManager_RemoveStaNotDuringTraining, sta Id = 0x%X
S 1 76 0 710 TrainingManager_RemoveStaDuringTraining, sta Id = 0x%X
S 1 76 0 774 TrainingManager_RemoveStaDuringStopping, sta Id = 0x%X
S 1 76 0 825 TrainingManager_HaltStaNotDuringTraining, sta Id = 0x%X
S 1 76 0 859 TrainingManager_HaltStaDuringTraining, sta Id = 0x%X
S 1 76 0 914 TrainingManager_StopStaDuringTraining, sta Id = 0x%X
S 1 76 0 1011 TrainingManager_SendTrainingStoppedConfirmation, cfmBitmap = 0x%08X, 0x%08X
S 1 76 0 1045 TrainingManager_IgnoreStopTraining
S 1 76 0 1084 TrainingManager_StartTraining, num of connected station = %d, All active vaps bitmap = 0x%04X, MU active vaps bitmap = 0x%04X, num of Pools = %d
S 1 76 0 1090 VAP SELECTED!!!, VAP ID = %d
S 1 76 0 1146 Build test plan and Training Vector finished, send Start Tx to NDPA Manager, num of station = %d, VAP ID = %d
S 1 76 0 1155 VAP NOT SELECTED!!!
S 1 76 0 1211 TrainingManager_BuildPools, input is active sta bitmap from Link adaptive:
S 1 76 0 1220 Final Active STA bitmap
S 1 76 0 1239 current VAP Id = %d
S 1 76 0 1267 Current feature bitmap for station %d = 0x%08X
S 1 76 0 1347 Start select stations!!! , pool id = %d
S 1 76 0 1382 Assert in file: "TrainingManager.c" in line: 1382
S 1 76 0 1415 STA index selected = %X
S 1 76 0 1451 Start Building Test Plan!!! , pool id = %d, current policies bitmap = 0x%04X, num of atennas = %d
S 1 76 0 1466 TrainingManager_BuildTestPlan: currentPlicyBitmap = 0x%04X, currentPolicy = %d
S 1 76 0 1476 Start Building Test Plan!!! , pool id = %d
S 1 76 0 1515 TrainingManager_StartResultsProcessing
S 1 76 0 1563 TrainingManager_UpdateGroupCombinationTable, poolId = %d, testPlanPoliciesBitmap = 0x%04X, num of antennas = %d
S 1 76 0 1578 TrainingManager_UpdateGroupCombinationTable: currentPlicyBitmap = 0x%04X, currentPolicy = %d
S 1 76 0 1588 TrainingManager_UpdateGroupCombinationTable, poolId = %d
S 1 76 0 1622 Bulding Test Plan for policy 0
S 1 76 0 1628 Bulding Test Plan for policy 1
S 1 76 0 1635 Bulding Test Plan for policy 2
S 1 76 0 1644 Bulding Test Plan for policy 3
S 1 76 0 1650 Bulding Test Plan for policy 4
S 1 76 0 1656 Bulding Test Plan for policy 5
S 1 76 0 1665 Bulding Test Plan for policy 6
S 1 76 0 1704 Bulding Test Plan for Segment 1xxx
S 1 76 0 1730 Num of combinations in 1XXX segment is %d
S 1 76 0 1749 Bulding Test Plan for Segment 2xxx
S 1 76 0 1779 Num of combinations in 2XXX segment is %d
S 1 76 0 1799 Bulding Test Plan for Segment 22xx
S 1 76 0 1846 Num of combinations in 22XX segment is %d
S 1 76 0 1867 Bulding Test Plan for Segment 21xx
S 1 76 0 1912 Num of combinations in 21XX segment is %d
S 1 76 0 1931 Bulding Test Plan for Segment 12xx
S 1 76 0 1976 Num of combinations in 12XX segment is %d
S 1 76 0 1996 Bulding Test Plan for Segment 11xx
S 1 76 0 2036 Num of combinations in 11XX segment is %d
S 1 76 0 2055 Bulding Test Plan for Segment 111x
S 1 76 0 2102 Num of combinations in 111X segment is %d
S 1 76 0 2120 Bulding Test Plan for Segment 211x
S 1 76 0 2172 Num of combinations in 211X segment is %d
S 1 76 0 2191 Bulding Test Plan for Segment 121x
S 1 76 0 2243 Num of combinations in 121X segment is %d
S 1 76 0 2262 Bulding Test Plan for Segment 112x
S 1 76 0 2314 Num of combinations in 112X segment is %d
S 1 76 0 2334 Bulding Test Plan for Segment 1111
S 1 76 0 2387 Num of combinations in 1111 segment is %d
S 1 76 0 2420 Update Group Combination table for policy 0
S 1 76 0 2427 Update Group Combination table for policy 1
S 1 76 0 2435 Update Group Combination table for policy 2
S 1 76 0 2445 Update Group Combination table for policy 3
S 1 76 0 2452 Update Group Combination table for policy 4
S 1 76 0 2459 Update Group Combination table for policy 5
S 1 76 0 2469 Update Group Combination table for policy 6
S 1 76 0 2504 Update Group Combination table for Segment 1xxx, output lines:
S 1 76 0 2538 Update Group Combination table for Segment 2xxx, output lines:
S 1 76 0 2578 Update Group Combination table for Segment 22xx, output lines:
S 1 76 0 2645 Update Group Combination table for Segment 21xx, output lines:
S 1 76 0 2712 Update Group Combination table for Segment 12xx, output lines:
S 1 76 0 2779 Update Group Combination table for Segment 11xx, output lines:
S 1 76 0 2842 Update Group Combination table for Segment 111x, output lines:
S 1 76 0 2912 Update Group Combination table for Segment 211x, output lines:
S 1 76 0 2987 Update Group Combination table for Segment 121x, output lines:
S 1 76 0 3061 Update Group Combination table for Segment 112x, output lines:
S 1 76 0 3135 Update Group Combination table for Segment 1111, output lines:
S 1 76 0 3291 Calculated group mark = %d
S 1 76 0 3340 Group combination table for table index %d is updated!!!
S 1 76 0 4014 Fatal Error in file: "TrainingManager.c"; Fatal Print: TrainingManager_Init
S 1 77 0 198 Ts Manager, ADD STA, SID %d, allowed %d, Filter %d
S 1 77 0 287 tsManagerRemoveVap
S 1 77 0 330 Assert in file: "TsManager.c" in line: 330
S 1 77 0 386 Ts Manager, Set Filter, SID %d
S 1 77 0 429 Ts Manager, Remove STA, SID %d
S 1 77 0 626 Fatal Error in file: "TsManager.c"; Fatal Print: TS Manager Action Packet Confirmed - Unknown Action
S 1 77 0 755 Assert in file: "TsManager.c" in line: 755
S 1 77 0 1130 Ts Manager, Send Confirmation, Client %d, SID %d
S 1 77 0 1656 Assert in file: "TsManager.c" in line: 1656
S 1 77 0 1657 Assert in file: "TsManager.c" in line: 1657
S 1 77 0 1658 Assert in file: "TsManager.c" in line: 1658
S 1 77 0 1718 Assert in file: "TsManager.c" in line: 1718
S 1 77 0 1753 Assert in file: "TsManager.c" in line: 1753
S 1 77 1 555 Fatal Error in file: "TsManagerInitiator.c"; Fatal Print: TS Manager Initiator Fatal
S 1 77 1 584 TS Manager Initiator Change SID %d, TID %d, State from %d to %d
S 1 77 1 1861 Assert in file: "TsManagerInitiator.c" in line: 1861
S 1 77 1 2182 tsManagerInitiatorBarConfirmedInOpenedSending station index = %d tid = %d
S 1 77 1 2339 tsManagerInitiatorBarStatusInOpenedSending status %d
S 1 77 1 2366 tsManagerInitiatorBarStatusInOpenedSending normal flow
S 1 77 1 3198 Assert in file: "TsManagerInitiator.c" in line: 3198
S 1 77 1 3233 Assert in file: "TsManagerInitiator.c" in line: 3233
S 1 77 1 3281 Assert in file: "TsManagerInitiator.c" in line: 3281
S 1 77 1 3781 Assert in file: "TsManagerInitiator.c" in line: 3781
S 1 77 1 3836 tsManagerInitiatorFlushIllegalPackets 
S 1 77 1 4376 Assert in file: "TsManagerInitiator.c" in line: 4376
S 1 77 1 4611 TsManagerInitiator_BarConfirmed TsDb->commonPart.stationId %d tid %d state %d
S 1 77 1 4651 TsManagerInitiator_BarStatus TsDb->commonPart.stationId %d tid %d state %d
S 1 77 1 4684 TsManagerInitiator_PdAllocated TsDb->commonPart.stationId %d tid %d state %d
S 1 77 1 4727 Assert in file: "TsManagerInitiator.c" in line: 4727
S 1 77 1 4770 TsManagerInitiator_DiscardedPacket TsDb->commonPart.stationId %d tid %d state %d
S 1 77 1 4806 TsManagerInitiator_QueueIsLocked TsDb->commonPart.stationId %d tid %d state %d
S 1 77 1 5192 Assert in file: "TsManagerInitiator.c" in line: 5192
S 1 77 1 5194 Assert in file: "TsManagerInitiator.c" in line: 5194
S 1 77 2 365 Fatal Error in file: "TsManagerRecipient.c"; Fatal Print: TS Manager Recipient Fatal
S 1 77 2 395 TS Manager Recipient SID %d, TID %d, Change State from %d to %d
S 1 77 2 809 tsManagerRecipientAddbaRequestReceivedInClosed stationIndex %d tid %d 
S 1 77 2 843 tsManagerRecipientAddbaRequestReceivedInOpeningthe s
S 1 77 2 850 tsManagerRecipientAddbaRequestReceivedInOpeningthe same dialog token %d
S 1 77 2 891 tsManagerRecipientAddbaRequestReceivedInOpenedthe s
S 1 77 2 894 tsManagerRecipientAddbaRequestReceivedInOpenedthe same dialog token %d
S 1 77 2 1010 tsManagerRecipientDelbaReceivedInOpeningWaitingForPd remove status %d
S 1 77 2 1055 tsManagerRecipientDelbaReceivedInOpening 
S 1 77 2 1091 tsManagerRecipientDelbaReceivedInOpened 
S 1 77 2 1135 tsManagerRecipientAddbaResponseConfirmedInOpening station index %d tid % d
S 1 77 2 1170 tsManagerRecipientAddbaResponseConfirmedInClosing station index %d tid % d
S 1 77 2 1237 tsManagerRecipientDelbaConfirmedInClosing station index %d tid % d
S 1 77 2 1305 tsManagerRecipientAddbaResponseConfirmedInClosingWaitingForConfirmation 
S 1 77 2 1338 tsManagerRecipientIllegalPacketReceivedInClosed station index %d tid % d
S 1 77 2 1378 tsManagerRecipientIllegalPacketReceivedInClosedWaitingForMessage station index %d tid % d
S 1 77 2 1416 tsManagerRecipientIllegalPacketReceivedInOpeningWaitingForPd station index %d tid % d
S 1 77 2 1458 tsManagerRecipientPdAllocatedInClosedWaitingForMessage station index %d tid % d
S 1 77 2 1495 tsManagerRecipientPdAllocatedInOpeningWaitingForPd station index %d tid % d
S 1 77 2 1536 tsManagerRecipientPdAllocatedInClosingWaitingForPdForDelba station index %d tid % d
S 1 77 2 1576 tsManagerRecipientPdAllocatedInClosingWaitingForPdForAddbaResponse station index %d tid % d
S 1 77 2 1651 tsManagerRecipientBarReceivedInClosed station index %d tid % d
S 1 77 2 1689 tsManagerRecipientBarReceivedInClosedWaitingForMessage station index %d tid % d
S 1 77 2 1727 tsManagerRecipientBarReceivedInOpeningWaitingForPd station index %d tid % d
S 1 77 2 1764 tsManagerRecipientBarReceivedInOpening station index %d tid % d
S 1 77 2 1795 tsManagerRecipientBarReceivedInOpened station index %d tid % d
S 1 77 2 1826 tsManagerRecipientBarReceivedInClosing station index %d tid % d
S 1 77 2 1858 tsManagerRecipientBarReceivedInClosingWaitingForPdForDelba station index %d tid % d
S 1 77 2 1890 tsManagerRecipientBarReceivedInClosingWaitingForPdForDelba station index %d tid % d
S 1 77 2 2074 tsManagerRecipientCloseBaAgreement stationIndex %d tid %d 
S 1 77 2 2171 tsManagerRecipientProcessAddbaRequest invalid parameters 
S 1 77 2 2177 tsManagerRecipientProcessAddbaRequest invalid parameters 
S 1 77 2 2186 tsManagerRecipientProcessAddbaRequest invalid parameters 
S 1 77 2 2277 tsManagerRecipientProcessAddbaRequest ADDBA request declined allocation status %d
S 1 77 2 2330 Assert in file: "TsManagerRecipient.c" in line: 2330
S 1 77 2 2342 TsManagerRecipient_TimerEvent inactivity timeout delete BA agreement %d
S 1 77 2 2646 Assert in file: "TsManagerRecipient.c" in line: 2646
S 1 77 2 2845 TsManagerRecipient_BarReceived illegal BAR
S 1 77 2 3021 Assert in file: "TsManagerRecipient.c" in line: 3021
S 1 77 2 3059 TsManagerRecipient_PdAllocated stationIndex %d tid %d state %d
S 1 77 2 3386 Assert in file: "TsManagerRecipient.c" in line: 3386
S 1 77 2 3388 Assert in file: "TsManagerRecipient.c" in line: 3388
S 1 79 2 87 Assert in file: "TxHandlerNtd.c" in line: 87
S 1 80 0 337 Assert in file: "TxManager.c" in line: 337
S 1 80 0 343 Assert in file: "TxManager.c" in line: 343
S 1 80 0 344 Assert in file: "TxManager.c" in line: 344
S 1 80 0 345 Assert in file: "TxManager.c" in line: 345
S 1 80 0 400 Assert in file: "TxManager.c" in line: 400
S 1 80 0 460 Assert in file: "TxManager.c" in line: 460
S 1 80 0 461 Assert in file: "TxManager.c" in line: 461
S 1 80 0 541 Assert in file: "TxManager.c" in line: 541
S 1 80 0 546 Assert in file: "TxManager.c" in line: 546
S 1 80 0 547 Assert in file: "TxManager.c" in line: 547
S 1 80 0 671 txManagerPackestFromFwListHandler packet descriptor %x
S 1 80 0 982 Fatal Error in file: "TxManager.c"; Fatal Print: txManagerNdpaHandler
S 1 80 0 1092 Assert in file: "TxManager.c" in line: 1092
S 1 80 0 1272 Assert in file: "TxManager.c" in line: 1272
S 1 80 0 1302 Fatal Error in file: "TxManager.c"; Fatal Print: txManagerAssert
S 1 80 0 1329 Fatal Error in file: "TxManager.c"; Fatal Print: txManagerListFatal
S 1 80 0 1434 -------- NTD configured for Sniffer --------
S 1 80 0 1689 Assert in file: "TxManager.c" in line: 1689
S 1 80 0 1808 Assert in file: "TxManager.c" in line: 1808
S 1 80 1 489 TX Manager STA Manager, Station %d changed from %d to %d
S 1 80 1 801 Fatal Error in file: "TxManager_StaManager.c"; Fatal Print: TX Manager STA Manager Fatal
S 1 81 0 148 Assert in file: "TxMulticastHandler.c" in line: 148
S 1 81 0 149 Assert in file: "TxMulticastHandler.c" in line: 149
S 1 81 0 375 Assert in file: "TxMulticastHandler.c" in line: 375
S 1 81 0 376 Assert in file: "TxMulticastHandler.c" in line: 376
S 1 81 0 377 Assert in file: "TxMulticastHandler.c" in line: 377
S 1 81 0 378 Assert in file: "TxMulticastHandler.c" in line: 378
S 1 81 0 418 Assert in file: "TxMulticastHandler.c" in line: 418
S 1 81 0 419 Assert in file: "TxMulticastHandler.c" in line: 419
S 1 81 0 420 Assert in file: "TxMulticastHandler.c" in line: 420
S 1 81 0 421 Assert in file: "TxMulticastHandler.c" in line: 421
S 1 81 0 460 Assert in file: "TxMulticastHandler.c" in line: 460
S 1 81 0 461 Assert in file: "TxMulticastHandler.c" in line: 461
S 1 81 0 571 Assert in file: "TxMulticastHandler.c" in line: 571
S 1 59 1 93 Assert in file: "TxPacketsClassifier.c" in line: 93
S 1 59 1 130 TxPacketsClassifier_SendDataPacket tid = %d
S 1 59 1 331 Assert in file: "TxPacketsClassifier.c" in line: 331
S 1 59 1 332 Assert in file: "TxPacketsClassifier.c" in line: 332
S 1 35 1 584 TxSelector_ReleaseStd, numPendQs = %d
S 1 35 1 716 Assert in file: "TxSelector.c" in line: 716
S 1 35 1 748 TxSelector_DisableRequest - put in pending, numPendingQueues = %d
S 1 35 1 868 TxSelector_LockRequest - put in pending, numPendingQueues = %d
S 1 35 1 1267 txSelectorUnLockQueueIndex - NOT clearing, pendingLockRequest.numPendQs = %d
S 1 35 1 1327 Assert in file: "TxSelector.c" in line: 1327
S 1 35 1 1452 Assert in file: "TxSelector.c" in line: 1452
S 1 35 1 1618 Assert in file: "TxSelector.c" in line: 1618
S 1 35 1 1636 Assert in file: "TxSelector.c" in line: 1636
S 1 35 1 1694 Assert in file: "TxSelector.c" in line: 1694
S 1 35 1 1703 Assert in file: "TxSelector.c" in line: 1703
S 1 35 1 1710 Assert in file: "TxSelector.c" in line: 1710
S 1 35 1 2320 Assert in file: "TxSelector.c" in line: 2320
S 1 35 1 2400 Assert in file: "TxSelector.c" in line: 2400
S 1 4 4 566 Assert in file: "TxSelector.c" in line: 566
S 1 4 4 1242 Fatal Error in file: "TxSelector.c"; Fatal Print: TxSelector_IsDataInQueue - back door not available in gen5b
S 1 4 4 1322 Fatal Error in file: "TxSelector.c"; Fatal Print: ISR TX Selector Error
S 1 82 0 99 Assert in file: "TxSequencer.c" in line: 99
S 1 4 6 157 Assert in file: "TxSequencer.c" in line: 157
S 1 4 6 170 Assert in file: "TxSequencer.c" in line: 170
S 1 83 0 867 [UMI_ADD_VAP_REQ LA]
S 1 83 0 1059 UMI_SET_INTERFERER_DETECTION_PARAMS_REQ: time %u
S 1 83 0 1184 [vUM_PHY_RX_STATUS_REQ]
S 1 83 0 1202 [vMC_PHY_RX_STATUS_CFM]
S 1 83 0 1252 [vUM_SET_CHAN_CFM]
S 1 83 0 1302 Assert in file: "um_interface_task.c" in line: 1302
S 1 83 0 1368 Fatal Error in file: "um_interface_task.c"; Fatal Print: Debug Assert Requested by Host
S 1 83 0 1374 Assert in file: "um_interface_task.c" in line: 1374
S 1 83 0 1395 [vUM_SET_CHAN_REQ]
S 1 83 0 1659 Assert in file: "um_interface_task.c" in line: 1659
S 1 83 0 1683 Assert in file: "um_interface_task.c" in line: 1683
S 1 83 0 1799 Assert in file: "um_interface_task.c" in line: 1799
S 1 83 0 1909 Assert in file: "um_interface_task.c" in line: 1909
S 1 83 0 1920 Assert in file: "um_interface_task.c" in line: 1920
S 1 83 0 2367 Assert in file: "um_interface_task.c" in line: 2367
S 1 83 0 2389 [startLockAttempt 1] *** semaphore test start *** 
S 1 83 0 2411 [startLockAttempt 2] UM is trying to get the lock -> lock is busy = %d
S 1 83 0 2416 [startLockAttempt 3] Get a non used lock 
S 1 83 0 2418 [startLockAttempt 4] Got the lock 
S 1 83 0 2420 [startLockAttempt 5] Free the lock 
S 1 83 0 2423 [startLockAttempt 6] Get a non used lock 
S 1 83 0 2425 Assert in file: "um_interface_task.c" in line: 2425
S 1 83 0 2426 [startLockAttempt 7] Got the lock 
S 1 83 0 2427 [startLockAttempt 8] Free the lock
S 1 83 0 2429 [startLockAttempt 9] Free 
S 1 83 0 2432 [startLockAttempt 10] Get a busy lock 
S 1 83 0 2434 [startLockAttempt 11] Locked 
S 1 83 0 2435 [startLockAttempt 12] Free the lock 
S 1 83 0 2437 [startLockAttempt 13] Free 
S 1 83 0 2474 UMAC Rx UM_DBG_CLI_REQ from Host, action:%d, argc:%d, data1:%d, data2:%d, data3:%d
S 1 83 0 2506 [1] time = %d globalCount = %d
S 1 83 0 2509 [2] time = %d globalCount = %d
S 1 83 0 2513 [3] How long does a trace take
S 1 83 0 2515 [3] a trace takes %d microSeconds
S 1 83 0 2521 semaphore lock was success %d
S 1 83 0 2602 [UmDbgCliReq] Unknown message type
S 1 83 0 2740 CLI req, data1=%d, data2=%d, data3=%d
S 1 83 0 2896 Assert in file: "um_interface_task.c" in line: 2896
S 1 83 0 2923 Assert in file: "um_interface_task.c" in line: 2923
S 1 83 0 2931 Assert in file: "um_interface_task.c" in line: 2931
S 1 83 0 2937 Assert in file: "um_interface_task.c" in line: 2937
S 1 83 0 2971 Assert in file: "um_interface_task.c" in line: 2971
S 1 83 0 2984 Assert in file: "um_interface_task.c" in line: 2984
S 1 83 0 3001 Assert in file: "um_interface_task.c" in line: 3001
S 1 83 0 3015 Assert in file: "um_interface_task.c" in line: 3015
S 1 83 0 3016 Assert in file: "um_interface_task.c" in line: 3016
S 1 83 0 3049 Assert in file: "um_interface_task.c" in line: 3049
S 1 83 0 3062 Assert in file: "um_interface_task.c" in line: 3062
S 1 83 0 3072 Assert in file: "um_interface_task.c" in line: 3072
S 1 83 0 3177 [vUMI_MAN_STA_ADD_REQ]
S 1 83 0 3199 [vUMI_MAN_STA_ADD_CFM]
S 1 83 0 3225 [vUMI_MAN_STA_REMOVE_REQ]
S 1 83 0 3246 [vUMI_MAN_STA_REMOVE_CFM]
S 1 83 0 3307 Assert in file: "um_interface_task.c" in line: 3307
S 1 83 0 3549 [vUMI_MAN_REQUEST_SID_REQ]
S 1 83 0 3569 [vUMI_MAN_REQUEST_SID_CFM]
S 1 83 0 3611 [vUMI_MAN_REMOVE_SID_REQ]
S 1 83 0 3757 Assert in file: "um_interface_task.c" in line: 3757
S 1 83 0 3810 Assert in file: "um_interface_task.c" in line: 3810
S 1 83 0 4079 [vUMI_MAN_REMOVE_SID_CFM]
S 1 83 0 4103 [vUMI_MAN_STOP_TRAFFIC_REQ]
S 1 83 0 4121 [vUMI_MAN_STOP_TRAFFIC_CFM]
S 1 83 0 4685 Fatal Error in file: "um_interface_task.c"; Fatal Print: UMI_GROUP_LOCK_CFM
S 1 83 0 5190 Assert in file: "um_interface_task.c" in line: 5190
S 1 83 0 5230 Assert in file: "um_interface_task.c" in line: 5230
S 1 83 0 5233 Assert in file: "um_interface_task.c" in line: 5233
S 1 41 1 190 Assert in file: "AlphaFilter.c" in line: 190
S 1 84 0 240 Assert in file: "CalendarWheel.c" in line: 240
S 1 84 0 291 Assert in file: "CalendarWheel.c" in line: 291
S 1 84 0 360 Assert in file: "CalendarWheel.c" in line: 360
S 1 36 5 82 Assert in file: "HwSemaphore.c" in line: 82
S 1 36 5 149 Assert in file: "HwSemaphore.c" in line: 149
S 1 36 5 191 Assert in file: "HwSemaphore.c" in line: 191
S 1 36 5 246 [HwSemaphore_Read 1] readValue is %d 
S 1 36 5 273 [HwSemaphore_FreeAllDebug 1] hwSemaphoreShadow = %d
S 1 36 0 121 Assert in file: "MT_Math.c" in line: 121
S 1 36 0 124 Assert in file: "MT_Math.c" in line: 124
S 1 36 0 197 Assert in file: "MT_Math.c" in line: 197
S 1 36 1 60 Assert in file: "Utils_Misc.c" in line: 60
S 1 36 1 81 Assert in file: "Utils_Misc.c" in line: 81
S 1 36 1 113 Assert in file: "Utils_Misc.c" in line: 113
S 1 36 1 166 Assert in file: "Utils_Misc.c" in line: 166
S 1 36 1 201 Assert in file: "Utils_Misc.c" in line: 201
S 1 36 1 567 Fatal Error in file: "Utils_Misc.c"; Fatal Print: Utils_determineSourceTypeAndDmaDirection
S 1 85 0 287 VapDb_AddVap: vapIndex is %X
S 1 85 0 362 VapDb_ResetVapEntry: vapIndex is %X
S 1 85 0 698 Assert in file: "VapDatabase.c" in line: 698
S 1 85 0 721 Assert in file: "VapDatabase.c" in line: 721
S 1 85 0 759 Assert in file: "VapDatabase.c" in line: 759
S 1 85 0 827 Assert in file: "VapDatabase.c" in line: 827
S 1 85 0 1263 VapDB_Init
S 1 85 0 1389 [VapDB_FindCompatibleVap], rssiTypeFlag = %d
S 1 7 4 263 Assert in file: "Beacon_BlockingManager.c" in line: 263
S 1 7 4 264 Assert in file: "Beacon_BlockingManager.c" in line: 264
S 1 7 4 312 Assert in file: "Beacon_BlockingManager.c" in line: 312
S 1 7 4 313 Assert in file: "Beacon_BlockingManager.c" in line: 313
S 1 7 4 514 Restart BeaconHandlerBlockingDb.state =%d
S 1 7 4 554 pScratchPadApiParams->numOfBeaconsTransmitted =%d, BeaconHandlerBlockingDb.lastNumBeaconsTransmitted =%d
S 1 7 4 569 BeaconHandlerBlockingDb.state =%d
S 1 7 4 585 BeaconHandlerBlockingDb.state =%d
S 1 28 23 549 sendChannelParams. Call Requester: %d 
S 1 28 23 564 hdkChannelNotificationCb
S 1 28 23 620 Assert in file: "HdkTask.c" in line: 620
S 1 28 23 641 Assert in file: "HdkTask.c" in line: 641
S 1 28 23 769 Fatal Error in file: "HdkTask.c"; Fatal Print:  In case we're running on FPGA,  we should't get here 
S 1 28 23 776 HDK_startUserDemandProcess. temp1 %d temp2 %d temp3 %d
S 1 28 23 982 limitFromHost %d, limitFromEfuse %d
S 1 28 23 1000 Assert in file: "HdkTask.c" in line: 1000
S 1 28 23 1059 HDK event: HDK_EVENT_ADD_FIRST_VAP. current state: %d
S 1 28 23 1068 HDK event: HDK_EVENT_REMOVE_LAST_VAP. current state: %d
S 1 28 23 1082 HDK event: HDK_EVENT_ENABLE_RF. current state: %d
S 1 28 23 1090 HDK event: HDK_EVENT_DISABLE_RF. current state: %d
S 1 28 23 1102 HDK event: HDK_EVENT_CALIBRATE. current state: %d
S 1 28 23 1113 HDK event: HDK_EVENT_SET_CHANNEL. current state: %d
S 1 28 23 1122 HDK event: HDK_EVENT_ONLINE_TIMER_EXPIRED. current state: %d
S 1 28 23 1135 HDK event: HDK_EVENT_SET_ANTENNAS. current state: %d
S 1 28 23 1144 HDK event: HDK_EVENT_USER_DEMAND. current state: %d
S 1 28 23 1155 Set Channel event: SET_CHANNEL_EVENT_SET_FREQUENCY. current state: %d
S 1 28 23 1164 Set Channel event: SET_CHANNEL_EVENT_FREQUENCY_SET. current state: %d
S 1 28 23 1173 Set Channel event: SET_CHANNEL_EVENT_CAL_RESULTS_LOADED. current state: %d
S 1 28 23 1182 Set Channel event: SET_CHANNEL_EVENT_OFFLINE_CAL_DONE. current state: %d
S 1 28 23 1191 Set Channel event: SET_CHANNEL_EVENT_CAL_RESULTS_STORED. current state: %d
S 1 28 23 1200 Set Channel event: SET_CHANNEL_EVENT_CHANNEL_NOTIFICATION_DONE. current state: %d
S 1 28 23 1209 Set Channel event: SET_CHANNEL_EVENT_REMOVE_LAST_VAP. current state: %d
S 1 28 23 1220 HDK Process event: HDK_PROCESS_EVENT_SCHEDULE_PROCESS_REQ. current state: %d proc: %d
S 1 28 23 1229 HDK Process event: HDK_PROCESS_EVENT_PROCESS_SCHEDULED. current state: %d proc: %d
S 1 28 23 1238 HDK Process event: HDK_PROCESS_EVENT_PROCESS_FINISHED. current state: %d proc: %d
S 1 28 23 1247 HDK Process event: HDK_PROCESS_EVENT_EXECUTION_COMPLETED. current state: %d proc: %d
S 1 28 23 1356 Assert in file: "HdkTask.c" in line: 1356
S 1 28 23 1472 Assert in file: "HdkTask.c" in line: 1472
S 1 28 23 1566 Assert in file: "HdkTask.c" in line: 1566
S 1 28 23 1578 [NO BEACON] hdkProcessScheduleProcessReqStateHandler processId = %d
S 1 28 23 1630 Assert in file: "HdkTask.c" in line: 1630
S 1 28 23 1715 Assert in file: "HdkTask.c" in line: 1715
S 1 28 23 1725 Assert in file: "HdkTask.c" in line: 1725
S 1 28 23 1735 setHdkMainSmState. state: %d
S 1 28 23 1747 setSetChannelSmState. state: %d
S 1 28 23 1761 setHdkProcessSmState. state: %d
S 1 28 23 1773 setHdkProcessId. processId: %d
S 1 28 23 2203 Assert in file: "HdkTask.c" in line: 2203
S 1 28 23 2284 Assert in file: "HdkTask.c" in line: 2284
S 1 28 23 2330 Assert in file: "HdkTask.c" in line: 2330
S 1 53 0 224 Assert in file: "ProcessManager.c" in line: 224
S 1 53 0 226 [NO BEACON] processManagerEnableProcessRequests processManagerParams.state = %d
S 1 53 0 249 Assert in file: "ProcessManager.c" in line: 249
S 1 53 0 251 [NO BEACON] processManagerDisableProcessRequests processManagerParams.state = %d
S 1 53 0 281 processManagerScheduleProcessRequest:Process Manager State = %x processId = %x
S 1 53 0 305 Fatal Error in file: "ProcessManager.c"; Fatal Print: Process Manager Schedule Process Unknown State
S 1 53 0 386 processManagerStartProcess:Process Manager State = %x
S 1 53 0 397 Fatal Error in file: "ProcessManager.c"; Fatal Print: Process Manager Start Process Unknown State
S 1 53 0 430 Fatal Error in file: "ProcessManager.c"; Fatal Print: Process Manager Queue Process Unknown State
S 1 53 0 469 Fatal Error in file: "ProcessManager.c"; Fatal Print: Process Manager Reject Process Unknown State
S 1 53 0 520 Fatal Error in file: "ProcessManager.c"; Fatal Print: Process Manager Abort Process Unknown State
S 1 53 0 548 Fatal Error in file: "ProcessManager.c"; Fatal Print: Process Manager Suspend Process Unknown State
S 1 53 0 579 Fatal Error in file: "ProcessManager.c"; Fatal Print: Process Manager Finish Process Unknown State
S 1 53 0 645 Assert in file: "ProcessManager.c" in line: 645
S 1 53 0 700 Assert in file: "ProcessManager.c" in line: 700
S 1 53 0 791 [NO BEACON] processManagerScanPendingProcessRequests processManagerParams.state = %d
S 1 53 0 809 Assert in file: "ProcessManager.c" in line: 809
S 1 53 0 866 processManagerRunServices:servicesBitMask = %x
S 1 41 8 345 setStaFixedRatesInHwDb 1 isRateInc = %d newRateindex= %d oldRate= %d 
S 1 41 8 361 setStaFixedRatesInHwDb 2 isRateInc = %d newRateindex= %d oldRate= %d 
S 1 41 8 1341 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1341
S 1 41 8 1514 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1514
S 1 41 8 1546 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1546
S 1 41 8 1712 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1712
S 1 41 8 1757 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1757
S 1 41 8 1759 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1759
S 1 41 8 1760 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1760
S 1 41 8 1773 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1773
S 1 41 8 1841 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1841
S 1 41 8 1933 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1933
S 1 41 8 1934 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1934
S 1 41 8 1935 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1935
S 1 41 8 1949 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1949
S 1 41 8 2025 Assert in file: "LinkAdaptationPhyDriver.c" in line: 2025
S 1 41 8 2114 Assert in file: "LinkAdaptationPhyDriver.c" in line: 2114
S 1 41 8 2878 Fatal Error in file: "LinkAdaptationPhyDriver.c"; Fatal Print: LinkAdaptationPhyDriver_UpdatePhyGenriscScpad
S 1 41 8 2920 Assert in file: "LinkAdaptationPhyDriver.c" in line: 2920
S 1 41 8 3047 Assert in file: "LinkAdaptationPhyDriver.c" in line: 3047
S 1 41 8 3154 Assert in file: "LinkAdaptationPhyDriver.c" in line: 3154
S 1 41 8 3157 Assert in file: "LinkAdaptationPhyDriver.c" in line: 3157
S 1 41 8 3197 Assert in file: "LinkAdaptationPhyDriver.c" in line: 3197
S 1 41 8 3208 Assert in file: "LinkAdaptationPhyDriver.c" in line: 3208
S 1 41 8 3218 Assert in file: "LinkAdaptationPhyDriver.c" in line: 3218
S 1 4 1 880 isr_AggregationBuilder_ErrorOrDone, status 0x%x
S 1 4 1 959 Assert in file: "AggregationBuilder.c" in line: 959
S 1 4 1 983 Assert in file: "AggregationBuilder.c" in line: 983
S 1 4 1 1014 Assert in file: "AggregationBuilder.c" in line: 1014
S 1 4 1 1021 Assert in file: "AggregationBuilder.c" in line: 1021
S 1 4 1 1072 Assert in file: "AggregationBuilder.c" in line: 1072
S 1 4 1 1103 Assert in file: "AggregationBuilder.c" in line: 1103
S 1 4 1 1319 Assert in file: "AggregationBuilder.c" in line: 1319
S 1 4 1 1343 Assert in file: "AggregationBuilder.c" in line: 1343
S 1 41 15 723 slowProbingHandler, staIndex = %d, stayWithLastProbingPoint = %d, notEffectveProbeCounter = %d
S 1 41 15 830 Assert in file: "RateAdaptation.c" in line: 830
S 1 41 15 841 raFastProbingProcessFeedback, WORKING POINT CHANGED, Bw=%d, Last rate = %d, new Rate = %d, newPER = %d
S 1 41 15 939 rateAdaptationChangeWorkingPoint, BW = %d, newRate = %d, prevRate = %d
S 1 41 15 962 Assert in file: "RateAdaptation.c" in line: 962
S 1 41 15 1035 updatePerStability, stabilityStateBeforeChange = %d, pStabilityState = %d
S 1 41 15 1097 updatePerStability, perDeviationStability = %d,targetPerStability = %d, resultPerStability = %d
S 1 41 15 1174 Assert in file: "RateAdaptation.c" in line: 1174
S 1 41 15 1248 Assert in file: "RateAdaptation.c" in line: 1248
S 1 41 15 1341 Assert in file: "RateAdaptation.c" in line: 1341
S 1 41 15 1349 Assert in file: "RateAdaptation.c" in line: 1349
S 1 41 15 1362 Assert in file: "RateAdaptation.c" in line: 1362
S 1 41 15 1672 Assert in file: "RateAdaptation.c" in line: 1672
S 1 41 15 1745 Assert in file: "RateAdaptation.c" in line: 1745
S 1 41 15 1877 rateAdaptationFastDrop, BW = %d, currentRateIndex = %d, newRateindex = %d
S 1 41 15 1903 rateAdaptationProbingTimerEvent , event %d 
S 1 41 15 1989 Assert in file: "RateAdaptation.c" in line: 1989
S 1 41 15 1990 Assert in file: "RateAdaptation.c" in line: 1990
S 1 41 15 1991 Assert in file: "RateAdaptation.c" in line: 1991
S 1 41 15 2042 Assert in file: "RateAdaptation.c" in line: 2042
S 1 41 15 2427 setStaDataRate isRateInc = %d
S 1 41 15 2430 setStaDataRate pLaDbDistributionParameter->uspIndex = %d
S 1 41 15 2449 setStaDataRate isRateInc = %d newRateindex = %d oldRate = %d 
S 1 41 15 2506 eeeeeeeeeee stationIndex = %d maxRatePerBW[0] = %d numberOfNss[0] = %d 
S 1 41 15 2517 eeeeeeeeeee stationIndex = %d maxRatePerBW[1] = %d numberOfNss[1] = %d 
S 1 41 15 2527 eeeeeeeeeee stationIndex = %d maxRatePerBW[2] = %d numberOfNss[2] = %d 
S 1 41 15 2552 eeeeeee powerAdaptationGetultimateEvm = %d getRatePowerOffsetForGroupMu = %d power = %d 
S 1 41 15 2568 eeeeeee  pTcr0Data->rfPower = %d pTcr0Data->rfPower = %d bfMode = %d 
S 1 41 15 2570 eeeeeee  pTcr0Data->rfPower = %d pTcr0Data->rfPower = %d bfMode = %d 
S 1 41 16 151 linkAdaptationStateMachine: la_state %d, event %d
S 1 41 16 209 timerAgerEvent
S 1 41 16 391 waitForNextProbeCycleStateBaTxReportEvent- waitForNextProbeCycleStateBaTxReportEvent == %d
S 1 41 16 652 waitForFastProbeValidStateBaTxReportEvent
S 1 41 16 758 waitForFastProbeValidStateBaProbeResponseEvent
S 1 41 16 804 waitForFastProbeValidStateProbingTimerEvent
S 1 41 16 1110 Assert in file: "LinkAdaptation_StateMachine.c" in line: 1110
S 1 41 16 1161 Probe response ignored after state aging, stationIndex = %d
S 1 41 16 1193 Assert in file: "LinkAdaptation_StateMachine.c" in line: 1193
S 1 41 16 1219 updateOverridePendingDb. override %d value %d
S 1 41 16 1239 Assert in file: "LinkAdaptation_StateMachine.c" in line: 1239
S 1 41 16 1307 executeParamOverride, staIdx: %d
S 1 41 16 1485 Fatal Error in file: "LinkAdaptation_StateMachine.c"; Fatal Print: laStateMachineProcessBaaReport
S 1 41 16 1491 laStateMachineProcessBaaReport, event %d
S 1 41 16 1496 laStateMachineProcessBaaReport, event %d
S 1 41 16 1524 laStateMachineProcessSequencerReport, event %d
S 1 41 16 1529 laStateMachineProcessSequencerReport, event %d
T 1 5 0 267 BaaTxReport_t
T 1 6 1 297 BaaTxReport_t
T 1 8 0 226 PacManagerStart_t
T 1 9 0 402 UMI_BEACON_SET
T 1 9 2 209 UMI_ADD_VAP
T 1 9 2 353 UMI_SET_BSS
T 1 9 2 548 UMI_SET_WMM_PARAMETERS
T 1 9 2 788 UMI_STOP_VAP_TRAFFIC
T 1 9 2 1093 VAP_MANAGER_REGISTRATION_ELEMENT
T 1 10 0 164 UM_SET_CHAN_PARAMS
T 1 14 0 186 UMI_MIB
T 1 16 2 173 metricFifoEntry_t
T 1 18 0 359 dutMessageHeader_t
T 1 18 1 152 dutChipVersion_t
T 1 18 1 207 dutSetAntennaParams_t
T 1 18 1 237 LinkAdaptationFixedAntennaSelection_t
T 1 18 1 261 dutSetAntennaParams_t
T 1 18 1 360 dutTxSpacelessParams_t
T 1 18 1 466 dutIfsParams_t
T 1 18 1 516 dutRssiParams_t
T 1 18 1 572 dutTpcFeedbackparams_t
T 1 18 1 679 dutRficRxGainsParams_t
T 1 18 1 699 dutXtalParams_t
T 1 18 1 717 dutXtalParams_t
T 1 18 1 758 dutMemoryAccessParams_t
T 1 18 1 796 dutMemoryAccessParams_t
T 1 18 1 911 dutTpcFeedbackparams_t
T 1 18 1 931 dutRficTxGainsParams_t
T 1 18 2 174 dutPowerOutVecParams_t
T 1 18 2 185 dutPowerOutVecParams_t
T 1 18 2 242 RssiGainBlock_t
T 1 18 2 250 RssiCwPower_t
T 1 18 2 256 S2dParams_t
T 1 18 2 264 DutRssiOffsetGain_t
T 1 18 2 271 RssiDBPower_t
T 1 18 2 280 Clipping_trigger_t
T 1 18 2 314 dutLnaMidGain_t
T 1 18 2 397 clbrHndlrResetConf_t
T 1 18 2 415 dutStartCalibrationParams_t
T 1 18 2 417 dutDB_t
T 1 18 2 681 dutSetRate_t
T 1 18 2 703 LaFixedRateParams_t
T 1 18 2 736 dutGetFwInfo_t
T 1 18 2 770 dutDB_t
T 1 18 3 260 dutTxParams_t
T 1 18 3 273 trafficParams_t
T 1 18 3 433 FM_PAYLOAD_MANAGEMENT_ACTION_PUBLIC_FRAME
T 1 18 3 449 manPacketDescriptor_t
T 1 27 18 683 ClbrMngr_TemperatureDB_t
T 1 27 18 684 ClbrMngr_OnlineCalibDB_t
T 1 27 18 748 ClbrMngr_CalibrateDB_t
T 1 27 18 798 ClbrMngr_CalibrateDB_t
T 1 31 0 950 UMI_MULTICAST_MODE
T 1 32 7 418 ENET_RXF
T 1 41 0 146 AntennaSelectionDatabase_t
T 1 41 0 160 AntennaSelectionDatabase_t
T 1 41 0 194 AntennaSelectionDatabase_t
T 1 41 0 483 AntennaSelectionDatabase_t
T 1 41 18 280 LaTcrModificationStruct_t
T 1 41 4 1214 LaStationGroupCommonParams_t
T 1 41 4 1215 LaStationUspCommonParams_t
T 1 41 4 1221 LaStationUniqueParams_t
T 1 41 4 1225 LaGroupUniqueParams_t
T 1 41 4 2240 SequencerTxReport_t
T 1 41 6 342 LaTcrModificationStruct_t
T 1 41 19 406 RateMask_t
T 1 41 19 788 RateMask_t
T 1 41 19 789 RateMask_t
T 1 41 19 813 RateMask_t
T 1 41 19 832 RateMask_t
T 1 41 19 833 RateMask_t
T 1 41 5 895 SequencerTxReport_t
T 1 41 5 1273 LaFixedRateParams_t
T 1 41 5 2153 RateMask_t
T 1 43 2 183 UmiLoggerMsgSetFilter_t
T 1 43 2 266 UmiLoggerMsgSetMode_t
T 1 43 2 333 UmiLoggerMsgFlushBuffer_t
T 1 76 0 420 GroupCombinationTableDebug_t
T 1 76 0 1147 TrainingVectorDebugStruct_t
T 1 76 0 1212 TrainingManagerStaBitmap_t
T 1 76 0 1221 TrainingManagerStaBitmap_t
T 1 76 0 1360 GroupManagerStationBitmap_t
T 1 76 0 1718 MuEffectiveRateDbRamEntry_u
T 1 76 0 1767 MuEffectiveRateDbRamEntry_u
T 1 76 0 1831 MuEffectiveRateDbRamEntry_u
T 1 76 0 1898 MuEffectiveRateDbRamEntry_u
T 1 76 0 1962 MuEffectiveRateDbRamEntry_u
T 1 76 0 2023 MuEffectiveRateDbRamEntry_u
T 1 76 0 2087 MuEffectiveRateDbRamEntry_u
T 1 76 0 2156 MuEffectiveRateDbRamEntry_u
T 1 76 0 2227 MuEffectiveRateDbRamEntry_u
T 1 76 0 2298 MuEffectiveRateDbRamEntry_u
T 1 76 0 2370 MuEffectiveRateDbRamEntry_u
T 1 76 0 2514 MuEffectiveRateDbRamEntry_u
T 1 76 0 2551 MuEffectiveRateDbRamEntry_u
T 1 76 0 2602 MuEffectiveRateDbRamEntry_u
T 1 76 0 2669 MuEffectiveRateDbRamEntry_u
T 1 76 0 2736 MuEffectiveRateDbRamEntry_u
T 1 76 0 2800 MuEffectiveRateDbRamEntry_u
T 1 76 0 2866 MuEffectiveRateDbRamEntry_u
T 1 76 0 2939 MuEffectiveRateDbRamEntry_u
T 1 76 0 3014 MuEffectiveRateDbRamEntry_u
T 1 76 0 3088 MuEffectiveRateDbRamEntry_u
T 1 76 0 3164 MuEffectiveRateDbRamEntry_u
T 1 76 0 3341 GroupCombinationTableEntry_t
T 1 83 0 790 UMI_MBSS_PRE_ACTIVATE
T 1 83 0 1277 UMI_SET_KEY
T 1 83 0 1435 UMI_GROUP_PN
T 1 83 0 3173 UMI_STA_ADD
T 1 83 0 3221 UMI_STA_REMOVE
T 1 83 0 3470 UMI_DATA_PATH_INIT_PARAMS
T 1 83 0 3551 UMI_REQUEST_SID
T 1 83 0 3609 UMI_REMOVE_SID
T 1 83 0 3639 UMI_QAMPLUS_ACTIVATE
T 1 83 0 3679 UMI_TS_VAP_CONFIGURE
T 1 83 0 3701 UMI_MSDU_IN_AMSDU_CONFIG
T 1 83 0 3728 UMI_MU_OPERATION_CONFIG
T 1 83 0 3754 UMI_RTS_MODE_CONFIG
T 1 83 0 3781 UMI_RTS_MODE_CONFIG
T 1 83 0 3891 UMI_FIXED_RATE_CONFIG
T 1 83 0 3984 UMI_BeaconBlockTimerInterval_t
T 1 83 0 4099 UMI_STOP_TRAFFIC
T 1 83 0 4144 UMI_FRAME_CLASS_ERROR
T 1 85 0 336 VapDb_t
T 1 28 23 550 ChannelNotificationParams_t
T 1 28 23 565 ChannelNotificationParams_t
T 1 28 23 603 UmiHwDependentConfig_t
T 1 28 23 682 tpcConfig_t
T 1 28 23 704 UMI_HDK_CONFIG
T 1 28 23 1106 UMI_CALIBRATE_PARAMS
T 1 28 23 1924 cocReq_t
T 1 28 23 2018 UmiHwDependentConfig_t
T 1 41 16 1262 overridePendingDb_t
