#!/bin/sh

# no longer needed for "Save and Apply" to restart ddns
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@ddns[-1]
	commit ucitrack
EOF

if [ -e "/usr/lib/ddns/update_aliyun_com.sh" ]; then
	printf "%s\\t\\t%s\\n" '"aliyun.com"' '"update_aliyun_com.sh"' >> /etc/ddns/services
	printf "%s\\t\\t%s\\n" '"aliyun.com"' '"update_aliyun_com.sh"' >> /etc/ddns/services_ipv6
fi
if [ -e "/usr/lib/ddns/update_cloudflare.com-v4.sh" ]; then
	printf "%s\\t%s\\n" '"cloudflare.com-v4.sh"' '"update_cloudflare_com_v4.sh"' >> /etc/ddns/services
	printf "%s\\t%s\\n" '"cloudflare.com-v4.sh"' '"update_cloudflare_com_v4.sh"' >> /etc/ddns/services_ipv6
fi
if [ -e "/usr/lib/ddns/update_no-ip_com.sh" ]; then
	printf "%s\\t%s\\n" '"no-ip.com"' '"update_no-ip_com.sh"' >> /etc/ddns/services
fi
rm -f /tmp/luci-indexcache
return 0
