O 1 FW
G 1 1 GLOBAL_GID_802_11_PROTOCOL
G 1 2 GLOBAL_AGER_EMULATOR
G 1 3 GLOBAL_GID_AGGREGATION_BUILDER
G 1 4 GLOBAL_GID_TX_HW_ACCELERATORS
G 1 5 GLOBAL_GID_ATF
G 1 6 GLOBAL_GID_BA_ANALYZER
G 1 7 GLOBAL_GID_HW_DRIVERS
G 1 8 GLOBAL_GID_BEACON_HANDLER
G 1 9 GLOBAL_GID_BSS
G 1 10 GLOBAL_GID_BSS_MANAGER
G 1 11 GLOBAL_GID_CHANNEL_SWITCH_MANAGER
G 1 12 GLOBAL_GID_COC
G 1 13 GLOBAL_GID_CSA_MANAGER
G 1 14 GLOBAL_GID_CTS_MANAGER
G 1 15 GLOBAL_GID_DATABASE
G 1 16 GLOBAL_GID_SECURITY_DEBRA
G 1 17 GLOBAL_GID_DEBUG_ENVIRONMENT
G 1 18 GLOBAL_GID_DMA_MANAGER
G 1 19 GLOBAL_GID_DUT
G 1 20 GLOBAL_GID_ERROR_HANDLER
G 1 21 GLOBAL_GID_EVENTS_MANAGER
G 1 22 GID_MTIDLPARSER
G 1 23 GID_LOG
G 1 24 GLOBAL_GID_GIDM_MANAGER
G 1 25 GLOBAL_GID_GROUP_DB
G 1 26 GLOBAL_GID_GROUP_MANAGER
G 1 27 GLOBAL_GID_HDK_CALIBRATIONS_1
G 1 28 GLOBAL_GID_CALIBRATIONS
G 1 29 GLOBAL_GID_HDK_MODULE
G 1 30 GLOBAL_GID_HDK_MODULE_1
G 1 31 GLOBAL_GID_GENRISCS_INTERFACE
G 1 32 GLOBAL_GID_HOST_IF
G 1 33 GLOBAL_GID_PAC
G 1 34 GLOBAL_GID_PAC_1
G 1 35 GLOBAL_GID_RX_QUEUES
G 1 36 GLOBAL_GID_TX_SELECTOR
G 1 37 GLOBAL_GID_UTILS
G 1 38 GLOBAL_GID_INTERFERER_DETECTION
G 1 39 GLOBAL_GID_SYS
G 1 40 GLOBAL_GID_IPC
G 1 41 GLOBAL_GID_KERNEL
G 1 42 GLOBAL_GID_LINK_ADAPTATION
G 1 43 GLOBAL_GID_LOCKER
G 1 44 GLOBAL_GID_LOGGER
G 1 45 GLOBAL_GID_LOWER_MAC
G 1 46 GLOBAL_GID_QUEUE_MGMT
G 1 47 GLOBAL_GID_LOWER_MAC_IF
G 1 48 GLOBAL_GID_MEMORY_MGMT
G 1 49 GLOBAL_GID_NDPA_MANAGER
G 1 50 GLOBAL_GID_PACKET_TRAFFIC_ARBITRATOR
G 1 51 GLOBAL_GID_PAC_MANAGER
G 1 52 GLOBAL_GID_PAUSER
G 1 53 GLOBAL_GID_PERIPHERALS
G 1 54 GLOBAL_GID_SECURITY
G 1 55 GLOBAL_GID_PROCESS_MANAGER
G 1 56 GLOBAL_GID_PROTECTED_DB_LOCK
G 1 57 GLOBAL_GID_PS_MANAGER
G 1 58 GLOBAL_GID_QOS
G 1 59 GLOBAL_GID_QS_MANAGER
G 1 60 GLOBAL_GID_REG_ACCESS
G 1 61 GLOBAL_GID_WAVE500
G 1 62 GLOBAL_GID_RX_CLASSIFIER
G 1 63 GLOBAL_GID_RX_DATA_PATH
G 1 64 GLOBAL_GID_RX_HANDLER
G 1 65 GLOBAL_GID_RX_LIBERATOR
G 1 66 GLOBAL_GID_RX_MANAGER
G 1 67 GLOBAL_GID_RX_POST_PROCESSING
G 1 68 GLOBAL_GID_RX_HW_ACCLERATORS
G 1 69 GLOBAL_GID_RSN
G 1 70 GLOBAL_GID_SENDER
G 1 71 GLOBAL_GID_SERVICES_HANDLER
G 1 72 GLOBAL_GID_SHARED_RAM
G 1 73 GLOBAL_GID_SMPS_MANAGER
G 1 74 GLOBAL_GID_STATION_DB
G 1 75 GID_STATISTICS_MANAGER
G 1 76 GLOBAL_GID_TX_APP
G 1 77 GLOBAL_GID_TINY_KERNEL
G 1 78 GID_TRAINING_MANAGER
G 1 79 GLOBAL_GID_TS_MANAGER
G 1 80 GLOBAL_GID_TX_DATA_PATH
G 1 81 GLOBAL_GID_TX_HANDLER
G 1 82 GLOBAL_GID_TX_MANAGER
G 1 83 GLOBAL_GID_TX
G 1 84 GLOBAL_GID_TX_SEQUENCER
G 1 85 GLOBAL_GID_UPPER_MAC_INTERFACE
G 1 86 GLOBAL_GID_CALENDAR_WHEEL
G 1 87 GLOBAL_GID_VAP_DB
S 1 42 20 54 DynamicTxop_SetTxopMode. staId %d mode %d
S 1 42 20 104 DynamicTxop_OverwriteTxopModeForMuMember. staId %d mode %d
S 1 42 20 155 DynamicTxop_RateOrBwIsChanged. currentMaxPsduTime %d newMaxPsduTime %d
S 1 42 20 174 DynamicTxop_UpdateEstimator. currentPsduTime %d counter %d
S 1 42 20 223 setTxopModeInHwStaDb. staId %d mode %d
S 1 42 20 241 setTxopInHwStaDb. staId %d enable %d
S 1 42 20 269 setTxopAccordingToPsduTimeEstimation. effectivePsduTime %d currentMaxPsduTime %d enable %d
S 1 42 20 294 calcMaxPsduTimePerRateAndBw. psduLength %d phyRate %d maxTime %d
S 1 42 20 305 getMaxPsduTimeFromStaDb. staId %d maxTime %d 
S 1 50 0 298 Assert in file: "PacketTrafficArbitrator.c" in line: 298
S 1 50 0 304 [PTA][PtaTest] Test command received
S 1 50 0 342 [PTA][PtaTestDriverReq]
S 1 50 0 354 [PTA][PtaTestEmulateGpio0Int] btActiveVal = %d txDemandVal = %d
S 1 50 0 370 [PTA][PtaTestReset]
S 1 50 0 418 [PTA][REP][PtaTestRep]
S 1 50 0 441 [PTA][PtaTestModifyQosParam] bUseRepetitionMoe value = %d
S 1 50 0 455 [PTA][PtaTestModifyQosParam] Suspend new value = %d will use = %d old value = %d resume = %d
S 1 50 0 470 [PTA][PtaTestModifyQosParam] Resume new value = %d will use = %d old value = %d suspend = %d
S 1 50 0 481 [PTA][PtaTestModifyQosParam] ZigBee radioHoldOffValue new value = %d old value = %d
S 1 50 0 492 [PTA][PtaTestModifyQosParam] ZigBee starvationTimeValue new value = %d old value = %d
S 1 50 0 504 [PTA][PtaTestModifyQosParam] BT radioHoldOffValue new value = %d old value = %d
S 1 50 0 516 [PTA][PtaTestModifyQosParam] BT starvationTimeValue new value = %d old value = %d
S 1 50 0 526 [PTA][PtaTestModifyQosParam] you are trying to change a PTA parameter but with wrong "parameter". allwoed values are 0 - 6
S 1 50 0 770 [PTA][ptaInit]
S 1 50 0 805 [PTA][ptaInit] Feature is disabled
S 1 50 0 836 [PTA][PtaPendingDriverReq]
S 1 50 0 844 Assert in file: "PacketTrafficArbitrator.c" in line: 844
S 1 50 0 874 Assert in file: "PacketTrafficArbitrator.c" in line: 874
S 1 50 0 876 [PTA][PtaStateChange] currentState = %d nextState = %d
S 1 50 0 981 Assert in file: "PacketTrafficArbitrator.c" in line: 981
S 1 50 0 983 Assert in file: "PacketTrafficArbitrator.c" in line: 983
S 1 50 0 985 Assert in file: "PacketTrafficArbitrator.c" in line: 985
S 1 50 0 998 [PTA][PtaStateInitTestCommand]
S 1 50 0 1125 [PTA][PtaStateTxStarvationTimerExpired] State = %d isGrantHigh = %d isBtActiveHigh = %d isTxDemandHigh = %d
S 1 50 0 1129 Assert in file: "PacketTrafficArbitrator.c" in line: 1129
S 1 50 0 1176 [PTA][PtaStateTestStarvationTimerExpired] State = %d 
S 1 50 0 1178 Assert in file: "PacketTrafficArbitrator.c" in line: 1178
S 1 50 0 1200 [PTA][PtaMoveToIdle]
S 1 50 0 1280 [PTA][PtaZigBeeDenyError] ZigBee does not understand DENY
S 1 50 0 1285 Assert in file: "PacketTrafficArbitrator.c" in line: 1285
S 1 50 0 1299 [PTA][PtaGrantNotUsed] radio = %d is not using the grant
S 1 50 0 1305 Assert in file: "PacketTrafficArbitrator.c" in line: 1305
S 1 50 0 1314 [PTA][PtaStartBtTx]
S 1 50 0 1329 [PTA][PtaStartZigBeeTx]
S 1 50 0 1350 [PTA][PtaTxOngoing] BT = %d
S 1 50 0 1424 [PTA][PtaHandle24GCoExReq]  Driver: ON
S 1 50 0 1440 [PTA][PtaHandle24GCoExReq] Delaying the handling of Driver command since PTA is not in IDLE. PTA State = %d
S 1 50 0 1449 [PTA][PtaHandle24GCoExReq] Driver: all other radios off
S 1 50 0 1462 [PTA][PtaHandle24GCoExReq] Driver: 2.4G co-ex feature is off
S 1 50 0 1477 [PTA][GPIO ERROR][PtaTestGpioValueIsWrong] GPIO = %d ERROR = %d
S 1 50 0 1495 [PTA][PtaTestHwTimerIsOK] Test completed OK
S 1 50 0 1529 [PTA][PtaGpioDetermineEvent] btCounter = %d BT->radioHoldOffValue = %d ZigBeeCounter = %d ZigBee->radioHoldOffValue = %d
S 1 50 0 1581 [PTA][PtaStarvationTimerStart] timeToGo = %d
S 1 50 0 1590 [PTA][PtaStarvationTimerStop]
S 1 50 0 1744 [PTA][Isr_PtaGpio0] BT_ACTIVE = %d TX_DEMAND = %d state = %d
S 1 50 0 1759 [PTA][Isr_PtaGpio0] ptaSmEvents = %d
S 1 50 0 1773 Assert in file: "PacketTrafficArbitrator.c" in line: 1773
S 1 50 0 1786 [PTA][Isr_MipsTimer1]
S 1 50 0 1791 Assert in file: "PacketTrafficArbitrator.c" in line: 1791
S 1 50 0 1845 [PTA][PtaHwTimerDetermineEvent] event = %d
S 1 50 0 1934 [PTA][PtaPhyTxRegisterSet] register = %d write regVal = 0x%x
S 1 50 0 2012 [PTA][PtaIgnoreEvent] State = %d event = %d									*** que pasa? ***
S 1 50 0 2016 Assert in file: "PacketTrafficArbitrator.c" in line: 2016
S 1 50 0 2028 Assert in file: "PacketTrafficArbitrator.c" in line: 2028
S 1 50 0 2046 [PTA][PtaIllegalEvent] State = %d event = %d									*** que pasa? ***
S 1 50 0 2050 Assert in file: "PacketTrafficArbitrator.c" in line: 2050
S 1 50 1 153 [PTA][REP][PtaRepEventStart] repetition enable = %d
S 1 50 1 172 [PTA][REP][PtaRepEventActiveTimer] repetition enable = %d
S 1 50 1 207 [PTA][REP][PtaRepEventProcessStart] repetition enable = %d
S 1 50 1 228 [PTA][REP][PtaRepEventInactiveTimer]
S 1 50 1 239 [PTA][REP][PtaRepEventProcessStop] repetition enable = %d
S 1 50 1 257 [PTA][REP][PtaRepEventIgnore]
S 1 50 1 263 [PTA][REP][PtaRepEventAssert] ASSERT === ASSERT === ASSERT
S 1 50 1 271 [PTA][REP][PtaRepStateChange] currrnet state = %d next state = %d
S 1 50 1 281 [PTA][REP][PtaRepTimerStart] timeToGo = %d
S 1 50 1 300 [PTA][REP][PtaRepConfig] enable = %d activePeriod = %d inactivePeriod = %d
S 1 50 1 312 [PTA][REP][PtaRepTimerExpiry]
S 1 50 1 324 [PTA][REP][PtaRepProcessStart]
S 1 50 1 335 [PTA][REP][PtaRepProcessEnd]
S 1 50 1 361 [PTA][PtaGpioReadBtActive] BT not connected to board. BT_ACTIVE = LOW
S 1 50 1 383 [PTA][PtaGpioWriteGrant] Both ZigBee and BT are not connected to board. GRANT is not set
S 1 50 1 397 [PTA][PtaGpioDirectionGrant] Both ZigBee and BT are not connected to board. Not setting GPIO direction for GRANT
S 1 50 1 415 [PTA][PtaGpioDirection] register = 0x%x value = 0x%x
S 1 50 1 425 [PTA][PtaGpioRead] before isolation register = 0x%x value = 0x%x
S 1 50 1 432 [PTA][PtaGpioRead] after  isolation register = 0x%x value = 0x%x
S 1 50 1 445 [PTA][PtaGpioWrite] Value read from register  = 0x%x value = 0x%x
S 1 50 1 456 [PTA][PtaGpioWrite] Value written to register = 0x%x value = 0x%x
S 1 50 1 467 [PTA][PtaGpioMaskGpio0] Value read from register  = 0x%x value = 0x%x
S 1 50 1 476 [PTA][PtaGpioMaskGpio0] Value written to register = 0x%x value = 0x%x
S 1 50 1 488 [PTA][PtaGpioInitGpioState] setting GRANT as HIGH
S 1 50 1 497 [PTA][ptaGpioLatchClearGpio0] Latch cleared
S 1 50 1 508 [PTA][ptaGpioUnmsakGpio0] Value read from register  = 0x%x value = 0x%x
S 1 50 1 517 [PTA][ptaGpioUnmsakGpio0] Value written to register = 0x%x value = 0x%x
S 1 50 1 525 [PTA][PtaGpioBtAllow]
S 1 50 1 535 [PTA][PtaGpioBtDeny]
S 1 50 1 544 [PTA][PtaGpioZigBeeAllow]
S 1 50 1 554 [PTA][PtaGpioZigBeeDeny]
S 1 50 2 144 [PTA][REP][PtaRepEventStart] repetition enable = %d
S 1 50 2 163 [PTA][REP][PtaRepEventActiveTimer] repetition enable = %d
S 1 50 2 198 [PTA][REP][PtaRepEventProcessStart] repetition enable = %d
S 1 50 2 219 [PTA][REP][PtaRepEventInactiveTimer]
S 1 50 2 230 [PTA][REP][PtaRepEventProcessStop] repetition enable = %d
S 1 50 2 248 [PTA][REP][PtaRepEventIgnore]
S 1 50 2 254 [PTA][REP][PtaRepEventAssert] ASSERT === ASSERT === ASSERT
S 1 50 2 262 [PTA][REP][PtaRepStateChange] currrnet state = %d next state = %d
S 1 50 2 272 [PTA][REP][PtaRepTimerStart] timeToGo = %d
S 1 50 2 291 [PTA][REP][PtaRepConfig] enable = %d activePeriod = %d inactivePeriod = %d
S 1 50 2 303 [PTA][REP][PtaRepTimerExpiry]
S 1 50 2 315 [PTA][REP][PtaRepProcessStart]
S 1 50 2 326 [PTA][REP][PtaRepProcessEnd]
S 1 50 2 352 [PTA][PtaGpioReadBtActive] BT not connected to board. BT_ACTIVE = LOW
S 1 50 2 369 [PTA][PtaGpioReadGrant] ZigBee is not connected to board. GRANT = HIGH
S 1 50 2 384 [PTA][PtaGpioWriteGrant] ZigBee is not connected to board. GRANT is not set
S 1 50 2 398 [PTA][PtaGpioDirectionGrant] ZigBee is not connected to board. Not setting GPIO direction for GRANT
S 1 50 2 411 [PTA][PtaGpioDirectionWlanDeny] BT is not connected to board. Not setting GPIO direction for WLAN_DENY
S 1 50 2 425 [PTA][PtaGpioWriteWlanDeny] BT is not connected to board. WLAN_DENY is not set
S 1 50 2 444 [PTA][PtaGpioDirection] register = 0x%x value = 0x%x
S 1 50 2 454 [PTA][PtaGpioRead] before isolation register = 0x%x value = 0x%x
S 1 50 2 461 [PTA][PtaGpioRead] after  isolation register = 0x%x value = 0x%x
S 1 50 2 474 [PTA][PtaGpioWrite] Value read from register  = 0x%x value = 0x%x
S 1 50 2 485 [PTA][PtaGpioWrite] Value written to register = 0x%x value = 0x%x
S 1 50 2 494 [PTA][PtaGpioMaskGpio0] Value written to register = 0x%x bit = %d value = 0x%x
S 1 50 2 510 [PTA][PtaGpioInitGpioState] setting GRANT as HIGH and WLAN_DENY as HIGH
S 1 50 2 519 [PTA][ptaGpioLatchClearGpio0] Latch cleared
S 1 50 2 528 [PTA][ptaGpioUnmsakGpio0] Value written to register = 0x%x bit = %d value = 0x%x
S 1 50 2 535 [PTA][PtaGpioBtAllow]
S 1 50 2 546 [PTA][PtaGpioBtDeny]
S 1 50 2 557 [PTA][PtaGpioZigBeeAllow]
S 1 50 2 568 [PTA][PtaGpioZigBeeDeny]
S 1 76 1 128 Assert in file: "tx_application_define.c" in line: 128
S 1 76 1 136 Assert in file: "tx_application_define.c" in line: 136
S 1 76 1 153 Assert in file: "tx_application_define.c" in line: 153
S 1 76 1 165 Assert in file: "tx_application_define.c" in line: 165
S 1 76 1 185 Assert in file: "tx_application_define.c" in line: 185
S 1 76 1 221 Assert in file: "tx_application_define.c" in line: 221
S 1 76 2 59 Assert in file: "tx_application_entry_func.c" in line: 59
S 1 76 2 62 Thread : %d  Entry func, recieved message 
S 1 76 2 63 Assert in file: "tx_application_entry_func.c" in line: 63
S 1 76 2 67 Assert in file: "tx_application_entry_func.c" in line: 67
S 1 76 3 96 Assert in file: "tx_application_func.c" in line: 96
S 1 76 3 113 Assert in file: "tx_application_func.c" in line: 113
S 1 76 3 123 Assert in file: "tx_application_func.c" in line: 123
S 1 76 3 151 Assert in file: "tx_application_func.c" in line: 151
S 1 76 3 203 Assert in file: "tx_application_func.c" in line: 203
S 1 76 3 222 Assert in file: "tx_application_func.c" in line: 222
S 1 76 3 243 Assert in file: "tx_application_func.c" in line: 243
S 1 76 3 296 Assert in file: "tx_application_func.c" in line: 296
S 1 76 3 315 Assert in file: "tx_application_func.c" in line: 315
S 1 76 3 316 Assert in file: "tx_application_func.c" in line: 316
S 1 76 3 337 Assert in file: "tx_application_func.c" in line: 337
S 1 76 3 411 Assert in file: "tx_application_func.c" in line: 411
S 1 76 3 416 Assert in file: "tx_application_func.c" in line: 416
S 1 76 5 46 Assert in file: "tx_application_msg_pool.c" in line: 46
S 1 76 5 87 Assert in file: "tx_application_msg_pool.c" in line: 87
S 1 76 5 108 Assert in file: "tx_application_msg_pool.c" in line: 108
S 1 76 5 113 Assert in file: "tx_application_msg_pool.c" in line: 113
S 1 76 5 138 Assert in file: "tx_application_msg_pool.c" in line: 138
S 1 76 5 142 Assert in file: "tx_application_msg_pool.c" in line: 142
S 1 76 5 198 Assert in file: "tx_application_msg_pool.c" in line: 198
S 1 76 5 214 Fatal Error in file: "tx_application_msg_pool.c"; Fatal Print: attempt to release a non allocated message
S 1 76 5 253 Fatal Error in file: "tx_application_msg_pool.c"; Fatal Print: Tried to decrease a reference count past zero
S 1 76 6 119 Assert in file: "tx_application_timer.c" in line: 119
S 1 1 1 117 Assert in file: "ieee_address.c" in line: 117
S 1 1 1 141 Assert in file: "ieee_address.c" in line: 141
S 1 1 1 166 Assert in file: "ieee_address.c" in line: 166
S 1 1 2 169 Assert in file: "Protocol_AirTimeAndDuration.c" in line: 169
S 1 1 2 198 Assert in file: "Protocol_AirTimeAndDuration.c" in line: 198
S 1 1 2 226 Assert in file: "Protocol_AirTimeAndDuration.c" in line: 226
S 1 1 2 255 Assert in file: "Protocol_AirTimeAndDuration.c" in line: 255
S 1 1 2 283 Assert in file: "Protocol_AirTimeAndDuration.c" in line: 283
S 1 1 2 310 Assert in file: "Protocol_AirTimeAndDuration.c" in line: 310
S 1 1 2 338 Assert in file: "Protocol_AirTimeAndDuration.c" in line: 338
S 1 4 1 887 isr_AggregationBuilder_ErrorOrDone, status 0x%x
S 1 4 1 966 Assert in file: "AggregationBuilder.c" in line: 966
S 1 4 1 990 Assert in file: "AggregationBuilder.c" in line: 990
S 1 4 1 1021 Assert in file: "AggregationBuilder.c" in line: 1021
S 1 4 1 1028 Assert in file: "AggregationBuilder.c" in line: 1028
S 1 4 1 1079 Assert in file: "AggregationBuilder.c" in line: 1079
S 1 4 1 1110 Assert in file: "AggregationBuilder.c" in line: 1110
S 1 4 1 1326 Assert in file: "AggregationBuilder.c" in line: 1326
S 1 4 1 1350 Assert in file: "AggregationBuilder.c" in line: 1350
S 1 6 0 187 Assert in file: "BaAnalyzer.c" in line: 187
S 1 6 0 276 Assert in file: "BaAnalyzer.c" in line: 276
S 1 6 0 277 Assert in file: "BaAnalyzer.c" in line: 277
S 1 6 0 293 Fatal Error in file: "BaAnalyzer.c"; Fatal Print: baAnalyzerIllegalStdStatus
S 1 6 0 365 Assert in file: "BaAnalyzer.c" in line: 365
S 1 6 0 766 Assert in file: "BaAnalyzer.c" in line: 766
S 1 6 0 956 Assert in file: "BaAnalyzer.c" in line: 956
S 1 6 0 967 Assert in file: "BaAnalyzer.c" in line: 967
S 1 6 0 984 Assert in file: "BaAnalyzer.c" in line: 984
S 1 6 0 1001 Assert in file: "BaAnalyzer.c" in line: 1001
S 1 6 0 1007 Assert in file: "BaAnalyzer.c" in line: 1007
S 1 7 1 316 Assert in file: "BaAnalyzer.c" in line: 316
S 1 8 4 255 Assert in file: "Beacon_BlockingManager.c" in line: 255
S 1 8 4 256 Assert in file: "Beacon_BlockingManager.c" in line: 256
S 1 8 4 304 Assert in file: "Beacon_BlockingManager.c" in line: 304
S 1 8 4 305 Assert in file: "Beacon_BlockingManager.c" in line: 305
S 1 8 4 506 Restart BeaconHandlerBlockingDb.state =%d
S 1 8 4 547 pScratchPadApiParams->numOfBeaconsTransmitted =%d, BeaconHandlerBlockingDb.lastNumBeaconsTransmitted =%d
S 1 8 4 563 BeaconHandlerBlockingDb.state =%d
S 1 8 4 579 BeaconHandlerBlockingDb.state =%d
S 1 9 0 226 vBSS_Initialize, send PAC_MANAGER_START_REQ
S 1 10 1 538 BSS Manager STA Manager, Station %d changed from %d to %d
S 1 10 1 575 Assert in file: "BssManager_StaManager.c" in line: 575
S 1 10 1 577 Assert in file: "BssManager_StaManager.c" in line: 577
S 1 10 1 579 Assert in file: "BssManager_StaManager.c" in line: 579
S 1 10 1 580 BSS MNG, STA MNG, Dispatch Reg %d, SID %d, num %d
S 1 10 1 595 BSS MNG, STA MNG, Dispatch Client %d, MsgId %d, TaskId %x
S 1 10 1 633 BSS MNG, STA MNG, Check Dispatcher, SID %d, state %d
S 1 10 1 636 Assert in file: "BssManager_StaManager.c" in line: 636
S 1 10 1 639 Assert in file: "BssManager_StaManager.c" in line: 639
S 1 10 1 642 Assert in file: "BssManager_StaManager.c" in line: 642
S 1 10 1 645 Assert in file: "BssManager_StaManager.c" in line: 645
S 1 10 1 715 BSS MNG, STA MNG, STA Open Done, SID %d
S 1 10 1 757 BSS MNG, STA MNG, Set Filter Done, SID %d
S 1 10 1 799 BSS MNG, STA MNG, Stop Traffic Done, SID %d
S 1 10 1 842 BSS MNG, STA MNG, STA Close Done, SID %d
S 1 10 1 876 BSS MNG, STA MNG, Check Confirm, SID %d, pending %d
S 1 10 1 886 Assert in file: "BssManager_StaManager.c" in line: 886
S 1 10 1 967 Fatal Error in file: "BssManager_StaManager.c"; Fatal Print: BSS Manager STA Manager Fatal
S 1 10 1 1006 Assert in file: "BssManager_StaManager.c" in line: 1006
S 1 10 1 1010 BSS MNG, STA MNG, Reg Confirm, SID %d, Client %d
S 1 10 1 1045 Assert in file: "BssManager_StaManager.c" in line: 1045
S 1 10 1 1048 Assert in file: "BssManager_StaManager.c" in line: 1048
S 1 10 1 1056 BSS MNG, STA MNG, ADD STA, SID %d
S 1 10 1 1093 Assert in file: "BssManager_StaManager.c" in line: 1093
S 1 10 1 1097 BSS MNG, STA MNG, Set Filter, SID %d
S 1 10 1 1134 Assert in file: "BssManager_StaManager.c" in line: 1134
S 1 10 1 1138 BSS MNG, STA MNG, Stop Traffic, SID %d
S 1 10 1 1175 Assert in file: "BssManager_StaManager.c" in line: 1175
S 1 10 1 1179 BSS MNG, STA MNG, Close STA, SID %d
S 1 13 0 177 CSA Manager changed from %d to %d
S 1 13 0 617 Fatal Error in file: "csaManager.c"; Fatal Print: CSA Manager Fatal
S 1 13 1 341 CSA Manager STA Manager, STA %d changed from %d to %d
S 1 13 1 1742 Fatal Error in file: "CsaManager_StaManager.c"; Fatal Print: Csa Manager STA Manager Fatal
S 1 13 1 1779 Assert in file: "CsaManager_StaManager.c" in line: 1779
S 1 13 1 1817 Assert in file: "CsaManager_StaManager.c" in line: 1817
S 1 13 2 267 CSA Manager VAP Manager, VAP %d changed from %d to %d
S 1 13 2 1247 Assert in file: "CsaManager_VapManager.c" in line: 1247
S 1 13 2 1643 Fatal Error in file: "CsaManager_VapManager.c"; Fatal Print: CSA Manager VAP Manager Fatal
S 1 14 0 216 CTS Manager changed from %d to %d
S 1 14 0 747 Fatal Error in file: "CtsManager.c"; Fatal Print: CTS Manager Fatal
S 1 14 0 793 Assert in file: "CtsManager.c" in line: 793
S 1 15 0 144 Assert in file: "mib.c" in line: 144
S 1 15 0 205 Assert in file: "mib.c" in line: 205
S 1 15 0 441 u16MIB_PutValue: u16ID=%d 
S 1 15 0 485 Assert in file: "mib.c" in line: 485
S 1 16 0 269 Assert in file: "Debra.c" in line: 269
S 1 17 2 137 Assert in file: "StatisticsPhyHandler.c" in line: 137
S 1 17 2 145 [PhyStatistics_MetricsFifoNotEmpty], rdType = %d
S 1 17 2 162 [PhyStatistics_MetricsFifoNotEmpty], stationId = %d, isAmpdu = %d, packetLength = %d
S 1 17 2 282 [PhyStatistics_GetPhyStatusReq]
S 1 17 2 296 Assert in file: "StatisticsPhyHandler.c" in line: 296
S 1 17 2 337 PhyStatistics_ChannelLoadTimerExpired, phyStatisticDb.totalChannelLoadBssLoad:%d, currentTime:%d, phyStatisticDb.channelLoadMesStartTimeBssLoad:%d, channelUtilization:%d
S 1 17 2 470 [PhyStatistics_ChannelSwitchDone]
S 1 17 4 131 RX TH - WriteRxTh2Phy THval: %d
S 1 17 4 188 RX TH - SetRxThReq THval: %d
S 1 17 4 231 RX TH - WriteMinRssi2Phy regVal: %d minRssi: %d
S 1 17 4 283 RX TH - RxThRemoveSta staId: %d , rssiVal %d
S 1 17 4 285 Assert in file: "StatisticsHandler.c" in line: 285
S 1 17 4 342 RX TH - RxThUpdateRssi newRssi: %d oldRssi:%d
S 1 17 4 344 Assert in file: "StatisticsHandler.c" in line: 344
S 1 17 4 426 RX TH - RxThAddSta staId: %d rssiVal:%d
S 1 17 1 129 RX TH - WriteRxTh2Phy THval: %d
S 1 17 1 183 RX TH - SetRxThReq THval: %d
S 1 17 1 224 RX TH - WriteMinRssi2Phy regVal: %d minRssi: %d
S 1 17 1 273 RX TH - RxThRemoveSta staId: %d , rssiVal %d
S 1 17 1 274 Assert in file: "StatisticsHandler.c" in line: 274
S 1 17 1 329 RX TH - RxThUpdateRssi newRssi: %d oldRssi:%d
S 1 17 1 330 Assert in file: "StatisticsHandler.c" in line: 330
S 1 17 1 410 RX TH - RxThAddSta staId: %d rssiVal:%d
S 1 18 0 69 Assert in file: "DmaManager.c" in line: 69
S 1 18 0 71 Assert in file: "DmaManager.c" in line: 71
S 1 18 1 315 Assert in file: "DmaDriver.c" in line: 315
S 1 18 3 305 Assert in file: "DmaDriver.c" in line: 305
S 1 18 3 323 Assert in file: "DmaDriver.c" in line: 323
S 1 19 0 156 -------- DUT VAP ADDED --------
S 1 19 0 177 Assert in file: "Dut.c" in line: 177
S 1 19 0 183 -------- DUT VAP REMOVED--------
S 1 19 0 200 -------- DUT Dut_HandleSetFixedRateCfm--------
S 1 19 0 287 DUT_CfmToHost  DUT_CfmToHost  DUT_CfmToHost  DUT_CfmToHost
S 1 19 0 313 Dut_MsgCallBackFromProcess
S 1 19 0 378 Assert in file: "Dut.c" in line: 378
S 1 19 1 177 dutResetBb, calling PhyDrv_ResetBB()
S 1 19 1 190 dutStartBb, calling PhyDrv_ReActivateBB()
S 1 19 1 307 dutHwAccessSetDefaultAntenaSet, calling PhyDrv_SetRFMtype(MTLK_RF_MGMT_TYPE_OFF) 
S 1 19 1 376 dutHwAccessSetSpacelessTransmission, dutDB_p->spaceless:%d
S 1 19 1 421 DUT_SendModifyIfsParamsReq, spacing[usec]:%d
S 1 19 1 439 DUT_SendModifyIfsParamsReq
S 1 19 1 497 DUT_SetIfsValue, spacingUsec:%d, ifsn:%d, slotTimer:%d
S 1 19 1 591 Assert in file: "Dut_HwAccess.c" in line: 591
S 1 19 1 604 dutHwAccessGetTxPowerFeedbackReq, dutTxState NOT is DUT_TX_STATE_TRANSMITTING ! return to user
S 1 19 1 649 dutHwAccessGetRxGains, ant:%d, BBGain = %d
S 1 19 1 664 dutHwAccessGetRxGains, ant:%d, lnaActiveValue = %d %d
S 1 19 1 688 dutHwAccessGetRxGains, sysGain[%d] = 0x%x
S 1 19 1 702 dutHwAccessGetRxGains, backoffToDbmOffset = 0x%x
S 1 19 1 709 dutHwAccessGetRxGains, rxGains_p->antRxGains[%d].bbGain = 0x%x
S 1 19 1 811 Assert in file: "Dut_HwAccess.c" in line: 811
S 1 19 1 825 Assert in file: "Dut_HwAccess.c" in line: 825
S 1 19 1 851 Assert in file: "Dut_HwAccess.c" in line: 851
S 1 19 1 867 Assert in file: "Dut_HwAccess.c" in line: 867
S 1 19 1 896 Assert in file: "Dut_HwAccess.c" in line: 896
S 1 19 1 906 dutHwAccessReadTxPowerFeedBack, powerIndex:%x, validSamples:0x%x, txEnabledAntennas:0x%x, phyBw:%d
S 1 19 1 915 dutHwAccessReadTxPowerFeedBack, ant:%d, voltageMeasure:%d
S 1 19 1 924 voltageMeasure, voltageMeasure:%d , ant = %d
S 1 20 0 236 vAPP_Assert assertGroupId=%d assertFileId=%d assertLine=%d
S 1 20 0 286 vAPP_Assert last PCs: Tx Sender 0x%04x, Rx Handler 0x%04x, Host I/F 0x%04x
S 1 20 0 658 Fatal Error in file: "ErrorHandler.c"; Fatal Print: Lower MAC Assertion
S 1 20 0 683 Assert in file: "ErrorHandler.c" in line: 683
S 1 20 0 715 Fatal Error in file: "ErrorHandler.c"; Fatal Print: Assert Requested by the Host
S 1 20 0 896 Assert in file: "ErrorHandler.c" in line: 896
S 1 21 0 184 Assert in file: "eventsManager.c" in line: 184
S 1 21 0 201 Fatal Error in file: "eventsManager.c"; Fatal Print: EventManager_MaskHwEvent
S 1 21 0 206 Fatal Error in file: "eventsManager.c"; Fatal Print: HwEvents_UnMaskEvent
S 1 21 0 225 Assert in file: "eventsManager.c" in line: 225
S 1 21 0 232 Assert in file: "eventsManager.c" in line: 232
S 1 21 2 202 Assert in file: "eventsManager.c" in line: 202
S 1 21 2 212 Assert in file: "eventsManager.c" in line: 212
S 1 21 2 243 Assert in file: "eventsManager.c" in line: 243
S 1 21 2 253 Assert in file: "eventsManager.c" in line: 253
S 1 24 0 162 Assert in file: "GidmManager.c" in line: 162
S 1 24 0 175 GidmManager_RunStateMachine: Sta = %d, CurrentState = %d, event = %d
S 1 24 0 183 GidmManager_ChangeState: staIndex = %d, newState = %d
S 1 24 0 190 Fatal Error in file: "GidmManager.c"; Fatal Print: GidmManager_IllegalEvent
S 1 24 0 326 Assert in file: "GidmManager.c" in line: 326
S 1 24 0 347 Assert in file: "GidmManager.c" in line: 347
S 1 24 0 351 Assert in file: "GidmManager.c" in line: 351
S 1 24 0 383 Assert in file: "GidmManager.c" in line: 383
S 1 25 0 106 Fatal Error in file: "GroupDatabase.c"; Fatal Print: GroupDb_SetTxPpduModePerUspInGroup
S 1 25 0 147 GroupDb_FillGroupParams: groupIndex is %x. SIDs in group (%d, %d, %d, %d)
S 1 25 0 415 Assert in file: "GroupDatabase.c" in line: 415
S 1 25 0 416 Assert in file: "GroupDatabase.c" in line: 416
S 1 25 0 417 Assert in file: "GroupDatabase.c" in line: 417
S 1 25 0 418 Assert in file: "GroupDatabase.c" in line: 418
S 1 25 0 425 Assert in file: "GroupDatabase.c" in line: 425
S 1 25 0 430 Fatal Error in file: "GroupDatabase.c"; Fatal Print: GroupDb_UpdateMuGroupAttributes invalid option
S 1 25 0 470 GroupDb_ResetGroupEntry: groupIndex is %X
S 1 25 0 507 GroupDB_Init
S 1 26 0 1021 Assert in file: "GroupManager.c" in line: 1021
S 1 26 0 1042 groupManagerAddStation: Adding station %d
S 1 26 0 1051 groupManagerAddStation: station id %d is not allowed
S 1 26 0 1094 groupManagerRemoveStation: received on SID %d
S 1 26 0 1143 groupManagerTrainingTimer: stations timer event, handle index %d
S 1 26 0 1161 groupManagerTrainingTimer: groups timer event, handle index %d
S 1 26 0 1351 groupManagerGroupsMarksReceived: word in Bitmap %d, stations waiting for group marks in this word 0x%x
S 1 26 0 1365 Assert in file: "GroupManager.c" in line: 1365
S 1 26 0 1451 groupManagerStationNssHasChanged: station index %d. New nss %d. virtual group removed %d
S 1 26 0 1468 groupManagerStationNssHasChanged: station index %d. New nss %d. active group removed %d
S 1 26 0 1510 groupManagerAddGroupConfirmation - groupIdx %d
S 1 26 0 1600 groupManagerRemovedGroupConfirmation: from LA on group index %d. group state %d
S 1 26 0 1642 groupManagerGroupsHasFailed: group index %d
S 1 26 0 1732 Fatal Error in file: "GroupManager.c"; Fatal Print: groupManagerResetMultiUserOperation
S 1 26 0 1748 Fatal Error in file: "GroupManager.c"; Fatal Print: groupManagerResetMultiUserOperation
S 1 26 0 1795 Fatal Error in file: "GroupManager.c"; Fatal Print: groupManagerSetMultiUserOperationCfm
S 1 26 0 1833 Assert in file: "GroupManager.c" in line: 1833
S 1 26 0 1834 Assert in file: "GroupManager.c" in line: 1834
S 1 26 0 1881 groupManagerSetMultiUserOperation: current MU state = %d
S 1 26 0 1896 groupManagerSetMultiUserOperation: MU is already active
S 1 26 0 1918 groupManagerSetMultiUserOperation: MU is already deactivated
S 1 26 0 1950 groupManagerSetMuFixedRate: isFixedRate %d
S 1 26 0 2150 Assert in file: "GroupManager.c" in line: 2150
S 1 26 0 2225 Assert in file: "GroupManager.c" in line: 2225
S 1 26 0 2378 groupManagerStationEventRemoveStationInActiveOrTempActive: on station index %d
S 1 26 0 2659 groupManagerStationEventRemoveGroupDueToStationInNotifying: group index %d, station index %d
S 1 26 0 2728 groupManagerStationEventRemoveGroupDueToStationInProbing: group index %d, station index %d. Configure station for selector as SU.
S 1 26 0 2743 groupManagerStationEventRemoveGroupDueToStationInProbing: group index %d, station index %d. Station is only a member in notifying groups
S 1 26 0 2754 groupManagerStationEventRemoveGroupDueToStationInProbing: group index %d, station index %d. Station is only a member in virtual groups
S 1 26 0 2764 groupManagerStationEventRemoveGroupDueToStationInProbing: group index %d, station index %d. Station is not a member of any group. Moving to HALT
S 1 26 0 2827 groupManagerStationEventRemoveGroupInTempActive: Removing groupIndex %d. stationIndex %d is tempActive of the group
S 1 26 0 2861 groupManagerStationEventRemoveGroupInTempActive: Removing groupIndex %d which is primary group of stationIndex %d. station is tempActive of another group and part of more active groups
S 1 26 0 2874 groupManagerStationEventRemoveGroupInTempActive: Removing groupIndex %d which is primary group of stationIndex %d. station is tempActive and member of only probing groups
S 1 26 0 2983 groupManagerStationEventRemoveGroupDueToStationInSuValWaitingLa: groupIndex %d, station index %d
S 1 26 0 2989 groupManagerStationEventRemoveGroupDueToStationInSuValWaitingLa: the primary group of station waiting to start SU val is removed, cancel SU val
S 1 26 0 3032 groupManagerStationEventRemoveGroupDueToStationInSingleUserValidation: group index %d, station index %d, primary group index = %d
S 1 26 0 3122 groupManagerStationEventRemoveGroupInNotifying: groupIndex %d, stationIndex %d
S 1 26 0 3174 groupManagerStationEventRemoveGroupInProbing: Station %d is primary of probing group %d which is beeing removed. configure station in selector to SU
S 1 26 0 3190 groupManagerStationEventRemoveGroupInProbing: Station %d remains member of only notify groups
S 1 26 0 3198 groupManagerStationEventRemoveGroupInProbing: Station %d is not a member of any active/probing/notify group
S 1 26 0 3554 groupManagerStationEventActivateGroupInProbing: group idx %d, SID %d 
S 1 26 0 3571 groupManagerStationEventActivateGroupInProbing: tempPrimaryGroup before activation is %d 
S 1 26 0 3940 groupManagerStationEventActivateGroupInSingleUserValidationEnded: SID %d, configured to be primary of group %d
S 1 26 0 4130 groupManagerStationEventSuValStartCfmInSuValWaitingLa: SID %d configured to SU mode
S 1 26 0 4274 groupManagerStationEventSuValEndCfmInSuValSucceeded: SID %d, configured to work in MU mode, primary for group %d
S 1 26 0 4579 Assert station %d state: %d
S 1 26 0 4581 Fatal Error in file: "GroupManager.c"; Fatal Print: Assert in group manager station event
S 1 26 0 4611 Ingore event station %d state: %d
S 1 26 0 4643 Remove Group event update station bitmap station %d state: %d group %d
S 1 26 0 4678 Add Group event update station bitmap station %d state: %d group %d
S 1 26 0 4759 groupManagerRunStationStateMachine station %d state: %d event %d
S 1 26 0 4773 Assert in file: "GroupManager.c" in line: 4773
S 1 26 0 4813 groupManagerChangeStationState: Change station %d state: old state %d new state %d
S 1 26 0 4863 group manager, Send Confirmation, Client %d, stationIndex %d
S 1 26 0 4901 groupManagerRemoveAllStationVirtualGroups: SID %d, virtualGroupsBitmap 0x%x
S 1 26 0 5008 Fatal Error in file: "GroupManager.c"; Fatal Print: Station was not found in virtual group
S 1 26 0 5055 Fatal Error in file: "GroupManager.c"; Fatal Print: Station was not found in group
S 1 26 0 5101 groupManagerSetStationPrimaryBitInGroupsDb: stationIndex %d, groupIndex %d, primary stations bitmap after adding new primary 0x%x
S 1 26 0 5136 groupManagerConfigureStationAsPrimaryInGroup: station index %d configured primary for selector with group index %d
S 1 26 0 5212 groupManagerClearStationPrimaryInGroup: station index %d, group index %d, primaryStationsbitmap for this group 0x%x
S 1 26 0 5234 Fatal Error in file: "GroupManager.c"; Fatal Print: Trying to delete staticGroup !
S 1 26 0 5272 groupManagerSendEndSingleUserValidationMessage: to LA on SID %d
S 1 26 0 5308 groupManagerTriggerRemoveStationInTraining: sent to Training mng on SID %d
S 1 26 0 5438 groupManagerFindBestGroup: group with best mark  is %d
S 1 26 0 5519 groupManagerRemoveGroupInActive: group index: %d, haltNeeded: %d 
S 1 26 0 5528 groupManagerRemoveGroupInActive: station has more active groups. bitmap of groups 0x%x
S 1 26 0 5703 groupManagerTryToStartNewSingleUserValidation: Single User Validation bitmap %d, SID %d
S 1 26 0 5708 groupManagerTryToStartNewSingleUserValidation: Single User Validation bitmap after adding new one %d, SID %d
S 1 26 0 5718 groupManagerTryToStartNewSingleUserValidation: start single user val on SID %d
S 1 26 0 5754 groupManagerSendGroupsMarksMessage
S 1 26 0 5808 groupManagerStationExitActiveState: station has more probing groups
S 1 26 0 5827 groupManagerStationExitActiveState: station has more notifying groups
S 1 26 0 5838 groupManagerStationExitActiveState: can remain in single user state. isHaltNeeded %d, virtual groups bitmap 0x%x
S 1 26 0 5846 groupManagerStationExitActiveState: station is moving to HALT
S 1 26 0 5905 groupManagerStartNewSingleUserValidation: all stations candidates for su validation bitmap 0x%x
S 1 26 0 5911 groupManagerStartNewSingleUserValidation: SID %d chosen next for SU validation, moving to Su val pending
S 1 26 0 5918 groupManagerStartNewSingleUserValidation: no candidates for su val found
S 1 26 0 5998 groupManagerConfigureNewGroupForSelector: numOfStations %d
S 1 26 0 6003 groupManagerConfigureNewGroupForSelector: sid %d
S 1 26 0 6014 groupManagerConfigureNewGroupForSelector: Configure primary SID %d for group %d in Selector
S 1 26 0 6214 Assert in file: "GroupManager.c" in line: 6214
S 1 26 0 6216 groupManagerGroupEventStartNotifying: group index for notification %d, virtual group index %d
S 1 26 0 6260 groupManagerGroupEventStartNotifying: station index %d, group index %d, uspVector 0x%x
S 1 26 0 6390 groupManagerGroupEventRemoveGroupInProbing: group %d
S 1 26 0 6430 groupManagerGroupEventRemoveGroupInActive: group %d
S 1 26 0 6483 groupManagerGroupEventNotificationCfmInProbingNotifying: on SID %d, groupIdx %d, notifStatus %d
S 1 26 0 6505 groupManagerGroupEventNotificationCfmInProbingNotifying: All notifications arrived successfully
S 1 26 0 6535 groupManagerGroupEventNotificationCfmInProbingNotifying: timer started after static group generation
S 1 26 0 6559 groupManagerGroupEventNotificationCfmInProbingNotifying: All notifications arrived - last FAILED
S 1 26 0 6591 groupManagerGroupEventNotificationCfmInProbingNotifying: one of notification failed, more notifications will arrive - start remove group now
S 1 26 0 6996 groupManagerGroupEventRemoveGroupCfmInRemovingWaitingForLaCfm
S 1 26 0 7048 groupManagerGroupEventProbingResultsAreReadyInProbing: group Idx %d, group mark %d, states (%d, %d, %d, %d)
S 1 26 0 7071 groupManagerGroupEventProbingResultsAreReadyInProbing: for group %d station %d mark is below threshold! (%d, %d, %d, %d)
S 1 26 0 7087 groupManagerGroupEventProbingResultsAreReadyInProbing: Group mark is below threshold!!!
S 1 26 0 7094 groupManagerGroupEventProbingResultsAreReadyInProbing: num of active groups %d, num of removing active groups %d
S 1 26 0 7117 groupManagerGroupEventProbingResultsAreReadyInProbing: active groups are full. Worth active group index %d, group mark %d, probing grop mark %d
S 1 26 0 7135 groupManagerGroupEventProbingResultsAreReadyInProbing: Send activateGroup event to SID %d
S 1 26 0 7162 groupManagerGroupEventProbingResultsAreReadyInProbing: Valid probing group found. Group idx %d. will be active
S 1 26 0 7192 groupManagerGroupEventProbingResultsAreReadyInProbing: Probing group idx %d is not valid. No primary station availabe for it. Will be removed
S 1 26 0 7244 Ignore 'probing results ready event' for group %d (static group) in state: %d
S 1 26 0 7250 Assert group %d state: %d on probing results ready event
S 1 26 0 7252 Fatal Error in file: "GroupManager.c"; Fatal Print: Assert in group manager group event
S 1 26 0 7380 Assert group %d state: %d
S 1 26 0 7382 Fatal Error in file: "GroupManager.c"; Fatal Print: Assert in group manager group event
S 1 26 0 7413 Ignore event group %d state: %d
S 1 26 0 7451 groupManagerRunGroupStateMachine group %d state: %d event %d
S 1 26 0 7480 groupManagerChangeGlobalState: current state: %d, new state %d
S 1 26 0 7514 groupManagerChangeGroupState: Change group %d state: old state %d new state %d
S 1 26 0 7556 groupManagerSendRemoveGroupMessage: groupIndex %d
S 1 26 0 7601 groupManagerSendAddGroupMessage: send add group to LA
S 1 26 0 7639 groupManagerLockGroup: sending lock request to Locker on group %d
S 1 26 0 7652 groupManagerLockGroup: lock was already sent. Adding group %d to waiting list. waitingLock bitmap 0x%x
S 1 26 0 7712 groupManagerGroupRemoveGroupInProbingNotifying: station %d is removed during probing, send stopTx to GIDM Mng
S 1 26 0 7726 groupManagerGroupRemoveGroupInProbingNotifying: send stopTx on station %d to GIDM Mng, notification cancelled
S 1 26 0 7742 groupManagerGroupRemoveGroupInProbingNotifying: station index received %d. notification status of the group (%d, %d, %d, %d)
S 1 26 0 7797 groupManagerHandleNextGroupWaitingForLock: group  %d
S 1 26 0 7835 groupManagerFinishGroupRemovalProcess: group idx %d, removingGroupsBitmap 0x%x, occupiedGroupsBitmap 0x%x, numberOfOccupiedGroups %d, activeGroupsBitmap 0x%x, probingGroupsBitmap 0x%x
S 1 26 0 7851 groupManagerFinishGroupRemovalProcess: group was in active state. After clear bits: activeGroupsBitmap 0x%x, numberOfActiveGroups %d, num of removing groups in active %d
S 1 26 0 7860 groupManagerFinishGroupRemovalProcess: group was in probing state. After clear bits: probingGroupsBitmap 0x%x, numberOfProbingGroups %d
S 1 26 0 7880 groupManagerFinishGroupRemovalProcess: group failed
S 1 26 0 7892 groupManagerFinishGroupRemovalProcess: group not failed
S 1 26 0 7942 groupManagerFinishGlobalRemovalProcess: sending multi user operation setting cfm
S 1 26 0 7953 groupManagerFinishGlobalRemovalProcess: starting static group generation
S 1 26 0 7997 groupManagerTryToFindNewGroupForProbing: probing groups %d, occupied groups %d
S 1 26 0 8010 groupManagerTryToFindNewGroupForProbing: virtuals db bitmap 0x%x
S 1 26 0 8078 groupManagerTryToFindNewGroupForProbing: virtual groups bitmap candidates for probing 0x%x
S 1 26 0 8094 groupManagerTryToFindNewGroupForProbing: found best virtual group index for probing %d
S 1 26 0 8432 GroupManager_TrainingWasStoppedConfirmation
S 1 26 0 8455 GroupManager_TrainingWasStoppedConfirmation: send multi user operation setting cfm
S 1 26 0 8473 GroupManager_TrainingWasStoppedConfirmation: Starting To create static group
S 1 26 0 8493 Fatal Error in file: "GroupManager.c"; Fatal Print: Assert in GroupManager_TrainingWasStoppedConfirmation
S 1 26 0 8592 GroupManager_TrainingResultsWereReceived: entry num %d
S 1 26 0 8598 GroupManager_TrainingResultsWereReceived: invalid	StaIdx %d
S 1 26 0 8606 GroupManager_TrainingResultsWereReceived: staIdx %d, invalid combination. 
S 1 26 0 8635 GroupManager_TrainingResultsWereReceived: staId %d - (%d, %d, %d, %d).
S 1 26 0 8637 GroupManager_TrainingResultsWereReceived: MCS - (%d, %d, %d, %d)
S 1 26 0 8639 GroupManager_TrainingResultsWereReceived: groupGrade - %d, singleNsts %d, doubleNsts %d
S 1 26 0 8672 GroupManager_TrainingResultsWereReceived: Nss bitmap: 0x%x
S 1 26 0 8685 GroupManager_TrainingResultsWereReceived:occupied groupId %d, groupStations (%d,%d,%d,%d)
S 1 26 0 8697 GroupManager_TrainingResultsWereReceived: Group Exists in occupied DB: EntryIdx %d, staId %d, groupIndex %d
S 1 26 0 8719 GroupManager_TrainingResultsWereReceived: virtualGroupId %d, groupStations (%d,%d,%d,%d)
S 1 26 0 8739 GroupManager_TrainingResultsWereReceived: Group Exists in VIRTUAL DB: EntryIdx %d, staId %d, virtualGroupIdx %d
S 1 26 0 8757 GroupManager_TrainingResultsWereReceived: Found free spot %d in virtual DB
S 1 26 0 8768 GroupManager_TrainingResultsWereReceived: Virtual DB is full!
S 1 26 0 8784 GroupManager_TrainingResultsWereReceived: new group will overwrite groupIdx %d in virtual DB. Prev group grade %d, new group grade %d
S 1 26 0 8932 GroupManager_GidmNotificationConfirmation: SID %d, notify group idx %d
S 1 26 0 9266 Assert in file: "GroupManager.c" in line: 9266
S 1 26 0 9498 groupManagerCreateMuStaticGroup: preparing for static group generation
S 1 26 0 9533 groupManagerDeleteMuStaticGroup
S 1 27 0 164 AfePhase: Executing Calibration
S 1 27 0 171 AfePhase: run time =%d
S 1 27 0 215 AfePhase: initCalibration() nCB mode
S 1 27 0 224 AfePhase: initCalibration() CB mode
S 1 27 0 290 AfePhase: AfePhase_Logic() initValue[%d] = h%x
S 1 27 0 317 Calibration Step delay[0] = h%x delay[1] = h%x delay[2] = h%x
S 1 27 0 318 Tx: res[0] = h%x res[1] = h%x res[2] = h%x
S 1 27 0 319 Rx: res[0] = h%x res[1] = h%x res[2] = h%x
S 1 27 0 386 Assert in file: "AfePhaseClbrHndlr.c" in line: 386
S 1 27 0 399 ant1equal = %d times, ant2equal= %d
S 1 27 0 452 Assert in file: "AfePhaseClbrHndlr.c" in line: 452
S 1 27 0 458 diff_array_rx[%d] = %d rxDelay = %d
S 1 27 0 459 diff_array_tx[%d] = %d 
S 1 27 3 568 START AFE CALIBRATION
S 1 27 3 597 retVal=%d, packetMod=%d
S 1 27 3 602 packetMod=%d,pElements->results.offlineModulationType=%d 
S 1 27 3 606 exit ALB mode, calibration end!
S 1 27 3 613 LastClRunTime: %d
S 1 27 3 673 QBF calibration finished
S 1 27 3 701 Setting TPC: %d, for extPa = %d
S 1 27 3 816 Assert in file: "BeamFormingClbrHndlr.c" in line: 816
S 1 27 3 823 agcGains(ant %d). lnaIndx = %d pgc1Indx = %d pgc2Indx = %d pgc3Indx = %d
S 1 27 3 833 Send packet %d => %d
S 1 27 3 849 Packet sent from ant %d to ant %d
S 1 27 3 868 BM calibration fail! number of recorded bins from sessions not identical
S 1 27 3 893 StopRisc called
S 1 27 3 930 Assert in file: "BeamFormingClbrHndlr.c" in line: 930
S 1 27 3 940 StartRisc called
S 1 27 3 979 TRSW: %x %x %x
S 1 27 3 1068 Assert in file: "BeamFormingClbrHndlr.c" in line: 1068
S 1 27 3 1092 Assert in file: "BeamFormingClbrHndlr.c" in line: 1092
S 1 27 3 1141 Registers values were not saved, cannot restore them
S 1 27 3 1142 Assert in file: "BeamFormingClbrHndlr.c" in line: 1142
S 1 27 3 1147 Stop risc
S 1 27 3 1163 Run risc
S 1 27 3 1209 Assert in file: "BeamFormingClbrHndlr.c" in line: 1209
S 1 27 3 1258 BF Calibration Failed!! could not achieve a good channel
S 1 27 3 1274 triggerTB
S 1 27 3 1336 Record Channel Failed !! packet did not arrive in time
S 1 27 3 1348 Record Channel Failed!! wrong channel size, CB: %d, numOfBins:%d
S 1 27 3 1359 Record Channel Failed!! Wrong Packet received with length %d
S 1 27 3 1373 Record channel failed!!! CRC error
S 1 27 3 1424 Assert in file: "BeamFormingClbrHndlr.c" in line: 1424
S 1 27 3 1430 Record %d bins
S 1 27 3 1578 CaluclateCalResult, calPair=%d
S 1 27 3 1580 Assert in file: "BeamFormingClbrHndlr.c" in line: 1580
S 1 27 3 1642 NCB mode: Start checking phase jump
S 1 27 3 1651 PhaseDiff = %d
S 1 27 3 1660 Phase jump found! correcting K calibration
S 1 27 3 1685 Phase jump not found
S 1 27 3 1768 Assert in file: "BeamFormingClbrHndlr.c" in line: 1768
S 1 27 3 1857 Assert in file: "BeamFormingClbrHndlr.c" in line: 1857
S 1 27 3 1873 START AGC GAINS CALIBRATION
S 1 27 3 1884 START K CALIBRATION
S 1 27 3 1908 START AGC OFFSET CALIBRATION
S 1 27 3 1916 START TX OFFSET CALIBRATION
S 1 27 3 1923 exit ALB mode, calibration end!, calStatus = %X
S 1 27 3 1953 Start K%d calibration, CB=%d
S 1 27 3 1991 extGainDb = %d, extGain = %d, trAttenDb = %d
S 1 27 3 2069 relative gain = %d
S 1 27 3 2094 Assert in file: "BeamFormingClbrHndlr.c" in line: 2094
S 1 27 3 2110 Warning: working at %d instead of 15 dB backoff
S 1 27 3 2118 BF Calibration Failed !! Attenuation between antennas too high:%d
S 1 27 3 2143 Send packet: Ant%d->Ant%d
S 1 27 3 2144 trSwTxAnt: %d
S 1 27 3 2316 Assert in file: "BeamFormingClbrHndlr.c" in line: 2316
S 1 27 3 2357 digital gain %d
S 1 27 3 2368 running for gains : LnaIndex %d, pgc1Index %d, pgc2Index %d,pgc3Index %d
S 1 27 3 2616 Assert in file: "BeamFormingClbrHndlr.c" in line: 2616
S 1 27 3 2798 Assert in file: "BeamFormingClbrHndlr.c" in line: 2798
S 1 27 3 2848 BF Calibration Failed!! could not achieve a good channel
S 1 27 3 2873 DisTxCancel
S 1 27 3 2880 EnTxCancel
S 1 28 0 178 LPF: Executing Calibration.
S 1 28 0 190 LPF: Finished Calibration. Ret Val = %d, Run Time = %d
S 1 28 0 216 LPF_LoadResults(): Ant %u lpfI=%u lpfQ=%u
S 1 28 5 140 MsSsiAdc: Executing Calibration
S 1 28 5 442 MsSsiAdc verifyCalibrationResults: antNum = %d Status = %d
S 1 28 5 443 MsSsiAdc verifyCalibrationResults: statusGain = %d gainDist = %d
S 1 28 5 444 MsSsiAdc verifyCalibrationResults: statusOffset = %d offsetDist = %d
S 1 28 6 114 RficBias: Executing Calibration
S 1 28 6 143 RficBias: status = %d, statusRpos = %d, statusRneg = %d
S 1 28 6 144 RficBias: Rint = %d Rpos = %d, Rneg = %d
S 1 28 6 154 RficBias: Finished Calibration. Run Time = %d
S 1 28 6 215 RficBias_calibrateRpos:Failed to reach comparator SUCCESS
S 1 28 6 276 RficBias_calibrateRneg:Failed to reach comparator SUCCESS
S 1 28 6 394 RficBias_LoadResults(): Rint=%d
S 1 28 7 127 RssiDcOffset: Executing Calibration
S 1 28 7 349 RssiDcOffset min_search !!! DEBUG !!!: delta=0: antenna %d
S 1 28 7 445 RssiDcOffset: Finished Calibration. Ret Code = %d, Run Time = %d
S 1 28 7 453 RssiDcOffset: AntNum = %d Status = %d
S 1 28 7 461 RssiDcOffset OFFSETS: I1 = %d I2 = %d I3 = %d
S 1 28 7 462 RssiDcOffset OFFSETS: I4 = %d I5 = %d
S 1 28 7 463 RssiDcOffset OFFSETS: Q1 = %d Q2 = %d Q3 = %d
S 1 28 7 464 RssiDcOffset OFFSETS: Q4 = %d Q5 = %d
S 1 28 7 472 RssiDcOffset DATA OUT OFFSETS: I1 = %d I2 = %d I3 = %d
S 1 28 7 473 RssiDcOffset DATA OUT OFFSETS: I4 = %d I5 = %d
S 1 28 7 474 RssiDcOffset DATA OUT OFFSETS: Q1 = %d Q2 = %d Q3 = %d
S 1 28 7 475 RssiDcOffset DATA OUT OFFSETS: Q4 = %d Q5 = %d
S 1 28 8 123 RSSI Path: Executing Calibration
S 1 28 8 153 RSSI Path Calibration:Antenna %d status %d
S 1 28 8 170 RSSI Path Calibration:Finished Calibration. ret = %d, Run Time = %d
S 1 28 8 210 RSSI Path calibrateSingleAntenna(): Antenna %d
S 1 28 8 222 Assert in file: "RssiPathClbrHndlr.c" in line: 222
S 1 28 8 244 RSSI Path calibrateSingleAntenna:Rssi = %d
S 1 28 8 283 RSSI Path calibrateSingleAntenna():Index = %d,Rssi = %d
S 1 28 8 308 RSSI Path calibrateSingleAntenna:Partitioned Section =%d Index = %d,Rssi = %d
S 1 28 8 468 Assert in file: "RssiPathClbrHndlr.c" in line: 468
S 1 28 8 512 RSSI Path measureRssi: measureRssi() time = %d
S 1 28 8 588 Assert in file: "RssiPathClbrHndlr.c" in line: 588
S 1 28 8 602 RSSI CalcDerivative: section=%d a=%d b=%d
S 1 28 8 618 RSSI Path calcDerivative(): time = %d
S 1 28 8 760 GenerateRssiTable:Dynamic Range low =%d high %d
S 1 28 8 761 GenerateRssiTable:First Calibrated Power In Dynamic Range: %d
S 1 28 8 762 GenerateRssiTable:Last Calibrated Power In Dynamic Range: %d
S 1 28 8 804 Assert in file: "RssiPathClbrHndlr.c" in line: 804
S 1 28 8 849 Assert in file: "RssiPathClbrHndlr.c" in line: 849
S 1 28 8 902 RSSI path VerifyResult: AntNum %d
S 1 28 8 938 RSSI path VerifyResult: transmit power %d  meaured rssi %d  calibrated power %d
S 1 28 8 963 RSSI path VerifyResult: Dynamic range %d low_power %d high_power %d
S 1 28 8 972 RSSI path VerifyResult: Status Fail, dynamicRange below minimum allowed %d
S 1 28 8 981 RSSI path VerifyResult: rssiPowerDiff %d maxDiffIsInPower %d
S 1 28 8 990 RSSI path VerifyResult: Status Fail, rssiPowerDiff exceeds maximum allowed %d
S 1 28 8 1005 RSSI path VerifyResult: measurementVariation %d min_measure %d max_measure %d
S 1 28 8 1014 RSSI path VerifyResult: Status Fail, measurementVariation exceeds maximum allowed %d
S 1 28 8 1030 RSSI Path VerifyResult(): ret %d status %d
S 1 28 8 1038 RSSI Path VerifyResult(): verify run time %d
S 1 28 8 1055 Assert in file: "RssiPathClbrHndlr.c" in line: 1055
S 1 28 10 132 Rx IQ: Executing Calibration
S 1 28 10 222 RxIQ ALGO:Finished Calibration. Ret Code = %d, Run Time = %d
S 1 28 10 255 Rx IQ: Restore Done. Duration = %d
S 1 28 10 310 Rx IQ: Init Done. Duration = %d
S 1 28 10 464 RxIQ error verification for ANTENNA %d  w1 = %d w2 = %d
S 1 28 10 465 RxIQ error verification II = %d QQ = %d IQ = %d
S 1 28 10 482 RxIQ verifyCalibrationResults: error verification Status = %d w1_Error= %d w2_Error= %d
S 1 29 5 256 Assert in file: "IndirectAccess.c" in line: 256
S 1 29 9 281 Fatal Error in file: "mt_phy_dummy.c"; Fatal Print: Bad PHY mdoe
S 1 29 9 351 Assert in file: "mt_phy_dummy.c" in line: 351
S 1 29 10 449 Assert in file: "PhyDriver.c" in line: 449
S 1 29 10 506 Assert in file: "PhyDriver.c" in line: 506
S 1 29 10 515 Assert in file: "PhyDriver.c" in line: 515
S 1 29 10 614 Assert in file: "PhyDriver.c" in line: 614
S 1 29 10 654 Assert in file: "PhyDriver.c" in line: 654
S 1 29 10 661 Assert in file: "PhyDriver.c" in line: 661
S 1 29 10 801 PhyDrv_DisableBB, %u
S 1 29 10 814 PhyDrv_EnableBB, %u
S 1 29 10 1079 Assert in file: "PhyDriver.c" in line: 1079
S 1 29 10 1104 Assert in file: "PhyDriver.c" in line: 1104
S 1 29 10 1130 Assert in file: "PhyDriver.c" in line: 1130
S 1 29 10 1165 Assert in file: "PhyDriver.c" in line: 1165
S 1 29 10 1326 Assert in file: "PhyDriver.c" in line: 1326
S 1 29 10 1370 Assert in file: "PhyDriver.c" in line: 1370
S 1 29 10 1371 Assert in file: "PhyDriver.c" in line: 1371
S 1 29 10 1396 Fatal Error in file: "PhyDriver.c"; Fatal Print: WD(phy) interrupt occured
S 1 29 10 1529 Assert in file: "PhyDriver.c" in line: 1529
S 1 29 10 1564 1continuousInterfererSample   = %d
S 1 29 13 461 PhyDrv_DisableBB
S 1 29 13 472 PhyDrv_EnableBB
S 1 29 13 621 Assert in file: "PhyDriver.c" in line: 621
S 1 29 13 649 Fatal Error in file: "PhyDriver.c"; Fatal Print: PHY DRV Get TCR All
S 1 29 13 735 ERROR 1 !!! DUT_SetIfsValue, spacingUsec:%d, m_phyDelays[PHY_DID_TIM_SLOT_TIMER]:%d, m_phyDelays[PHY_DID_SIFS]:%d
S 1 29 13 741 ERROR 2 !!! DUT_SetIfsValue, spacingUsec:%d, m_phyDelays[PHY_DID_SIFS]:%d
S 1 29 13 803 Assert in file: "PhyDriver.c" in line: 803
S 1 29 13 894 Assert in file: "PhyDriver.c" in line: 894
S 1 29 13 896 Assert in file: "PhyDriver.c" in line: 896
S 1 29 13 897 Assert in file: "PhyDriver.c" in line: 897
S 1 29 13 907 Fatal Error in file: "PhyDriver.c"; Fatal Print: WD(phy) interrupt occured
S 1 29 13 914 Fatal Error in file: "PhyDriver.c"; Fatal Print: Tx packet interrupt
S 1 29 24 103 LmHdk_init
S 1 31 5 176 Fatal Error in file: "HostGenRiscInterface.c"; Fatal Print: Host Interface 2 MIPS Error Start
S 1 31 5 192 Fatal Error in file: "HostGenRiscInterface.c"; Fatal Print: Unsupported Message ID
S 1 31 5 217 Fatal Error in file: "HostGenRiscInterface.c"; Fatal Print: Unsupported Message ID
S 1 31 5 229 Fatal Error in file: "HostGenRiscInterface.c"; Fatal Print: Host Interface 2 MIPS Unknown event
S 1 31 5 420 Assert in file: "HostGenRiscInterface.c" in line: 420
S 1 31 5 451 Assert in file: "HostGenRiscInterface.c" in line: 451
S 1 31 5 502 Assert in file: "HostGenRiscInterface.c" in line: 502
S 1 32 3 67 Assert in file: "HostInterfaceAcc.c" in line: 67
S 1 32 3 73 Assert in file: "HostInterfaceAcc.c" in line: 73
S 1 32 3 156 Assert in file: "HostInterfaceAcc.c" in line: 156
S 1 32 3 240 HostIfAcc_SetPdThreshold - %d
S 1 32 2 447 HostIfAcc_SetPdThreshold - %d
S 1 33 4 83 [Pac_DurEnableNavInitMode] - WAVE400------------------------------------end]
S 1 33 5 95 [PTA][Pac_RxcSetForceCca] read regVal = 0x%x
S 1 33 5 103 [PTA][Pac_RxcSetForceCca] write regVal = 0x%x
S 1 33 5 108 [PTA][Pac_RxcSetForceCca] read u32PacRxcMtForceCCA = 0x%x
S 1 33 5 119 [PTA][Pac_RxcSetForceCcaToNormalMode] read regVal = 0x%x
S 1 33 5 129 [PTA][Pac_RxcSetForceCcaToNormalMode] write regVal = 0x%x
S 1 33 5 379 [Pac_RxcEnableRssiAbort]--WAVE400
S 1 33 5 403 [Pac_RxcDisableRssiAbort]--WAVE400
S 1 33 6 588 [Pac_RxdConfigureRssiMode]---WAVE400------------------------end]
S 1 33 7 274 Assert in file: "PacRxf.c" in line: 274
S 1 33 7 277 [Pac_RxfSetMACAddressfilter] before, sRXF.asLFCs[0].u32Ref1 = %x, sRXF.asLFCs[0].u32Ref2 = %x, sRXF.asLFCs[0].u32Control = %x
S 1 33 7 330 [Pac_RxfSetMACAddressfilter] after, sRXF.asLFCs[0].u32Ref1 = %x, sRXF.asLFCs[0].u32Ref2 = %x, sRXF.asLFCs[0].u32Control = %x
S 1 33 7 334 [Pac_RxfSetMACAddressfilter]---WAVE400----------------------end]
S 1 33 7 350 Assert in file: "PacRxf.c" in line: 350
S 1 33 7 379 [Pac_RxfUseFixedVapId] - WAVE400------------------------------------end]
S 1 33 7 416 [Pac_RxfNormalVapId]---WAVE400------------------------------end]
S 1 33 8 148 Assert in file: "PacTim.c" in line: 148
S 1 33 9 291 LmUtil_setIfsValue, ifsValue[ifs resolution]:%d, spacingUsec:%d, PhyDrv_GetDelayValue(PHY_DID_PIFS):%d
S 1 33 20 134 Assert in file: "Pac.c" in line: 134
S 1 33 23 143 Assert in file: "PacDeliniator.c" in line: 143
S 1 33 24 149 Assert in file: "PacDur.c" in line: 149
S 1 33 25 111 [PTA][Pac_RxcSetForceCca] read regVal = 0x%x
S 1 33 25 119 [PTA][Pac_RxcSetForceCca] write regVal = 0x%x
S 1 33 25 132 [PTA][Pac_RxcSetForceCcaToNormalMode] read regVal = 0x%x
S 1 33 25 140 [PTA][Pac_RxcSetForceCcaToNormalMode] write regVal = 0x%x
S 1 33 26 489 Fatal Error in file: "PacRxd.c"; Fatal Print: Pac_RxdConfigureScanMode
S 1 33 27 255 Assert in file: "PacRxf.c" in line: 255
S 1 33 27 375 Assert in file: "PacRxf.c" in line: 375
S 1 33 27 597 Assert in file: "PacRxf.c" in line: 597
S 1 33 27 612 [Pac_RxfSetMACAddressfilter], PacManagerGlobalParameters->longFilter0Ref1RegNormal = %x
S 1 33 27 613 [Pac_RxfSetMACAddressfilter], PacManagerGlobalParameters->longFilter0Ref2RegNormal = %x
S 1 33 27 647 [Pac_RxfSetMACAddressfilter], longFilterRef1Address = %x
S 1 33 27 648 [Pac_RxfSetMACAddressfilter], longFilter0Ref1Reg.val = %x
S 1 33 27 649 [Pac_RxfSetMACAddressfilter], longFilterRef2Address = %x
S 1 33 27 650 [Pac_RxfSetMACAddressfilter], longFilter0Ref2Reg.val = %x
S 1 33 27 670 Assert in file: "PacRxf.c" in line: 670
S 1 33 27 744 [Pac_RxfNormalVapId], pLocalPacManagerGlobalParameters->vapIdBitMap = %d
S 1 33 27 745 [Pac_RxfNormalVapId], longFilterRef1Address = %x
S 1 33 27 746 [Pac_RxfNormalVapId], pLocalPacManagerGlobalParameters->longFilter0Ref1RegNormal = %x
S 1 33 27 747 [Pac_RxfNormalVapId], longFilterRef2Address = %x
S 1 33 27 748 [Pac_RxfNormalVapId], pLocalPacManagerGlobalParameters->longFilter0Ref2RegNormal = %x
S 1 7 4 157 Assert in file: "HwEvents.c" in line: 157
S 1 7 4 249 Fatal Error in file: "HwEvents.c"; Fatal Print: hwEventsRxClassifierRekey
S 1 7 5 273 Assert in file: "HwLogger.c" in line: 273
S 1 7 5 355 Assert in file: "HwLogger.c" in line: 355
S 1 7 5 356 Assert in file: "HwLogger.c" in line: 356
S 1 7 5 387 Assert in file: "HwLogger.c" in line: 387
S 1 7 5 570 Assert in file: "HwLogger.c" in line: 570
S 1 7 5 586 Assert in file: "HwLogger.c" in line: 586
S 1 7 5 806 Assert in file: "HwLogger.c" in line: 806
S 1 7 5 863 Assert in file: "HwLogger.c" in line: 863
S 1 7 5 2238 Fatal Error in file: "HwLogger.c"; Fatal Print: hwLoggerEnableDisableUnknown
S 1 7 5 2269 Fatal Error in file: "HwLogger.c"; Fatal Print: hwLoggerEnableDisableMuLockerLogs
S 1 7 5 2274 Fatal Error in file: "HwLogger.c"; Fatal Print: hwLoggerEnableDisablePacExtraLogs
S 1 7 5 2279 Fatal Error in file: "HwLogger.c"; Fatal Print: hwLoggerEnableDisableMuBfLogs
S 1 7 5 2284 Fatal Error in file: "HwLogger.c"; Fatal Print: hwLoggerEnableDisableMuBitmapSelectLogs
S 1 35 0 548 Assert in file: "RxQueues.c" in line: 548
S 1 35 0 591 Assert in file: "RxQueues.c" in line: 591
S 1 35 0 599 Assert in file: "RxQueues.c" in line: 599
S 1 35 0 607 Assert in file: "RxQueues.c" in line: 607
S 1 35 0 766 Assert in file: "RxQueues.c" in line: 766
S 1 35 0 788 Assert in file: "RxQueues.c" in line: 788
S 1 38 2 117 ContinuousInterfererDetectionGlobalParameters.maxMeasuremenet = %d continuousInterfererMessageParameters.channel: %d
S 1 38 2 208 continuousInterfererMessageParameters.maximumValue = %d continuousInterfererMessageParameters.channel: %d
S 1 39 0 441 Fatal Error in file: "InterruptManager.c"; Fatal Print: Spurious Interrupt
S 1 39 0 475 Assert in file: "InterruptManager.c" in line: 475
S 1 39 0 481 Assert in file: "InterruptManager.c" in line: 481
S 1 39 0 523 Assert in file: "InterruptManager.c" in line: 523
S 1 39 0 527 Assert in file: "InterruptManager.c" in line: 527
S 1 39 0 688 Assert in file: "InterruptManager.c" in line: 688
S 1 40 0 78 IPC UM Debug - MSG from other core: %d : MsgType: 0x%x
S 1 40 0 80 IPC LM Debug - MSG from other core: %d : MsgType: 0x%x
S 1 40 0 143 Assert in file: "ipc.c" in line: 143
S 1 40 0 275 Assert in file: "ipc.c" in line: 275
S 1 41 0 183 Fatal Error in file: "kccmsg.c"; Fatal Print: pre-allocated message space insufficient
S 1 41 0 200 Assert in file: "kccmsg.c" in line: 200
S 1 41 0 201 Assert in file: "kccmsg.c" in line: 201
S 1 41 0 202 Assert in file: "kccmsg.c" in line: 202
S 1 41 0 203 Assert in file: "kccmsg.c" in line: 203
S 1 41 0 217 Assert in file: "kccmsg.c" in line: 217
S 1 41 0 253 Fatal Error in file: "kccmsg.c"; Fatal Print: Tried to increase a reference count past limit
S 1 42 3 305 CyclicPrefixSetNextProbingPoint, tcrCpTable[%d] = %d
S 1 42 3 394 Assert in file: "CyclicPrefix.c" in line: 394
S 1 42 3 444 CyclicPrefixProcessFeedback,workingPointPer = %d,slowProbingPointPer = %d, effectiveTpWp = %d,  effectiveTpProbing = %d
S 1 42 3 456 CyclicPrefixProcessFeedback, Chane WP, tcrCpTable[%d] = =%d
S 1 42 3 492 Assert in file: "CyclicPrefix.c" in line: 492
S 1 42 3 496 CyclicPrefix - SET RATE + 1
S 1 42 3 573 Assert in file: "CyclicPrefix.c" in line: 573
S 1 42 9 115 Assert in file: "LinkAdaptationProductAdjustment.c" in line: 115
S 1 42 11 76 [LinkAdaptation_QAMplusInit] Wave500B, QAMplusEnableFromLm = %d
S 1 43 0 172 lockerScheduleRequest  lockRequesterParams= %x 
S 1 43 0 176 Assert in file: "Locker.c" in line: 176
S 1 43 0 229 lockerScheduleGroupRequest  lockRequesterParams=0x %x 
S 1 43 0 233 Assert in file: "Locker.c" in line: 233
S 1 43 0 300 Locker_LockRequestServiced  stationOrVapNum= %x tid = %x callerContext = %x
S 1 43 0 354 Locker_LockGroupRequestServiced status= %d
S 1 44 0 317 Assert in file: "logger.c" in line: 317
S 1 44 0 505 Assert in file: "logger.c" in line: 505
S 1 44 0 509 Assert in file: "logger.c" in line: 509
S 1 44 0 531 Assert in file: "logger.c" in line: 531
S 1 44 0 532 Assert in file: "logger.c" in line: 532
S 1 44 0 630 Assert in file: "logger.c" in line: 630
S 1 44 0 892 Assert in file: "logger.c" in line: 892
S 1 44 0 937 Assert in file: "logger.c" in line: 937
S 1 44 0 1047 Assert in file: "logger.c" in line: 1047
S 1 44 0 1240 Assert in file: "logger.c" in line: 1240
S 1 44 0 1295 Assert in file: "logger.c" in line: 1295
S 1 44 0 1299 Assert in file: "logger.c" in line: 1299
S 1 44 0 1321 ** missed logs: lack of buffers: %d, lack of BD: %d
S 1 44 0 1363 Assert in file: "logger.c" in line: 1363
S 1 44 0 1401 Assert in file: "logger.c" in line: 1401
S 1 44 0 1417 Assert in file: "logger.c" in line: 1417
S 1 44 0 1440 Assert in file: "logger.c" in line: 1440
S 1 44 0 1460 Assert in file: "logger.c" in line: 1460
S 1 44 2 215 LoggerApi_SetSeverity, level:%d, targetCPU:%d
S 1 44 2 221 Logger severity request is out of range:%d ! (should be [%d, %d]
S 1 44 2 284 Assert in file: "loggerAPI.c" in line: 284
S 1 44 2 306 Assert in file: "loggerAPI.c" in line: 306
S 1 44 2 406 Assert in file: "loggerAPI.c" in line: 406
S 1 44 2 589 Assert in file: "loggerAPI.c" in line: 589
S 1 44 2 599 Assert in file: "loggerAPI.c" in line: 599
S 1 45 2 197 Fatal Error in file: "lmint.c"; Fatal Print: Status FIFO has overflowed
S 1 45 2 244 Fatal Error in file: "lmint.c"; Fatal Print: Unused TSF timer
S 1 45 2 502 INT_GP_TIMER_2_ISR in OPERATION_MODE_DUT, calling LowerSenderDutTxEndHandler
S 1 45 2 571 Assert in file: "lmint.c" in line: 571
S 1 45 2 572 Assert in file: "lmint.c" in line: 572
S 1 45 3 321 [lmmain_HwSemaphoreTest 2] got the lock
S 1 45 3 333 [lmmain_HwSemaphoreTest 3] try to free
S 1 45 3 339 [lmmain_HwSemaphoreTest 4] lock is free
S 1 45 3 349 [1] Try to get the lock. Lock status is %d
S 1 45 3 353 [2] I got the lock. Lock status is %d
S 1 45 3 357 [3] I freed the lock. lock status is %d
S 1 45 7 210 Assert in file: "lmwmertns.c" in line: 210
S 1 45 7 223 Assert in file: "lmwmertns.c" in line: 223
S 1 45 7 225 Assert in file: "lmwmertns.c" in line: 225
S 1 45 7 255 Assert in file: "lmwmertns.c" in line: 255
S 1 46 0 83 Assert in file: "lmi_queue.c" in line: 83
S 1 47 0 205 Assert in file: "lm_interface_task.c" in line: 205
S 1 47 0 217 Assert in file: "lm_interface_task.c" in line: 217
S 1 47 0 218 Assert in file: "lm_interface_task.c" in line: 218
S 1 47 0 219 Assert in file: "lm_interface_task.c" in line: 219
S 1 47 0 220 Assert in file: "lm_interface_task.c" in line: 220
S 1 47 0 224 Assert in file: "lm_interface_task.c" in line: 224
S 1 47 0 402 Assert in file: "lm_interface_task.c" in line: 402
S 1 47 0 403 Assert in file: "lm_interface_task.c" in line: 403
S 1 7 10 118 Assert in file: "Mac2index.c" in line: 118
S 1 7 10 121 Assert in file: "Mac2index.c" in line: 121
S 1 7 10 269 Assert in file: "Mac2index.c" in line: 269
S 1 7 10 272 Assert in file: "Mac2index.c" in line: 272
S 1 48 0 84 Assert in file: "init_ifmsg.c" in line: 84
S 1 48 0 86 Assert in file: "init_ifmsg.c" in line: 86
S 1 48 0 139 Assert in file: "init_ifmsg.c" in line: 139
S 1 48 0 145 Assert in file: "init_ifmsg.c" in line: 145
S 1 48 1 64 Assert in file: "MT_NSSMemoryPool.c" in line: 64
S 1 48 1 77 Assert in file: "MT_NSSMemoryPool.c" in line: 77
S 1 48 1 83 Assert in file: "MT_NSSMemoryPool.c" in line: 83
S 1 48 1 130 Assert in file: "MT_NSSMemoryPool.c" in line: 130
S 1 48 1 138 Assert in file: "MT_NSSMemoryPool.c" in line: 138
S 1 48 1 169 Assert in file: "MT_NSSMemoryPool.c" in line: 169
S 1 48 1 177 Assert in file: "MT_NSSMemoryPool.c" in line: 177
S 1 48 1 190 Assert in file: "MT_NSSMemoryPool.c" in line: 190
S 1 48 2 182 Assert in file: "PacketDescriptorsPool.c" in line: 182
S 1 48 2 214 Assert in file: "PacketDescriptorsPool.c" in line: 214
S 1 49 0 201 Fatal Error in file: "NdpaManager.c"; Fatal Print: ndpaManagerIllegalEvent
S 1 49 0 206 ndpaManagerChangeState: newState = %d
S 1 49 0 213 Assert in file: "NdpaManager.c" in line: 213
S 1 49 0 215 ndpaManagerRunStateMachine: CurrentState = %d, event = %d
S 1 49 0 228 Assert in file: "NdpaManager.c" in line: 228
S 1 49 0 231 ndpaManagerStartTxReq: received NdpaStartTx !!!
S 1 49 0 281 ndpaManagerStopTxReq: received NdpaStoptTx !!!
S 1 49 0 304 Assert in file: "NdpaManager.c" in line: 304
S 1 49 0 336 Assert in file: "NdpaManager.c" in line: 336
S 1 49 0 351 Assert in file: "NdpaManager.c" in line: 351
S 1 49 0 389 ndpaManagerIgnoreEvent: CurrentState = %d
S 1 49 0 402 ndpaManagerLaBfReportIndPdReleased: status = %d
S 1 49 0 412 ndpaManagerLaBfReportIndPdNotReleased: status = %d
S 1 49 0 424 ndpaManagerLaBfReportIndWaitForLock: status = %d
S 1 49 0 466 Assert in file: "NdpaManager.c" in line: 466
S 1 49 0 468 ndpaManagerLockCfmInWaitForLock: Lock status %d
S 1 49 0 504 Assert in file: "NdpaManager.c" in line: 504
S 1 49 0 536 Assert in file: "NdpaManager.c" in line: 536
S 1 52 0 134 Assert in file: "TxPauser.c" in line: 134
S 1 52 0 495 Assert in file: "TxPauser.c" in line: 495
S 1 52 2 193 Assert in file: "TxPauser.c" in line: 193
S 1 52 2 209 Assert in file: "TxPauser.c" in line: 209
S 1 52 2 224 Assert in file: "TxPauser.c" in line: 224
S 1 52 2 240 Assert in file: "TxPauser.c" in line: 240
S 1 52 2 257 Assert in file: "TxPauser.c" in line: 257
S 1 52 2 272 Assert in file: "TxPauser.c" in line: 272
S 1 52 2 312 Assert in file: "TxPauser.c" in line: 312
S 1 53 0 153 Assert in file: "mt_addr_sharing.c" in line: 153
S 1 53 0 208 Assert in file: "mt_addr_sharing.c" in line: 208
S 1 55 0 183 Fatal Error in file: "ProcessManager.c"; Fatal Print: Process Manager Schedule Process Unknown State
S 1 55 0 263 processManagerStartProcess:Process Manager State = %x
S 1 55 0 273 Fatal Error in file: "ProcessManager.c"; Fatal Print: Process Manager Start Process Unknown State
S 1 55 0 306 Fatal Error in file: "ProcessManager.c"; Fatal Print: Process Manager Queue Process Unknown State
S 1 55 0 345 Fatal Error in file: "ProcessManager.c"; Fatal Print: Process Manager Reject Process Unknown State
S 1 55 0 375 Fatal Error in file: "ProcessManager.c"; Fatal Print: Process Manager Finish Process Unknown State
S 1 55 0 419 Assert in file: "ProcessManager.c" in line: 419
S 1 55 0 523 processManagerRunServices:servicesBitMask = %x
S 1 57 0 107 Assert in file: "PsManager.c" in line: 107
S 1 57 0 590 Assert in file: "PsManager.c" in line: 590
S 1 57 2 129 Assert in file: "PsManager.c" in line: 129
S 1 46 1 85 Assert in file: "GeneralQ.c" in line: 85
S 1 59 0 80 Assert in file: "QSmanager.c" in line: 80
S 1 60 0 185 Fatal Error in file: "RegAccess.c"; Fatal Print: REG Access Write Secured
S 1 61 0 253 Assert in file: "ResourceManager.c" in line: 253
S 1 61 0 287 Assert in file: "ResourceManager.c" in line: 287
S 1 61 0 291 Assert in file: "ResourceManager.c" in line: 291
S 1 61 0 295 Assert in file: "ResourceManager.c" in line: 295
S 1 61 0 301 Assert in file: "ResourceManager.c" in line: 301
S 1 61 0 544 Resource Manager - no ID available for pool type %d, return msg %d, return task %d, context %d
S 1 61 0 548 Assert in file: "ResourceManager.c" in line: 548
S 1 61 0 585 Assert in file: "ResourceManager.c" in line: 585
S 1 61 0 586 Assert in file: "ResourceManager.c" in line: 586
S 1 61 0 626 Assert in file: "ResourceManager.c" in line: 626
S 1 61 0 657 Assert in file: "ResourceManager.c" in line: 657
S 1 61 0 661 Assert in file: "ResourceManager.c" in line: 661
S 1 61 0 702 Assert in file: "ResourceManager.c" in line: 702
S 1 61 0 732 Assert in file: "ResourceManager.c" in line: 732
S 1 62 0 931 Assert in file: "RxClassifier.c" in line: 931
S 1 62 0 989 [RxClassifier_FillRtd], staIndex = %d
S 1 62 0 1009 [RxClassifier_FillRtd], rssiTypeFlag = %d, isMulticastOrBroadcast = %d, isStaIndexValid = %d
S 1 62 0 1023 Assert in file: "RxClassifier.c" in line: 1023
S 1 62 0 1400 RxClassifier_RxFilters drop sn %d
S 1 62 0 1774 Assert in file: "RxClassifier.c" in line: 1774
S 1 62 0 1798 Assert in file: "RxClassifier.c" in line: 1798
S 1 62 0 1822 Assert in file: "RxClassifier.c" in line: 1822
S 1 62 0 1849 Assert in file: "RxClassifier.c" in line: 1849
S 1 62 0 1877 Assert in file: "RxClassifier.c" in line: 1877
S 1 62 0 1906 Assert in file: "RxClassifier.c" in line: 1906
S 1 62 0 1935 Assert in file: "RxClassifier.c" in line: 1935
S 1 62 0 1969 Assert in file: "RxClassifier.c" in line: 1969
S 1 62 0 2032 Assert in file: "RxClassifier.c" in line: 2032
S 1 62 0 2122 Assert in file: "RxClassifier.c" in line: 2122
S 1 62 0 2235 Assert in file: "RxClassifier.c" in line: 2235
S 1 62 0 2263 Assert in file: "RxClassifier.c" in line: 2263
S 1 62 0 2389 -------- Rx Classifier configured for Sniffer --------
S 1 62 0 2483 [RxClassifier_ConfigureNormalMode] - WAVE400------------------end]
S 1 62 0 2510 [RxClassifier_ConfigureRssiMode]-------- Rx Classifier configured for RSSI -WAVE400------- RxClassifierDb.rssiTypeFlag = %d
S 1 7 12 597 Assert in file: "RxClassifier.c" in line: 597
S 1 7 12 820 [RxClassifier_ConfigureNormalMode]-------- Rx Classifier RAM configured for NORMAL_AFTER_RSSI --------
S 1 7 12 829 [RxClassifier_ConfigureNormalMode]--------------------------end
S 1 7 12 864 [RxClassifier_ConfigureRssiMode]-------- Rx Classifier RAM configured for RSSI --------
S 1 7 12 871 [RxClassifier_ConfigureRssiMode], StaDB_IsDataEncrypted(%d) = %d, StaDB_IsManagementEncrypted(%d) = %d
S 1 7 12 879 [RxClassifier_ConfigureRssiMode]------------------------------------end]
S 1 7 12 945 -------- Rx Classifier configured for Sniffer --------
S 1 63 0 445 Assert in file: "RxDataPath.c" in line: 445
S 1 63 0 470 Assert in file: "RxDataPath.c" in line: 470
S 1 64 2 243 Assert in file: "RxHandler_Rtd.c" in line: 243
S 1 64 2 278 Assert in file: "RxHandler_Rtd.c" in line: 278
S 1 67 0 284 Assert in file: "Reordering.c" in line: 284
S 1 67 0 823 Assert in file: "Reordering.c" in line: 823
S 1 67 0 931 Assert in file: "Reordering.c" in line: 931
S 1 67 2 169 Assert in file: "RxPp.c" in line: 169
S 1 67 2 189 Assert in file: "RxPp.c" in line: 189
S 1 67 2 861 Assert in file: "RxPp.c" in line: 861
S 1 67 2 1340 Assert in file: "RxPp.c" in line: 1340
S 1 68 1 179 Assert in file: "RxPp.c" in line: 179
S 1 68 1 467 Assert in file: "RxPp.c" in line: 467
S 1 68 1 477 Assert in file: "RxPp.c" in line: 477
S 1 68 1 517 Assert in file: "RxPp.c" in line: 517
S 1 68 1 654 Assert in file: "RxPp.c" in line: 654
S 1 68 1 1001 Assert in file: "RxPp.c" in line: 1001
S 1 68 1 1110 Assert in file: "RxPp.c" in line: 1110
S 1 54 5 96 Assert in file: "cipher_shared_ram_db.c" in line: 96
S 1 54 5 97 Assert in file: "cipher_shared_ram_db.c" in line: 97
S 1 54 5 136 Assert in file: "cipher_shared_ram_db.c" in line: 136
S 1 54 5 138 Assert in file: "cipher_shared_ram_db.c" in line: 138
S 1 54 5 170 Assert in file: "cipher_shared_ram_db.c" in line: 170
S 1 54 5 171 Assert in file: "cipher_shared_ram_db.c" in line: 171
S 1 54 5 173 Assert in file: "cipher_shared_ram_db.c" in line: 173
S 1 54 5 202 Assert in file: "cipher_shared_ram_db.c" in line: 202
S 1 54 7 98 Assert in file: "cipher_suite_ccmp.c" in line: 98
S 1 54 8 97 Assert in file: "cipher_suite_wep.c" in line: 97
S 1 54 8 123 Assert in file: "cipher_suite_wep.c" in line: 123
S 1 54 8 154 Assert in file: "cipher_suite_wep.c" in line: 154
S 1 54 1 94 Assert in file: "key_manager.c" in line: 94
S 1 54 2 227 Sec Manager, Send Confirmation, Client %d, SID %d
S 1 54 2 258 SEC Manager STA Manager, Station %d changed from %d to %d
S 1 54 2 916 Fatal Error in file: "secManager_StaManager.c"; Fatal Print: SEC Manager STA Manager Fatal
S 1 54 2 956 Assert in file: "secManager_StaManager.c" in line: 956
S 1 54 2 1058 Assert in file: "secManager_StaManager.c" in line: 1058
S 1 54 2 1098 Assert in file: "secManager_StaManager.c" in line: 1098
S 1 54 2 1139 Assert in file: "secManager_StaManager.c" in line: 1139
S 1 54 2 1179 Assert in file: "secManager_StaManager.c" in line: 1179
S 1 70 1 99 Assert in file: "LowerSenderTxCancel.c" in line: 99
S 1 70 1 106 Assert in file: "LowerSenderTxCancel.c" in line: 106
S 1 70 1 121 Assert in file: "LowerSenderTxCancel.c" in line: 121
S 1 70 1 135 Assert in file: "LowerSenderTxCancel.c" in line: 135
S 1 70 1 147 Assert in file: "LowerSenderTxCancel.c" in line: 147
S 1 31 4 165 Sender Error: file ID %d, line %d, state %d
S 1 31 4 166 Fatal Error in file: "SenderInterface.c"; Fatal Print: Sender Error Start
S 1 31 4 185 Fatal Error in file: "SenderInterface.c"; Fatal Print: Unsupported Message ID
S 1 31 4 211 Fatal Error in file: "SenderInterface.c"; Fatal Print: Unsupported Message ID
S 1 31 4 223 Fatal Error in file: "SenderInterface.c"; Fatal Print: Sender Unknown Event
S 1 31 4 363 Assert in file: "SenderInterface.c" in line: 363
S 1 31 4 396 Assert in file: "SenderInterface.c" in line: 396
S 1 31 4 464 Assert in file: "SenderInterface.c" in line: 464
S 1 71 0 448 [servicesHandlerSendCTS2Self], ctsParams->duration = %d, servicesHandlerParams.currentRunningServiceData = %d
S 1 71 0 476 Fatal Error in file: "ServicesHandler.c"; Fatal Print: servicesHandlerError
S 1 71 0 535 ServicesHandler_RunService:Service Id %d
S 1 71 0 543 Assert in file: "ServicesHandler.c" in line: 543
S 1 72 0 58 Assert in file: "shram_interruptSection.c" in line: 58
S 1 72 0 63 Assert in file: "shram_interruptSection.c" in line: 63
S 1 73 0 281 Smps Manager STA Manager, STA %d changed from %d to %d
S 1 73 0 1346 Assert in file: "SmpsManager_StaManager.c" in line: 1346
S 1 73 0 1522 Assert in file: "SmpsManager_StaManager.c" in line: 1522
S 1 73 0 1560 Assert in file: "SmpsManager_StaManager.c" in line: 1560
S 1 75 0 306 Statistics Manager, Send Confirmation, Client %d, SID %d
S 1 75 0 337 Statistics Manager, Send Confirmation, VapId %d
S 1 75 0 455 statisticsManagerIncrease %d %d %d %d
S 1 75 0 476 statisticsManagerDecrease %d %d %d %d
S 1 75 0 505 Fatal Error in file: "StatisticsManager.c"; Fatal Print: statisticsManagerArithmetic
S 1 75 0 553 Fatal Error in file: "StatisticsManager.c"; Fatal Print: statisticsManagerSet
S 1 75 0 620 Fatal Error in file: "StatisticsManager.c"; Fatal Print: statisticsManagerSet
S 1 75 0 765 Assert in file: "StatisticsManager.c" in line: 765
S 1 75 0 927 Assert in file: "StatisticsManager.c" in line: 927
S 1 75 0 931 Assert in file: "StatisticsManager.c" in line: 931
S 1 75 0 1035 Assert in file: "StatisticsManager.c" in line: 1035
S 1 75 0 1040 Assert in file: "StatisticsManager.c" in line: 1040
S 1 75 0 1041 Assert in file: "StatisticsManager.c" in line: 1041
S 1 75 0 1071 Assert in file: "StatisticsManager.c" in line: 1071
S 1 75 0 1072 Assert in file: "StatisticsManager.c" in line: 1072
S 1 75 0 1134 Assert in file: "StatisticsManager.c" in line: 1134
S 1 75 0 1135 Assert in file: "StatisticsManager.c" in line: 1135
S 1 75 0 1168 Fatal Error in file: "StatisticsManager.c"; Fatal Print: Current implementation: table stored in IRAM
S 1 75 0 1618 Assert in file: "StatisticsManager.c" in line: 1618
S 1 75 0 1653 Assert in file: "StatisticsManager.c" in line: 1653
S 1 75 0 1805 pGetAocsInfo->dynamicBW20MHz, %d
S 1 75 0 1806 pGetAocsInfo->dynamicBW40MHz, %d
S 1 75 0 1807 pGetAocsInfo->dynamicBW80MHz, %d
S 1 75 0 1808 pGetAocsInfo->extStaRx, %d
S 1 75 0 1809 pGetAocsInfo->noiseFloor, %d
S 1 75 0 1810 pGetAocsInfo->TxPower, %d
S 1 75 0 1811 pGetAocsInfo->channelLoad, %d
S 1 75 0 1812 pGetAocsInfo->CWIvalue, %d
S 1 75 0 1813 numOfStationCounter, %d
S 1 75 0 1814 averageRssi, %d
S 1 75 0 1815 pGetAocsInfo->RSSI, %d
S 1 75 0 1816 pGetAocsInfo->SNR, %d
S 1 75 0 1817 phyRxStatusDb.devicePhyRxStatus.rf_gain[ant], %d
S 1 75 0 1883 Assert in file: "StatisticsManager.c" in line: 1883
S 1 75 0 2036 Assert in file: "StatisticsManager.c" in line: 2036
S 1 75 0 2046 Assert in file: "StatisticsManager.c" in line: 2046
S 1 75 0 2124 Assert in file: "StatisticsManager.c" in line: 2124
S 1 75 0 2131 Assert in file: "StatisticsManager.c" in line: 2131
S 1 75 0 2133 Assert in file: "StatisticsManager.c" in line: 2133
S 1 75 0 2213 j:%d i:%d
S 1 75 0 2275 %d %d
S 1 39 1 131 Fatal Error in file: "System_Configuration.c"; Fatal Print: System_ConvertUsToSystemClk
S 1 77 0 112 Assert in file: "TinyKernel_Messages.c" in line: 112
S 1 77 0 139 Assert in file: "TinyKernel_Messages.c" in line: 139
S 1 77 0 148 Assert in file: "TinyKernel_Messages.c" in line: 148
S 1 77 0 152 Assert in file: "TinyKernel_Messages.c" in line: 152
S 1 77 0 205 Assert in file: "TinyKernel_Messages.c" in line: 205
S 1 77 0 226 Assert in file: "TinyKernel_Messages.c" in line: 226
S 1 77 0 227 Assert in file: "TinyKernel_Messages.c" in line: 227
S 1 77 0 250 Assert in file: "TinyKernel_Messages.c" in line: 250
S 1 77 0 264 Assert in file: "TinyKernel_Messages.c" in line: 264
S 1 77 0 413 Assert in file: "TinyKernel_Messages.c" in line: 413
S 1 77 0 444 Assert in file: "TinyKernel_Messages.c" in line: 444
S 1 78 0 235 Assert in file: "TrainingManager.c" in line: 235
S 1 78 0 242 TrainingManager_RunStateMachine: CurrentState = %d, event = %d
S 1 78 0 252 TrainingManager_ChangeState: newState = %d
S 1 78 0 312 Fatal Error in file: "TrainingManager.c"; Fatal Print: TrainingManager_IllegalEvent
S 1 78 0 339 TrainingManager_SendLaInfoReq, muActiveVapBitmap = 0x%04X
S 1 78 0 391 TrainingManager_CheckNdpaConfirmationStatus, Status = %d
S 1 78 0 419 Group Manager result BW = %d
S 1 78 0 453 TrainingManager_StopTrainingDuringTraining
S 1 78 0 484 TrainingManager_StopTrainingDuringWaitingForLaInfo
S 1 78 0 523 TrainingManager_AddVap, new VAP id = %d
S 1 78 0 664 TrainingManager_RemoveStaNotDuringTraining, sta Id = 0x%X
S 1 78 0 710 TrainingManager_RemoveStaDuringTraining, sta Id = 0x%X
S 1 78 0 774 TrainingManager_RemoveStaDuringStopping, sta Id = 0x%X
S 1 78 0 825 TrainingManager_HaltStaNotDuringTraining, sta Id = 0x%X
S 1 78 0 859 TrainingManager_HaltStaDuringTraining, sta Id = 0x%X
S 1 78 0 914 TrainingManager_StopStaDuringTraining, sta Id = 0x%X
S 1 78 0 1011 TrainingManager_SendTrainingStoppedConfirmation, cfmBitmap = 0x%08X, 0x%08X
S 1 78 0 1045 TrainingManager_IgnoreStopTraining
S 1 78 0 1084 TrainingManager_StartTraining, num of connected station = %d, All active vaps bitmap = 0x%04X, MU active vaps bitmap = 0x%04X, num of Pools = %d
S 1 78 0 1090 VAP SELECTED!!!, VAP ID = %d
S 1 78 0 1146 Build test plan and Training Vector finished, send Start Tx to NDPA Manager, num of station = %d, VAP ID = %d
S 1 78 0 1155 VAP NOT SELECTED!!!
S 1 78 0 1211 TrainingManager_BuildPools, input is active sta bitmap from Link adaptive:
S 1 78 0 1220 Final Active STA bitmap
S 1 78 0 1239 current VAP Id = %d
S 1 78 0 1267 Current feature bitmap for station %d = 0x%08X
S 1 78 0 1347 Start select stations!!! , pool id = %d
S 1 78 0 1382 Assert in file: "TrainingManager.c" in line: 1382
S 1 78 0 1415 STA index selected = %X
S 1 78 0 1451 Start Building Test Plan!!! , pool id = %d, current policies bitmap = 0x%04X, num of atennas = %d
S 1 78 0 1466 TrainingManager_BuildTestPlan: currentPlicyBitmap = 0x%04X, currentPolicy = %d
S 1 78 0 1476 Start Building Test Plan!!! , pool id = %d
S 1 78 0 1515 TrainingManager_StartResultsProcessing
S 1 78 0 1563 TrainingManager_UpdateGroupCombinationTable, poolId = %d, testPlanPoliciesBitmap = 0x%04X, num of antennas = %d
S 1 78 0 1578 TrainingManager_UpdateGroupCombinationTable: currentPlicyBitmap = 0x%04X, currentPolicy = %d
S 1 78 0 1588 TrainingManager_UpdateGroupCombinationTable, poolId = %d
S 1 78 0 1622 Bulding Test Plan for policy 0
S 1 78 0 1628 Bulding Test Plan for policy 1
S 1 78 0 1635 Bulding Test Plan for policy 2
S 1 78 0 1644 Bulding Test Plan for policy 3
S 1 78 0 1650 Bulding Test Plan for policy 4
S 1 78 0 1656 Bulding Test Plan for policy 5
S 1 78 0 1665 Bulding Test Plan for policy 6
S 1 78 0 1704 Bulding Test Plan for Segment 1xxx
S 1 78 0 1730 Num of combinations in 1XXX segment is %d
S 1 78 0 1749 Bulding Test Plan for Segment 2xxx
S 1 78 0 1779 Num of combinations in 2XXX segment is %d
S 1 78 0 1799 Bulding Test Plan for Segment 22xx
S 1 78 0 1846 Num of combinations in 22XX segment is %d
S 1 78 0 1867 Bulding Test Plan for Segment 21xx
S 1 78 0 1912 Num of combinations in 21XX segment is %d
S 1 78 0 1931 Bulding Test Plan for Segment 12xx
S 1 78 0 1976 Num of combinations in 12XX segment is %d
S 1 78 0 1996 Bulding Test Plan for Segment 11xx
S 1 78 0 2036 Num of combinations in 11XX segment is %d
S 1 78 0 2055 Bulding Test Plan for Segment 111x
S 1 78 0 2102 Num of combinations in 111X segment is %d
S 1 78 0 2120 Bulding Test Plan for Segment 211x
S 1 78 0 2172 Num of combinations in 211X segment is %d
S 1 78 0 2191 Bulding Test Plan for Segment 121x
S 1 78 0 2243 Num of combinations in 121X segment is %d
S 1 78 0 2262 Bulding Test Plan for Segment 112x
S 1 78 0 2314 Num of combinations in 112X segment is %d
S 1 78 0 2334 Bulding Test Plan for Segment 1111
S 1 78 0 2387 Num of combinations in 1111 segment is %d
S 1 78 0 2420 Update Group Combination table for policy 0
S 1 78 0 2427 Update Group Combination table for policy 1
S 1 78 0 2435 Update Group Combination table for policy 2
S 1 78 0 2445 Update Group Combination table for policy 3
S 1 78 0 2452 Update Group Combination table for policy 4
S 1 78 0 2459 Update Group Combination table for policy 5
S 1 78 0 2469 Update Group Combination table for policy 6
S 1 78 0 2504 Update Group Combination table for Segment 1xxx, output lines:
S 1 78 0 2538 Update Group Combination table for Segment 2xxx, output lines:
S 1 78 0 2578 Update Group Combination table for Segment 22xx, output lines:
S 1 78 0 2645 Update Group Combination table for Segment 21xx, output lines:
S 1 78 0 2712 Update Group Combination table for Segment 12xx, output lines:
S 1 78 0 2779 Update Group Combination table for Segment 11xx, output lines:
S 1 78 0 2842 Update Group Combination table for Segment 111x, output lines:
S 1 78 0 2912 Update Group Combination table for Segment 211x, output lines:
S 1 78 0 2987 Update Group Combination table for Segment 121x, output lines:
S 1 78 0 3061 Update Group Combination table for Segment 112x, output lines:
S 1 78 0 3135 Update Group Combination table for Segment 1111, output lines:
S 1 78 0 3291 Calculated group mark = %d
S 1 78 0 3340 Group combination table for table index %d is updated!!!
S 1 78 0 4017 Fatal Error in file: "TrainingManager.c"; Fatal Print: TrainingManager_Init
S 1 82 0 342 Assert in file: "TxManager.c" in line: 342
S 1 82 0 350 Assert in file: "TxManager.c" in line: 350
S 1 82 0 351 Assert in file: "TxManager.c" in line: 351
S 1 82 0 352 Assert in file: "TxManager.c" in line: 352
S 1 82 0 407 Assert in file: "TxManager.c" in line: 407
S 1 82 0 469 Assert in file: "TxManager.c" in line: 469
S 1 82 0 470 Assert in file: "TxManager.c" in line: 470
S 1 82 0 550 Assert in file: "TxManager.c" in line: 550
S 1 82 0 557 Assert in file: "TxManager.c" in line: 557
S 1 82 0 558 Assert in file: "TxManager.c" in line: 558
S 1 82 0 682 txManagerPackestFromFwListHandler packet descriptor %x
S 1 82 0 995 Fatal Error in file: "TxManager.c"; Fatal Print: txManagerNdpaHandler
S 1 82 0 1105 Assert in file: "TxManager.c" in line: 1105
S 1 82 0 1285 Assert in file: "TxManager.c" in line: 1285
S 1 82 0 1315 Fatal Error in file: "TxManager.c"; Fatal Print: txManagerAssert
S 1 82 0 1342 Fatal Error in file: "TxManager.c"; Fatal Print: txManagerListFatal
S 1 82 0 1447 -------- NTD configured for Sniffer --------
S 1 82 0 1702 Assert in file: "TxManager.c" in line: 1702
S 1 82 0 1821 Assert in file: "TxManager.c" in line: 1821
S 1 4 4 566 Assert in file: "TxSelector.c" in line: 566
S 1 4 4 1242 Fatal Error in file: "TxSelector.c"; Fatal Print: TxSelector_IsDataInQueue - back door not available in gen5b
S 1 4 4 1322 Fatal Error in file: "TxSelector.c"; Fatal Print: ISR TX Selector Error
S 1 84 0 99 Assert in file: "TxSequencer.c" in line: 99
S 1 4 6 157 Assert in file: "TxSequencer.c" in line: 157
S 1 4 6 170 Assert in file: "TxSequencer.c" in line: 170
S 1 86 0 240 Assert in file: "CalendarWheel.c" in line: 240
S 1 86 0 291 Assert in file: "CalendarWheel.c" in line: 291
S 1 86 0 360 Assert in file: "CalendarWheel.c" in line: 360
S 1 37 5 82 Assert in file: "HwSemaphore.c" in line: 82
S 1 37 5 149 Assert in file: "HwSemaphore.c" in line: 149
S 1 37 5 191 Assert in file: "HwSemaphore.c" in line: 191
S 1 37 5 246 [HwSemaphore_Read 1] readValue is %d 
S 1 37 5 273 [HwSemaphore_FreeAllDebug 1] hwSemaphoreShadow = %d
S 1 37 0 121 Assert in file: "MT_Math.c" in line: 121
S 1 37 0 124 Assert in file: "MT_Math.c" in line: 124
S 1 37 0 197 Assert in file: "MT_Math.c" in line: 197
S 1 12 0 120 Assert in file: "CoC.c" in line: 120
S 1 12 0 121 Assert in file: "CoC.c" in line: 121
S 1 12 0 167 Assert in file: "CoC.c" in line: 167
S 1 12 0 168 Assert in file: "CoC.c" in line: 168
S 1 12 0 215 Assert in file: "CoC.c" in line: 215
S 1 12 0 216 Assert in file: "CoC.c" in line: 216
S 1 12 0 275 Assert in file: "CoC.c" in line: 275
S 1 12 0 353 Assert in file: "CoC.c" in line: 353
S 1 12 0 381 Assert in file: "CoC.c" in line: 381
S 1 12 0 415 Assert in file: "CoC.c" in line: 415
S 1 19 2 128 DUT API NOT SUPPORTED !!
S 1 19 2 354 Assert in file: "Dut_Managment.c" in line: 354
S 1 19 2 438 dutStartCalibration, abort request, calibration in process: %d
S 1 19 2 456 dutStartCalibration, start DUT_CALIBRATION_TYPE_ONLINE
S 1 19 2 465 dutStartCalibration, start DUT_CALIBRATION_TYPE_OFFLINE
S 1 19 2 471 Assert in file: "Dut_Managment.c" in line: 471
S 1 19 2 491 Assert in file: "Dut_Managment.c" in line: 491
S 1 19 2 513 Assert in file: "Dut_Managment.c" in line: 513
S 1 19 2 532 DUT_HandleCalibDone, calibration type: %d ended
S 1 19 2 607 Assert in file: "Dut_Managment.c" in line: 607
S 1 19 2 727 Assert in file: "Dut_Managment.c" in line: 727
S 1 19 3 159 Assert in file: "Dut_Tx.c" in line: 159
S 1 19 3 169 dutTxSetState, old state:%d, new state:%d
S 1 19 3 223 dutTxGetPowerVectorPerAnt, index:%d, measuredVoltagePerPower:%d
S 1 19 3 273 ----- dutTxStartTransmision ----
S 1 19 3 288 Error!, dutTxStartTransmision, isChannelSet:%d
S 1 19 3 301 dutTxStartTransmision, DUT_STATUS_TX_START_IS_ONGOING
S 1 19 3 307 dutTxStartTransmision, DUT_STATUS_TX_STOP_IS_ONGOING
S 1 19 3 312 Assert in file: "Dut_Tx.c" in line: 312
S 1 19 3 329 ----- dutTxStopTransmision ---- TxState = 0x%x
S 1 19 3 340 dutTxStopTransmision, packetsTransmitted:%d, packetsProcessed:%d
S 1 19 3 345 dutTxStopTransmision, DUT_STATUS_TX_ALREADY_STOPPED
S 1 19 3 351 dutTxStopTransmision, DUT_STATUS_TX_STOP_IS_ONGOING
S 1 19 3 356 Assert in file: "Dut_Tx.c" in line: 356
S 1 19 3 370 Assert in file: "Dut_Tx.c" in line: 370
S 1 19 3 425 dutTransmitPacketReq, dutDB_p->spaceless:%d
S 1 19 3 435 ---- dutTransmitPacketReq, no free desc
S 1 19 3 477 dutTransmitPacketReq, calling TxPacketsClassifier_SendManagementPacketFromFw, dutDB_p->m_DutTrafficParams.packetsProcessed:%d
S 1 19 3 504 Assert in file: "Dut_Tx.c" in line: 504
S 1 19 3 519 dutHandleCbInTransmittingState transmitPowerVector.numOfTransmitionPerPower[PVpowerToTransmitIndex]:%d
S 1 19 3 540 dutHandleCbInTransmittingState SET NEW POWER AND LENGTH
S 1 19 3 546 dutHandleCbInTransmittingState packetLength:%d
S 1 19 3 547 dutHandleCbInTransmittingState dutPowerAndPacketLength.txPower:%d
S 1 19 3 568 dutHandleCbInTransmittingState, calling TxPacketsClassifier_SendManagementPacketFromFw, m_DutTrafficParams_p->packetsProcessed:%d
S 1 19 3 585 dutHandleTxActionPublicFrameCb, DUT_TX_STATE_TRANSMITTING -> DUT_TX_STATE_IDLE, calling ResourceManager_ReleaseDescriptor
S 1 19 3 622 dutHandleTxActionPublicFrameCb, m_DutTrafficParams_p->trafficState:%d, m_DutTrafficParams_p->txPacketIsOngoing:%d, packetsTransmitted:%d
S 1 19 3 645 Assert in file: "Dut_Tx.c" in line: 645
S 1 27 5 647 START AFE CALIBRATION
S 1 27 5 676 retVal=%d, packetMod=%d
S 1 27 5 686 packetMod=%d,pElements->results.offlineModulationType=%d 
S 1 27 5 690 exit ALB mode, calibration end!
S 1 27 5 697 LastClRunTime: %d
S 1 27 5 757 QBF calibration finished
S 1 27 5 788 Setting TPC: %d, for extPa = %d
S 1 27 5 881 Assert in file: "BeamFormingClbrHndlr.c" in line: 881
S 1 27 5 884 agcGains(ant %d). lnaIndx = %d pgc1Indx = %d pgc2Indx = %d pgc3Indx = %d
S 1 27 5 896 Send packet %d => %d
S 1 27 5 909 Packet sent from ant %d to ant %d
S 1 27 5 920 BM calibration fail! number of recorded bins from sessions not identical
S 1 27 5 942 StopRisc called
S 1 27 5 998 StartRisc called
S 1 27 5 1052 TRSW: %x %x %x
S 1 27 5 1202 Registers values were not saved, cannot restore them
S 1 27 5 1203 Assert in file: "BeamFormingClbrHndlr.c" in line: 1203
S 1 27 5 1208 Stop risc
S 1 27 5 1230 Run risc
S 1 27 5 1275 Assert in file: "BeamFormingClbrHndlr.c" in line: 1275
S 1 27 5 1329 BF Calibration Failed!! could not achieve a good channel
S 1 27 5 1349 triggerTB
S 1 27 5 1429 Record channel failed!!! CRC error
S 1 27 5 1539 Assert in file: "BeamFormingClbrHndlr.c" in line: 1539
S 1 27 5 1546 Record %d bins
S 1 27 5 1907 Assert in file: "BeamFormingClbrHndlr.c" in line: 1907
S 1 27 5 1997 Assert in file: "BeamFormingClbrHndlr.c" in line: 1997
S 1 27 5 2018 START AGC GAINS CALIBRATION
S 1 27 5 2031 START K CALIBRATION
S 1 27 5 2059 START AGC OFFSET CALIBRATION
S 1 27 5 2069 START TX OFFSET CALIBRATION
S 1 27 5 2084 exit ALB mode, calibration end!, calStatus = %X
S 1 27 5 2114 Start K%d calibration, CB=%d
S 1 27 5 2216 relative gain = %d
S 1 27 5 2241 Assert in file: "BeamFormingClbrHndlr.c" in line: 2241
S 1 27 5 2256 Warning: working at %d instead of 15 dB backoff
S 1 27 5 2264 BF Calibration Failed !! Attenuation between antennas too high:%d
S 1 27 5 2305 Send packet: Ant%d->Ant%d
S 1 27 5 2306 trSwTxAnt: %d
S 1 27 5 2504 Assert in file: "BeamFormingClbrHndlr.c" in line: 2504
S 1 27 5 2571 digital gain %d
S 1 27 5 2584 running for gains : LnaIndex %d, pgc1Index %d, pgc2Index %d,pgc3Index %d
S 1 27 5 2838 Assert in file: "BeamFormingClbrHndlr.c" in line: 2838
S 1 27 5 3038 Assert in file: "BeamFormingClbrHndlr.c" in line: 3038
S 1 27 5 3088 BF Calibration Failed!! could not achieve a good channel
S 1 27 5 3164 DisTxCancel
S 1 27 5 3171 EnTxCancel
S 1 27 9 645 START AFE CALIBRATION
S 1 27 9 674 retVal=%d, packetMod=%d
S 1 27 9 684 packetMod=%d,pElements->results.offlineModulationType=%d 
S 1 27 9 688 exit ALB mode, calibration end!
S 1 27 9 695 LastClRunTime: %d
S 1 27 9 755 QBF calibration finished
S 1 27 9 786 Setting TPC: %d, for extPa = %d
S 1 27 9 879 Assert in file: "BeamFormingClbrHndlr.c" in line: 879
S 1 27 9 882 agcGains(ant %d). lnaIndx = %d pgc1Indx = %d pgc2Indx = %d pgc3Indx = %d
S 1 27 9 894 Send packet %d => %d
S 1 27 9 907 Packet sent from ant %d to ant %d
S 1 27 9 918 BM calibration fail! number of recorded bins from sessions not identical
S 1 27 9 940 StopRisc called
S 1 27 9 996 StartRisc called
S 1 27 9 1050 TRSW: %x %x %x
S 1 27 9 1200 Registers values were not saved, cannot restore them
S 1 27 9 1201 Assert in file: "BeamFormingClbrHndlr.c" in line: 1201
S 1 27 9 1206 Stop risc
S 1 27 9 1228 Run risc
S 1 27 9 1273 Assert in file: "BeamFormingClbrHndlr.c" in line: 1273
S 1 27 9 1327 BF Calibration Failed!! could not achieve a good channel
S 1 27 9 1347 triggerTB
S 1 27 9 1429 Record channel failed!!! CRC error
S 1 27 9 1537 Assert in file: "BeamFormingClbrHndlr.c" in line: 1537
S 1 27 9 1543 Record %d bins
S 1 27 9 1898 Assert in file: "BeamFormingClbrHndlr.c" in line: 1898
S 1 27 9 1989 Assert in file: "BeamFormingClbrHndlr.c" in line: 1989
S 1 27 9 2010 START AGC GAINS CALIBRATION
S 1 27 9 2023 START K CALIBRATION
S 1 27 9 2051 START AGC OFFSET CALIBRATION
S 1 27 9 2061 START TX OFFSET CALIBRATION
S 1 27 9 2076 exit ALB mode, calibration end!, calStatus = %X
S 1 27 9 2106 Start K%d calibration, CB=%d
S 1 27 9 2208 relative gain = %d
S 1 27 9 2233 Assert in file: "BeamFormingClbrHndlr.c" in line: 2233
S 1 27 9 2248 Warning: working at %d instead of 15 dB backoff
S 1 27 9 2256 BF Calibration Failed !! Attenuation between antennas too high:%d
S 1 27 9 2297 Send packet: Ant%d->Ant%d
S 1 27 9 2298 trSwTxAnt: %d
S 1 27 9 2496 Assert in file: "BeamFormingClbrHndlr.c" in line: 2496
S 1 27 9 2563 digital gain %d
S 1 27 9 2576 running for gains : LnaIndex %d, pgc1Index %d, pgc2Index %d,pgc3Index %d
S 1 27 9 2830 Assert in file: "BeamFormingClbrHndlr.c" in line: 2830
S 1 27 9 3030 Assert in file: "BeamFormingClbrHndlr.c" in line: 3030
S 1 27 9 3080 BF Calibration Failed!! could not achieve a good channel
S 1 27 9 3156 DisTxCancel
S 1 27 9 3163 EnTxCancel
S 1 28 1 124 Assert in file: "LpfClbrUtils.c" in line: 124
S 1 28 28 279 RSSI Path: Executing Calibration
S 1 28 28 290 Assert in file: "RssiPathClbrHndlr.c" in line: 290
S 1 28 28 596 Assert in file: "RssiPathClbrHndlr.c" in line: 596
S 1 28 28 628 Assert in file: "RssiPathClbrHndlr.c" in line: 628
S 1 28 28 646 Assert in file: "RssiPathClbrHndlr.c" in line: 646
S 1 28 29 280 RSSI Path: Executing Calibration
S 1 28 29 291 Assert in file: "RssiPathClbrHndlr.c" in line: 291
S 1 28 29 597 Assert in file: "RssiPathClbrHndlr.c" in line: 597
S 1 28 29 629 Assert in file: "RssiPathClbrHndlr.c" in line: 629
S 1 28 29 647 Assert in file: "RssiPathClbrHndlr.c" in line: 647
S 1 28 11 548 Assert in file: "TpcClbrHndlr.c" in line: 548
S 1 28 11 570 Assert in file: "TpcClbrHndlr.c" in line: 570
S 1 28 11 761 Assert in file: "TpcClbrHndlr.c" in line: 761
S 1 28 11 1107 Assert in file: "TpcClbrHndlr.c" in line: 1107
S 1 28 11 1155 ===================== Calibrate index %d, ant %d, bw %d ==============================
S 1 28 11 1204 -------- feedback %d, measured %d, target %d -----------
S 1 28 11 1228 old %d, new %d, steps %d
S 1 28 11 1439 Assert in file: "TpcClbrHndlr.c" in line: 1439
S 1 28 11 1450 Assert in file: "TpcClbrHndlr.c" in line: 1450
S 1 28 11 1451 Assert in file: "TpcClbrHndlr.c" in line: 1451
S 1 28 14 131 use ssb loop %d
S 1 28 14 188 Tx IQ: Finished Calibration. Ret Code = %d, Run Time = %d
S 1 28 14 270 Tx IQ initAntennaOnlineIterationDetails: last antenna = %d
S 1 28 14 380 TXIQ calibrateSingleAntenna:RF Ant %d,LoopBackRxAnt %d, LoopBackTxAnt %d
S 1 28 14 442 Tx IQ calibrateSingleAntenna(): Restore Hw Registers Run Time = %d
S 1 28 14 499 amplitude: %d digital gain: %d
S 1 28 14 500 Tx IQ: Init Done. Duration = %d
S 1 28 14 528 Tx IQ: Restore Done. Duration = %d
S 1 28 14 593 setTxIqAdaptiveGain. acc result(II) = %d. accumNorm = %d
S 1 28 14 612 Accumulator measurement is low - increase gain. course = %d
S 1 28 14 624 Accumulator measurement is high - decrease gain. course = %d
S 1 28 14 645 old Amp: %d new Amp: %d old digital: %d new digital: %d
S 1 28 14 666 Assert in file: "TxIQMismatchClbrHndlr.c" in line: 666
S 1 28 14 683 a: %d phiSquared: %d IMR: %d
S 1 28 14 817 Tx IQ calibrateAndVerifySingleBin:Bin %d
S 1 28 14 837 Reference energy (bin %d - %d): %d
S 1 28 14 889 Tx IQ calibrateAndVerifySingleBin(): Run Time = %d
S 1 28 14 948 tx ant: %d. rx ant: %d. II: %d QQ: %d IQ: %d
S 1 28 14 952 Tx IQ calcMinimumCoeffcientsValue(): a energy x0=%d x1=%d x2=%d
S 1 28 14 953 Tx IQ calcMinimumCoeffcientsValue(): a energy x3=%d x4=%d x5=%d
S 1 28 14 954 Tx IQ calcMinimumCoeffcientsValue(): a energy x6=%d x7=%d x8=%d
S 1 28 14 973 tx ant: %d. rx ant: %d. II: %d QQ: %d IQ: %d
S 1 28 14 977 Tx IQ calcMinimumCoeffcientsValue(): b energy x0=%d x1=%d x2=%d
S 1 28 14 978 Tx IQ calcMinimumCoeffcientsValue(): b energy x3=%d x4=%d x5=%d
S 1 28 14 979 Tx IQ calcMinimumCoeffcientsValue(): b energy x6=%d x7=%d x8=%d
S 1 28 14 988 Tx IQ calcMinCoeffcientValues(): a=%d, b=%d
S 1 28 14 1178 Assert in file: "TxIQMismatchClbrHndlr.c" in line: 1178
S 1 28 14 1201 Tx IQ VerifyCalibrationResults(): Energy(log) = %d
S 1 28 14 1214 Tx IQ verifyCalibrationResults():Energy exceeds max TH = %d status = %d
S 1 28 14 1231 Tx IQ verifyCalibrationResults(): Single bin verify Run Time = %d
S 1 28 14 1256 Assert in file: "TxIQMismatchClbrHndlr.c" in line: 1256
S 1 28 14 1260 Verify. a = %d b = %d
S 1 28 14 1264 Verify. tx ant: %d. rx ant: %d. II: %d QQ: %d IQ: %d
S 1 28 14 1271 Verify. IMR(dB) = %d
S 1 28 14 1284 Tx IQ verifyCalibrationResults():Energy exceeds max TH = %d status = %d
S 1 28 14 1301 Tx IQ verifyCalibrationResults(): Single bin verify Run Time = %d
S 1 28 14 1440 Tx IQ fixFailedBins(): Can't fix bins - calibration of all bins in range failed !!!
S 1 28 14 1456 Tx IQ fixFailedBins():Minimal Coefficient Values: bin=%d a=%d, b=%d
S 1 28 14 1467 Tx IQ fixFailedBins(): Failed bins %d, Fixed bins %d
S 1 28 14 1487 Tx IQ fixFailedBins(): Range sign %d, Run Time = %d
S 1 28 14 1601 Tx IQ calcInterpolatedCoefficients(): Interpolation between 2 bins [0,1] Run Time = %d
S 1 28 14 1644 Assert in file: "TxIQMismatchClbrHndlr.c" in line: 1644
S 1 28 14 1751 TxIQClbr_StoreResults(): CB mode %d
S 1 28 14 1772 TxIQClbr_StoreResults(): binIndex %d a=%d b=%d
S 1 28 14 1784 TxIQClbr_StoreResults(): binIndex %d a=%d b=%d
S 1 28 14 1929 Assert in file: "TxIQMismatchClbrHndlr.c" in line: 1929
S 1 28 14 1952 Assert in file: "TxIQMismatchClbrHndlr.c" in line: 1952
S 1 28 14 1970 ant: %d bin: %d a_k: %d b_k: %d
S 1 28 14 1985 x: %d, p/2: %d, e: %d
S 1 28 14 2000 F00: %d, F01: %d, F10: %d, F11: %d
S 1 28 14 2017 e %d sqrte %d ret %d
S 1 28 17 32 Assert in file: "CalibrationHandlerUtils.c" in line: 32
S 1 28 18 353 Load Store event: LOAD_STORE_EVENT_TRIGGER_LOAD. current state: %d
S 1 28 18 362 Load Store event: LOAD_STORE_EVENT_DMA_DONE. current state: %d
S 1 28 18 371 Load Store event: LOAD_STORE_EVENT_TRIGGER_STORE. current state: %d
S 1 28 18 424 Assert in file: "CalibrationManager.c" in line: 424
S 1 28 18 439 setLoadStoreSmState. state: %d
S 1 28 18 556 ClbrMngr_RunOnlineCalibration
S 1 28 18 559 Assert in file: "CalibrationManager.c" in line: 559
S 1 28 18 578 ClbrMngr_RunOfflineCalibration
S 1 28 18 590 SWITCH TYPE %d ++++++++ 
S 1 28 18 614 BITMAP BEFORE m_curOfflineProcBitmap = %d
S 1 28 18 629 Assert in file: "CalibrationManager.c" in line: 629
S 1 28 18 668 Assert in file: "CalibrationManager.c" in line: 668
S 1 28 18 687 CM_STATISTICS_ONLINE_CAL_NET_DURATION %d proc %d
S 1 28 18 689 Assert in file: "CalibrationManager.c" in line: 689
S 1 28 18 788 ClbrMngr_HandleCalibrateProcessStart
S 1 28 18 833 ClbrMngr_CalibrateChannelDone
S 1 28 18 858 Fatal Error in file: "CalibrationManager.c"; Fatal Print: Calibration WD Timer Expired
S 1 30 1 61 Assert in file: "efuseAccess.c" in line: 61
S 1 30 1 62 Assert in file: "efuseAccess.c" in line: 62
S 1 30 1 110 Assert in file: "efuseAccess.c" in line: 110
S 1 29 14 335 Assert in file: "PhyDriver.c" in line: 335
S 1 29 14 345 Fatal Error in file: "PhyDriver.c"; Fatal Print: MIPS halt done
S 1 29 14 466 PhyDrv_ReleaseSWreset
S 1 29 14 655 PhyDrv_DisableBB
S 1 29 14 662 PhyDrv_EnableBB
S 1 29 14 737 Assert in file: "PhyDriver.c" in line: 737
S 1 29 14 761 Fatal Error in file: "PhyDriver.c"; Fatal Print: PHY DRV Get TCR All
S 1 29 14 811 Assert in file: "PhyDriver.c" in line: 811
S 1 29 14 842 Assert in file: "PhyDriver.c" in line: 842
S 1 29 14 889 Assert in file: "PhyDriver.c" in line: 889
S 1 29 14 991 ERROR 1 !!! DUT_SetIfsValue, spacingUsec:%d, m_phyDelays[PHY_DID_TIM_SLOT_TIMER]:%d, m_phyDelays[PHY_DID_SIFS]:%d
S 1 29 14 996 ERROR 2 !!! DUT_SetIfsValue, spacingUsec:%d, m_phyDelays[PHY_DID_SIFS]:%d
S 1 29 14 1060 Assert in file: "PhyDriver.c" in line: 1060
S 1 29 14 1161 Assert in file: "PhyDriver.c" in line: 1161
S 1 29 14 1162 Assert in file: "PhyDriver.c" in line: 1162
S 1 29 14 1170 Assert in file: "PhyDriver.c" in line: 1170
S 1 29 14 1171 Assert in file: "PhyDriver.c" in line: 1171
S 1 29 14 1199 Fatal Error in file: "PhyDriver.c"; Fatal Print: WD(phy) interrupt occured
S 1 29 14 1340 Assert in file: "PhyDriver.c" in line: 1340
S 1 29 14 1413 Assert in file: "PhyDriver.c" in line: 1413
S 1 29 14 1447 PhyDrvInterfererDetection_FlushContinuousInterfererDetectionFifo index = %d continuousInterfererSample = %d 
S 1 29 14 1635 Assert in file: "PhyDriver.c" in line: 1635
S 1 29 14 1666 Assert in file: "PhyDriver.c" in line: 1666
S 1 29 14 1695 Assert in file: "PhyDriver.c" in line: 1695
S 1 29 15 121 Assert in file: "PhyTestBus.c" in line: 121
S 1 29 15 141 Assert in file: "PhyTestBus.c" in line: 141
S 1 29 15 165 Fatal Error in file: "PhyTestBus.c"; Fatal Print: PhyTestBus_Read, illegal case
S 1 29 22 217 Assert in file: "PSD.c" in line: 217
S 1 29 22 292 Assert in file: "PSD.c" in line: 292
S 1 29 22 303 Assert in file: "PSD.c" in line: 303
S 1 29 22 395 Assert in file: "PSD.c" in line: 395
S 1 29 22 431 Assert in file: "PSD.c" in line: 431
S 1 29 22 472 Assert in file: "PSD.c" in line: 472
S 1 29 22 512 Assert in file: "PSD.c" in line: 512
S 1 29 22 591 Assert in file: "PSD.c" in line: 591
S 1 29 22 592 Assert in file: "PSD.c" in line: 592
S 1 29 22 630 Assert in file: "PSD.c" in line: 630
S 1 29 22 677 Assert in file: "PSD.c" in line: 677
S 1 29 22 1048 Assert in file: "PSD.c" in line: 1048
S 1 38 1 144 Assert in file: "RadarDetection.c" in line: 144
S 1 38 1 192 Assert in file: "RadarDetection.c" in line: 192
S 1 38 1 235 Assert in file: "RadarDetection.c" in line: 235
S 1 38 1 269 Assert in file: "RadarDetection.c" in line: 269
S 1 38 1 313 Assert in file: "RadarDetection.c" in line: 313
S 1 38 1 388 Assert in file: "RadarDetection.c" in line: 388
S 1 38 1 393 Assert in file: "RadarDetection.c" in line: 393
S 1 38 1 446 Assert in file: "RadarDetection.c" in line: 446
S 1 38 1 532 Assert in file: "RadarDetection.c" in line: 532
S 1 38 1 555 Assert in file: "RadarDetection.c" in line: 555
S 1 38 1 659 Assert in file: "RadarDetection.c" in line: 659
S 1 38 1 660 Assert in file: "RadarDetection.c" in line: 660
S 1 38 1 668 Assert in file: "RadarDetection.c" in line: 668
S 1 38 1 672 Assert in file: "RadarDetection.c" in line: 672
S 1 38 1 735 Assert in file: "RadarDetection.c" in line: 735
S 1 38 1 905 Assert in file: "RadarDetection.c" in line: 905
S 1 38 1 906 Assert in file: "RadarDetection.c" in line: 906
S 1 42 2 230 Assert in file: "BwAdaptation.c" in line: 230
S 1 42 2 259 Assert in file: "BwAdaptation.c" in line: 259
S 1 42 2 362 Fatal Error in file: "BwAdaptation.c"; Fatal Print: BwSetNextProbingPoint
S 1 42 2 372 Assert in file: "BwAdaptation.c" in line: 372
S 1 42 2 392 Fatal Error in file: "BwAdaptation.c"; Fatal Print: BwSetNextProbingPoint - No probing should be done if BW loop is not activate
S 1 42 18 95 CddAddSta: %d cddIndex: %d
S 1 42 18 135 non effective loop
S 1 42 18 191 CddProcessFeedback, workingPointPer = %d, slowProbingPointPer = %d
S 1 42 18 217 PB is better than WP - change WP!
S 1 42 18 245 CddProcessFeedback - SET RATE + 1
S 1 42 18 300 validRate: %d antennaCount: %d stbc: %d
S 1 42 18 320 CddStaNumOfAntsIsChanged: antCount %d
S 1 42 18 389 nextPermutation: 0x%x
S 1 42 18 397 cddIndex: %d
S 1 42 18 444 setCddInStaTcr. cddAnt1: %d cddAnt2: %d cddAnt3: %d
S 1 42 18 468 setCddValues. cddAnt1 %d, cddAnt2 %d cddAnt3 %d
S 1 42 18 483 setCddFixedValues. cddAnt1 %d, cddAnt2 %d cddAnt3 %d
S 1 42 18 494 getPermutation. antCount%d
S 1 42 18 496 Assert in file: "CDD.c" in line: 496
S 1 42 18 497 Assert in file: "CDD.c" in line: 497
S 1 42 18 519 tcrCddAnt1: %d tcrCddAnt2: %d tcrCddAnt3: %d
S 1 42 18 528 sameAsWorkingPoint = %d
S 1 42 12 120 Assert in file: "LinkAdaptation_Tests.c" in line: 120
S 1 42 12 230 Assert in file: "LinkAdaptation_Tests.c" in line: 230
S 1 42 12 302 Assert in file: "LinkAdaptation_Tests.c" in line: 302
S 1 42 12 359 Assert in file: "LinkAdaptation_Tests.c" in line: 359
S 1 42 1 190 Assert in file: "AlphaFilter.c" in line: 190
S 1 28 16 344 Assert in file: "CalibrationHandler.c" in line: 344
S 1 28 16 352 Assert in file: "CalibrationHandler.c" in line: 352
S 1 28 16 375 Calibrating...
S 1 28 16 536 Assert in file: "CalibrationHandler.c" in line: 536
S 1 28 16 551 runCalibration. clbrType: %d dataStoreState: %d
S 1 28 16 570 runCalibration. proc %d
S 1 28 16 573 Assert in file: "CalibrationHandler.c" in line: 573
S 1 28 16 586 Calibrations fragmented
S 1 28 16 590 Finished Calibrations
S 1 28 16 690 CalibrationHandler getUpdateOfflineStatus(). StatusVector = 0x%x %d
S 1 10 0 228 BssManager_StartActivateProcess
S 1 10 0 230 Assert in file: "BSSmanager.c" in line: 230
S 1 10 0 263 Assert in file: "BSSmanager.c" in line: 263
S 1 10 0 390 Assert in file: "BSSmanager.c" in line: 390
S 1 10 0 418 Assert in file: "BSSmanager.c" in line: 418
S 1 11 0 154 channelSwitchManager_ChangeState from %d, to %d
S 1 11 0 195 Assert in file: "ChannelSwitchManager.c" in line: 195
S 1 11 0 202 [channelSwitchManager_SetChannelRequest] CHANNEL_SWITCH_MANAGER_STATE_IDLE, channelSwitchManagerParams.pUmSetChannelParams->switch_type=%d
S 1 11 0 225 [channelSwitchManager_SetChannelRequest] in RSSI 0
S 1 11 0 256 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: illegal switch type
S 1 11 0 262 [channelSwitchManager_SetChannelRequest] in RSSI 1
S 1 11 0 331 Assert in file: "ChannelSwitchManager.c" in line: 331
S 1 11 0 363 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Channel Switch Manager: illegal type in current state
S 1 11 0 368 Assert in file: "ChannelSwitchManager.c" in line: 368
S 1 11 0 383 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Channel Switch Manager: illegal event in current state
S 1 11 0 415 [channelSwitchManager_ProcessStartConfirm] channelSwitchManagerParams.state = %d, channelSwitchManagerParams.pUmSetChannelParams->switch_type = %d
S 1 11 0 417 Assert in file: "ChannelSwitchManager.c" in line: 417
S 1 11 0 443 [channelSwitchManager_ProcessStartConfirm] send message to HDK
S 1 11 0 485 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: illegal switch type
S 1 11 0 489 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Channel Switch Manager: illegal event in current state
S 1 11 0 520 state: %d, event: Tx Queue Lock Confirm
S 1 11 0 592 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Channel Switch Manager: illegal event in current state
S 1 11 0 618 [channelSwitchManager_ProcessFinishConfirm] channelSwitchManagerParams.state = %d
S 1 11 0 631 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Channel Switch Manager: illegal event in current state
S 1 11 0 671 [channelSwitchManager_SetChannelConfirm] channelSwitchManagerParams.state = %d
S 1 11 0 680 [channelSwitchManager_SetChannelConfirm] CHANNEL_SWITCH_MANAGER_STATE_WAIT_FOR_SET_CHANNEL_CFM_FROM_HDK, channelSwitchManagerParams.pUmSetChannelParams->switch_type = %d
S 1 11 0 713 [channelSwitchManager_SetChannelConfirm] in ST_NORMAL_AFTER_RSSI
S 1 11 0 714 [channelSwitchManager_SetChannelConfirm], pUmSetChannelParamsLocal->u16SID = %d, pRssiParams->vapId = %d
S 1 11 0 718 [channelSwitchManager_SetChannelConfirm] in ST_NORMAL_AFTER_RSSI, before Process Manager Resume all
S 1 11 0 732 [channelSwitchManager_SetChannelConfirm], pUmSetChannelParamsLocal->u16SID = %d, pRssiParams->vapId = %d
S 1 11 0 733 [channelSwitchManager_SetChannelConfirm] in ST_RSSI
S 1 11 0 799 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: illegal switch type
S 1 11 0 805 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Channel Switch Manager: illegal event in current state
S 1 11 0 832 state: %d, event: Tx Resume Confirm
S 1 11 0 851 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Channel Switch Manager: illegal event in current state
S 1 11 0 877 state: %d, event: Rx Resume Confirm
S 1 11 0 897 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Channel Switch Manager: illegal event in current state
S 1 11 0 924 state: %d, event: Tx Pause Confirm
S 1 11 0 956 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Channel Switch Manager: illegal event in current state
S 1 11 0 984 state: %d, event: TX Pause VAP Confirm
S 1 11 0 1050 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Channel Switch Manager: illegal event in current state
S 1 11 0 1079 state: %d, event: Rx Pause Confirm
S 1 11 0 1121 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Channel Switch Manager: illegal event in current state
S 1 11 0 1149 state: %d, event: Timer Expired
S 1 11 0 1180 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Channel Switch Manager: illegal event in current state
S 1 11 0 1209 state: %d, event: Beacon Add Csa Ie Confirm
S 1 11 0 1237 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Channel Switch Manager: illegal event in current state
S 1 11 0 1267 state: %d, event: CSA Beacon Done Indication
S 1 11 0 1325 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Channel Switch Manager: illegal event in current state
S 1 11 0 1354 state: %d, event: Stop CSA Beacons Confirm
S 1 11 0 1393 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Channel Switch Manager: illegal event in current state
S 1 11 0 1510 channelSwitchManager_VapManagerRegistrationEventAddVap, state: %d, event: Vap Manager Registration Event Add Vap
S 1 11 0 1512 Assert in file: "ChannelSwitchManager.c" in line: 1512
S 1 11 0 1555 state: %d, event: Vap Manager Registration Event Post Remove Vap
S 1 11 0 1557 Assert in file: "ChannelSwitchManager.c" in line: 1557
S 1 11 0 1596 state: %d, event: Csa Manager Start Tx Cfm
S 1 11 0 1657 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: channelSwitchManager_ProcessInterruptedIndication
S 1 11 0 1685 state: %d, event: Csa Manager Stop Tx Cfm
S 1 11 0 1768 [channelSwitchManager_SendConfirmationToHost] channelSwitchManagerParams.pUmSetChannelParams->rssi[%d] = %d
S 1 11 0 1777 [channelSwitchManager_SendConfirmationToHost] --------------------------end]
S 1 11 0 1806 Assert in file: "ChannelSwitchManager.c" in line: 1806
S 1 11 0 1844 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Utils_GetPrimaryChannel: 80+80 not supported
S 1 11 0 1847 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Utils_GetPrimaryChannel: Illegal rate
S 1 11 0 1895 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Utils_GetSecondayChannelOffset: 80+80 not supported
S 1 11 0 1898 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Utils_GetSecondayChannelOffset: Illegal rate
S 1 11 0 1938 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: ChannelSwitchManager_GetChannelWidth: not supported
S 1 11 0 1941 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: ChannelSwitchManager_GetChannelWidth: not supported
S 1 11 0 1944 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: ChannelSwitchManager_GetChannelWidth: Illegal channel width
S 1 11 0 1987 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: ChannelSwitchManager_GetCenterFreq0Idx: not supported
S 1 11 0 1990 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: ChannelSwitchManager_GetCenterFreq0Idx: not supported
S 1 11 0 1993 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: ChannelSwitchManager_GetCenterFreq0Idx: Illegal channel width
S 1 28 13 679 Assert in file: "TpcClbrHndlr.c" in line: 679
S 1 28 13 680 Assert in file: "TpcClbrHndlr.c" in line: 680
S 1 29 0 1098 Assert in file: "Afe.c" in line: 1098
S 1 29 0 1131 Assert in file: "Afe.c" in line: 1131
S 1 29 0 1293 Assert in file: "Afe.c" in line: 1293
S 1 29 0 1438 Assert in file: "Afe.c" in line: 1438
S 1 29 4 854 Assert in file: "Afe.c" in line: 854
S 1 29 4 1383 Assert in file: "Afe.c" in line: 1383
S 1 29 4 1524 Assert in file: "Afe.c" in line: 1524
S 1 30 4 852 Assert in file: "Afe.c" in line: 852
S 1 30 4 1378 Assert in file: "Afe.c" in line: 1378
S 1 30 4 1519 Assert in file: "Afe.c" in line: 1519
S 1 32 0 315 [hostInterfaceRingsSetAtfBufferEnable] stationId:%d
S 1 32 0 344 [hostInterfaceRingsSetAtfBufferDisable]
S 1 32 0 388 Assert in file: "HostInterface.c" in line: 388
S 1 32 0 390 Assert in file: "HostInterface.c" in line: 390
S 1 32 0 396 HostInterface_RestrictedAcMsg: User indicates that Restricted AC should not be used by HOST I/F TASK. QoS TASK shall use it.
S 1 32 0 786 Assert in file: "HostInterface.c" in line: 786
S 1 32 0 817 Fatal Error in file: "HostInterface.c"; Fatal Print: Error buffer descriptor in FIFO!
S 1 32 0 839 Assert in file: "HostInterface.c" in line: 839
S 1 32 0 918 Ts Manager, Send Confirmation, Client %d, SID %d
S 1 32 0 1035 Assert in file: "HostInterface.c" in line: 1035
S 1 32 0 1038 Assert in file: "HostInterface.c" in line: 1038
S 1 32 0 1050 Assert in file: "HostInterface.c" in line: 1050
S 1 32 0 1344 Assert in file: "HostInterface.c" in line: 1344
S 1 32 0 1353 Assert in file: "HostInterface.c" in line: 1353
S 1 32 0 1390 Fatal Error in file: "HostInterface.c"; Fatal Print: Error buffer descriptor in FIFO!
S 1 32 0 1480 Assert in file: "HostInterface.c" in line: 1480
S 1 32 0 1519 Assert in file: "HostInterface.c" in line: 1519
S 1 32 0 1553 HostInterface_GlobalDb.atf_AgeingEnable %d ttlCount %d, HostInterface_GlobalDb.atf_End_of_interval_ttl %d, HostInterface_GlobalDb.atf_AgeingTtlCriteria %d
S 1 32 0 1554 willAged%d
S 1 7 6 371 Assert in file: "HwQManager.c" in line: 371
S 1 7 6 399 Assert in file: "HwQManager.c" in line: 399
S 1 7 6 429 Assert in file: "HwQManager.c" in line: 429
S 1 7 6 458 Assert in file: "HwQManager.c" in line: 458
S 1 7 6 487 Assert in file: "HwQManager.c" in line: 487
S 1 7 6 516 Assert in file: "HwQManager.c" in line: 516
S 1 7 6 546 Assert in file: "HwQManager.c" in line: 546
S 1 7 6 574 Assert in file: "HwQManager.c" in line: 574
S 1 7 8 191 Assert in file: "HwQManager.c" in line: 191
S 1 7 8 194 Assert in file: "HwQManager.c" in line: 194
S 1 7 8 200 Assert in file: "HwQManager.c" in line: 200
S 1 7 8 262 Assert in file: "HwQManager.c" in line: 262
S 1 7 8 691 HwQManager_ErrorEvent: 0x%X 
S 1 7 8 693 Fatal Error in file: "HwQManager.c"; Fatal Print: HW Q Manager Error Event
S 1 7 8 720 Assert in file: "HwQManager.c" in line: 720
S 1 7 8 751 Assert in file: "HwQManager.c" in line: 751
S 1 7 8 785 Assert in file: "HwQManager.c" in line: 785
S 1 31 2 162 Fatal Error in file: "RxHandler.c"; Fatal Print: RX Handler Error Start
S 1 31 2 178 Fatal Error in file: "RxHandler.c"; Fatal Print: Unsupported Message ID
S 1 31 2 203 Fatal Error in file: "RxHandler.c"; Fatal Print: Unsupported Message ID
S 1 31 2 215 Fatal Error in file: "RxHandler.c"; Fatal Print: RX Handler Unknown Event
S 1 31 2 390 Assert in file: "RxHandler.c" in line: 390
S 1 31 2 424 Assert in file: "RxHandler.c" in line: 424
S 1 31 2 475 Assert in file: "RxHandler.c" in line: 475
S 1 45 0 117 Assert in file: "System_Main.c" in line: 117
S 1 83 0 148 Assert in file: "TxMulticastHandler.c" in line: 148
S 1 83 0 149 Assert in file: "TxMulticastHandler.c" in line: 149
S 1 83 0 375 Assert in file: "TxMulticastHandler.c" in line: 375
S 1 83 0 376 Assert in file: "TxMulticastHandler.c" in line: 376
S 1 83 0 377 Assert in file: "TxMulticastHandler.c" in line: 377
S 1 83 0 378 Assert in file: "TxMulticastHandler.c" in line: 378
S 1 83 0 418 Assert in file: "TxMulticastHandler.c" in line: 418
S 1 83 0 419 Assert in file: "TxMulticastHandler.c" in line: 419
S 1 83 0 420 Assert in file: "TxMulticastHandler.c" in line: 420
S 1 83 0 421 Assert in file: "TxMulticastHandler.c" in line: 421
S 1 83 0 460 Assert in file: "TxMulticastHandler.c" in line: 460
S 1 83 0 461 Assert in file: "TxMulticastHandler.c" in line: 461
S 1 83 0 587 Assert in file: "TxMulticastHandler.c" in line: 587
S 1 51 0 153 Assert in file: "PacManager.c" in line: 153
S 1 51 0 187 [PacManagerSetRxd]---------------------------------------end]
S 1 51 0 301 [PacManagerNormalActivation] -------------------------------------------end]
S 1 51 0 339 [PacManagerRssiActivation]----------------------------------end]
S 1 51 0 382 -------- RXF configured for Sniffer --------
S 1 51 0 387 -------- RXD configured for Sniffer --------
S 1 51 0 393 -------- RXC reserved storage size configured for Sniffer --------
S 1 51 0 398 -------- RXC Rssi abort disabled for Sniffer --------
S 1 51 0 402 Assert in file: "PacManager.c" in line: 402
S 1 51 0 404 -------- RXC configured correctly --------
S 1 51 0 548 Assert in file: "PacManager.c" in line: 548
S 1 51 0 615 Assert in file: "PacManager.c" in line: 615
S 1 51 0 633 Assert in file: "PacManager.c" in line: 633
S 1 8 3 188 beaconHandlerDeactivateHw for vap:%d
S 1 8 3 220 beaconHandlerSendTemplateWasSetIndication for vap:%d
S 1 8 3 297 beaconHandlerUpdateIEsPdList for vap:%d
S 1 8 3 668 Assert in file: "BeaconHandler.c" in line: 668
S 1 8 3 696 beaconHandlerUpdateIEsPdList Vap Id:%d is active so calling Locker
S 1 8 3 704 beaconHandlerUpdateIEsPdList Vap Id:%d is inactive sending template was set indication
S 1 8 3 742 BeaconHandler_AddVap for vap:%d
S 1 8 3 843 beaconHandlerDeactivateBeacon for vap:%d
S 1 8 3 1042 Assert in file: "BeaconHandler.c" in line: 1042
S 1 8 3 1047 Assert in file: "BeaconHandler.c" in line: 1047
S 1 8 3 1052 Assert in file: "BeaconHandler.c" in line: 1052
S 1 8 3 1057 Assert in file: "BeaconHandler.c" in line: 1057
S 1 8 3 1188 Assert in file: "BeaconHandler.c" in line: 1188
S 1 8 5 172 Beacon CSA Manager changed from %d to %d
S 1 8 5 398 Assert in file: "Beacon_CsaManager.c" in line: 398
S 1 8 5 658 Fatal Error in file: "Beacon_CsaManager.c"; Fatal Print: Beacon CSA Manager Fatal
S 1 8 5 690 Assert in file: "Beacon_CsaManager.c" in line: 690
S 1 8 5 721 Assert in file: "Beacon_CsaManager.c" in line: 721
S 1 10 2 271 BssManager_VapManager_SetState, vapId:%d, vapManagerNewState:%d
S 1 10 2 299 Assert in file: "BSSmanager_VapManager.c" in line: 299
S 1 10 2 300 BssManager_VapManager_AddVap of vapId:%d
S 1 10 2 335 BssManager_VapManager_StartAddVaptProcess of vapId:%d
S 1 10 2 380 Assert in file: "BSSmanager_VapManager.c" in line: 380
S 1 10 2 384 Assert in file: "BSSmanager_VapManager.c" in line: 384
S 1 10 2 421 Assert in file: "BSSmanager_VapManager.c" in line: 421
S 1 10 2 460 BssManager_VapManager_StartSetBssProcess of vapId:%d
S 1 10 2 468 Assert in file: "BSSmanager_VapManager.c" in line: 468
S 1 10 2 513 Assert in file: "BSSmanager_VapManager.c" in line: 513
S 1 10 2 520 Assert in file: "BSSmanager_VapManager.c" in line: 520
S 1 10 2 584 BssManager_VapManager_StartSetWmmParamsProcess of vapId:%d
S 1 10 2 595 Assert in file: "BSSmanager_VapManager.c" in line: 595
S 1 10 2 630 Assert in file: "BSSmanager_VapManager.c" in line: 630
S 1 10 2 633 BssManager_VapManager_FinalizeSetWmmParamsProcess of vapId:%d
S 1 10 2 713 BssManager_VapManager_StartRemoveVapProcess, vapId:%d
S 1 10 2 753 Assert in file: "BSSmanager_VapManager.c" in line: 753
S 1 10 2 756 BssManager_VapManager_FinalizeRemoveVapProcess of vapId:%d
S 1 10 2 759 Assert in file: "BSSmanager_VapManager.c" in line: 759
S 1 10 2 796 Assert in file: "BSSmanager_VapManager.c" in line: 796
S 1 10 2 839 Assert in file: "BSSmanager_VapManager.c" in line: 839
S 1 10 2 840 Assert in file: "BSSmanager_VapManager.c" in line: 840
S 1 10 2 877 BssManager_VapManager_EventHandlerConfirm, got cfm from taskID:%d
S 1 10 2 878 Assert in file: "BSSmanager_VapManager.c" in line: 878
S 1 10 2 879 Assert in file: "BSSmanager_VapManager.c" in line: 879
S 1 10 2 1090 Assert in file: "BSSmanager_VapManager.c" in line: 1090
S 1 10 2 1157 Assert in file: "BSSmanager_VapManager.c" in line: 1157
S 1 10 2 1163 Assert in file: "BSSmanager_VapManager.c" in line: 1163
S 1 10 2 1169 Assert in file: "BSSmanager_VapManager.c" in line: 1169
S 1 10 2 1175 Assert in file: "BSSmanager_VapManager.c" in line: 1175
S 1 10 2 1188 Assert in file: "BSSmanager_VapManager.c" in line: 1188
S 1 10 2 1194 Assert in file: "BSSmanager_VapManager.c" in line: 1194
S 1 10 2 1200 Assert in file: "BSSmanager_VapManager.c" in line: 1200
S 1 10 2 1202 Assert in file: "BSSmanager_VapManager.c" in line: 1202
S 1 10 2 1207 Assert in file: "BSSmanager_VapManager.c" in line: 1207
S 1 10 2 1213 Assert in file: "BSSmanager_VapManager.c" in line: 1213
S 1 10 2 1218 Assert in file: "BSSmanager_VapManager.c" in line: 1218
S 1 7 3 181 Assert in file: "HwErrors.c" in line: 181
S 1 7 3 198 hwErrorsRxcRxBufferOverflow rxBufferOverflowDroppedMpdus = %d
S 1 7 3 250 Assert in file: "HwErrors.c" in line: 250
S 1 7 3 267 Assert in file: "HwErrors.c" in line: 267
S 1 7 3 281 Assert in file: "HwErrors.c" in line: 281
S 1 7 3 347 Fatal Error in file: "HwErrors.c"; Fatal Print: hwErrorsRxEof
S 1 7 3 371 Fatal Error in file: "HwErrors.c"; Fatal Print: hwErrorsRxAggr
S 1 7 3 403 Assert in file: "HwErrors.c" in line: 403
S 1 7 3 462 Fatal Error in file: "HwErrors.c"; Fatal Print: hwErrorsTxSelector
S 1 7 3 496 Assert in file: "HwErrors.c" in line: 496
S 1 7 3 519 Assert in file: "HwErrors.c" in line: 519
S 1 7 3 534 Assert in file: "HwErrors.c" in line: 534
S 1 7 3 548 Assert in file: "HwErrors.c" in line: 548
S 1 7 3 562 Assert in file: "HwErrors.c" in line: 562
S 1 7 3 575 Assert in file: "HwErrors.c" in line: 575
S 1 7 3 589 Assert in file: "HwErrors.c" in line: 589
S 1 7 3 608 Fatal Error in file: "HwErrors.c"; Fatal Print: hwErrorsDelineatorFifoOverflow
S 1 7 3 691 Assert in file: "HwErrors.c" in line: 691
S 1 7 3 695 isr_HwErrors errorIndex %d num of errors %d
S 1 42 16 153 linkAdaptationStateMachine: la_state %d, event %d
S 1 42 16 402 waitForNextProbeCycleStateBaTxReportEvent- waitForNextProbeCycleStateBaTxReportEvent == %d
S 1 42 16 1139 Assert in file: "LinkAdaptation_StateMachine.c" in line: 1139
S 1 42 16 1190 Probe response ignored after state aging, stationIndex = %d
S 1 42 16 1222 Assert in file: "LinkAdaptation_StateMachine.c" in line: 1222
S 1 42 16 1248 updateOverridePendingDb. override %d value %d
S 1 42 16 1268 Assert in file: "LinkAdaptation_StateMachine.c" in line: 1268
S 1 42 16 1337 executeParamOverride, staIdx: %d
S 1 42 16 1515 Fatal Error in file: "LinkAdaptation_StateMachine.c"; Fatal Print: laStateMachineProcessBaaReport
S 1 42 16 1521 laStateMachineProcessBaaReport, event %d
S 1 42 16 1526 laStateMachineProcessBaaReport, event %d
S 1 42 16 1554 laStateMachineProcessSequencerReport, event %d
S 1 42 16 1559 laStateMachineProcessSequencerReport, event %d
S 1 45 5 217 Assert in file: "lmtimerUtility.c" in line: 217
S 1 45 5 265 Assert in file: "lmtimerUtility.c" in line: 265
S 1 42 0 145 AntennaSelectionAddSta. ActivatedAntennasCount %d antSelMask %d
S 1 42 0 193 AntennaSelectionSetNextProbingPoint
S 1 42 0 205 AntennaSelectionSetNextProbingPoint. nextprobingMask 0x%x
S 1 42 0 261 AntennaSelectionProcessFeedback
S 1 42 0 304 AntennaSelectionProcessFeedback. PB is better than WP - change WP!
S 1 42 0 332 AntennaSelectionProcessFeedback - SET RATE + 1
S 1 42 0 482 setAntSelParams. numOfAntennas %d isLimitingState %d validAntennas %d 
S 1 42 0 507 getPermutation. antennasIndex %d permutationIndex %d 
S 1 42 0 509 Assert in file: "AntennaSelection.c" in line: 509
S 1 42 0 510 Assert in file: "AntennaSelection.c" in line: 510
S 1 42 0 552 increaseAntSelectionProbingIndices. nextPermutation 0x%x antennaIndex %d permutationIndex %d 
S 1 42 0 600 increaseAntSelectionProbingIndices. validPermutationFound %d ActivatedAntennasBitmap 0x%x 
S 1 42 0 635 Assert in file: "AntennaSelection.c" in line: 635
S 1 42 0 684 Assert in file: "AntennaSelection.c" in line: 684
S 1 42 0 743 Assert in file: "AntennaSelection.c" in line: 743
S 1 42 0 828 Assert in file: "AntennaSelection.c" in line: 828
S 1 42 0 1104 setAntSelectionInStaTcr 0x%x isProbing: %d
S 1 42 0 1138 AntSelectionModificationFunc.numOfAntsPp %d, change also CDD
S 1 42 0 1249 AntennaSelectionBfModeIsChanged. newBfMode %d
S 1 79 2 409 Fatal Error in file: "TsManagerRecipient.c"; Fatal Print: TS Manager Recipient Fatal
S 1 79 2 439 TS Manager Recipient SID %d, TID %d, Change State from %d to %d
S 1 79 2 922 tsManagerRecipientAddbaRequestReceivedInClosed stationIndex %d tid %d 
S 1 79 2 956 tsManagerRecipientAddbaRequestReceivedInOpeningthe s
S 1 79 2 963 tsManagerRecipientAddbaRequestReceivedInOpeningthe same dialog token %d
S 1 79 2 1004 tsManagerRecipientAddbaRequestReceivedInOpenedthe s
S 1 79 2 1007 tsManagerRecipientAddbaRequestReceivedInOpenedthe same dialog token %d
S 1 79 2 1149 tsManagerRecipientDelbaReceivedInOpeningWaitingForPd remove status %d
S 1 79 2 1194 tsManagerRecipientDelbaReceivedInOpening 
S 1 79 2 1229 tsManagerRecipientDelbaReceivedInOpened 
S 1 79 2 1358 tsManagerRecipientAddbaResponseConfirmedInOpening station index %d tid % d
S 1 79 2 1425 tsManagerRecipientAddbaResponseConfirmedInClosing station index %d tid % d
S 1 79 2 1492 tsManagerRecipientDelbaConfirmedInClosing station index %d tid % d
S 1 79 2 1560 tsManagerRecipientAddbaResponseConfirmedInClosingWaitingForConfirmation 
S 1 79 2 1593 tsManagerRecipientIllegalPacketReceivedInClosed station index %d tid % d
S 1 79 2 1633 tsManagerRecipientIllegalPacketReceivedInClosedWaitingForMessage station index %d tid % d
S 1 79 2 1671 tsManagerRecipientIllegalPacketReceivedInOpeningWaitingForPd station index %d tid % d
S 1 79 2 1713 tsManagerRecipientPdAllocatedInClosedWaitingForMessage station index %d tid % d
S 1 79 2 1750 tsManagerRecipientPdAllocatedInOpeningWaitingForPd station index %d tid % d
S 1 79 2 1827 tsManagerRecipientPdAllocatedInClosingWaitingForPdForDelba station index %d tid % d
S 1 79 2 1867 tsManagerRecipientPdAllocatedInClosingWaitingForPdForAddbaResponse station index %d tid % d
S 1 79 2 1942 tsManagerRecipientBarReceivedInClosed station index %d tid % d
S 1 79 2 1980 tsManagerRecipientBarReceivedInClosedWaitingForMessage station index %d tid % d
S 1 79 2 2018 tsManagerRecipientBarReceivedInOpeningWaitingForPd station index %d tid % d
S 1 79 2 2055 tsManagerRecipientBarReceivedInOpening station index %d tid % d
S 1 79 2 2086 tsManagerRecipientBarReceivedInOpened station index %d tid % d
S 1 79 2 2117 tsManagerRecipientBarReceivedInClosing station index %d tid % d
S 1 79 2 2149 tsManagerRecipientBarReceivedInClosingWaitingForPdForDelba station index %d tid % d
S 1 79 2 2181 tsManagerRecipientBarReceivedInClosingWaitingForPdForDelba station index %d tid % d
S 1 79 2 2436 tsManagerRecipientCloseBaAgreement stationIndex %d tid %d 
S 1 79 2 2533 tsManagerRecipientProcessAddbaRequest invalid parameters 
S 1 79 2 2541 tsManagerRecipientProcessAddbaRequest invalid parameters 
S 1 79 2 2642 tsManagerRecipientProcessAddbaRequest ADDBA request declined allocation status %d
S 1 79 2 2704 Assert in file: "TsManagerRecipient.c" in line: 2704
S 1 79 2 2719 TsManagerRecipient_TimerEvent inactivity timeout delete BA agreement %d
S 1 79 2 3021 Assert in file: "TsManagerRecipient.c" in line: 3021
S 1 79 2 3220 TsManagerRecipient_BarReceived illegal BAR
S 1 79 2 3396 Assert in file: "TsManagerRecipient.c" in line: 3396
S 1 79 2 3434 TsManagerRecipient_PdAllocated stationIndex %d tid %d state %d
S 1 79 2 3771 Assert in file: "TsManagerRecipient.c" in line: 3771
S 1 79 2 3773 Assert in file: "TsManagerRecipient.c" in line: 3773
S 1 5 0 276 [printGrants] stationID:%d grant:%d
S 1 5 0 303 [printGrants] stationID:%d grant:%d
S 1 5 0 329 [printGrants] stationID:%d grant:%d
S 1 5 0 357 [printPdTypeList] PdType:%d head:%x; tail:%x
S 1 5 0 461 Assert in file: "Atf.c" in line: 461
S 1 5 0 569 Atf_Manager_setAgeing AtfDb.AgeingEnable:%d, AtfDb.AgeingTtlCriteria:%d, AtfDb.end_of_interval_ttl:%d end_of_interval_ttl:%d
S 1 5 0 705 [Atf_Manager_transition] newAtmDistributionType:%d AtfDb.AtmDistributionType: %d; newAtmAlgorithmType: %d interval:%d freeTime:%d
S 1 5 0 732 Assert in file: "Atf.c" in line: 732
S 1 5 0 750 Assert in file: "Atf.c" in line: 750
S 1 5 0 765 Assert in file: "Atf.c" in line: 765
S 1 5 0 772 [Atf_Manager_transition] NO_ERRORS
S 1 5 0 779 [Atf_Manager_transition] Error %d
S 1 5 0 785 Assert in file: "Atf.c" in line: 785
S 1 5 0 823 [Atf_Manager_ValidateStationConnected] ATF_NOT_ALL_CONNECTED_STATIONS_RECEIVED_GRANT stationId:%d
S 1 5 0 843 [Atf_Manager_ValidateStationConnected] ATF_STATION_IN_GRANT_LIST_IS_NOT_CONNECTED stationId:%d
S 1 5 0 980 [Atf_Buffering_timerExpiredMsg]
S 1 5 0 1092 Assert in file: "Atf.c" in line: 1092
S 1 5 0 1113 Assert in file: "Atf.c" in line: 1113
S 1 5 0 1145 [ATF_Manager_StaManagerSendConfirm], Send Confirmation, Client %d, SID %d
S 1 5 0 1265 [Atf_GrantCalc_dynamicWeighted] maxGrant %d; ac %d
S 1 5 0 1308 [Atf_GrantCalc_dynamicWeighted] stationID:%d sta_TXOP_limit:%d AtfShramDb.maxGrant[stationId][ATF_USED_AC]:%d
S 1 5 0 1381 [Atf_GrantCalc_staticWeighted] stationID:%d grant:%d AtfShramDb.maxGrant[stationId]:%d
S 1 5 0 1407 [Atf_Buffering_lockReqHandler] stationId:%d
S 1 5 0 1445 [Atf_Buffering_lockReq] pushToStack stationId:%d
S 1 5 0 1487 [Atf_Buffering_lockCfmMsg] ATF_INVALID_LOCK_IDX stationId:%d
S 1 5 0 1496 [Atf_Buffering_lockCfmMsg] station:%d Lock Cfm msg in wait for lock state
S 1 5 0 1508 [Atf_Buffering_lockCfmMsg] station:%d During locking got timer event
S 1 5 0 1520 [Atf_Buffering_lockCfmMsg] station:%d During locking got stop traffic
S 1 5 0 1532 Assert in file: "Atf.c" in line: 1532
S 1 5 0 1562 [Atf_Buffering_himBufferReq] station:%d 
S 1 5 0 1567 Assert in file: "Atf.c" in line: 1567
S 1 5 0 1568 Assert in file: "Atf.c" in line: 1568
S 1 5 0 1621 [Atf_Buffering_himBufferCfmHandler] stationId:%d
S 1 5 0 1633 [Atf_Buffering_himBufferCfmMsg] During locking the station:%d got timer event
S 1 5 0 1640 [Atf_Buffering_himBufferCfmMsg] During locking the station:%d got stop traffic
S 1 5 0 1669 Assert in file: "Atf.c" in line: 1669
S 1 5 0 1691 [Atf_Buffering_unbufferHim], stationId %d
S 1 5 0 1723 [Atf_Buffering_flushStationQueues] station:%d Flush start
S 1 5 0 1781 [Atf_Buffering_flushStationQueues] managements exist
S 1 5 0 1795 [Atf_Buffering_flushStationQueues] aged exist
S 1 5 0 1818 2[Atf_Buffering_flushStationQueues] AtfBufferedList[%d][%d].head:%x tail:%x
S 1 5 0 1844 [---Atf_Buffering_Unbuffer---], stationId %d
S 1 5 0 1911 [Atf_Buffering_unbufferPushBuffered] AtfBufferedList[%d][%d].head:%x tail:%x
S 1 5 0 1941 [Atf_Buffering_unbufferDropToLiberator] station:%d unbuffer drop start
S 1 5 0 1965 [Atf_Buffering_unbufferPushToQueues] station:%d unbuffer queues start
S 1 5 0 1991 [Atf_Buffering_drop_buffered], stationId %d
S 1 5 0 2036 [Atf_Manager_stopTrafficMsg] stationId:%d
S 1 5 0 2088 [Atf_Buffering_AddStaMsg] stationId:%d
S 1 5 0 2147 [---Atf_Buffering_senderStopTxMsg---], stationId %d
S 1 5 0 2171 [Atf_Buffering_PushPacketToTail] pDesc:%x
S 1 5 0 2173 Assert in file: "Atf.c" in line: 2173
S 1 5 0 2216 [Atf_Buffering_PushListToHead]
S 1 5 0 2463 Assert in file: "Atf.c" in line: 2463
S 1 5 0 2488 Assert in file: "Atf.c" in line: 2488
S 1 5 0 2493 [Atf_buffering_StaSmRun] stationId:%d event:%d currentState:%d
S 1 5 0 2603 [Atf_SetStationState] stationId: %d, state:ATF_STATION_STATE_IDLE
S 1 5 0 2608 [Atf_SetStationState] stationId: %d, state:ATF_STATION_STATIC_STATE_CONNECTED_BUFFERED
S 1 5 0 2613 [Atf_SetStationState] stationId: %d, state:ATF_STATION_STATIC_STATE_CONNECTED_UNBUFFERED
S 1 5 0 2618 [Atf_SetStationState] stationId: %d, state:ATF_STATION_STATIC_STATE_CONNECTED_WAIT_FOR_HOSTINTERFACE
S 1 5 0 2623 [Atf_SetStationState] stationId: %d, state:ATF_STATION_STATIC_STATE_CONNECTED_WAIT_FOR_HOSTINTERFACE_STOP_UNBUFFER
S 1 5 0 2628 [Atf_SetStationState] stationId: %d, state:ATF_STATION_STATIC_STATE_CONNECTED_WAIT_FOR_HOSTINTERFACE_STOP_DROP
S 1 5 0 2633 [Atf_SetStationState] stationId: %d, state:ATF_STATION_STATIC_STATE_CONNECTED_WAIT_FOR_LOCK
S 1 5 0 2638 [Atf_SetStationState] stationId: %d, state:ATF_STATION_STATIC_STATE_CONNECTED_WAIT_FOR_LOCK_STOP_UNBUFFER
S 1 5 0 2643 [Atf_SetStationState] stationId: %d, state:ATF_STATION_STATIC_STATE_CONNECTED_WAIT_FOR_LOCK_STOP_DROP
S 1 5 0 2649 [Atf_SetStationState] stationId: %d, state:%d
S 1 32 1 349 Assert in file: "HostInterfaceRings.c" in line: 349
S 1 32 1 401 Assert in file: "HostInterfaceRings.c" in line: 401
S 1 32 1 409 Assert in file: "HostInterfaceRings.c" in line: 409
S 1 32 1 410 Assert in file: "HostInterfaceRings.c" in line: 410
S 1 32 1 438 Assert in file: "HostInterfaceRings.c" in line: 438
S 1 32 1 448 Assert in file: "HostInterfaceRings.c" in line: 448
S 1 32 1 691 Assert in file: "HostInterfaceRings.c" in line: 691
S 1 32 1 921 Assert in file: "HostInterfaceRings.c" in line: 921
S 1 32 1 950 Assert in file: "HostInterfaceRings.c" in line: 950
S 1 32 1 951 Assert in file: "HostInterfaceRings.c" in line: 951
S 1 32 1 999 Assert in file: "HostInterfaceRings.c" in line: 999
S 1 32 1 1000 Assert in file: "HostInterfaceRings.c" in line: 1000
S 1 64 0 214 Assert in file: "RxHandler.c" in line: 214
S 1 64 0 251 Assert in file: "RxHandler.c" in line: 251
S 1 64 0 319 Assert in file: "RxHandler.c" in line: 319
S 1 64 0 426 Assert in file: "RxHandler.c" in line: 426
S 1 64 0 544 Frame is bigger than Max sniffer payload size (1600 bytes) and has been reduces!! Sniffer original payload size is %d
S 1 64 0 702 Assert in file: "RxHandler.c" in line: 702
S 1 64 0 893 Assert in file: "RxHandler.c" in line: 893
S 1 64 0 1542 Assert in file: "RxHandler.c" in line: 1542
S 1 64 0 1546 Assert in file: "RxHandler.c" in line: 1546
S 1 64 0 1773 Assert in file: "RxHandler.c" in line: 1773
S 1 64 0 2081 [RxHandler_CopyMetricsToMetricsFifo] trigger SW event EVENT_ID_METRICS_FIFO_NOT_EMPTY, pFifoEntry->rxPhyMetrics.geriscSpare2 = %d
S 1 64 1 790 Assert in file: "RxHandler_Decryption.c" in line: 790
S 1 64 1 937 Assert in file: "RxHandler_Decryption.c" in line: 937
S 1 64 1 1089 Assert in file: "RxHandler_Decryption.c" in line: 1089
S 1 64 1 1149 Assert in file: "RxHandler_Decryption.c" in line: 1149
S 1 64 1 1387 Assert in file: "RxHandler_Decryption.c" in line: 1387
S 1 54 6 158 Assert in file: "cipher_suite.c" in line: 158
S 1 54 6 174 Assert in file: "cipher_suite.c" in line: 174
S 1 54 6 188 Assert in file: "cipher_suite.c" in line: 188
S 1 54 6 214 Assert in file: "cipher_suite.c" in line: 214
S 1 54 6 216 Assert in file: "cipher_suite.c" in line: 216
S 1 54 3 169 SEC Manager VAP Manager, Vap %d changed from %d to %d
S 1 54 3 239 vUM_MAN_SET_KEY_REQ: u16Status:%d psMsg->header.vapId:%d
S 1 54 3 345 Assert in file: "secManager_VapManager.c" in line: 345
S 1 54 3 422 Assert in file: "secManager_VapManager.c" in line: 422
S 1 54 3 556 Fatal Error in file: "secManager_VapManager.c"; Fatal Print: SEC Manager STA Manager Fatal
S 1 54 3 624 Assert in file: "secManager_VapManager.c" in line: 624
S 1 54 3 696 Assert in file: "secManager_VapManager.c" in line: 696
S 1 54 3 734 Assert in file: "secManager_VapManager.c" in line: 734
S 1 54 3 774 Assert in file: "secManager_VapManager.c" in line: 774
S 1 54 3 777 secManager_VapManagerRemoveVap
S 1 70 3 109 Assert in file: "UpperSender_Encryption.c" in line: 109
S 1 70 3 327 Assert in file: "UpperSender_Encryption.c" in line: 327
S 1 70 3 511 Assert in file: "UpperSender_Encryption.c" in line: 511
S 1 74 0 169 Assert in file: "StaDatabase.c" in line: 169
S 1 74 0 176 Assert in file: "StaDatabase.c" in line: 176
S 1 74 0 186 Assert in file: "StaDatabase.c" in line: 186
S 1 74 0 193 Assert in file: "StaDatabase.c" in line: 193
S 1 74 0 205 Assert in file: "StaDatabase.c" in line: 205
S 1 74 0 365 StaDb_RemoveStationFromDB %X
S 1 74 0 474 Assert in file: "StaDatabase.c" in line: 474
S 1 74 0 511 Assert in file: "StaDatabase.c" in line: 511
S 1 74 0 664 Assert in file: "StaDatabase.c" in line: 664
S 1 74 0 1107 Assert in file: "StaDatabase.c" in line: 1107
S 1 74 0 1108 Assert in file: "StaDatabase.c" in line: 1108
S 1 74 0 1142 Assert in file: "StaDatabase.c" in line: 1142
S 1 74 0 1143 Assert in file: "StaDatabase.c" in line: 1143
S 1 74 0 1201 Assert in file: "StaDatabase.c" in line: 1201
S 1 74 0 1511 StaDB_SetPrimaryStationSuTxopAndNumMpdus: SID %d, txop %d, mpdus %d
S 1 74 0 1535 Assert in file: "StaDatabase.c" in line: 1535
S 1 74 0 1562 Assert in file: "StaDatabase.c" in line: 1562
S 1 74 0 1583 Assert in file: "StaDatabase.c" in line: 1583
S 1 74 0 1584 Assert in file: "StaDatabase.c" in line: 1584
S 1 74 0 1606 Assert in file: "StaDatabase.c" in line: 1606
S 1 79 0 204 Ts Manager, ADD STA, SID %d, allowed %d, Filter %d
S 1 79 0 293 tsManagerRemoveVap
S 1 79 0 336 Assert in file: "TsManager.c" in line: 336
S 1 79 0 392 Ts Manager, Set Filter, SID %d
S 1 79 0 435 Ts Manager, Remove STA, SID %d
S 1 79 0 632 Fatal Error in file: "TsManager.c"; Fatal Print: TS Manager Action Packet Confirmed - Unknown Action
S 1 79 0 762 Assert in file: "TsManager.c" in line: 762
S 1 79 0 1137 Ts Manager, Send Confirmation, Client %d, SID %d
S 1 79 0 1667 Assert in file: "TsManager.c" in line: 1667
S 1 79 0 1668 Assert in file: "TsManager.c" in line: 1668
S 1 79 0 1669 Assert in file: "TsManager.c" in line: 1669
S 1 79 0 1729 Assert in file: "TsManager.c" in line: 1729
S 1 79 0 1764 Assert in file: "TsManager.c" in line: 1764
S 1 81 2 87 Assert in file: "TxHandlerNtd.c" in line: 87
S 1 61 1 104 Assert in file: "TxPacketsClassifier.c" in line: 104
S 1 61 1 243 num_Pds =%d agerCount=%d IsrTime=%d pdCount=%d
S 1 61 1 404 Assert in file: "TxPacketsClassifier.c" in line: 404
S 1 61 1 405 Assert in file: "TxPacketsClassifier.c" in line: 405
S 1 87 0 274 VapDb_AddVap: vapIndex is %X
S 1 87 0 355 VapDb_ResetVapEntry: vapIndex is %X
S 1 87 0 521 Assert in file: "VapDatabase.c" in line: 521
S 1 87 0 542 Assert in file: "VapDatabase.c" in line: 542
S 1 87 0 586 Assert in file: "VapDatabase.c" in line: 586
S 1 87 0 655 Assert in file: "VapDatabase.c" in line: 655
S 1 87 0 754 Assert in file: "VapDatabase.c" in line: 754
S 1 87 0 775 Assert in file: "VapDatabase.c" in line: 775
S 1 87 0 837 Assert in file: "VapDatabase.c" in line: 837
S 1 87 0 860 Assert in file: "VapDatabase.c" in line: 860
S 1 87 0 1295 VapDB_Init
S 1 87 0 1420 [VapDB_FindCompatibleVap], rssiTypeFlag = %d
S 1 42 17 374 Assert in file: "Beamforming.c" in line: 374
S 1 42 17 918 linkAdaptationHandleAgingTimerEvent
S 1 42 19 145 [QAMplus_ResetCounters]
S 1 42 19 186 [QAMplus_ResetParams]
S 1 42 19 233 [QAMplus_SupportedState], LA in steadyState
S 1 42 19 297 [QAMplus_TrialState] pBaaReport->successMpdu = %d, pBaaReport->MpduCnt = %d
S 1 42 19 314 Assert in file: "QAMplus.c" in line: 314
S 1 42 19 358 [QAMplus_TrialState] pQAMplusDatabase->lastRSSIdB = %d
S 1 42 19 401 Assert in file: "QAMplus.c" in line: 401
S 1 42 19 410 [QAMplus_NewBAReport] start
S 1 42 19 438 [QAMplus_NewBAReport] start, isWorkingPoint = %d, highestRateIndex = %d
S 1 42 19 439 [QAMplus_NewBAReport] start, rateIndexFromCurrentBA = %d
S 1 42 19 440 [QAMplus_NewBAReport] QAM_PLUS_STATE_SUPPORTED start, pQAMplusDatabase->successHighestRateWPCounter = %d
S 1 42 19 441 [QAMplus_NewBAReport] QAM_PLUS_STATE_SUPPORTED start, pBaaReport->successMpdu = %d
S 1 42 19 446 [QAMplus_NewBAReport] QAM_PLUS_STATE_SUPPORTED end, pQAMplusDatabase->successHighestRateWPCounter = %d
S 1 42 19 454 [QAMplus_NewBAReport] QAM_PLUS_STATE_TRIAL start, pBaaReport->phyMode = %d, rateIndexFromCurrentBA = %d, RatesTable[rateIndexFromCurrentBA].vhtMcs = %d
S 1 42 19 468 [QAMplus_NewBAReport] end
S 1 42 19 498 [QAMplus_AddStationReq]  QAMplusEnableFromDriver = %d, QAMplusEnable = %d
S 1 42 19 507 [QAMplus_AddStationReq]  QAMplus_GetState = %d
S 1 42 19 518 [QAMplus_AddStationReq] stationId = %d
S 1 42 19 553 [QAMplus_compareRSSI], start 
S 1 42 19 565 [QAMplus_compareRSSI], end newRSSILarger = %d, pQAMplusDatabase->lastRSSIdB = %d, maxCurrentRssidB = %d
S 1 42 19 607 [QAMplus_findMaxRssi], maxCurrentRssidB = %d
S 1 42 19 635 [QAMplus_SetState] QAMplus_GetState = %d
S 1 42 19 709 [QAMplus_SetSupportedThresh], pQAMplusDatabase->supportedThresh = %d
S 1 42 19 746 [QAMplus_GetMaxNssInMask], MaxNss = %d, indexNss = %d, localRateMask[0] = %d, localRateMask[1] = %d
S 1 42 19 756 Assert in file: "QAMplus.c" in line: 756
S 1 42 19 792 [QAMplus_UpdateLaRateMask] before update
S 1 42 19 802 Assert in file: "QAMplus.c" in line: 802
S 1 42 19 816 [QAMplus_UpdateLaRateMask], maxNss according to raIndexMask= %d
S 1 42 19 817 [QAMplus_UpdateLaRateMask], maxNss according to raIndexMaskOrg= %d
S 1 42 19 821 Assert in file: "QAMplus.c" in line: 821
S 1 42 19 822 Assert in file: "QAMplus.c" in line: 822
S 1 42 19 836 [QAMplus_UpdateLaRateMask] after update
S 1 42 19 873 [QAMplus_SetThresh]
S 1 42 19 902 [QAMplus_Enable], QAMplusEnableFromDriver = %d
S 1 42 19 933 [QAMplus_SetSupportedThresh]
S 1 42 19 965 [QAMplus_GetThresh], pQAMplusConfigParams->trialThresh=%d, pQAMplusConfigParams->inactiveTrialThresh = %d, pQAMplusDatabase->supportedThresh = %d
S 1 42 19 994 [QAMplus_GetCounters] stationId = %d: failureCounter = %d, numberTrialsCounter = %d, successHighestRateWPCounter = %d
S 1 45 8 239 Assert in file: "lm_StaDatabase.c" in line: 239
S 1 45 8 277 Assert in file: "lm_StaDatabase.c" in line: 277
S 1 45 8 309 Assert in file: "lm_StaDatabase.c" in line: 309
S 1 45 8 335 Assert in file: "lm_StaDatabase.c" in line: 335
S 1 66 0 357 Assert in file: "RxManager.c" in line: 357
S 1 66 0 362 Assert in file: "RxManager.c" in line: 362
S 1 66 0 363 Assert in file: "RxManager.c" in line: 363
S 1 66 0 538 Fatal Error in file: "RxManager.c"; Fatal Print: RX Manager Timer Unknown Type
S 1 66 0 661 Fatal Error in file: "RxManager.c"; Fatal Print: RX Manager Classifier Resource Timeout
S 1 66 0 695 [rxManagerClassifierConfigureNormalMode]--------------------end]
S 1 66 0 731 [rxManagerClassifierConfigureRssiMode]----------------------end]
S 1 66 0 780 [rxManagerConfigureNormalMode]------------------------------end]
S 1 66 0 822 [rxManagerConfigureRssiMode]--------------------------------end]
S 1 66 0 869 Assert in file: "RxManager.c" in line: 869
S 1 66 0 887 Assert in file: "RxManager.c" in line: 887
S 1 66 0 911 Assert in file: "RxManager.c" in line: 911
S 1 66 0 912 Assert in file: "RxManager.c" in line: 912
S 1 66 0 1211 Assert in file: "RxManager.c" in line: 1211
S 1 66 0 1315 rxManagerPsSettingsFifoNotEmpty %x
S 1 66 0 1328 Assert in file: "RxManager.c" in line: 1328
S 1 66 0 1333 rxManagerPsSettingsFifoNotEmpty  Station Changed Ps Mode Set Ps Status %x Clear Ps Status %x
S 1 66 0 1426 [ARP][rxManagerDebugRdsListHandler] SN = %d
S 1 66 0 1540 Assert in file: "RxManager.c" in line: 1540
S 1 66 0 1546 Assert in file: "RxManager.c" in line: 1546
S 1 66 0 1553 Assert in file: "RxManager.c" in line: 1553
S 1 66 0 1643 rxManagerErrorRdsListHandler
S 1 66 0 1804 Fatal Error in file: "RxManager.c"; Fatal Print: RX Manager RD Handler
S 1 66 0 1869 Assert in file: "RxManager.c" in line: 1869
S 1 66 0 1913 Assert in file: "RxManager.c" in line: 1913
S 1 66 0 1970 Assert in file: "RxManager.c" in line: 1970
S 1 66 0 2109 Assert in file: "RxManager.c" in line: 2109
S 1 66 0 2307 rxManagerMulticastRekeyTimeout, vap ID - %d, prev key ID - %d
S 1 66 0 2357 rxManagerCheckMulticastRekey, vap ID - %d, last Rx key ID - %d, key Id - %d
S 1 66 0 3121 Assert in file: "RxManager.c" in line: 3121
S 1 66 0 3346 RX Manager, Send Confirmation, Client %d, SID %d
S 1 66 0 3386 Assert in file: "RxManager.c" in line: 3386
S 1 66 0 3761 Assert in file: "RxManager.c" in line: 3761
S 1 66 0 3762 Assert in file: "RxManager.c" in line: 3762
S 1 66 0 3763 Assert in file: "RxManager.c" in line: 3763
S 1 66 0 3764 Assert in file: "RxManager.c" in line: 3764
S 1 37 1 60 Assert in file: "Utils_Misc.c" in line: 60
S 1 37 1 81 Assert in file: "Utils_Misc.c" in line: 81
S 1 37 1 113 Assert in file: "Utils_Misc.c" in line: 113
S 1 37 1 166 Assert in file: "Utils_Misc.c" in line: 166
S 1 37 1 202 Assert in file: "Utils_Misc.c" in line: 202
S 1 37 1 568 Fatal Error in file: "Utils_Misc.c"; Fatal Print: Utils_determineSourceTypeAndDmaDirection
S 1 42 6 310 Assert in file: "LinkAdaptationPhyDriver.c" in line: 310
S 1 42 6 334 Assert in file: "LinkAdaptationPhyDriver.c" in line: 334
S 1 42 6 340 pDataTcr1->tcr1TxPower = %d
S 1 42 6 453 Assert in file: "LinkAdaptationPhyDriver.c" in line: 453
S 1 42 6 526 Assert in file: "LinkAdaptationPhyDriver.c" in line: 526
S 1 42 6 867 Assert in file: "LinkAdaptationPhyDriver.c" in line: 867
S 1 42 6 882 Assert in file: "LinkAdaptationPhyDriver.c" in line: 882
S 1 42 6 1301 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1301
S 1 42 6 1523 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1523
S 1 42 6 1548 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1548
S 1 42 6 1662 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1662
S 1 42 6 1770 bwAdaptationSetStationBwLimit, laDatabase->bwAdaptationDb.maxSupportedBw = %d
S 1 42 6 1818 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1818
S 1 42 6 1840 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1840
S 1 42 6 1927 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1927
S 1 42 6 2083 Assert in file: "LinkAdaptationPhyDriver.c" in line: 2083
S 1 42 6 2224 Assert in file: "LinkAdaptationPhyDriver.c" in line: 2224
S 1 42 6 2226 Assert in file: "LinkAdaptationPhyDriver.c" in line: 2226
S 1 42 6 2261 Assert in file: "LinkAdaptationPhyDriver.c" in line: 2261
S 1 42 8 338 setStaFixedRatesInHwDb 1 isRateInc = %d newRateindex= %d oldRate= %d 
S 1 42 8 354 setStaFixedRatesInHwDb 2 isRateInc = %d newRateindex= %d oldRate= %d 
S 1 42 8 1323 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1323
S 1 42 8 1496 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1496
S 1 42 8 1528 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1528
S 1 42 8 1695 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1695
S 1 42 8 1740 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1740
S 1 42 8 1742 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1742
S 1 42 8 1743 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1743
S 1 42 8 1756 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1756
S 1 42 8 1824 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1824
S 1 42 8 1916 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1916
S 1 42 8 1917 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1917
S 1 42 8 1918 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1918
S 1 42 8 1932 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1932
S 1 42 8 2008 Assert in file: "LinkAdaptationPhyDriver.c" in line: 2008
S 1 42 8 2097 Assert in file: "LinkAdaptationPhyDriver.c" in line: 2097
S 1 42 8 2842 Assert in file: "LinkAdaptationPhyDriver.c" in line: 2842
S 1 42 8 2969 Assert in file: "LinkAdaptationPhyDriver.c" in line: 2969
S 1 42 8 3076 Assert in file: "LinkAdaptationPhyDriver.c" in line: 3076
S 1 42 8 3079 Assert in file: "LinkAdaptationPhyDriver.c" in line: 3079
S 1 42 8 3119 Assert in file: "LinkAdaptationPhyDriver.c" in line: 3119
S 1 42 8 3130 Assert in file: "LinkAdaptationPhyDriver.c" in line: 3130
S 1 42 8 3140 Assert in file: "LinkAdaptationPhyDriver.c" in line: 3140
S 1 45 9 179 Assert in file: "lm_VapDatabase.c" in line: 179
S 1 3 0 446 Assert in file: "AggregationBuilder.c" in line: 446
S 1 3 0 478 Assert in file: "AggregationBuilder.c" in line: 478
S 1 3 0 606 Assert in file: "AggregationBuilder.c" in line: 606
S 1 3 0 622 Assert in file: "AggregationBuilder.c" in line: 622
S 1 3 0 783 Assert in file: "AggregationBuilder.c" in line: 783
S 1 3 0 788 Assert in file: "AggregationBuilder.c" in line: 788
S 1 3 0 941 Assert in file: "AggregationBuilder.c" in line: 941
S 1 42 4 440 estimatorsResetFastProbingFilters
S 1 42 4 805 Assert in file: "Estimators.c" in line: 805
S 1 42 4 848 Assert in file: "Estimators.c" in line: 848
S 1 42 4 857 Assert in file: "Estimators.c" in line: 857
S 1 42 4 1036 Assert in file: "Estimators.c" in line: 1036
S 1 42 4 1104 Assert in file: "Estimators.c" in line: 1104
S 1 42 4 1194 Assert in file: "Estimators.c" in line: 1194
S 1 42 4 1224 estimatorsProcessBaaReport, rate changed, new rate = %d
S 1 42 4 1366 Assert in file: "Estimators.c" in line: 1366
S 1 42 4 1655 estimatorsSlowProbingDbUpdate av per,RateIndex = %d,bandwidth = %d,filterinput = %d, filterResult = %d, alpha = %d
S 1 42 4 1705 calculatePer, resWeighted = %d, resMPduNum = %d, resLength = %d
S 1 42 4 1709 Assert in file: "Estimators.c" in line: 1709
S 1 42 4 1766 Assert in file: "Estimators.c" in line: 1766
S 1 42 4 1791 Assert in file: "Estimators.c" in line: 1791
S 1 42 4 1823 Assert in file: "Estimators.c" in line: 1823
S 1 42 4 1882 estimatorsProbingValidationCriteria,currentPacketTsf = %d, probeIsValid = %d, currentTsfMod = %d, tsfDiff = %d, validationCounter = %d
S 1 42 4 1972 estimatorsAgingCheck, staId = %d, Station's grade is - %d
S 1 42 4 2023 Fatal Error in file: "Estimators.c"; Fatal Print: estimatorsSetSlowProbingPointRateIndex
S 1 42 4 2093 Assert in file: "Estimators.c" in line: 2093
S 1 42 4 2138 Assert in file: "Estimators.c" in line: 2138
S 1 42 4 2184 Assert in file: "Estimators.c" in line: 2184
S 1 42 4 2223 estimatorsProcessSequencerReport, staId = %d, Station's grade is - %d
S 1 42 4 2250 Sequencer estimaror processing - goodput update, current totalgroup's avgGoodput = %d, normAvgGoodput %d, groupId %d
S 1 42 4 2296 estimatorsProcessSequencerReport recovery
S 1 42 4 2324 estimatorsProcessSequencerReport, rate changed, new rate = %d
S 1 42 4 2533 Assert in file: "Estimators.c" in line: 2533
S 1 42 4 2584 estimatorsProcessCollisionsBaaReport, currentBer = %d
S 1 42 4 2707 Assert in file: "Estimators.c" in line: 2707
S 1 42 4 2709 fastDropEstimator, windowFailedPacketBitmap = %d, numberOfFailedPacketInWindow = %d,  consFailMask = %d, numbOfFailsinWind = %d, consequtiveFailsCondition = %d, FailIndication = %d,failsInWindow = %d
S 1 42 4 2766 Assert in file: "Estimators.c" in line: 2766
S 1 42 4 2785 estimatorsFastProbingSearchMaxEffTp, AvPerFilter: filetrResult = %d, alpha = %d, Last TSF = %d
S 1 42 4 2859 Assert in file: "Estimators.c" in line: 2859
S 1 42 4 2902 Assert in file: "Estimators.c" in line: 2902
S 1 42 4 2947 Assert in file: "Estimators.c" in line: 2947
S 1 42 4 2968 Assert in file: "Estimators.c" in line: 2968
S 1 42 4 2972 Assert in file: "Estimators.c" in line: 2972
S 1 42 4 3005 linkAdaptationCalcMuCandidacyGrade - stationInPsWithinAwindowCount =%d 
S 1 42 4 3006 linkAdaptationCalcMuCandidacyGrade - lowFrameRateCounter =%d 
S 1 42 4 3007 linkAdaptationCalcMuCandidacyGrade - wpAverageGoodPut =%d 
S 1 42 13 669 Assert in file: "PowerAdaptation.c" in line: 669
S 1 42 13 825 PowerSetNextProbingPointAndIndications,wpPower = %d, newProbingPower = %d
S 1 42 13 844 PowerSetNextProbingPointAndIndications,probingPower = %d, newProbingPower = %d
S 1 42 13 850 PowerSetNextProbingPointAndIndications, Bw %d, newPower = %d
S 1 42 13 961 PowerAdaptationAdjustAdditionalSteps nextPowerProbingPoint = %d probingPowerStep = %d powerAdditionalStepUp = %d powerAdditionalStepDown = %d
S 1 42 13 1043 PowerProcessFeedback, workingPointPer = %d, slowProbingPointPer = %d
S 1 42 13 1110 PowerProcessFeedback: Change power working point newPower = %d
S 1 42 13 1124 PowerProcessFeedback - SET RATE + 1
S 1 42 13 1194 powerStepTemp %d
S 1 42 13 1222 powerStepTemp %d
S 1 42 13 1242 *pAdditionalStep %d minAbsPowerStep %d
S 1 42 13 1258 nextStepTemp %d
S 1 42 13 1271 *pAdditionalStep %d
S 1 42 13 1328 CalcLimitsAndGetStaTcrPowerVal, Bw = %d, rateIndex = %d, powerVal = %d, newPower = %d, newTcrPowerVal = %d
S 1 42 13 1440 Assert in file: "PowerAdaptation.c" in line: 1440
S 1 42 13 1645 Assert in file: "PowerAdaptation.c" in line: 1645
S 1 42 13 1786 Assert in file: "PowerAdaptation.c" in line: 1786
S 1 42 13 1903 Assert in file: "PowerAdaptation.c" in line: 1903
S 1 42 13 1935 Assert in file: "PowerAdaptation.c" in line: 1935
S 1 42 13 1942 Assert in file: "PowerAdaptation.c" in line: 1942
S 1 42 13 1988 Assert in file: "PowerAdaptation.c" in line: 1988
S 1 42 13 2050 calcInternalLowerLimit, Limit = %d
S 1 42 13 2079 calcExternalLowerLimit, BW %d, Limit = %d
S 1 42 13 2118 calcExternalUpperLimit, BW %d, Limit = %d
S 1 42 13 2308 PowerAdaptationCalcPowerInStaLimits, newPower = %d, isPowerBlocked = %d
S 1 42 13 2636 Assert in file: "PowerAdaptation.c" in line: 2636
S 1 42 13 2662 Assert in file: "PowerAdaptation.c" in line: 2662
S 1 42 15 723 slowProbingHandler, staIndex = %d, stayWithLastProbingPoint = %d, notEffectveProbeCounter = %d
S 1 42 15 830 Assert in file: "RateAdaptation.c" in line: 830
S 1 42 15 843 raFastProbingProcessFeedback, WORKING POINT CHANGED AFTER PROBING, Last rate = %d, new Rate = %d, newPER = %d
S 1 42 15 957 rateAdaptationChangeWorkingPoint, BW = %d, newRate = %d, prevRate = %d
S 1 42 15 980 Assert in file: "RateAdaptation.c" in line: 980
S 1 42 15 1053 updatePerStability,  pStabilityState = %d
S 1 42 15 1115 updatePerStability, perDeviationStability = %d,targetPerStability = %d, resultPerStability = %d
S 1 42 15 1192 Assert in file: "RateAdaptation.c" in line: 1192
S 1 42 15 1266 Assert in file: "RateAdaptation.c" in line: 1266
S 1 42 15 1365 Assert in file: "RateAdaptation.c" in line: 1365
S 1 42 15 1373 Assert in file: "RateAdaptation.c" in line: 1373
S 1 42 15 1386 Assert in file: "RateAdaptation.c" in line: 1386
S 1 42 15 1700 Assert in file: "RateAdaptation.c" in line: 1700
S 1 42 15 1777 Assert in file: "RateAdaptation.c" in line: 1777
S 1 42 15 1913 FAST DROP, StaINdex = %d, BW = %d, currentRateIndex = %d, newRateindex = %d
S 1 42 15 2024 Assert in file: "RateAdaptation.c" in line: 2024
S 1 42 15 2025 Assert in file: "RateAdaptation.c" in line: 2025
S 1 42 15 2026 Assert in file: "RateAdaptation.c" in line: 2026
S 1 42 15 2077 Assert in file: "RateAdaptation.c" in line: 2077
S 1 42 5 710 Assert in file: "LinkAdaptation.c" in line: 710
S 1 42 5 784 Assert in file: "LinkAdaptation.c" in line: 784
S 1 42 5 920 Assert in file: "LinkAdaptation.c" in line: 920
S 1 42 5 1197 Assert in file: "LinkAdaptation.c" in line: 1197
S 1 42 5 1201 Assert in file: "LinkAdaptation.c" in line: 1201
S 1 42 5 1461 Assert in file: "LinkAdaptation.c" in line: 1461
S 1 42 5 1668 Assert in file: "LinkAdaptation.c" in line: 1668
S 1 42 5 1678 Assert in file: "LinkAdaptation.c" in line: 1678
S 1 42 5 1892 linkAdaptationHandleAgingTimerEvent
S 1 42 5 1904 Assert in file: "LinkAdaptation.c" in line: 1904
S 1 42 5 1908 Assert in file: "LinkAdaptation.c" in line: 1908
S 1 42 5 2155 [linkAdaptationAddStationReq], staPHYmode = %d
S 1 42 5 2320 Assert in file: "LinkAdaptation.c" in line: 2320
S 1 42 5 2699 Assert in file: "LinkAdaptation.c" in line: 2699
S 1 42 5 2842 Assert in file: "LinkAdaptation.c" in line: 2842
S 1 42 5 3069 [setLinkAdaptationRatesMask], pLmStaDbSwinfo->supportedRates = %d
S 1 42 5 3106 [setLinkAdaptationRatesMask] pLinkAdaptationDb->laStaUspCommon.raIndexMask.raIndexMask64bit[0] = %d
S 1 42 5 3107 [setLinkAdaptationRatesMask] pLinkAdaptationDb->laStaUspCommon.raIndexMask.raIndexMask64bit[1] = %d
S 1 42 5 3356 Assert in file: "LinkAdaptation.c" in line: 3356
S 1 42 5 3405 Assert in file: "LinkAdaptation.c" in line: 3405
S 1 42 5 3537 Assert in file: "LinkAdaptation.c" in line: 3537
S 1 42 5 3714 Assert in file: "LinkAdaptation.c" in line: 3714
S 1 42 5 3825 Assert in file: "LinkAdaptation.c" in line: 3825
S 1 42 5 3830 Assert in file: "LinkAdaptation.c" in line: 3830
S 1 42 5 3844 Assert in file: "LinkAdaptation.c" in line: 3844
S 1 42 5 3946 Assert in file: "LinkAdaptation.c" in line: 3946
S 1 42 5 3967 Assert in file: "LinkAdaptation.c" in line: 3967
S 1 42 5 3984 Assert in file: "LinkAdaptation.c" in line: 3984
S 1 42 5 4113 Assert in file: "LinkAdaptation.c" in line: 4113
S 1 42 5 4145 Assert in file: "LinkAdaptation.c" in line: 4145
S 1 42 5 4175 Assert in file: "LinkAdaptation.c" in line: 4175
S 1 42 5 4447 [FAST DROP] linkAdaptationFastDropConfig enableFastDrop = %d pFastDropCfg->enableFastDrop = %d 
S 1 42 5 4600 [updateTransmissionTimeParams] rate is above threshold: %d
S 1 42 5 4606 [updateTransmissionTimeParams] rate is below threshold: %d. limit transmission time
S 1 42 5 4644 clientIsolationRateIsChanged oldPhyRate: %d newPhyRate: %d oldPhymode %d newPhyMode %d
S 1 42 5 4732 Assert in file: "LinkAdaptation.c" in line: 4732
S 1 42 5 4855 Assert in file: "LinkAdaptation.c" in line: 4855
S 1 42 5 4875 pTcrPowerModified = %d
S 1 42 5 5001 Assert in file: "LinkAdaptation.c" in line: 5001
S 1 42 5 5016 Assert in file: "LinkAdaptation.c" in line: 5016
S 1 42 5 5023 Fatal Error in file: "LinkAdaptation.c"; Fatal Print: linkAdaptationProcessCurrentBaaReport
S 1 42 5 5065 Assert in file: "LinkAdaptation.c" in line: 5065
S 1 42 5 5295 Assert in file: "LinkAdaptation.c" in line: 5295
S 1 42 5 5334 [ChangeStaToSteadyStateConfigurationParams]
S 1 42 5 5371 Assert in file: "LinkAdaptation.c" in line: 5371
S 1 42 5 5379 Fatal Error in file: "LinkAdaptation.c"; Fatal Print: updateLaDbDistributionParam
S 1 42 5 5505 Assert in file: "LinkAdaptation.c" in line: 5505
S 1 42 5 5580 Assert in file: "LinkAdaptation.c" in line: 5580
S 1 42 5 5616 Assert in file: "LinkAdaptation.c" in line: 5616
S 1 42 5 5643 Assert in file: "LinkAdaptation.c" in line: 5643
S 1 42 5 5821 Assert in file: "LinkAdaptation.c" in line: 5821
S 1 42 5 5824 Assert in file: "LinkAdaptation.c" in line: 5824
S 1 42 5 5830 Assert in file: "LinkAdaptation.c" in line: 5830
S 1 70 0 338 Assert in file: "LowerSender.c" in line: 338
S 1 70 0 455 Assert in file: "LowerSender.c" in line: 455
S 1 70 0 486 Assert in file: "LowerSender.c" in line: 486
S 1 70 0 491 Assert in file: "LowerSender.c" in line: 491
S 1 70 0 501 Assert in file: "LowerSender.c" in line: 501
S 1 70 0 604 Assert in file: "LowerSender.c" in line: 604
S 1 70 0 665 LowerSenderDutTxEndHandler, DUT_TX_STATE_STOPPING, toStop == TRUE
S 1 70 0 671 Assert in file: "LowerSender.c" in line: 671
S 1 70 0 681 Assert in file: "LowerSender.c" in line: 681
S 1 70 0 689 LowerSenderDutTxAbortHandler
S 1 70 0 909 Assert in file: "LowerSender.c" in line: 909
S 1 70 0 1056 Assert in file: "LowerSender.c" in line: 1056
S 1 70 0 1175 LowerSender_DutConfig
S 1 70 0 1199 LowerSender_UpdateStdWithDutParams, alloctedStd_p:0x%x, current std:0x%x
S 1 70 2 294 Assert in file: "UpperSender.c" in line: 294
S 1 70 2 296 Assert in file: "UpperSender.c" in line: 296
S 1 70 2 298 Assert in file: "UpperSender.c" in line: 298
S 1 70 2 665 Assert in file: "UpperSender.c" in line: 665
S 1 70 2 703 Assert in file: "UpperSender.c" in line: 703
S 1 70 2 765 Assert in file: "UpperSender.c" in line: 765
S 1 70 2 766 Assert in file: "UpperSender.c" in line: 766
S 1 79 1 564 Fatal Error in file: "TsManagerInitiator.c"; Fatal Print: TS Manager Initiator Fatal
S 1 79 1 593 TS Manager Initiator Change SID %d, TID %d, State from %d to %d
S 1 79 1 1882 Assert in file: "TsManagerInitiator.c" in line: 1882
S 1 79 1 2233 tsManagerInitiatorBarConfirmedInOpenedSending station index = %d tid = %d
S 1 79 1 2401 tsManagerInitiatorBarStatusInOpenedSending status %d
S 1 79 1 2428 tsManagerInitiatorBarStatusInOpenedSending normal flow
S 1 79 1 3307 Assert in file: "TsManagerInitiator.c" in line: 3307
S 1 79 1 3342 Assert in file: "TsManagerInitiator.c" in line: 3342
S 1 79 1 3390 Assert in file: "TsManagerInitiator.c" in line: 3390
S 1 79 1 3921 Assert in file: "TsManagerInitiator.c" in line: 3921
S 1 79 1 3976 tsManagerInitiatorFlushIllegalPackets 
S 1 79 1 4512 Assert in file: "TsManagerInitiator.c" in line: 4512
S 1 79 1 4747 TsManagerInitiator_BarConfirmed TsDb->commonPart.stationId %d tid %d state %d
S 1 79 1 4787 TsManagerInitiator_BarStatus TsDb->commonPart.stationId %d tid %d state %d
S 1 79 1 4820 TsManagerInitiator_PdAllocated TsDb->commonPart.stationId %d tid %d state %d
S 1 79 1 4863 Assert in file: "TsManagerInitiator.c" in line: 4863
S 1 79 1 4906 TsManagerInitiator_DiscardedPacket TsDb->commonPart.stationId %d tid %d state %d
S 1 79 1 4942 TsManagerInitiator_QueueIsLocked TsDb->commonPart.stationId %d tid %d state %d
S 1 79 1 5343 Assert in file: "TsManagerInitiator.c" in line: 5343
S 1 79 1 5345 Assert in file: "TsManagerInitiator.c" in line: 5345
S 1 82 1 503 TX Manager STA Manager, Station %d changed from %d to %d
S 1 82 1 827 Fatal Error in file: "TxManager_StaManager.c"; Fatal Print: TX Manager STA Manager Fatal
S 1 36 1 599 TxSelector_ReleaseStd, numPendQs = %d
S 1 36 1 733 Assert in file: "TxSelector.c" in line: 733
S 1 36 1 765 TxSelector_DisableRequest - put in pending, numPendingQueues = %d
S 1 36 1 885 TxSelector_LockRequest - put in pending, numPendingQueues = %d
S 1 36 1 1294 txSelectorUnLockQueueIndex - NOT clearing, pendingLockRequest.numPendQs = %d
S 1 36 1 1354 Assert in file: "TxSelector.c" in line: 1354
S 1 36 1 1485 Assert in file: "TxSelector.c" in line: 1485
S 1 36 1 1653 Assert in file: "TxSelector.c" in line: 1653
S 1 36 1 1672 Assert in file: "TxSelector.c" in line: 1672
S 1 36 1 1731 Assert in file: "TxSelector.c" in line: 1731
S 1 36 1 1741 Assert in file: "TxSelector.c" in line: 1741
S 1 36 1 1749 Assert in file: "TxSelector.c" in line: 1749
S 1 36 1 2359 Assert in file: "TxSelector.c" in line: 2359
S 1 36 1 2439 Assert in file: "TxSelector.c" in line: 2439
S 1 36 1 2739 [DTIM][TxSelector_DtimStartIndication] pDtimBitmap = 0x%x
S 1 36 1 2765 [DTIM][TxSelector_DtimStartIndicationPostQueueSwitch] vapIndex = %d qIndex = %d pPsReqBitmap = 0x%x
S 1 36 1 2786 [DTIM][TxSelector_DtimEndIndication] vapIndex = %d qIndex = %d pPsReqBitmap = 0x%x
S 1 36 1 2808 [DTIM][txSelectorDtimEndIndicationPostQueueSwitch] pDtimBitmap = 0x%x
S 1 28 9 351 Assert in file: "RxDcOffsetClbrHndlr.c" in line: 351
S 1 28 9 657 Assert in file: "RxDcOffsetClbrHndlr.c" in line: 657
S 1 28 9 671 Assert in file: "RxDcOffsetClbrHndlr.c" in line: 671
S 1 29 6 639 Assert in file: "PhyCalDriver.c" in line: 639
S 1 29 6 1081 Assert in file: "PhyCalDriver.c" in line: 1081
S 1 29 6 1311 Assert in file: "PhyCalDriver.c" in line: 1311
S 1 29 8 780 Assert in file: "PhyCalDriver.c" in line: 780
S 1 29 8 781 Assert in file: "PhyCalDriver.c" in line: 781
S 1 29 8 812 Assert in file: "PhyCalDriver.c" in line: 812
S 1 29 8 866 Assert in file: "PhyCalDriver.c" in line: 866
S 1 29 8 1396 Assert in file: "PhyCalDriver.c" in line: 1396
S 1 29 8 1688 Assert in file: "PhyCalDriver.c" in line: 1688
S 1 42 14 223 Assert in file: "ProtectionAdaptation.c" in line: 223
S 1 42 14 248 Assert in file: "ProtectionAdaptation.c" in line: 248
S 1 42 14 294 ProtectionAdaptation_SetFixedMode : %d
S 1 42 14 341 Assert in file: "ProtectionAdaptation.c" in line: 341
S 1 42 14 368 Assert in file: "ProtectionAdaptation.c" in line: 368
S 1 42 14 370 Assert in file: "ProtectionAdaptation.c" in line: 370
S 1 42 14 409 Assert in file: "ProtectionAdaptation.c" in line: 409
S 1 42 14 439 ProtectionAdaptation_VapSm - vapCollisionTotalRatio is very high : %d, Ackbitmap:%d, Ctsbitmap:%d
S 1 42 14 448 ProtectionAdaptation_VapSm -got indication for invalid VAP 
S 1 42 14 459 ProtectionAdaptation_VapSm -VAP state:NONE-VAP_PROTECTION_FORCE_STATE : %d
S 1 42 14 464 ProtectionAdaptation_VapSm -VAP in PROTECTION_NONE_STATE collsion Count : %d
S 1 42 14 469 ProtectionAdaptation_VapSm -Transition to threshold - collsion Count : %d
S 1 42 14 482 Assert in file: "ProtectionAdaptation.c" in line: 482
S 1 42 14 500 Assert in file: "ProtectionAdaptation.c" in line: 500
S 1 42 14 512 ProtectionAdaptation_VapSm - VAP state:  VAP_PROTECTION_THRESHOLD_STATE
S 1 42 14 525 ProtectionAdaptation_VapSm - berGap = %d
S 1 42 14 532 ProtectionAdaptation_VapSm - Transition to  VAP_PROTECTION_NONE_STATE
S 1 42 14 554 ProtectionAdaptation_VapSm - Transition to  VAP_PROTECTION_NONE_STATE - protection doen't improve
S 1 42 14 569 ProtectionAdaptation_VapSm -VAP state:TH- VAP_PROTECTION_DISABLE_STATE
S 1 42 14 575 Assert in file: "ProtectionAdaptation.c" in line: 575
S 1 42 14 580 ProtectionAdaptation_VapSm -VAP state: VAP_PROTECTION_FORCED_STATE
S 1 42 14 586 ProtectionAdaptation_VapSm -transition to VAP_PROTECTION_NONE_STATE
S 1 42 14 597 ProtectionAdaptation_VapSm -VAP state:Force- VAP_PROTECTION_DISABLE_STATE
S 1 42 14 605 Assert in file: "ProtectionAdaptation.c" in line: 605
S 1 42 14 609 Assert in file: "ProtectionAdaptation.c" in line: 609
S 1 42 14 638 protectionAdaptationStaSm - staCollisionCount : %d, Ackbitmap:%d, Ctsbitmap:%d
S 1 42 14 640 protectionAdaptationStaSm - staCollisionCount is very high
S 1 42 14 643 protectionAdaptationStaSm, vapCollisionResetCounter = %d, staCollisionResetCounter = %d
S 1 42 14 652 protectionAdaptationStaSm, pStaProtectionEstimatorPtr->staCollisionResetCounter = %d
S 1 42 14 662 protectionAdaptationStaSm -statino state: STA_PROTECTION_NONE_STATE
S 1 42 14 668 protectionAdaptationStaSm -transition to STA_THRESHOLD_MODE vapStaCollisionDelta = %d
S 1 42 14 677 protectionAdaptationStaSm -statino state: STA_PROTECTION_THRESHOLD_STATE  vapStaCollisionDelta = %d
S 1 42 14 682 protectionAdaptationStaSm -transition to STA_FORCE_PROTECTION_MODE vapStaCollisionDelta = %d
S 1 42 14 695 protectionAdaptationStaSm -transition to STA_NO_PROTECTION_MODE vapStaCollisionDelta = %d
S 1 42 14 705 protectionAdaptationStaSm -transition to STA_NO_PROTECTION_MODE vapStaCollisionDelta = %d
S 1 42 14 716 protectionAdaptationStaSm -statino state: STA_PROTECTION_FORCE_STATE vapStaCollisionDelta = %d
S 1 42 14 721 protectionAdaptationStaSm -transition to STA_THRESHOLD_MODE - delta exceed threshold, delta = %d
S 1 42 14 736 protectionAdaptationStaSm -transition to STA_NO_PROTECTION_MODE - No improvement with protection vapStaCollisionDelta = %d
S 1 42 14 758 protectionAdaptationStaSm -BAA report arrived to a non-valid station!
S 1 42 14 762 Assert in file: "ProtectionAdaptation.c" in line: 762
S 1 42 14 787 Assert in file: "ProtectionAdaptation.c" in line: 787
S 1 42 14 824 ProtectionAdaptation_WlanTimerEventHandler -collosionRatio == %d
S 1 42 14 971 Assert in file: "ProtectionAdaptation.c" in line: 971
S 1 42 14 981 protectionAdaptationResetCollisionsCounters, vapCollisionResetCounter = %d, staCollisionResetCounter = %d
S 1 42 14 995 protectionAdaptationAgingReset, staCollisionResetCounter = %d, vapCollisionResetCounter = %d
S 1 28 15 143 Tx Lo: Executing Calibration: CalibType(offline(1)/online(2)) = %d,
S 1 28 15 183 Tx Lo: Finished Calibration. Ret Code = %d, Run Time = %d
S 1 28 15 358 TXLo calibrateSingleAntenna:RF Ant %d,LoopBackRxAnt %d, LoopBackTxAnt %d
S 1 28 15 373 TxLo calibrateSingleAntenna(): Restore Hw Registers Run Time = %d
S 1 28 15 650 TxLo calibrateAndVerifySingleTpc: TPC %d
S 1 28 15 688 Tx Lo calibrateAndVerifySingleTpc(): Verify reference Energy(log) = %d
S 1 28 15 782 TxLo doAxisIteration(). Iteration = %d, I = %d
S 1 28 15 794 TxLo doAxisIteration(). Iteration = %d, Q = %d
S 1 28 15 810 TxLo calibrateAndVerifySingleTpc digitalDacI = %d, digitalDacQ = %d
S 1 28 15 818 TxLo calibrateAndVerifySingleTpc dacI = %d, dacQ = %d
S 1 28 15 829 TxLo calibrateAndVerifySingleTpc(): Run Time = %d
S 1 28 15 877 ant: %d. inHi: %d inLow %d energy high %d energy low: %d
S 1 28 15 894 ant: %d. inHi: %d inLow %d energy high %d energy low: %d
S 1 28 15 965 TxLo digitalDacUpdateRequired() DAC  %d exceeds allowed range but digital DAC max iterations %d exceeded
S 1 28 15 1120 Tx Lo VerifyCalibrationResults(): TPC Energy(log) = %d Diff from Ref %d
S 1 28 15 1128 fail!! Tx Lo verifyCalibrationResults():Energy diff from ref %d below TH = %d status = %d
S 1 28 15 1133 pass!!! TxLo verifyCalibrationResults status = %d
S 1 28 15 1139 TxLo verifyCalibrationResults(): Single TPC verify Run Time = %d
S 1 28 15 1294 TxLo updateTpcsToNextCalibTpc: next TPC = %d
S 1 28 15 1386 Assert in file: "TxLOLeakageClbrHndlr.c" in line: 1386
S 1 28 15 1435 TxLoLeakage_StoreResults(): Ant %d Digital DAC: I=%d Q=%d
S 1 28 15 1443 TxLoLeakage_StoreResults(): Ant %d Num Calibrated TPCs=%d
S 1 28 15 1454 TxLoLeakage_StoreResults(): Ant %d TPC %d DAC: I=%d Q=%d
S 1 29 16 701 Assert in file: "RficDriver.c" in line: 701
S 1 29 16 748 Assert in file: "RficDriver.c" in line: 748
S 1 29 16 793 Assert in file: "RficDriver.c" in line: 793
S 1 29 16 1033 Assert in file: "RficDriver.c" in line: 1033
S 1 29 16 1152 Assert in file: "RficDriver.c" in line: 1152
S 1 29 16 1153 Assert in file: "RficDriver.c" in line: 1153
S 1 29 16 1154 Assert in file: "RficDriver.c" in line: 1154
S 1 29 16 1230 Assert in file: "RficDriver.c" in line: 1230
S 1 29 16 1342 Assert in file: "RficDriver.c" in line: 1342
S 1 29 16 1404 Assert in file: "RficDriver.c" in line: 1404
S 1 29 16 1452 Assert in file: "RficDriver.c" in line: 1452
S 1 29 16 1493 Assert in file: "RficDriver.c" in line: 1493
S 1 29 16 1537 Assert in file: "RficDriver.c" in line: 1537
S 1 29 16 1577 Assert in file: "RficDriver.c" in line: 1577
S 1 29 16 1682 Assert in file: "RficDriver.c" in line: 1682
S 1 29 16 1760 Assert in file: "RficDriver.c" in line: 1760
S 1 29 16 1775 Assert in file: "RficDriver.c" in line: 1775
S 1 29 16 1842 Assert in file: "RficDriver.c" in line: 1842
S 1 29 16 1928 RficDriver_SetFrequency
S 1 29 16 1955 [RficDriver_SetFrequency], Flo = %d
S 1 29 16 2114 Assert in file: "RficDriver.c" in line: 2114
S 1 29 16 2228 Assert in file: "RficDriver.c" in line: 2228
S 1 29 16 2328 Assert in file: "RficDriver.c" in line: 2328
S 1 29 16 2386 Assert in file: "RficDriver.c" in line: 2386
S 1 29 16 2469 Assert in file: "RficDriver.c" in line: 2469
S 1 29 16 2470 Assert in file: "RficDriver.c" in line: 2470
S 1 29 16 2510 Assert in file: "RficDriver.c" in line: 2510
S 1 29 16 2511 Assert in file: "RficDriver.c" in line: 2511
S 1 29 16 2587 Assert in file: "RficDriver.c" in line: 2587
S 1 29 16 2627 Assert in file: "RficDriver.c" in line: 2627
S 1 29 16 2760 Assert in file: "RficDriver.c" in line: 2760
S 1 29 20 708 Assert in file: "RficDriver.c" in line: 708
S 1 29 20 755 Assert in file: "RficDriver.c" in line: 755
S 1 29 20 931 Assert in file: "RficDriver.c" in line: 931
S 1 29 20 1027 Assert in file: "RficDriver.c" in line: 1027
S 1 29 20 1087 Assert in file: "RficDriver.c" in line: 1087
S 1 29 20 1336 Assert in file: "RficDriver.c" in line: 1336
S 1 29 20 1351 Assert in file: "RficDriver.c" in line: 1351
S 1 29 20 1418 Assert in file: "RficDriver.c" in line: 1418
S 1 29 20 1512 RficDriver_SetFrequency freq = %d, bw = %d
S 1 29 20 1877 Assert in file: "RficDriver.c" in line: 1877
S 1 29 20 1938 Assert in file: "RficDriver.c" in line: 1938
S 1 29 20 2011 Assert in file: "RficDriver.c" in line: 2011
S 1 29 20 2055 Assert in file: "RficDriver.c" in line: 2055
S 1 29 20 2161 Assert in file: "RficDriver.c" in line: 2161
S 1 29 20 2175 Assert in file: "RficDriver.c" in line: 2175
S 1 29 20 2254 Assert in file: "RficDriver.c" in line: 2254
S 1 29 20 2289 Assert in file: "RficDriver.c" in line: 2289
S 1 29 20 2954 Assert in file: "RficDriver.c" in line: 2954
S 1 29 20 2965 Assert in file: "RficDriver.c" in line: 2965
S 1 30 2 710 Assert in file: "RficDriver.c" in line: 710
S 1 30 2 757 Assert in file: "RficDriver.c" in line: 757
S 1 30 2 1042 Assert in file: "RficDriver.c" in line: 1042
S 1 30 2 1138 Assert in file: "RficDriver.c" in line: 1138
S 1 30 2 1198 Assert in file: "RficDriver.c" in line: 1198
S 1 30 2 1260 Assert in file: "RficDriver.c" in line: 1260
S 1 30 2 1308 Assert in file: "RficDriver.c" in line: 1308
S 1 30 2 1349 Assert in file: "RficDriver.c" in line: 1349
S 1 30 2 1393 Assert in file: "RficDriver.c" in line: 1393
S 1 30 2 1433 Assert in file: "RficDriver.c" in line: 1433
S 1 30 2 1535 Assert in file: "RficDriver.c" in line: 1535
S 1 30 2 1613 Assert in file: "RficDriver.c" in line: 1613
S 1 30 2 1628 Assert in file: "RficDriver.c" in line: 1628
S 1 30 2 1695 Assert in file: "RficDriver.c" in line: 1695
S 1 30 2 1799 RficDriver_SetFrequency freq = %d, bw = %d
S 1 30 2 1805 DRIVER set frequency %d ....FREQ FOR CALIBRATE, is diffrent from LoFrequencies_G[2]=%d
S 1 30 2 1807 LoFrequencies_G[1]=%d, .LoFrequencies_G[2]=%d
S 1 30 2 1974 Assert in file: "RficDriver.c" in line: 1974
S 1 30 2 2176 Assert in file: "RficDriver.c" in line: 2176
S 1 30 2 2237 Assert in file: "RficDriver.c" in line: 2237
S 1 30 2 2310 Assert in file: "RficDriver.c" in line: 2310
S 1 30 2 2358 Assert in file: "RficDriver.c" in line: 2358
S 1 30 2 2593 Assert in file: "RficDriver.c" in line: 2593
S 1 30 2 2628 Assert in file: "RficDriver.c" in line: 2628
S 1 85 0 922 [UMI_ADD_VAP_REQ LA]
S 1 85 0 1114 UMI_SET_INTERFERER_DETECTION_PARAMS_REQ: time %u
S 1 85 0 1239 [vUM_PHY_RX_STATUS_REQ]
S 1 85 0 1257 [vMC_PHY_RX_STATUS_CFM]
S 1 85 0 1307 [vUM_SET_CHAN_CFM]
S 1 85 0 1357 Assert in file: "um_interface_task.c" in line: 1357
S 1 85 0 1423 Fatal Error in file: "um_interface_task.c"; Fatal Print: Debug Assert Requested by Host
S 1 85 0 1429 Assert in file: "um_interface_task.c" in line: 1429
S 1 85 0 1450 [vUM_SET_CHAN_REQ]
S 1 85 0 1714 Assert in file: "um_interface_task.c" in line: 1714
S 1 85 0 1738 Assert in file: "um_interface_task.c" in line: 1738
S 1 85 0 1854 Assert in file: "um_interface_task.c" in line: 1854
S 1 85 0 1964 Assert in file: "um_interface_task.c" in line: 1964
S 1 85 0 1975 Assert in file: "um_interface_task.c" in line: 1975
S 1 85 0 2422 Assert in file: "um_interface_task.c" in line: 2422
S 1 85 0 2444 [startLockAttempt 1] *** semaphore test start *** 
S 1 85 0 2466 [startLockAttempt 2] UM is trying to get the lock -> lock is busy = %d
S 1 85 0 2471 [startLockAttempt 3] Get a non used lock 
S 1 85 0 2473 [startLockAttempt 4] Got the lock 
S 1 85 0 2475 [startLockAttempt 5] Free the lock 
S 1 85 0 2478 [startLockAttempt 6] Get a non used lock 
S 1 85 0 2480 Assert in file: "um_interface_task.c" in line: 2480
S 1 85 0 2481 [startLockAttempt 7] Got the lock 
S 1 85 0 2482 [startLockAttempt 8] Free the lock
S 1 85 0 2484 [startLockAttempt 9] Free 
S 1 85 0 2487 [startLockAttempt 10] Get a busy lock 
S 1 85 0 2489 [startLockAttempt 11] Locked 
S 1 85 0 2490 [startLockAttempt 12] Free the lock 
S 1 85 0 2492 [startLockAttempt 13] Free 
S 1 85 0 2529 UMAC Rx UM_DBG_CLI_REQ from Host, action:%d, argc:%d, data1:%d, data2:%d, data3:%d
S 1 85 0 2607 [UmDbgCliReq] Unknown message type
S 1 85 0 2748 CLI req, data1=%d, data2=%d, data3=%d
S 1 85 0 2861 Assert in file: "um_interface_task.c" in line: 2861
S 1 85 0 2883 Assert in file: "um_interface_task.c" in line: 2883
S 1 85 0 2891 Assert in file: "um_interface_task.c" in line: 2891
S 1 85 0 2897 Assert in file: "um_interface_task.c" in line: 2897
S 1 85 0 2927 Assert in file: "um_interface_task.c" in line: 2927
S 1 85 0 2939 Assert in file: "um_interface_task.c" in line: 2939
S 1 85 0 2952 Assert in file: "um_interface_task.c" in line: 2952
S 1 85 0 2964 Assert in file: "um_interface_task.c" in line: 2964
S 1 85 0 2965 Assert in file: "um_interface_task.c" in line: 2965
S 1 85 0 2993 Assert in file: "um_interface_task.c" in line: 2993
S 1 85 0 3006 Assert in file: "um_interface_task.c" in line: 3006
S 1 85 0 3016 Assert in file: "um_interface_task.c" in line: 3016
S 1 85 0 3144 [vUMI_MAN_STA_ADD_REQ]
S 1 85 0 3166 [vUMI_MAN_STA_ADD_CFM]
S 1 85 0 3192 [vUMI_MAN_STA_REMOVE_REQ]
S 1 85 0 3213 [vUMI_MAN_STA_REMOVE_CFM]
S 1 85 0 3274 Assert in file: "um_interface_task.c" in line: 3274
S 1 85 0 3516 [vUMI_MAN_REQUEST_SID_REQ]
S 1 85 0 3536 [vUMI_MAN_REQUEST_SID_CFM]
S 1 85 0 3578 [vUMI_MAN_REMOVE_SID_REQ]
S 1 85 0 3724 Assert in file: "um_interface_task.c" in line: 3724
S 1 85 0 3798 Assert in file: "um_interface_task.c" in line: 3798
S 1 85 0 3979 Assert in file: "um_interface_task.c" in line: 3979
S 1 85 0 4167 [vUMI_MAN_REMOVE_SID_CFM]
S 1 85 0 4191 [vUMI_MAN_STOP_TRAFFIC_REQ]
S 1 85 0 4209 [vUMI_MAN_STOP_TRAFFIC_CFM]
S 1 85 0 4883 Fatal Error in file: "um_interface_task.c"; Fatal Print: UMI_GROUP_LOCK_CFM
S 1 85 0 5436 Assert in file: "um_interface_task.c" in line: 5436
S 1 85 0 5476 Assert in file: "um_interface_task.c" in line: 5476
S 1 85 0 5479 Assert in file: "um_interface_task.c" in line: 5479
S 1 2 1 204 Assert in file: "AgerEmulator.c" in line: 204
S 1 2 1 244 Assert in file: "AgerEmulator.c" in line: 244
S 1 2 1 280 Assert in file: "AgerEmulator.c" in line: 280
S 1 2 1 314 Assert in file: "AgerEmulator.c" in line: 314
S 1 2 1 316 Assert in file: "AgerEmulator.c" in line: 316
S 1 2 1 704 agerEmulatorHandlePeriodicTimer >>> Not performing check
S 1 2 1 993 agerEmulatorSendConfirmToStationManager, Client %d, stationIndex %d
S 1 2 1 1467 agerEmulatorProcessQueue BAR TtlCount = %d , , retransmission = %d
S 1 2 1 1524 agerEmulatorProcessQueue MANAGEMENT  TtlCount = %d 
S 1 2 1 1559 agerEmulatorProcessQueue RETRANSMIT PDs 
S 1 2 1 1580 agerEmulatorProcessQueue RETRANSMIT NOT DISCARD locationInArray = %d, locationInBitmap = %d, locationInWord = %d 
S 1 2 1 1606 agerEmulatorProcessQueue RETRANSMIT PDs current = %x, amsdu tail = %x , ttlCount = %d , numberOfPdsInAmsdu %d 
S 1 2 1 1611 agerEmulatorProcessQueue RETRANSMIT DISCARD umacListHead = %x, umacListTail = %x 
S 1 2 1 1661 agerEmulatorProcessQueue RETRANSMIT PDs current = %x, amsdu tail = %x , ttlCount = %d , numberOfPdsInAmsdu %d 
S 1 2 1 1666 agerEmulatorProcessQueue RETRANSMIT DISCARD umacListHead = %x, umacListTail = %x 
S 1 2 1 1704 agerEmulatorProcessQueue NOT RETRANSMIT PDs TtlCount = %d
S 1 2 1 1724 agerEmulatorProcessQueue NOT RETRANSMIT DISCARD liberatorListHead = %x, liberatorListTail = %x
S 1 2 1 1748 agerEmulatorProcessQueue pHeadDesc = %x , pTailDesc = %x , numberOfDiscardedPds = %d 
S 1 2 1 1785 agerEmulatorProcessQueue AGER_EMULATOR_FIRST_PART_OF_BITMAP pdIndex = %d , currentPacketDescriptor = %x , amsduTail = %x , notDiscardedListHead = %x, notDiscardedListTail = %x
S 1 2 1 1813 agerEmulatorProcessQueue AGER_EMULATOR_FIRST_PART_OF_BITMAP pdIndex = %d , currentPacketDescriptor = %x , amsduTail = %x , notDiscardedListHead = %x, notDiscardedListTail = %x
S 1 2 1 1822 agerEmulatorProcessQueue NOT DISCARDED LIST notDiscardedListHead = %x, notDiscardedListTail = %x
S 1 2 1 1833 agerEmulatorProcessQueue LIBERATOR LIST liberatorListHead = %x, liberatorListTail = %x
S 1 2 1 1842 agerEmulatorProcessQueue UMAC LIST umacListHead = %x, umacListTail = %x
S 1 58 0 222 Assert in file: "Qos.c" in line: 222
S 1 58 0 633 [qosSingleCheckDone]
S 1 58 0 664 [qosSingleCheckDone], numberOfFreePdsNeeded = %d, currentNumberOfFreePds = %d
S 1 58 0 671 [qosSingleCheckDone], QosAgerSingleCheckConfigurationParameters.maximumPdsToDiscard = %d, QosSingleCheckParameters.currentPdLimitIndex = %d
S 1 58 0 678 [qosSingleCheckDone], QosSingleCheckParameters.currentTtl = %d
S 1 58 0 736 [qosSingleCheckDone] stop single check
S 1 58 0 996 [qosPdThresholdConfig], QoSPdThresholdDb.mode = %d, config->mode = %d, config->minPdDiff = %d , config->minPdAmount = %d 
S 1 58 0 999 Assert in file: "Qos.c" in line: 999
S 1 58 0 1022 [qosPdThresholdConfig], in QOS_PD_THRESHOLD_DISABLED
S 1 58 0 1240 Assert in file: "Qos.c" in line: 1240
S 1 58 0 1298 Assert in file: "Qos.c" in line: 1298
S 1 58 0 1479 Qos, Send Confirmation, Client %d, stationIndex %d
S 1 58 0 1543 Assert in file: "Qos.c" in line: 1543
S 1 58 0 1585 [DROP_DEBUG][QosSetAgerParams] hostInterfaceAcceleratorFreePdsThreshold = %d freePdsHysteresisNumber = %d pollingTimer = %d
S 1 29 23 629 sendChannelParams. Call Requester: %d 
S 1 29 23 644 hdkChannelNotificationCb
S 1 29 23 700 Assert in file: "HdkTask.c" in line: 700
S 1 29 23 721 Assert in file: "HdkTask.c" in line: 721
S 1 29 23 849 Fatal Error in file: "HdkTask.c"; Fatal Print:  In case we're running on FPGA,  we should't get here 
S 1 29 23 856 HDK_startUserDemandProcess. temp1 %d temp2 %d temp3 %d
S 1 29 23 1063 limitFromHost %d, limitFromEfuse %d
S 1 29 23 1081 Assert in file: "HdkTask.c" in line: 1081
S 1 29 23 1144 HDK event: HDK_EVENT_ADD_FIRST_VAP. current state: %d
S 1 29 23 1153 HDK event: HDK_EVENT_REMOVE_LAST_VAP. current state: %d
S 1 29 23 1167 HDK event: HDK_EVENT_ENABLE_RF. current state: %d
S 1 29 23 1175 HDK event: HDK_EVENT_DISABLE_RF. current state: %d
S 1 29 23 1187 HDK event: HDK_EVENT_CALIBRATE. current state: %d
S 1 29 23 1198 HDK event: HDK_EVENT_SET_CHANNEL. current state: %d
S 1 29 23 1207 HDK event: HDK_EVENT_ONLINE_TIMER_EXPIRED. current state: %d
S 1 29 23 1220 HDK event: HDK_EVENT_SET_ANTENNAS. current state: %d
S 1 29 23 1229 HDK event: HDK_EVENT_USER_DEMAND. current state: %d
S 1 29 23 1241 Set Channel event: SET_CHANNEL_EVENT_SET_FREQUENCY. current state: %d
S 1 29 23 1250 Set Channel event: SET_CHANNEL_EVENT_FREQUENCY_SET. current state: %d
S 1 29 23 1259 Set Channel event: SET_CHANNEL_EVENT_CAL_RESULTS_LOADED. current state: %d
S 1 29 23 1268 Set Channel event: SET_CHANNEL_EVENT_OFFLINE_CAL_DONE. current state: %d
S 1 29 23 1277 Set Channel event: SET_CHANNEL_EVENT_CAL_RESULTS_STORED. current state: %d
S 1 29 23 1286 Set Channel event: SET_CHANNEL_EVENT_CHANNEL_NOTIFICATION_DONE. current state: %d
S 1 29 23 1295 Set Channel event: SET_CHANNEL_EVENT_REMOVE_LAST_VAP. current state: %d
S 1 29 23 1306 HDK Process event: HDK_PROCESS_EVENT_SCHEDULE_PROCESS_REQ. current state: %d proc: %d
S 1 29 23 1315 HDK Process event: HDK_PROCESS_EVENT_PROCESS_SCHEDULED. current state: %d proc: %d
S 1 29 23 1324 HDK Process event: HDK_PROCESS_EVENT_PROCESS_FINISHED. current state: %d proc: %d
S 1 29 23 1333 HDK Process event: HDK_PROCESS_EVENT_EXECUTION_COMPLETED. current state: %d proc: %d
S 1 29 23 1435 Assert in file: "HdkTask.c" in line: 1435
S 1 29 23 1551 FREEEEEE MSG............
S 1 29 23 1647 Assert in file: "HdkTask.c" in line: 1647
S 1 29 23 1709 Assert in file: "HdkTask.c" in line: 1709
S 1 29 23 1794 Assert in file: "HdkTask.c" in line: 1794
S 1 29 23 1804 Assert in file: "HdkTask.c" in line: 1804
S 1 29 23 1814 setHdkMainSmState. state: %d
S 1 29 23 1826 setSetChannelSmState. state: %d
S 1 29 23 1840 setHdkProcessSmState. state: %d
S 1 29 23 1852 setHdkProcessId. processId: %d
S 1 29 23 1865 setFreqJumpSmState. state: %d
S 1 29 23 2361 Assert in file: "HdkTask.c" in line: 2361
S 1 29 23 2442 Assert in file: "HdkTask.c" in line: 2442
S 1 29 23 2495 Assert in file: "HdkTask.c" in line: 2495
S 1 29 23 2499 Assert in file: "HdkTask.c" in line: 2499
S 1 29 23 2657 BITMAP FJ_CHANNEL_STATE m_curOfflineProcBitmap = %d
S 1 29 23 2761 Freq Jump event 2 + 3: FREQ_JUMP_EVENT_NEXT_BW. current state: %d
S 1 29 23 2768 Freq Jump event 4 done: FREQ_JUMP_EVENT_CAL_DONE. current state: %d
S 1 29 23 2779 Assert in file: "HdkTask.c" in line: 2779
S 1 29 23 2875 SWITCH TYPE REAL FJ  %d ++++++++ 
S 1 29 23 2898 +++++FREQ JUMP HNDLR++++++++	
S 1 29 23 2915 INTO NextBW %d & Restore RestoreOriginParms 
S 1 29 23 2931 NextBW %d NOT the LAST. fill params 
S 1 29 23 2941 LOOPPPPPPPP ======= no send param
S 1 46 2 123 Assert in file: "MT_FifoQ.c" in line: 123
S 1 46 2 174 Assert in file: "MT_FifoQ.c" in line: 174
S 1 46 2 179 Assert in file: "MT_FifoQ.c" in line: 179
S 1 46 2 192 Assert in file: "MT_FifoQ.c" in line: 192
S 1 46 2 222 Assert in file: "MT_FifoQ.c" in line: 222
S 1 46 2 227 Assert in file: "MT_FifoQ.c" in line: 227
S 1 46 2 255 Assert in file: "MT_FifoQ.c" in line: 255
S 1 46 2 289 Assert in file: "MT_FifoQ.c" in line: 289
S 1 46 2 294 Assert in file: "MT_FifoQ.c" in line: 294
S 1 46 2 305 Assert in file: "MT_FifoQ.c" in line: 305
S 1 39 2 452 Fatal Error in file: "System_MipsTimers.c"; Fatal Print: Rx Pasue Timer isn't used in Wave500B
S 1 39 2 543 Assert in file: "System_MipsTimers.c" in line: 543
S 1 39 2 567 Assert in file: "System_MipsTimers.c" in line: 567
S 1 8 0 619 Assert in file: "BeaconHandler.c" in line: 619
S 1 8 0 643 Assert in file: "BeaconHandler.c" in line: 643
S 1 8 0 667 Assert in file: "BeaconHandler.c" in line: 667
S 1 8 0 692 beaconHandlerSendTemplateWasSetIndication for vap:%d
S 1 8 0 879 Assert in file: "BeaconHandler.c" in line: 879
S 1 8 0 880 Assert in file: "BeaconHandler.c" in line: 880
S 1 8 0 915 Assert in file: "BeaconHandler.c" in line: 915
S 1 8 0 923 Assert in file: "BeaconHandler.c" in line: 923
S 1 8 0 987 Assert in file: "BeaconHandler.c" in line: 987
S 1 8 0 1329 Assert in file: "BeaconHandler.c" in line: 1329
S 1 8 0 1492 Assert in file: "BeaconHandler.c" in line: 1492
S 1 8 0 1631 Assert in file: "BeaconHandler.c" in line: 1631
S 1 8 0 1705 Assert in file: "BeaconHandler.c" in line: 1705
S 1 8 0 1797 Assert in file: "BeaconHandler.c" in line: 1797
S 1 8 0 1866 Assert in file: "BeaconHandler.c" in line: 1866
S 1 8 0 1915 Assert in file: "BeaconHandler.c" in line: 1915
S 1 8 0 2083 Assert in file: "BeaconHandler.c" in line: 2083
S 1 8 0 2341 Assert in file: "BeaconHandler.c" in line: 2341
S 1 8 0 2383 Assert in file: "BeaconHandler.c" in line: 2383
S 1 8 0 2464 Assert in file: "BeaconHandler.c" in line: 2464
S 1 8 0 2502 Assert in file: "BeaconHandler.c" in line: 2502
S 1 8 0 2538 Assert in file: "BeaconHandler.c" in line: 2538
S 1 8 0 2749 Assert in file: "BeaconHandler.c" in line: 2749
S 1 8 0 2771 Assert in file: "BeaconHandler.c" in line: 2771
S 1 8 0 2793 Assert in file: "BeaconHandler.c" in line: 2793
S 1 8 0 2815 Assert in file: "BeaconHandler.c" in line: 2815
T 1 42 20 173 DynamicTxopDB_t
T 1 50 0 533 PtaDb_t
T 1 50 0 534 PtaRepetitionParams_t
T 1 6 0 267 BaaTxReport_t
T 1 7 1 304 BaaTxReport_t
T 1 9 0 227 PacManagerStart_t
T 1 15 0 191 UMI_MIB
T 1 17 2 161 metricFifoEntry_t
T 1 19 0 333 dutMessageHeader_t
T 1 19 1 153 dutChipVersion_t
T 1 19 1 214 dutSetAntennaParams_t
T 1 19 1 246 LinkAdaptationFixedAntennaSelection_t
T 1 19 1 272 dutSetAntennaParams_t
T 1 19 1 375 dutTxSpacelessParams_t
T 1 19 1 485 dutIfsParams_t
T 1 19 1 537 dutRssiParams_t
T 1 19 1 594 dutTpcFeedbackparams_t
T 1 19 1 715 dutRficRxGainsParams_t
T 1 19 1 737 dutXtalParams_t
T 1 19 1 757 dutXtalParams_t
T 1 19 1 800 dutMemoryAccessParams_t
T 1 19 1 840 dutMemoryAccessParams_t
T 1 19 1 958 dutTpcFeedbackparams_t
T 1 19 1 979 dutRficTxGainsParams_t
T 1 33 7 415 ENET_RXF
T 1 44 2 190 UmiLoggerMsgSetFilter_t
T 1 44 2 273 UmiLoggerMsgSetMode_t
T 1 44 2 340 UmiLoggerMsgFlushBuffer_t
T 1 78 0 420 GroupCombinationTableDebug_t
T 1 78 0 1147 TrainingVectorDebugStruct_t
T 1 78 0 1212 TrainingManagerStaBitmap_t
T 1 78 0 1221 TrainingManagerStaBitmap_t
T 1 78 0 1360 GroupManagerStationBitmap_t
T 1 78 0 1718 MuEffectiveRateDbRamEntry_u
T 1 78 0 1767 MuEffectiveRateDbRamEntry_u
T 1 78 0 1831 MuEffectiveRateDbRamEntry_u
T 1 78 0 1898 MuEffectiveRateDbRamEntry_u
T 1 78 0 1962 MuEffectiveRateDbRamEntry_u
T 1 78 0 2023 MuEffectiveRateDbRamEntry_u
T 1 78 0 2087 MuEffectiveRateDbRamEntry_u
T 1 78 0 2156 MuEffectiveRateDbRamEntry_u
T 1 78 0 2227 MuEffectiveRateDbRamEntry_u
T 1 78 0 2298 MuEffectiveRateDbRamEntry_u
T 1 78 0 2370 MuEffectiveRateDbRamEntry_u
T 1 78 0 2514 MuEffectiveRateDbRamEntry_u
T 1 78 0 2551 MuEffectiveRateDbRamEntry_u
T 1 78 0 2602 MuEffectiveRateDbRamEntry_u
T 1 78 0 2669 MuEffectiveRateDbRamEntry_u
T 1 78 0 2736 MuEffectiveRateDbRamEntry_u
T 1 78 0 2800 MuEffectiveRateDbRamEntry_u
T 1 78 0 2866 MuEffectiveRateDbRamEntry_u
T 1 78 0 2939 MuEffectiveRateDbRamEntry_u
T 1 78 0 3014 MuEffectiveRateDbRamEntry_u
T 1 78 0 3088 MuEffectiveRateDbRamEntry_u
T 1 78 0 3164 MuEffectiveRateDbRamEntry_u
T 1 78 0 3341 GroupCombinationTableEntry_t
T 1 19 2 171 dutPowerOutVecParams_t
T 1 19 2 182 dutPowerOutVecParams_t
T 1 19 2 240 RssiGainBlock_t
T 1 19 2 251 RssiCwPower_t
T 1 19 2 259 S2dParams_t
T 1 19 2 270 DutRssiOffsetGain_t
T 1 19 2 280 RssiDBPower_t
T 1 19 2 294 Clipping_trigger_t
T 1 19 2 331 dutLnaMidGain_t
T 1 19 2 409 clbrHndlrResetConf_t
T 1 19 2 427 dutStartCalibrationParams_t
T 1 19 2 428 dutDB_t
T 1 19 2 658 dutSetRate_t
T 1 19 2 678 LaFixedRateParams_t
T 1 19 2 707 dutGetFwInfo_t
T 1 19 3 261 dutTxParams_t
T 1 19 3 278 trafficParams_t
T 1 19 3 455 FM_PAYLOAD_MANAGEMENT_ACTION_PUBLIC_FRAME
T 1 19 3 471 manPacketDescriptor_t
T 1 28 18 725 ClbrMngr_TemperatureDB_t
T 1 28 18 726 ClbrMngr_OnlineCalibDB_t
T 1 28 18 789 ClbrMngr_CalibrateDB_t
T 1 28 18 834 ClbrMngr_CalibrateDB_t
T 1 42 18 280 LaTcrModificationStruct_t
T 1 11 0 190 UM_SET_CHAN_PARAMS
T 1 32 0 1285 UMI_MULTICAST_MODE
T 1 10 2 301 UMI_ADD_VAP
T 1 10 2 418 UMI_SET_BSS
T 1 10 2 585 UMI_SET_WMM_PARAMETERS
T 1 10 2 794 UMI_STOP_VAP_TRAFFIC
T 1 10 2 1083 VAP_MANAGER_REGISTRATION_ELEMENT
T 1 42 16 1292 overridePendingDb_t
T 1 42 0 146 AntennaSelectionDatabase_t
T 1 42 0 160 AntennaSelectionDatabase_t
T 1 42 0 194 AntennaSelectionDatabase_t
T 1 42 0 483 AntennaSelectionDatabase_t
T 1 42 19 411 RateMask_t
T 1 42 19 793 RateMask_t
T 1 42 19 794 RateMask_t
T 1 42 19 818 RateMask_t
T 1 42 19 837 RateMask_t
T 1 42 19 838 RateMask_t
T 1 42 6 341 LaTcrModificationStruct_t
T 1 42 4 1237 LaStationGroupCommonParams_t
T 1 42 4 1238 LaStationUspCommonParams_t
T 1 42 4 1242 LaStationUniqueParams_t
T 1 42 4 1246 LaGroupUniqueParams_t
T 1 42 4 2268 SequencerTxReport_t
T 1 42 5 927 SequencerTxReport_t
T 1 42 5 2262 RateMask_t
T 1 30 2 1806 SetChannelParams_t
T 1 85 0 846 UMI_MBSS_PRE_ACTIVATE
T 1 85 0 1332 UMI_SET_KEY
T 1 85 0 1490 UMI_GROUP_PN
T 1 85 0 3140 UMI_STA_ADD
T 1 85 0 3188 UMI_STA_REMOVE
T 1 85 0 3437 UMI_DATA_PATH_INIT_PARAMS
T 1 85 0 3518 UMI_REQUEST_SID
T 1 85 0 3576 UMI_REMOVE_SID
T 1 85 0 3646 UMI_TS_VAP_CONFIGURE
T 1 85 0 3668 UMI_MSDU_IN_AMSDU_CONFIG
T 1 85 0 3721 UMI_RTS_MODE_CONFIG
T 1 85 0 3748 UMI_MAX_MPDU
T 1 85 0 3897 UMI_FIXED_RATE_CONFIG
T 1 85 0 3935 UMI_SET_TXOP_CONFIG_t
T 1 85 0 3975 UMI_ATF_QUOTAS
T 1 85 0 4052 UMI_BeaconBlockTimerInterval_t
T 1 85 0 4105 UMI_FAST_DROP_CONFIG_REQ_t
T 1 85 0 4187 UMI_STOP_TRAFFIC
T 1 85 0 4232 UMI_FRAME_CLASS_ERROR
T 1 85 0 4273 UMI_TKIP_MIC_FAILURE
T 1 85 0 4430 UMI_SET_PD_THRESH
T 1 85 0 4465 UMI_SET_RESTRICTED_AC
T 1 85 0 5414 UMI_SET_2_4_G_COEX
T 1 29 23 630 ChannelNotificationParams_t
T 1 29 23 645 ChannelNotificationParams_t
T 1 29 23 683 UmiHwDependentConfig_t
T 1 29 23 762 tpcConfig_t
T 1 29 23 784 UMI_HDK_CONFIG
T 1 29 23 1191 UMI_CALIBRATE_PARAMS
T 1 29 23 2057 cocReq_t
T 1 29 23 2151 UmiHwDependentConfig_t
T 1 29 23 2939 HdkSetChannelReqParams_t
T 1 29 23 2940 HdkSetChannelReqParams_t
