#!/bin/sh
# Remove a VAP 
# Needed object: None

script_name="$0"

[ ! "$LIB_COMMON_SOURCED" ] && . /tmp/fapi_wlan_wave_lib_common.sh

interface_name=$1

# Find the radio index
radio_name=${interface_name%%.*}
radio_index=`find_index_from_interface_name $radio_name`

print2log $radio_index DEBUG "$script_name $*"
timestamp $radio_index "$script_name:begin"

pid=$$

# Only remove a VAP if it isn't a radio interface.
is_vap=`check_is_vap $interface_name`
if [ "$is_vap" = "true" ]
then
	# Remove VAP name VAPs list
	sed -i '/'$interface_name'/d' ${VAPS_LIST}_${radio_name}
	# Remove all the conf files related to this interface
	prepare_confs $interface_name $radio_name $pid $VAP ssid_delete
	echo "restart_${interface_name%%.*}=yes" >> ${CONF_DIR}/${RESTART_FLAG}_${radio_name}
fi

# Call the up script to restart the interfaces without the removed VAP
${ETC_PATH}/fapi_wlan_wave_up $radio_name

# Create the output configuration file
cat /dev/null > ${OUT_CONF}

# Configuration is completed successfully
update_conf_out "wlan_configuration_status" "success"

# DEBUG: set debug_save_conf in fapi_wlan_wave_lib_common.sh to save the out conf file
[ "$debug_save_conf" ] && cp ${OUT_CONF} ${CONF_DIR}/ssid_delete_out_conf

print2log $radio_index DEBUG "$script_name done"
timestamp $radio_index "$script_name:done"
