#!/bin/sh
# Return the Radio State
# Needed object: None

script_name="$0"

[ ! "$LIB_COMMON_SOURCED" ] && . /tmp/fapi_wlan_wave_lib_common.sh

interface_name=$1

# Find the radio index
radio_index=`find_index_from_interface_name $interface_name`

# If interface name is not supplied, exit script
[ -z "$interface_name" ] && print2log $radio_index ALERT "$script_name: interface_name is missing. exit execution" && exit 1

local_db_source RADIO

print2log $radio_index DEBUG "$script_name $*"
timestamp $radio_index "$script_name:begin"

radio_state=`db2fapi_convert boolean Enable $radio_index`

# Create the output configuration file and add state value
cat /dev/null > ${OUT_CONF}
update_conf_out "Object_0" "$RADIO_OBJECT"
update_conf_out "Enable_0" "$radio_state"

# Configuration is completed successfully
update_conf_out "wlan_configuration_status" "success"

# DEBUG: set debug_save_conf in fapi_wlan_wave_lib_common.sh to save the out conf file
[ "$debug_save_conf" ] && cp ${OUT_CONF} ${CONF_DIR}/radio_state_query_${interface_name}

print2log $radio_index DEBUG "$script_name done"
timestamp $radio_index "$script_name:$interface_name:done"
