#!/bin/sh
# Add interface to bridge
# Called when event of bridge enabled was received
# Needed object: None

script_name="$0"

[ ! "$LIB_COMMON_SOURCED" ] && . /tmp/fapi_wlan_wave_lib_common.sh

interface_name=$1
pid=$$

# Find the interface index and the radio index
interface_index=`find_index_from_interface_name $interface_name`
local_db_source SSID

ssid_type=`db2fapi_convert regular X_LANTIQ_COM_Vendor_SsidType $interface_index`
if [ "$ssid_type" = "EndPoint" ]
then
	ap_type="$STA"
	radio_name=`get_radio_name_from_endpoint $interface_name`
	local_db_source ENDPOINT
	conf_in_progress_interface=$interface_name
elif [ "$ssid_type" = "Radio" ]
then
	ap_type="$AP"
	radio_name=${interface_name%%.*}
	local_db_source ACCESSPOINT
	conf_in_progress_interface=$radio_name
else
	ap_type="$VAP"
	radio_name=${interface_name%%.*}
	local_db_source ACCESSPOINT
	conf_in_progress_interface=$radio_name
fi
radio_index=`find_index_from_interface_name $radio_name`

print2log $radio_index DEBUG "$script_name $*"
timestamp $radio_index "$script_name:begin"

# Read the bridge name
bridge_name=`db2fapi_convert regular X_LANTIQ_COM_Vendor_BridgeName $interface_index`

# Create the output configuration file
cat /dev/null > ${OUT_CONF}

# Check if need to re-add the interface to the bridge
interface_in_bridge=`brctl show | grep -w $interface_name -c`
# Check if interface is enabled
interface_enabled=`db2fapi_convert boolean Enable $interface_index`
if [ $interface_in_bridge -eq 0 ] && [ "$interface_enabled" = "1" ]
then
	# Prepare the temporary configuration files to use
	prepare_confs $interface_name $conf_in_progress_interface $pid $ap_type
	# Get the pid to use in this configuration session
	. ${CONF_IN_PROGRESS}_${conf_in_progress_interface}

	# Set the restart flag to re-add the interfaces to the bridge
	echo "restart_${interface_name%%.*}=yes" >> ${CONF_DIR}/${RESTART_FLAG}_${conf_in_progress_interface}
fi
# Configuration is completed successfully
update_conf_out "wlan_configuration_status" "success"

# DEBUG: set debug_save_conf in fapi_wlan_wave_lib_common.sh to save the out conf file
[ "$debug_save_conf" ] && cp ${OUT_CONF} ${CONF_DIR}/add_to_bridge_${interface_name}

print2log $radio_index DEBUG "$script_name done"
timestamp $radio_index "$script_name:done"
