#!/bin/sh
# Return the MAC address of an interface
# Needed object: None

script_name="$0"

[ ! "$LIB_COMMON_SOURCED" ] && . /tmp/fapi_wlan_wave_lib_common.sh

interface_name=$1

# Find the interface index and the radio index
interface_index=`find_index_from_interface_name $interface_name`
radio_name=${interface_name%%.*}
radio_index=`find_index_from_interface_name $radio_name`

# If interface name is not supplied, exit script
[ -z "$interface_name" ] && print2log $radio_index ALERT "$script_name: interface_name is missing. exit execution" && exit 1

local_db_source SSID

print2log $radio_index DEBUG "$script_name $*"
timestamp $radio_index "$script_name:begin"

mac_address=`db2fapi_convert regular MACAddress $interface_index`

# Create the output configuration file and add state value
cat /dev/null > ${OUT_CONF}
update_conf_out "Object_0" "$SSID_OBJECT"
update_conf_out "MACAddress_0" "$mac_address"

# Configuration is completed successfully
update_conf_out "wlan_configuration_status" "success"

# DEBUG: set debug_save_conf in fapi_wlan_wave_lib_common.sh to save the out conf file
[ "$debug_save_conf" ] && cp ${OUT_CONF} ${CONF_DIR}/mac_address_query_${interface_name}

print2log $radio_index DEBUG "$script_name done"
timestamp $radio_index "$script_name:$interface_name:done"
