#!/bin/sh
# complete recovery - un-init and recovery to the state of the last known DB.
# Needed param: interface_name

script_name="$0"
interface_name="$1"

if [ -e /opt/lantiq/wave/scripts/fapi_wlan_wave_lib_common.sh ]
then
	. /opt/lantiq/wave/scripts/fapi_wlan_wave_lib_common.sh
elif [ -e /etc/wave/scripts/fapi_wlan_wave_lib_common.sh ]
then
	. /etc/wave/scripts/fapi_wlan_wave_lib_common.sh
fi

echo "$script_name:begin" > /dev/console

if [ ! -e "$INIT_COMPLETE_RECOVERY_FLAG" ]; then

	touch $INIT_COMPLETE_RECOVERY_FLAG

	echo "$script_name:complete recovery in progress trigger by $interface_name" > /dev/console

	if [ -e $FAPI_RPC ]
	then
		fapi_wlan_cli reset
	else
		${ETC_PATH}/fapi_wlan_wave_hw_uninit
		${ETC_PATH}/fapi_wlan_wave_recovery_init
	fi
else
	echo "$script_name:complete recovery in progress cannot re-started for $interface_name" > /dev/console
fi

update_conf_out "wlan_configuration_status" "success"

echo "$script_name:done" > /dev/console
