#!/bin/sh
# Init Wave driver from clean environment for complete recovery
# Needed object: None

script_name="$0"

if [ -e /opt/lantiq/wave/scripts/fapi_wlan_wave_lib_common.sh ]
then
	. /opt/lantiq/wave/scripts/fapi_wlan_wave_lib_common.sh
elif [ -e /etc/wave/scripts/fapi_wlan_wave_lib_common.sh ]
then
	. /etc/wave/scripts/fapi_wlan_wave_lib_common.sh
fi

echo "$script_name:begin" > /dev/console

# make sure  un-init was done before.
if [ ! -e ${CONF_DIR}/runner_hw_init.sh ]
then
		build_wlan_notification "servd" "NOTIFY_WIFI_WLAN_INIT" "complete_recovery"
else
	echo "$script_name: un-init must be done before complete recovery" > /dev/console
fi

update_conf_out "wlan_configuration_status" "success"

echo "$script_name:done" > /dev/console
