#!/bin/sh
# fapi_wlan_wave_wavflow_init (called from fapi_wlan_wavflow_init)
# Bring up the interfaces of a Wave radio
# Needed object: None
#set -ex
#set -o errtrace

script_name="$0"

echo " ############################## $script_name ############################## "

[ ! "$LIB_COMMON_SOURCED" ] && . /tmp/fapi_wlan_wave_lib_common.sh

# Activate the listener during the init - it'll enable the radio for all existing AP interfaces
/usr/lib/fapi_wlan_beerock_cli INIT

cat /dev/null > ${OUT_CONF}

update_conf_out "wlan_configuration_status" "success"