#!/bin/sh

script_name="$0"

[ ! "$LIB_COMMON_SOURCED" ] && . /tmp/fapi_wlan_wave_lib_common.sh
[ ! "$RC_CONF_SOURCED" ] && rc_conf_source

ap_index=$1
[ -z "$ap_index" ] && print2log 0 ERROR "$script_name is missing the ap index, aborting" && return

timestamp $ap_index "$script_name:$ap_index:begin"
print2log $ap_index DEBUG "$script_name $*"

eval interface_name=\${wlmnwave_${ap_index}_interfaceName}

# Last scan results can be retrieved from a file saved after last scan or using the iw call
if [ ! -e ${TEMP_CONF_DIR}/${interface_name}_scan_MAPI.result ]
then
	# Get scan results of last scan (may be empty if the linux kernel cleaned the scan results)
	iw dev $interface_name scan dump > ${TEMP_CONF_DIR}/${interface_name}_scan.dump
	# Parse the scan results to a MAPI format and source the output file
	cat ${TEMP_CONF_DIR}/${interface_name}_scan.dump | awk -v output="MAPI" -f ${ETC_PATH}/fapi_wlan_wave_ap_scan_parse.awk > ${TEMP_CONF_DIR}/${interface_name}_scan_MAPI.result
fi

cat ${TEMP_CONF_DIR}/${interface_name}_scan_MAPI.result

print2log $ap_index DEBUG "$script_name done"
timestamp $ap_index "$script_name:$ap_index:done"
