#!/bin/sh /etc/rc.common

START=99
STOP=80
CONFIG_FILE=/tmp/etc/dnsmasq.d/dc1.conf

start() {
	local enable
	enable=$(uci get dc1svr.@dc1svr[0].enabled)
	if [ $enable -eq 1 ]; then
		/usr/DC1/dc1svr &
	fi
	mkdir -p /tmp/dnsmasq.d
	echo "address=/Smartplugconnect.phicomm.com/$(uci get network.@lan.ipaddr)" > $CONFIG_FILE
	/etc/init.d/dnsmasq restart >/dev/null 2>&1
}

stop() {
killall dc1svr
rm $CONFIG_FILE
/etc/init.d/dnsmasq restart >/dev/null 2>&1
}

