#!/bin/sh

script_name="wave_wlan_get_logger_stream_info"

[ ! "$LIB_COMMON_SOURCED" ] && . /tmp/wave_wlan_lib_common.sh
[ ! "$LIB_LOGGER_SOURCED" ] && . /tmp/wave_wlan_lib_logger.sh
[ ! "$RC_CONF_SOURCED" ] && rc_conf_source

# Define local parameters
local ap_index component_id source_ip source_mac

ap_index=$1
component_id=$2

# Get the source IP and MAC address
### Currently (only FW streams are supported): the source MAC is a MAC address not known to the bridge and the source IP is the bridge IP
#source_mac=`get_source_mac $ap_index $component_id`
#source_ip=`get_source_ip $ap_index $component_id`
source_mac="00:00:00:00:00:10"
eval source_ip=\${lan_main_0_ipAddr}

echo "sourceIp=\"$source_ip\""
echo "sourceMac=\"$source_mac\""

print2log $ap_index DEBUG "$script_name done"
timestamp "$script_name:$ap_index:done"
