#!/bin/sh

script_name="wave_wlan_wps_trigger_pin"

[ ! "$LIB_COMMON_SOURCED" ] && . /tmp/wave_wlan_lib_common.sh
[ ! "$LIB_WPS_SOURCED" ] && . /tmp/wave_wlan_lib_wps.sh
[ ! "$RC_CONF_SOURCED" ] && rc_conf_source

# Define local parameters
local ap_index interface_name
local enrollee_pin enrollee_mac

ap_index=$1
enrollee_pin=$2
enrollee_mac=$3

[ -z "$ap_index" ] && print2log 0 ERROR "$script_name is missing the ap index, aborting" && return

timestamp $ap_index "$script_name:$ap_index:begin"
print2log $ap_index DEBUG "$script_name $*"

eval interface_name=\${wlmnwave_${ap_index}_interfaceName}

print2log $ap_index WPS "The button 'Connect' for PIN connection was activated for $interface_name with PIN=$enrollee_pin and MAC=$enrollee_mac"
# Save PIN and MAC of STA in temp files
echo "enrollee_pin=$enrollee_pin" > $WPS_PIN_TEMP_FILE
echo "enrollee_mac=$enrollee_mac" >> $WPS_PIN_TEMP_FILE

wps_connect_via_pin $ap_index $interface_name $enrollee_pin $enrollee_mac

print2log $ap_index DEBUG "$script_name done"
timestamp $ap_index "$script_name:$ap_index:done"
