#!/bin/sh

script_name="wave_wlan_get_logger_info"

[ ! "$LIB_COMMON_SOURCED" ] && . /tmp/wave_wlan_lib_common.sh
[ ! "$RC_CONF_SOURCED" ] && rc_conf_source

# Define local parameters
local max_fw_debug max_driver_debug max_config_debug max_hostapd_debug

# Read the debug level the components were compiled with.
# TODO: remove comment once iwprivs are supported by driver
#max_fw_debug=`iwpriv wlan0 gCompiledFwDebugLevel`
#max_driver_debug=`iwpriv wlan0 gCompiledDriverDebugLevel`
max_fw_debug=7
max_driver_debug=7
max_config_debug=7
max_hostapd_debug=4

echo "maxFwDebugLevel=\"$max_fw_debug\""
echo "maxDriverDebugLevel=\"$max_driver_debug\""
echo "maxConfigurationsDebugLevel=\"$max_config_debug\""
echo "maxHostapdDebugLevel=\"$max_hostapd_debug\""

print2log $ap_index DEBUG "$script_name done"
timestamp "$script_name:$ap_index:done"
