#!/bin/sh

script_name="wave_wlan_uninit"

# If wave_wlan_lib_common.sh link in /tmp is broken, source directly from /etc/rc.d
if [ ! "$LIB_COMMON_SOURCED" ]
then
	if [ -e /tmp/wave_wlan_lib_common.sh ]
	then
		. /tmp/wave_wlan_lib_common.sh
	else
		. /etc/rc.d/wave_wlan_lib_common.sh
	fi
fi
[ ! "$RC_CONF_SOURCED" ] && rc_conf_source

# Define local parameters
local ap_index
local mtlk_genl_family_id

ap_index=`find_index_from_wave_if wlan0`
timestamp $ap_index "$script_name:$ap_index:begin"
print2log $ap_index DEBUG "$script_name $*"

# Delete the runner file
rm -f $CONF_DIR/$WAVE_WLAN_RUNNNER

# rmmod HS2.0 related drivers
echo "(. $ETC_PATH/wave_wifi_parp_ctrl.sh stop)" >> $CONF_DIR/$WAVE_WLAN_RUNNNER
echo "(. $ETC_PATH/wave_wifi_l2f_ctrl.sh stop)" >> $CONF_DIR/$WAVE_WLAN_RUNNNER
echo "(. $ETC_PATH/wmdctrl.sh stop)" >> $CONF_DIR/$WAVE_WLAN_RUNNNER

# rmmod WAVE driver
if [ `lsmod | grep "mtlk " -c` -gt 0  ]
then
	# In mtlkroot.ko insmod we pass to the driver the Netlink ID to reuse it on Netlink create.
	# Therefore, before removing driver, use iwpriv to read the ID that the kernel allocated, save it in file.
	mtlk_genl_family_id=`iwpriv wlan0 gGenlFamilyId | sed 's/.*gGenlFamilyId://'`
	if [ "$mtlk_genl_family_id" != "" ]
	then
		echo "echo $mtlk_genl_family_id > $GENL_FAMILY_ID_FILE" >> $CONF_DIR/$WAVE_WLAN_RUNNNER
	fi
	echo "rmmod mtlk" >> $CONF_DIR/$WAVE_WLAN_RUNNNER
	#TODO: add check for rmmod success.
fi

# Bring down the logger interface and remove it from the bridge
echo "ifconfig rtlog0 down" >> $CONF_DIR/$WAVE_WLAN_RUNNNER
echo "brctl delif br0 rtlog0" >> $CONF_DIR/$WAVE_WLAN_RUNNNER

# rmmod RTLogger
if [ `lsmod | grep -c "mtlkroot"` -gt 0 ]
then
	echo "killall mtdump 2>/dev/null" >> $CONF_DIR/$WAVE_WLAN_RUNNNER
	# Unload driver
	echo "rmmod mtlkroot" >> $CONF_DIR/$WAVE_WLAN_RUNNNER
	#TODO: add check for rmmod success.
fi
# Stop drvhlpr
echo "killall drvhlpr 2>/dev/null" >> $CONF_DIR/$WAVE_WLAN_RUNNNER
echo "drvhlpr_count=\`ps | grep drvhlpr -c\`" >> $CONF_DIR/$WAVE_WLAN_RUNNNER
echo "while [ "\$drvhlpr_count" -gt 1 ]; do sleep 1; drvhlpr_count=\`ps | grep drvhlpr -c\`; done" >> $CONF_DIR/$WAVE_WLAN_RUNNNER

# Remove related soflinks and folder from /tmp/
echo "cd /tmp/" >> $CONF_DIR/$WAVE_WLAN_RUNNNER
echo "rm -rf $TEMP_CONF_DIR mtlk*.ko fw_scd_file.scd /tmp/wave_wlan_* /tmp/drvhlpr_* \`cd $IMAGES_PATH/; ls *; cd - > /dev/null\`" >> $CONF_DIR/$WAVE_WLAN_RUNNNER

# Execute the runner
chmod +x $CONF_DIR/$WAVE_WLAN_RUNNNER
$CONF_DIR/$WAVE_WLAN_RUNNNER

print2log $ap_index DEBUG "$script_name done"
timestamp $ap_index "$script_name:$ap_index:done"
