#!/bin/sh

script_name="wave_wlan_stop"

[ ! "$LIB_COMMON_SOURCED" ] && . /tmp/wave_wlan_lib_common.sh
[ ! "$RC_CONF_SOURCED" ] && rc_conf_source

# Define local parameters
local ap_index
local config_command i radio_cpe_id vendor i_ap_type

# TODO: add check if wlan0 exists before trying to read its parameters.
ap_index=`find_index_from_wave_if wlan0`
timestamp $ap_index "$script_name:$ap_index:begin"
print2log $ap_index DEBUG "$script_name $*"

(. $ETC_PATH/wave_wlan_config_execute.sh stop $ap_index)

print2log $ap_index DEBUG "$script_name done"
timestamp $ap_index "$script_name:$ap_index:done"
