#!/bin/sh

script_name="wave_wlan_get_assoc"

[ ! "$LIB_COMMON_SOURCED" ] && . /tmp/wave_wlan_lib_common.sh
[ ! "$RC_CONF_SOURCED" ] && rc_conf_source

# Define local parameters
local ap_index interface_name
local iwlist_output i mac_index

ap_index=$1
[ -z "$ap_index" ] && print2log 0 ERROR "$script_name is missing the ap index, aborting" && return

timestamp $ap_index "$script_name:$ap_index:begin"
print2log $ap_index DEBUG "$script_name $*"

eval interface_name=\${wlmnwave_${ap_index}_interfaceName}

iwlist_output=`iwlist $interface_name peers`

i=0
mac_index=0
for mac in $iwlist_output
do
	if [ $i -lt 4 ]
	then
		i=$((i+1))
		continue
	fi
	if [ "$mac" = "range" ]
	then
		continue
	fi
	echo "mac_$mac_index=\""$mac"\""
	echo "ip_$mac_index=\"0.0.0.0\""
	echo "auth_$mac_index=\"1\""
	rate=`mtdump $interface_name PeerFlowStatus $mac -f /bin/mtdump.mtidlc_PeerFlowStat`
	rate=${rate#*unicast packets received}
	rate=`echo ${rate%% : Last*} | xargs`
	echo "rate_$mac_index=\""$rate"\""
	mac_index=$((mac_index+1))
done

echo "assoc_count=\""$mac_index"\""

print2log $ap_index DEBUG "$script_name done"
timestamp $ap_index "$script_name:$ap_index:done"
