#!/bin/sh

script_name="wave_wlan_start"

[ ! "$LIB_COMMON_SOURCED" ] && . /tmp/wave_wlan_lib_common.sh
[ ! "$RC_CONF_SOURCED" ] && rc_conf_source

# Define local parameters
local ap_index
local config_command i radio_cpe_id vendor i_ap_type features_list

ap_index=`find_index_from_wave_if wlan0`
timestamp $ap_index "$script_name:$ap_index:begin"
print2log $ap_index DEBUG "$script_name $*"

config_command=""

# Go over all the interfaces and prepare configuration files for WAVE interfaces.
i=0
while [ $i -lt $wlan_main_Count ]
do
	eval radio_cpe_id=\${wlmn_${i}_radioCpeId}
	radio_cpe_id=$((radio_cpe_id-1))
	eval vendor=\${wlss_${radio_cpe_id}_vendor}
	if [ "$vendor" = "LANTIQ" ]
	then
		eval i_ap_type=\${wlmn_${i}_apType}
		eval features_list=\${FULL_FEATURES_LIST_${i_ap_type}}
		for feature in $features_list
		do
			config_command="$config_command $feature $i"
		done
	fi
	i=$((i+1))
done

# Call the script to configure and start the interfaces.
# The "start" command is added to indicate wave_wlan_config_execute.sh that it was called by wave_wlan_start.sh
if [ -n "$config_command" ]
then
	config_command="start $config_command"
	(. $ETC_PATH/wave_wlan_config_execute.sh $config_command)
fi

# Call the script to compare between the drver, FW, progmodels version in version.sh and in driver /proc
(. $ETC_PATH/wave_wlan_check_overlay.sh $ap_index &)

print2log $ap_index DEBUG "$script_name done"
timestamp $ap_index "$script_name:$ap_index:done"
