#!/bin/sh

script_name="wave_wlan_get_ap_dyn_info"

[ ! "$LIB_COMMON_SOURCED" ] && . /tmp/wave_wlan_lib_common.sh
[ ! "$RC_CONF_SOURCED" ] && rc_conf_source

# Define local parameters
local ap_index interface_name pap_index pap_name
local status bssid radio_enabled wlan_init_incomplete ifconfig_status

ap_index=$1
[ -z "$ap_index" ] && print2log 0 ERROR "$script_name is missing the ap index, aborting" && return

timestamp $ap_index "$script_name:$ap_index:begin"
print2log $ap_index DEBUG "$script_name $*"

eval interface_name=\${wlmnwave_${ap_index}_interfaceName}
# Find parent interface name and index.
eval pap_index=\${wlmn_${ap_index}_radioCpeId}
pap_index=$((pap_index-1))
pap_name=${interface_name%%.*}

# Check if PAP radio is enabled and if the PAP is ready.
eval radio_enabled=\${wlphy_${pap_index}_radioEnable}
wlan_init_incomplete=`check_interface_is_ready $pap_name`
ifconfig_status=`ifconfig | grep $interface_name`

if [ "$radio_enabled" = "0" ] || [ "$wlan_init_incomplete" = "1" ] || [ "$ifconfig_status" = "" ]
then
	status=0
	bssid=""
else
	status=1
	bssid=`iwconfig $interface_name | grep "Access Point:" | xargs`
	bssid=${bssid#*Mode:*: }
fi
echo "status=\"$status\""
echo "bssid=\"$bssid\""

print2log $ap_index DEBUG "$script_name done"
timestamp $ap_index "$script_name:$ap_index:done"
