#!/bin/sh

script_name="wave_wlan_get_stats"

[ ! "$LIB_COMMON_SOURCED" ] && . /tmp/wave_wlan_lib_common.sh
[ ! "$RC_CONF_SOURCED" ] && rc_conf_source

# Define local parameters
local ap_index interface_name
local temp_ifconfig temp_mtdump \
bytes_sent_successfully bytes_received packets_transmitted packets_received unicast_packets_transmitted \
unicast_packets_received multicast_packets_transmitted multicast_packets_received broadcast_packets_transmitted broadcast_packets_received \
tx_errors rx_errors tx_dropped rx_dropped

ap_index=$1
[ -z "$ap_index" ] && print2log 0 ERROR "$script_name is missing the ap index, aborting" && return

timestamp $ap_index "$script_name:$ap_index:begin"
print2log $ap_index DEBUG "$script_name $*"

eval interface_name=\${wlmnwave_${ap_index}_interfaceName}

temp_ifconfig="/tmp/ifconfig_$$.log"
temp_mtdump="/tmp/mtdump_$$.log"

# Read statistics once, to temp files
ifconfig $interface_name > $temp_ifconfig
mtdump $interface_name WLANFlowStatus  -f /bin/mtdump.mtidlc_WLANFlowStatus > $temp_mtdump

# Read statistics from mtdump results
bytes_sent_successfully=`grep "Number of bytes sent successfully" $temp_mtdump | awk '{print $1}'`
bytes_received=`grep "Number of bytes received" $temp_mtdump | awk '{print $1}'`
packets_transmitted=`grep "Number of packets transmitted" $temp_mtdump | awk '{print $1}'`
packets_received=`grep "Number of packets received" $temp_mtdump | awk '{print $1}'`
unicast_packets_transmitted=`grep "Number of unicast packets transmitted" $temp_mtdump | awk '{print $1}'`
unicast_packets_received=`grep "Number of unicast packets received" $temp_mtdump | awk '{print $1}'`
multicast_packets_transmitted=`grep "Number of multicast packets transmitted" $temp_mtdump | awk '{print $1}'`
multicast_packets_received=`grep "Number of multicast packets received" $temp_mtdump | awk '{print $1}'`
broadcast_packets_transmitted=`grep "Number of broadcast packets transmitted" $temp_mtdump | awk '{print $1}'`
broadcast_packets_received=`grep "Number of broadcast packets received" $temp_mtdump | awk '{print $1}'`

# Read statistics from ifconfig results
rx_packets_line=`grep "RX packets" $temp_ifconfig | xargs`
tx_packets_line=`grep "TX packets" $temp_ifconfig | xargs`

rx_errors=${rx_packets_line#RX packets:*:}
rx_errors=${rx_errors%% *}
rx_dropped=${rx_packets_line#RX packets:*:*:}
rx_dropped=${rx_dropped%% *}
tx_errors=${tx_packets_line#TX packets:*:}
tx_errors=${tx_errors%% *}
tx_dropped=${tx_packets_line#TX packets:*:*:}
tx_dropped=${tx_dropped%% *}

echo "bytesTx=\"$bytes_sent_successfully"\"
echo "bytesRx=\"$bytes_received"\"
echo "pktsTx=\"$packets_transmitted"\"
echo "pktsRx=\"$packets_received"\"
echo "errorsTx=\"$tx_errors"\"
echo "errorsRx=\"$rx_errors"\"
echo "discardPktsTx=\"$tx_dropped"\"
echo "discardPktsRx=\"$rx_dropped"\"
echo "ucPktsTx=\"$unicast_packets_transmitted"\"
echo "ucPktsRx=\"$unicast_packets_received"\"
echo "mcPktsTx=\"$multicast_packets_transmitted"\"
echo "mcPktsRx=\"$multicast_packets_received"\"
echo "bcPktsTx=\"$broadcast_packets_transmitted"\"
echo "bcPktsRx=\"$broadcast_packets_received"\"

rm -f $temp_ifconfig
rm -f $temp_mtdump

print2log $ap_index DEBUG "$script_name done"
timestamp $ap_index "$script_name:$ap_index:done"
