#!/bin/sh

script_name="wave_wlan_vap_enable"

[ ! "$LIB_COMMON_SOURCED" ] && . /tmp/wave_wlan_lib_common.sh
[ ! "$RC_CONF_SOURCED" ] && rc_conf_source

# Define local parameters
local ap_index
local config_command features_list

ap_index=$1
[ -z "$ap_index" ] && print2log 0 ERROR "$script_name is missing the ap index, aborting" && return

timestamp $ap_index "$script_name:$ap_index:begin"
print2log $ap_index DEBUG "$script_name $*"

config_command=""
eval features_list=\${FULL_FEATURES_LIST_${VAP}}
for feature in $features_list
do
	config_command="$config_command $feature $ap_index"
done
(. $ETC_PATH/wave_wlan_config_execute.sh $config_command)

print2log $ap_index DEBUG "$script_name done"
timestamp $ap_index "$script_name:$ap_index:done"
