#define DEVICE_WIFI                                                                                                                                           1
#define DEVICE_WIFI_RADIONUMBEROFENTRIES                                                                                                                      2
#define DEVICE_WIFI_SSIDNUMBEROFENTRIES                                                                                                                       3
#define DEVICE_WIFI_ACCESSPOINTNUMBEROFENTRIES                                                                                                                4
#define DEVICE_WIFI_ENDPOINTNUMBEROFENTRIES                                                                                                                   5
#define DEVICE_WIFI_RADIO                                                                                                                                     6
#define DEVICE_WIFI_RADIO_ENABLE                                                                                                                              7
#define DEVICE_WIFI_RADIO_STATUS                                                                                                                              8
#define DEVICE_WIFI_RADIO_ALIAS                                                                                                                               9
#define DEVICE_WIFI_RADIO_NAME                                                                                                                                10
#define DEVICE_WIFI_RADIO_LASTCHANGE                                                                                                                          11
#define DEVICE_WIFI_RADIO_LOWERLAYERS                                                                                                                         12
#define DEVICE_WIFI_RADIO_UPSTREAM                                                                                                                            13
#define DEVICE_WIFI_RADIO_MAXBITRATE                                                                                                                          14
#define DEVICE_WIFI_RADIO_SUPPORTEDFREQUENCYBANDS                                                                                                             15
#define DEVICE_WIFI_RADIO_OPERATINGFREQUENCYBAND                                                                                                              16
#define DEVICE_WIFI_RADIO_SUPPORTEDSTANDARDS                                                                                                                  17
#define DEVICE_WIFI_RADIO_OPERATINGSTANDARDS                                                                                                                  18
#define DEVICE_WIFI_RADIO_POSSIBLECHANNELS                                                                                                                    19
#define DEVICE_WIFI_RADIO_CHANNELSINUSE                                                                                                                       20
#define DEVICE_WIFI_RADIO_CHANNEL                                                                                                                             21
#define DEVICE_WIFI_RADIO_AUTOCHANNELSUPPORTED                                                                                                                22
#define DEVICE_WIFI_RADIO_AUTOCHANNELENABLE                                                                                                                   23
#define DEVICE_WIFI_RADIO_AUTOCHANNELREFRESHPERIOD                                                                                                            24
#define DEVICE_WIFI_RADIO_OPERATINGCHANNELBANDWIDTH                                                                                                           25
#define DEVICE_WIFI_RADIO_EXTENSIONCHANNEL                                                                                                                    26
#define DEVICE_WIFI_RADIO_GUARDINTERVAL                                                                                                                       27
#define DEVICE_WIFI_RADIO_MCS                                                                                                                                 28
#define DEVICE_WIFI_RADIO_TRANSMITPOWERSUPPORTED                                                                                                              29
#define DEVICE_WIFI_RADIO_TRANSMITPOWER                                                                                                                       30
#define DEVICE_WIFI_RADIO_IEEE80211HSUPPORTED                                                                                                                 31
#define DEVICE_WIFI_RADIO_IEEE80211HENABLED                                                                                                                   32
#define DEVICE_WIFI_RADIO_REGULATORYDOMAIN                                                                                                                    33
#define DEVICE_WIFI_RADIO_RETRYLIMIT                                                                                                                          34
#define DEVICE_WIFI_RADIO_CCAREQUEST                                                                                                                          35
#define DEVICE_WIFI_RADIO_CCAREPORT                                                                                                                           36
#define DEVICE_WIFI_RADIO_RPIHISTOGRAMREQUEST                                                                                                                 37
#define DEVICE_WIFI_RADIO_RPIHISTOGRAMREPORT                                                                                                                  38
#define DEVICE_WIFI_RADIO_FRAGMENTATIONTHRESHOLD                                                                                                              39
#define DEVICE_WIFI_RADIO_RTSTHRESHOLD                                                                                                                        40
#define DEVICE_WIFI_RADIO_LONGRETRYLIMIT                                                                                                                      41
#define DEVICE_WIFI_RADIO_BEACONPERIOD                                                                                                                        42
#define DEVICE_WIFI_RADIO_DTIMPERIOD                                                                                                                          43
#define DEVICE_WIFI_RADIO_PACKETAGGREGATIONENABLE                                                                                                             44
#define DEVICE_WIFI_RADIO_PREAMBLETYPE                                                                                                                        45
#define DEVICE_WIFI_RADIO_BASICDATATRANSMITRATES                                                                                                              46
#define DEVICE_WIFI_RADIO_OPERATIONALDATATRANSMITRATES                                                                                                        47
#define DEVICE_WIFI_RADIO_SUPPORTEDDATATRANSMITRATES                                                                                                          48
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR                                                                                                                 49
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_MAXNUMVAPS                                                                                                      50
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_DOT11DENABLE                                                                                                    51
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_DOT11NPROTECTION                                                                                                52
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_TXRETRYLIFETIME                                                                                                 53
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_DYNAMICBANDWIDTHENABLED                                                                                         54
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEEXPLICITBEAMFORMING                                                                                         55
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEIMPLICITBEAMFORMING                                                                                         56
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_AUTOCOCENABLED                                                                                                  57
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEAUTOCOC1X1TIMERINTERVAL                                                                                     58
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEAUTOCOC2X2TIMERINTERVAL                                                                                     59
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEAUTOCOC3X3TIMERINTERVAL                                                                                     60
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEAUTOCOC4X4TIMERINTERVAL                                                                                     61
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEAUTOCOC1X1HIGHLIMIT                                                                                         62
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEAUTOCOC2X2LOWLIMIT                                                                                          63
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEAUTOCOC2X2HIGHLIMIT                                                                                         64
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEAUTOCOC3X3LOWLIMIT                                                                                          65
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEAUTOCOC3X3HIGHLIMIT                                                                                         66
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEAUTOCOC4X4LOWLIMIT                                                                                          67
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_NUMOFANTENNAS                                                                                                   68
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_COEXRSSITHRESHOLD                                                                                               69
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_COEXCHANNELSWITCHTHRESHOLD                                                                                      70
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_COEX40INTOLERANCEENABLED                                                                                        71
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_COEXSCANINTERVAL                                                                                                72
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_COEXPASSIVEDWELL                                                                                                73
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_COEXACTIVEDWELL                                                                                                 74
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_COEXPASSIVEPERCH                                                                                                75
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_COEXACTIVEPERCH                                                                                                 76
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_COEXTRANSDELAY                                                                                                  77
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_COEXACTIVITYTHRESHOLD                                                                                           78
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEPOWERCOCENABLED                                                                                             79
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEDRIVERDEBUGLEVELCONSOLE                                                                                     80
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWLOGGERSEVERITY                                                                                            81
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVERTLOGGERENABLED                                                                                             82
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFASTRECOVERYENABLED                                                                                         83
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFASTRECOVERYLIMIT                                                                                           84
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFULLRECOVERYENABLED                                                                                         85
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFULLRECOVERYLIMIT                                                                                           86
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVECOMPLETERECOVERYENABLED                                                                                     87
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVERECOVERYTIMER                                                                                               88
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEAUTORECOVERYDUMPSENABLED                                                                                    89
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVERECOVERYNUMOFDUMPS                                                                                          90
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWDEBUGENABLED                                                                                              91
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEDRIVERDEBUGLEVEL                                                                                            92
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVECONFIGURATIONDEBUGLEVEL                                                                                     93
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWDEBUGLEVEL                                                                                                94
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEHOSTAPDDEBUGLEVEL                                                                                           95
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEHALTONERRORLOG                                                                                              96
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEDRIVERSTREAMNUMBEROFENTRIES                                                                                 97
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVECONFIGURATIONSTREAMNUMBEROFENTRIES                                                                          98
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEHOSTAPDSTREAMNUMBEROFENTRIES                                                                                99
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWSTREAMNUMBEROFENTRIES                                                                                     100
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEPASSIVESCANTIME                                                                                             101
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEACTIVESCANTIME                                                                                              102
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVENUMPROBEREQS                                                                                                103
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEPROBEREQINTERVAL                                                                                            104
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEPASSIVESCANVALIDTIME                                                                                        105
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEACTIVESCANVALIDTIME                                                                                         106
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEPASSIVESCANTIMEBG                                                                                           107
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEACTIVESCANTIMEBG                                                                                            108
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVENUMPROBEREQSBG                                                                                              109
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEPROBEREQINTERVALBG                                                                                          110
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVENUMCHANSINCHUNKBG                                                                                           111
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVECHANCHUNKINTERVALBG                                                                                         112
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVESCANMODIFIER                                                                                                113
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVECHANNELWIDTHMASK24                                                                                          114
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVECHANNELWIDTHMASK5                                                                                           115
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_HTSTBCENABLED                                                                                                   116
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_HTLDPCENABLED                                                                                                   117
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_HTAMSDULEN                                                                                                      118
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_VHTMPDULEN                                                                                                      119
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_VHTLDPCENABLED                                                                                                  120
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_VHTGUARDINTERVAL                                                                                                121
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_VHTSTBCTXENABLED                                                                                                122
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_VHTSTBCRXENABLED                                                                                                123
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_VHTSUBEAMFORMERENABLED                                                                                          124
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_VHTSUBEAMFORMEEENABLED                                                                                          125
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_VHTBFANTENNA                                                                                                    126
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_VHTSOUNDINGDIMENSION                                                                                            127
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_VHTTXOPPOWERSAVEENABLED                                                                                         128
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_VHTAMPDULENEXPONENT                                                                                             129
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEACSNUMSCANS                                                                                                 130
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEACSNUMBSSCOEF                                                                                               131
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVERADARSIMULATIONCHANNELENABLED                                                                               132
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVERADARSIMULATIONCHANNEL                                                                                      133
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEDOT11HALLOWEDCHANNELS                                                                                       134
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFASTPATHENABLED                                                                                             135
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEQAMPLUS                                                                                                     136
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEOFFLINECALIBRATIONMASK                                                                                      137
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEONLINECALIBRATIONMASK                                                                                       138
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVESCRIPTSDEBUGLEVEL                                                                                           139
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVESCRIPTSDEBUGOUTPUT                                                                                          140
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVESCRIPTSPROFILINGENABLED                                                                                     141
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEPOWERCOCLIMITLOWER                                                                                          142
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEPOWERCOCLIMITUPPER                                                                                          143
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEPOWERCOCHIGH2LOW                                                                                            144
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEPOWERCOCLOW2HIGH                                                                                            145
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVETXOPMODE                                                                                                    146
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVETXOPSTAID                                                                                                   147
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEHTNUMMSDUSINAMSDU                                                                                           148
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEVHTNUMMSDUSINAMSDU                                                                                          149
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_NUMOFANTENNASSUPPORTED                                                                                          150
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEASSOCRESPRXMCSMASK                                                                                          151
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVESCANEXPIRATIONTIME                                                                                          152
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_COEXENABLED                                                                                                     153
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEIGNORE40MHZINTOLERANT                                                                                       154
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVERADARDETECTRSSITHRESHOLD                                                                                    155
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEDISABLEAHB                                                                                                  156
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEEXTERNALLYMANAGED                                                                                           157
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEACSCHANNOISEPENALTY                                                                                         158
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEACSVHTDYNAMICBW                                                                                             159
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEACSPOLICY                                                                                                   160
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEACSUPDATETIMEOUT                                                                                            161
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEMAXMPDULEN                                                                                                  162
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEBFMODE                                                                                                      163
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVERTSSIGNALINGBW                                                                                              164
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVELOGGERBRIDGENAME                                                                                            165
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEVENDORVHTENABLE                                                                                             166
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFRAUTORATE                                                                                                  167
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFRSTATIONINDEX                                                                                              168
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFRBANDWIDTH                                                                                                 169
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFRPHYMODE                                                                                                   170
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFRNSS                                                                                                       171
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFRMCS                                                                                                       172
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFRSCP                                                                                                       173
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEINTERFERERDETECTIONTHRESHOLD                                                                                174
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVECCATH                                                                                                       175
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVECCAADAPT                                                                                                    176
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEACSFALLBACKCHANNEL                                                                                          177
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVECONTROLAFILTERBANK                                                                                          178
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVECONTROLBFILTERBANK                                                                                          179
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEIRESTANDALONEENABLE                                                                                         180
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEATFENABLED                                                                                                  181
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEATFDISTRIBUTIONTYPE                                                                                         182
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEATFALGOTYPE                                                                                                 183
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEATFINTERVAL                                                                                                 184
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEATFFREETIME                                                                                                 185
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEATFVAPENABLED                                                                                               186
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEATFSTATIONENABLED                                                                                           187
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEATFRADIOSTATIONSANDWEIGHTS                                                                                  188
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEMUOPERATION                                                                                                 189
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEDRIVERSTREAM                                                                                                190
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEDRIVERSTREAM_WAVEDRIVERSTREAMNUMBER                                                                         191
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEDRIVERSTREAM_WAVEDRIVERSTREAMENABLE                                                                         192
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEDRIVERSTREAM_WAVEDRIVERREMOTEINTERFACE                                                                      193
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEDRIVERSTREAM_WAVEDRIVERDESTINATIONIP                                                                        194
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEDRIVERSTREAM_WAVEDRIVERGWIP                                                                                 195
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEDRIVERSTREAM_WAVEDRIVERDESTINATIONMACADDRESS                                                                196
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVECONFIGURATIONSTREAM                                                                                         197
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVECONFIGURATIONSTREAM_WAVECONFIGURATIONSTREAMNUMBER                                                           198
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVECONFIGURATIONSTREAM_WAVECONFIGURATIONSTREAMENABLE                                                           199
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVECONFIGURATIONSTREAM_WAVECONFIGURATIONREMOTEINTERFACE                                                        200
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVECONFIGURATIONSTREAM_WAVECONFIGURATIONDESTINATIONIP                                                          201
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVECONFIGURATIONSTREAM_WAVECONFIGURATIONDESTINATIONMACADDRESS                                                  202
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEHOSTAPDSTREAM                                                                                               203
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEHOSTAPDSTREAM_WAVEHOSTAPDSTREAMNUMBER                                                                       204
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEHOSTAPDSTREAM_WAVEHOSTAPDSTREAMENABLE                                                                       205
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEHOSTAPDSTREAM_WAVEHOSTAPDREMOTEINTERFACE                                                                    206
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEHOSTAPDSTREAM_WAVEHOSTAPDDESTINATIONIP                                                                      207
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEHOSTAPDSTREAM_WAVEHOSTAPDDESTINATIONMACADDRESS                                                              208
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWSTREAM                                                                                                    209
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWSTREAM_WAVEFWSTREAMNUMBER                                                                                 210
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWSTREAM_WAVEFWSTREAMENABLE                                                                                 211
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWSTREAM_WAVEFWREMOTEINTERFACE                                                                              212
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWSTREAM_WAVEFWDESTINATIONIP                                                                                213
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWSTREAM_WAVEFWDESTINATIONMACADDRESS                                                                        214
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWSTREAM_WAVEFWGWIP                                                                                         215
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWSTREAM_WAVEMACFIFO                                                                                        216
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWSTREAM_WAVEHOSTIFFIFO                                                                                     217
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWSTREAM_WAVERXHANDLERRISCFIFO                                                                              218
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWSTREAM_WAVEPHYGENRISCFIFO                                                                                 219
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWSTREAM_WAVEPHYHW                                                                                          220
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWSTREAM_WAVEHWFIFO1                                                                                        221
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWSTREAM_WAVEHWFIFO2                                                                                        222
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWSTREAM_WAVEHWFIFO3                                                                                        223
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWSTREAM_WAVEHWFIFO4                                                                                        224
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWSTREAM_WAVEHWFIFO5                                                                                        225
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWSTREAM_WAVEHWFIFO6                                                                                        226
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWSTREAM_WAVEHWFIFO1MODULE                                                                                  227
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWSTREAM_WAVEHWFIFO2MODULE                                                                                  228
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWSTREAM_WAVEHWFIFO3MODULE                                                                                  229
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWSTREAM_WAVEHWFIFO4MODULE                                                                                  230
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWSTREAM_WAVEHWFIFO5MODULE                                                                                  231
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WAVEFWSTREAM_WAVEHWFIFO6MODULE                                                                                  232
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WPS                                                                                                             233
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WPS_STATUS                                                                                                      234
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WPS_WPS2CONFIGMETHODSSUPPORTED                                                                                  235
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WPS_WPS2CONFIGMETHODSENABLED                                                                                    236
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WPS_PIN                                                                                                         237
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WPS_CONFIGSTATE                                                                                                 238
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WPS_AUTHORIZEDMAC                                                                                               239
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WPS_ENDPOINTPIN                                                                                                 240
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WPS_WPSACTION                                                                                                   241
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WPS_UUID                                                                                                        242
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WPS_DEVICENAME                                                                                                  243
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WPS_MANUFACTURERURL                                                                                             244
#define DEVICE_WIFI_RADIO_X_LANTIQ_COM_VENDOR_WPS_WPSDUALBANDS                                                                                                245
#define DEVICE_WIFI_RADIO_STATS                                                                                                                               246
#define DEVICE_WIFI_RADIO_STATS_BYTESSENT                                                                                                                     247
#define DEVICE_WIFI_RADIO_STATS_BYTESRECEIVED                                                                                                                 248
#define DEVICE_WIFI_RADIO_STATS_PACKETSSENT                                                                                                                   249
#define DEVICE_WIFI_RADIO_STATS_PACKETSRECEIVED                                                                                                               250
#define DEVICE_WIFI_RADIO_STATS_ERRORSSENT                                                                                                                    251
#define DEVICE_WIFI_RADIO_STATS_ERRORSRECEIVED                                                                                                                252
#define DEVICE_WIFI_RADIO_STATS_DISCARDPACKETSSENT                                                                                                            253
#define DEVICE_WIFI_RADIO_STATS_DISCARDPACKETSRECEIVED                                                                                                        254
#define DEVICE_WIFI_RADIO_STATS_PLCPERRORCOUNT                                                                                                                255
#define DEVICE_WIFI_RADIO_STATS_FCSERRORCOUNT                                                                                                                 256
#define DEVICE_WIFI_RADIO_STATS_INVALIDMACCOUNT                                                                                                               257
#define DEVICE_WIFI_RADIO_STATS_PACKETSOTHERRECEIVED                                                                                                          258
#define DEVICE_WIFI_RADIO_STATS_NOISE                                                                                                                         259
#define DEVICE_WIFI_NEIGHBORINGWIFIDIAGNOSTIC                                                                                                                 260
#define DEVICE_WIFI_NEIGHBORINGWIFIDIAGNOSTIC_DIAGNOSTICSSTATE                                                                                                261
#define DEVICE_WIFI_NEIGHBORINGWIFIDIAGNOSTIC_RESULTNUMBEROFENTRIES                                                                                           262
#define DEVICE_WIFI_NEIGHBORINGWIFIDIAGNOSTIC_RESULT                                                                                                          263
#define DEVICE_WIFI_NEIGHBORINGWIFIDIAGNOSTIC_RESULT_RADIO                                                                                                    264
#define DEVICE_WIFI_NEIGHBORINGWIFIDIAGNOSTIC_RESULT_SSID                                                                                                     265
#define DEVICE_WIFI_NEIGHBORINGWIFIDIAGNOSTIC_RESULT_BSSID                                                                                                    266
#define DEVICE_WIFI_NEIGHBORINGWIFIDIAGNOSTIC_RESULT_MODE                                                                                                     267
#define DEVICE_WIFI_NEIGHBORINGWIFIDIAGNOSTIC_RESULT_CHANNEL                                                                                                  268
#define DEVICE_WIFI_NEIGHBORINGWIFIDIAGNOSTIC_RESULT_SIGNALSTRENGTH                                                                                           269
#define DEVICE_WIFI_NEIGHBORINGWIFIDIAGNOSTIC_RESULT_SECURITYMODEENABLED                                                                                      270
#define DEVICE_WIFI_NEIGHBORINGWIFIDIAGNOSTIC_RESULT_ENCRYPTIONMODE                                                                                           271
#define DEVICE_WIFI_NEIGHBORINGWIFIDIAGNOSTIC_RESULT_OPERATINGFREQUENCYBAND                                                                                   272
#define DEVICE_WIFI_NEIGHBORINGWIFIDIAGNOSTIC_RESULT_SUPPORTEDSTANDARDS                                                                                       273
#define DEVICE_WIFI_NEIGHBORINGWIFIDIAGNOSTIC_RESULT_OPERATINGSTANDARDS                                                                                       274
#define DEVICE_WIFI_NEIGHBORINGWIFIDIAGNOSTIC_RESULT_OPERATINGCHANNELBANDWIDTH                                                                                275
#define DEVICE_WIFI_NEIGHBORINGWIFIDIAGNOSTIC_RESULT_BEACONPERIOD                                                                                             276
#define DEVICE_WIFI_NEIGHBORINGWIFIDIAGNOSTIC_RESULT_NOISE                                                                                                    277
#define DEVICE_WIFI_NEIGHBORINGWIFIDIAGNOSTIC_RESULT_BASICDATATRANSFERRATES                                                                                   278
#define DEVICE_WIFI_NEIGHBORINGWIFIDIAGNOSTIC_RESULT_SUPPORTEDDATATRANSFERRATES                                                                               279
#define DEVICE_WIFI_NEIGHBORINGWIFIDIAGNOSTIC_RESULT_DTIMPERIOD                                                                                               280
#define DEVICE_WIFI_SSID                                                                                                                                      281
#define DEVICE_WIFI_SSID_ENABLE                                                                                                                               282
#define DEVICE_WIFI_SSID_STATUS                                                                                                                               283
#define DEVICE_WIFI_SSID_ALIAS                                                                                                                                284
#define DEVICE_WIFI_SSID_NAME                                                                                                                                 285
#define DEVICE_WIFI_SSID_LASTCHANGE                                                                                                                           286
#define DEVICE_WIFI_SSID_LOWERLAYERS                                                                                                                          287
#define DEVICE_WIFI_SSID_BSSID                                                                                                                                288
#define DEVICE_WIFI_SSID_MACADDRESS                                                                                                                           289
#define DEVICE_WIFI_SSID_SSID                                                                                                                                 290
#define DEVICE_WIFI_SSID_X_LANTIQ_COM_VENDOR_BRIDGENAME                                                                                                       291
#define DEVICE_WIFI_SSID_X_LANTIQ_COM_VENDOR_SSIDTYPE                                                                                                         292
#define DEVICE_WIFI_SSID_X_LANTIQ_COM_VENDOR_ISENDPOINT                                                                                                       293
#define DEVICE_WIFI_SSID_X_LANTIQ_COM_VENDOR_WAVEATFVAPWEIGHT                                                                                                 294
#define DEVICE_WIFI_SSID_STATS                                                                                                                                295
#define DEVICE_WIFI_SSID_STATS_BYTESSENT                                                                                                                      296
#define DEVICE_WIFI_SSID_STATS_BYTESRECEIVED                                                                                                                  297
#define DEVICE_WIFI_SSID_STATS_PACKETSSENT                                                                                                                    298
#define DEVICE_WIFI_SSID_STATS_PACKETSRECEIVED                                                                                                                299
#define DEVICE_WIFI_SSID_STATS_ERRORSSENT                                                                                                                     300
#define DEVICE_WIFI_SSID_STATS_RETRANSCOUNT                                                                                                                   301
#define DEVICE_WIFI_SSID_STATS_FAILEDRETRANSCOUNT                                                                                                             302
#define DEVICE_WIFI_SSID_STATS_RETRYCOUNT                                                                                                                     303
#define DEVICE_WIFI_SSID_STATS_MULTIPLERETRYCOUNT                                                                                                             304
#define DEVICE_WIFI_SSID_STATS_ACKFAILURECOUNT                                                                                                                305
#define DEVICE_WIFI_SSID_STATS_AGGREGATEDPACKETCOUNT                                                                                                          306
#define DEVICE_WIFI_SSID_STATS_ERRORSRECEIVED                                                                                                                 307
#define DEVICE_WIFI_SSID_STATS_UNICASTPACKETSSENT                                                                                                             308
#define DEVICE_WIFI_SSID_STATS_UNICASTPACKETSRECEIVED                                                                                                         309
#define DEVICE_WIFI_SSID_STATS_DISCARDPACKETSSENT                                                                                                             310
#define DEVICE_WIFI_SSID_STATS_DISCARDPACKETSRECEIVED                                                                                                         311
#define DEVICE_WIFI_SSID_STATS_MULTICASTPACKETSSENT                                                                                                           312
#define DEVICE_WIFI_SSID_STATS_MULTICASTPACKETSRECEIVED                                                                                                       313
#define DEVICE_WIFI_SSID_STATS_BROADCASTPACKETSSENT                                                                                                           314
#define DEVICE_WIFI_SSID_STATS_BROADCASTPACKETSRECEIVED                                                                                                       315
#define DEVICE_WIFI_SSID_STATS_UNKNOWNPROTOPACKETSRECEIVED                                                                                                    316
#define DEVICE_WIFI_ACCESSPOINT                                                                                                                               317
#define DEVICE_WIFI_ACCESSPOINT_ENABLE                                                                                                                        318
#define DEVICE_WIFI_ACCESSPOINT_STATUS                                                                                                                        319
#define DEVICE_WIFI_ACCESSPOINT_ALIAS                                                                                                                         320
#define DEVICE_WIFI_ACCESSPOINT_SSIDREFERENCE                                                                                                                 321
#define DEVICE_WIFI_ACCESSPOINT_SSIDADVERTISEMENTENABLED                                                                                                      322
#define DEVICE_WIFI_ACCESSPOINT_WMMCAPABILITY                                                                                                                 323
#define DEVICE_WIFI_ACCESSPOINT_UAPSDCAPABILITY                                                                                                               324
#define DEVICE_WIFI_ACCESSPOINT_WMMENABLE                                                                                                                     325
#define DEVICE_WIFI_ACCESSPOINT_UAPSDENABLE                                                                                                                   326
#define DEVICE_WIFI_ACCESSPOINT_ASSOCIATEDDEVICENUMBEROFENTRIES                                                                                               327
#define DEVICE_WIFI_ACCESSPOINT_MAXASSOCIATEDDEVICES                                                                                                          328
#define DEVICE_WIFI_ACCESSPOINT_ISOLATIONENABLE                                                                                                               329
#define DEVICE_WIFI_ACCESSPOINT_SECURITY                                                                                                                      330
#define DEVICE_WIFI_ACCESSPOINT_SECURITY_RESET                                                                                                                331
#define DEVICE_WIFI_ACCESSPOINT_SECURITY_MODESSUPPORTED                                                                                                       332
#define DEVICE_WIFI_ACCESSPOINT_SECURITY_MODEENABLED                                                                                                          333
#define DEVICE_WIFI_ACCESSPOINT_SECURITY_WEPKEY                                                                                                               334
#define DEVICE_WIFI_ACCESSPOINT_SECURITY_PRESHAREDKEY                                                                                                         335
#define DEVICE_WIFI_ACCESSPOINT_SECURITY_KEYPASSPHRASE                                                                                                        336
#define DEVICE_WIFI_ACCESSPOINT_SECURITY_REKEYINGINTERVAL                                                                                                     337
#define DEVICE_WIFI_ACCESSPOINT_SECURITY_RADIUSSERVERIPADDR                                                                                                   338
#define DEVICE_WIFI_ACCESSPOINT_SECURITY_SECONDARYRADIUSSERVERIPADDR                                                                                          339
#define DEVICE_WIFI_ACCESSPOINT_SECURITY_RADIUSSERVERPORT                                                                                                     340
#define DEVICE_WIFI_ACCESSPOINT_SECURITY_SECONDARYRADIUSSERVERPORT                                                                                            341
#define DEVICE_WIFI_ACCESSPOINT_SECURITY_RADIUSSECRET                                                                                                         342
#define DEVICE_WIFI_ACCESSPOINT_SECURITY_SECONDARYRADIUSSECRET                                                                                                343
#define DEVICE_WIFI_ACCESSPOINT_WPS                                                                                                                           344
#define DEVICE_WIFI_ACCESSPOINT_WPS_ENABLE                                                                                                                    345
#define DEVICE_WIFI_ACCESSPOINT_WPS_CONFIGMETHODSSUPPORTED                                                                                                    346
#define DEVICE_WIFI_ACCESSPOINT_WPS_CONFIGMETHODSENABLED                                                                                                      347
#define DEVICE_WIFI_ACCESSPOINT_ASSOCIATEDDEVICE                                                                                                              348
#define DEVICE_WIFI_ACCESSPOINT_ASSOCIATEDDEVICE_MACADDRESS                                                                                                   349
#define DEVICE_WIFI_ACCESSPOINT_ASSOCIATEDDEVICE_AUTHENTICATIONSTATE                                                                                          350
#define DEVICE_WIFI_ACCESSPOINT_ASSOCIATEDDEVICE_LASTDATADOWNLINKRATE                                                                                         351
#define DEVICE_WIFI_ACCESSPOINT_ASSOCIATEDDEVICE_LASTDATAUPLINKRATE                                                                                           352
#define DEVICE_WIFI_ACCESSPOINT_ASSOCIATEDDEVICE_SIGNALSTRENGTH                                                                                               353
#define DEVICE_WIFI_ACCESSPOINT_ASSOCIATEDDEVICE_RETRANSMISSIONS                                                                                              354
#define DEVICE_WIFI_ACCESSPOINT_ASSOCIATEDDEVICE_ACTIVE                                                                                                       355
#define DEVICE_WIFI_ACCESSPOINT_ASSOCIATEDDEVICE_X_LANTIQ_COM_VENDOR_SIGNALSTRENGTH2                                                                          356
#define DEVICE_WIFI_ACCESSPOINT_ASSOCIATEDDEVICE_X_LANTIQ_COM_VENDOR_SIGNALSTRENGTH3                                                                          357
#define DEVICE_WIFI_ACCESSPOINT_ASSOCIATEDDEVICE_X_LANTIQ_COM_VENDOR_SIGNALSTRENGTH4                                                                          358
#define DEVICE_WIFI_ACCESSPOINT_ASSOCIATEDDEVICE_IPADDRESS                                                                                                    359
#define DEVICE_WIFI_ACCESSPOINT_ASSOCIATEDDEVICE_SECURITYMODE                                                                                                 360
#define DEVICE_WIFI_ACCESSPOINT_ASSOCIATEDDEVICE_STATS                                                                                                        361
#define DEVICE_WIFI_ACCESSPOINT_ASSOCIATEDDEVICE_STATS_BYTESSENT                                                                                              362
#define DEVICE_WIFI_ACCESSPOINT_ASSOCIATEDDEVICE_STATS_BYTESRECEIVED                                                                                          363
#define DEVICE_WIFI_ACCESSPOINT_ASSOCIATEDDEVICE_STATS_PACKETSSENT                                                                                            364
#define DEVICE_WIFI_ACCESSPOINT_ASSOCIATEDDEVICE_STATS_PACKETSRECEIVED                                                                                        365
#define DEVICE_WIFI_ACCESSPOINT_ASSOCIATEDDEVICE_STATS_ERRORSSENT                                                                                             366
#define DEVICE_WIFI_ACCESSPOINT_ASSOCIATEDDEVICE_STATS_RETRANSCOUNT                                                                                           367
#define DEVICE_WIFI_ACCESSPOINT_ASSOCIATEDDEVICE_STATS_FAILEDRETRANSCOUNT                                                                                     368
#define DEVICE_WIFI_ACCESSPOINT_ASSOCIATEDDEVICE_STATS_RETRYCOUNT                                                                                             369
#define DEVICE_WIFI_ACCESSPOINT_ASSOCIATEDDEVICE_STATS_MULTIPLERETRYCOUNT                                                                                     370
#define DEVICE_WIFI_ACCESSPOINT_AC                                                                                                                            371
#define DEVICE_WIFI_ACCESSPOINT_AC_ACCESSCATEGORY                                                                                                             372
#define DEVICE_WIFI_ACCESSPOINT_AC_ALIAS                                                                                                                      373
#define DEVICE_WIFI_ACCESSPOINT_AC_AIFSN                                                                                                                      374
#define DEVICE_WIFI_ACCESSPOINT_AC_ECWMIN                                                                                                                     375
#define DEVICE_WIFI_ACCESSPOINT_AC_ECWMAX                                                                                                                     376
#define DEVICE_WIFI_ACCESSPOINT_AC_TXOPMAX                                                                                                                    377
#define DEVICE_WIFI_ACCESSPOINT_AC_ACKPOLICY                                                                                                                  378
#define DEVICE_WIFI_ACCESSPOINT_AC_OUTQLENHISTOGRAMINTERVALS                                                                                                  379
#define DEVICE_WIFI_ACCESSPOINT_AC_OUTQLENHISTOGRAMSAMPLEINTERVAL                                                                                             380
#define DEVICE_WIFI_ACCESSPOINT_AC_STATS                                                                                                                      381
#define DEVICE_WIFI_ACCESSPOINT_AC_STATS_BYTESSENT                                                                                                            382
#define DEVICE_WIFI_ACCESSPOINT_AC_STATS_BYTESRECEIVED                                                                                                        383
#define DEVICE_WIFI_ACCESSPOINT_AC_STATS_PACKETSSENT                                                                                                          384
#define DEVICE_WIFI_ACCESSPOINT_AC_STATS_PACKETSRECEIVED                                                                                                      385
#define DEVICE_WIFI_ACCESSPOINT_AC_STATS_ERRORSSENT                                                                                                           386
#define DEVICE_WIFI_ACCESSPOINT_AC_STATS_ERRORSRECEIVED                                                                                                       387
#define DEVICE_WIFI_ACCESSPOINT_AC_STATS_DISCARDPACKETSSENT                                                                                                   388
#define DEVICE_WIFI_ACCESSPOINT_AC_STATS_DISCARDPACKETSRECEIVED                                                                                               389
#define DEVICE_WIFI_ACCESSPOINT_AC_STATS_RETRANSCOUNT                                                                                                         390
#define DEVICE_WIFI_ACCESSPOINT_AC_STATS_OUTQLENHISTOGRAM                                                                                                     391
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR                                                                                                           392
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_MACADDRESSCONTROLENABLED                                                                                  393
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_ALLOWEDMACADDRESS                                                                                         394
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_MACADDRESSCONTROLMODE                                                                                     395
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_MACADDRESSCONTROLLIST                                                                                     396
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_RESERVEDASSOCIATEDDEVICES                                                                                 397
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_RELIABLEMUTICASTENABLE                                                                                    398
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_PPAENABLE                                                                                                 399
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_APMAXINACTIVITY                                                                                           400
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_WAVEWDSENABLED                                                                                            401
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_WAVEWDSSECURITYMODE                                                                                       402
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_WAVEWDSKEY                                                                                                403
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_WAVEWDSPEERS                                                                                              404
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_QOSMAP                                                                                                    405
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_SENDQOSMAPFRAME                                                                                           406
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_PROXYARP                                                                                                  407
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_WAVEAMSDUENABLED                                                                                          408
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_WAVEBAAGREEMENTENABLED                                                                                    409
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_WAVEMBOENABLED                                                                                            410
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_WAVEMBOCELLAWARE                                                                                          411
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_WAVEMBORRMNEIGHBORREPORT                                                                                  412
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_WAVEMBOBSSTRANSITION                                                                                      413
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_WAVEMBOPMFBYPASS                                                                                          414
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_WAVE4ADDRESSESMODE                                                                                        415
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_WAVE4ADDRESSESSTALIST                                                                                     416
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_RRMLINKMEASUREMENT                                                                                        417
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_RRMSTASTATISTICS                                                                                          418
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_RRMCHANNELLOAD                                                                                            419
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_RRMNOISEHISTOGRAM                                                                                         420
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_RRMBEACONREPORTPASSIVE                                                                                    421
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_RRMBEACONREPORTTABLE                                                                                      422
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_WAVEATFVAPSTATIONSANDWEIGHTS                                                                              423
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_GASCOMEBACKDELAY                                                                                          424
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_SECURITY                                                                                                  425
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_SECURITY_MANAGEMENTFRAMEPROTECTION                                                                        426
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_SECURITY_SAQUERYMAXTIMEOUT                                                                                427
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_SECURITY_SAQUERYRETRYTIMEOUT                                                                              428
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_SECURITY_FASTTRANSIONSUPPORT                                                                              429
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_SECURITY_DOT11FTMOBILITYDOMAINID                                                                          430
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_SECURITY_FTOVERDS                                                                                         431
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_SECURITY_DOT11FTR0KEYLIFETIME                                                                             432
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_SECURITY_DOT11FTR1KEYHOLDERID                                                                             433
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_SECURITY_DOT11FTREASSOCIATIONDEADLINE                                                                     434
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_SECURITY_R0KHNUMBEROFENTRIES                                                                              435
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_SECURITY_R0KH1MACADDRESS                                                                                  436
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_SECURITY_NASIDENTIFIER1                                                                                   437
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_SECURITY_R0KH1KEY                                                                                         438
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_SECURITY_R0KH2MACADDRESS                                                                                  439
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_SECURITY_NASIDENTIFIER2                                                                                   440
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_SECURITY_R0KH2KEY                                                                                         441
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_SECURITY_R1KHNUMBEROFENTRIES                                                                              442
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_SECURITY_R1KH1MACADDRESS                                                                                  443
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_SECURITY_R1KH1ID                                                                                          444
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_SECURITY_R1KH1KEY                                                                                         445
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_SECURITY_R1KH2MACADDRESS                                                                                  446
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_SECURITY_R1KH2ID                                                                                          447
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_SECURITY_R1KH2KEY                                                                                         448
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_SECURITY_PMKR1PUSH                                                                                        449
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_SECURITY_INTERACCESSPOINTPROTOCOL                                                                         450
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_SECURITY_FTKEYMANAGMENT                                                                                   451
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_SECURITY_NASIDENTIFIERAP                                                                                  452
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_AC                                                                                                        453
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_AC_ACCESSCATEGORY                                                                                         454
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_AC_WAVESTAAIFSN                                                                                           455
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_AC_WAVESTAECWMIN                                                                                          456
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_AC_WAVESTAECWMAX                                                                                          457
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_AC_WAVESTATXOPMAX                                                                                         458
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20                                                                                                      459
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_ENABLE                                                                                               460
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_OSENENABLED                                                                                          461
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_DGAFDISABLED                                                                                         462
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_ANQPDOMAINID                                                                                         463
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_ACCESSNETWORKTYPE                                                                                    464
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_NETWORKAUTHENTICATIONTYPE                                                                            465
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_NETWORKAUTHENTICATIONURL                                                                             466
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_INTERNETCONNECTIVITYENABLED                                                                          467
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_DOMAINNAME                                                                                           468
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_HESSID                                                                                               469
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_IPV4ADDRESSTYPE                                                                                      470
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_IPV6ADDRESSTYPE                                                                                      471
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_THREEGPP                                                                                             472
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_OPERATINGCLASS                                                                                       473
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_VENUEGROUP                                                                                           474
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_VENUETYPE                                                                                            475
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_OSUSSID                                                                                              476
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_L2FWENABLED                                                                                          477
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_WANMETRICSDURATION                                                                                   478
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_WANPORT                                                                                              479
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_OPERATORFRIENDLYNAMENUMBEROFENTRIES                                                                  480
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_VENUENAMENUMBEROFENTRIES                                                                             481
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_ROAMINGCONSORTIUMNUMBEROFENTRIES                                                                     482
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_CONNECTIONCAPABILITYNUMBEROFENTRIES                                                                  483
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_NAIREALMNUMBEROFENTRIES                                                                              484
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_OSUICONSNUMBEROFENTRIES                                                                              485
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_OSUPROVIDERSNUMBEROFENTRIES                                                                          486
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_L2FIREWALLNUMBEROFENTRIES                                                                            487
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_WANMETRICSENABLE                                                                                     488
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_OPERATORFRIENDLYNAME                                                                                 489
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_OPERATORFRIENDLYNAME_OPERATORFRIENDLYNAME                                                            490
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_VENUENAME                                                                                            491
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_VENUENAME_VENUENAME                                                                                  492
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_ROAMINGCONSORTIUM                                                                                    493
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_ROAMINGCONSORTIUM_ROAMINGCONSORTIUM                                                                  494
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_ROAMINGCONSORTIUM_OBJINDEX                                                                           495
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_CONNECTIONCAPABILITY                                                                                 496
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_CONNECTIONCAPABILITY_PROTOCOL                                                                        497
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_CONNECTIONCAPABILITY_PORT                                                                            498
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_CONNECTIONCAPABILITY_STATUS                                                                          499
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_NAIREALM                                                                                             500
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_NAIREALM_NAIREALMNAME                                                                                501
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_NAIREALM_EAPMETHOD1                                                                                  502
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_NAIREALM_EAPMETHOD2                                                                                  503
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_WANMETRICSLINKSTATUS                                                                                 504
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_WANMETRICSSYMMETRICLINK                                                                              505
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_WANMETRICSATCAPACITY                                                                                 506
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_WANMETRICSDLSPEED                                                                                    507
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_WANMETRICSULSPEED                                                                                    508
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_WANMETRICSDLLOAD                                                                                     509
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_WANMETRICSULLOAD                                                                                     510
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_WANMETRICSLOADMEASUREMENTDURATION                                                                    511
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_OSUICONS                                                                                             512
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_OSUICONS_WIDTH                                                                                       513
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_OSUICONS_HEIGHT                                                                                      514
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_OSUICONS_LANGUAGECODE                                                                                515
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_OSUICONS_TYPE                                                                                        516
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_OSUICONS_NAME                                                                                        517
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_OSUICONS_FILEPATH                                                                                    518
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_OSUPROVIDERS                                                                                         519
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_OSUPROVIDERS_OSUPROVIDERSERVERURI                                                                    520
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_OSUPROVIDERS_OSUPROVIDERFRIENDLYNAME                                                                 521
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_OSUPROVIDERS_OSUPROVIDERFRIENDLYNAME2                                                                522
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_OSUPROVIDERS_OSUPROVIDERNAI                                                                          523
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_OSUPROVIDERS_OSUPROVIDERMETHODLIST                                                                   524
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_OSUPROVIDERS_OSUPROVIDERICON                                                                         525
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_OSUPROVIDERS_OSUPROVIDERICON2                                                                        526
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_OSUPROVIDERS_OSUPROVIDERSERVICEDESCRIPTION                                                           527
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_OSUPROVIDERS_OSUPROVIDERSERVICEDESCRIPTION2                                                          528
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_L2FIREWALL                                                                                           529
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_L2FIREWALL_ACTION                                                                                    530
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_L2FIREWALL_INGRESSINTERFACE                                                                          531
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_L2FIREWALL_EGRESSINTERFACE                                                                           532
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_L2FIREWALL_PROTOCOL                                                                                  533
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_L2FIREWALL_SOURCEMAC                                                                                 534
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_L2FIREWALL_DESTINATIONMAC                                                                            535
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_L2FIREWALL_PACKETTYPE                                                                                536
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_L2FIREWALL_SOURCEIP                                                                                  537
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_L2FIREWALL_DESTINATIONIP                                                                             538
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_L2FIREWALL_SOURCEPORT                                                                                539
#define DEVICE_WIFI_ACCESSPOINT_X_LANTIQ_COM_VENDOR_HS20_L2FIREWALL_DESTINATIONPORT                                                                           540
#define DEVICE_WIFI_ENDPOINT                                                                                                                                  541
#define DEVICE_WIFI_ENDPOINT_ENABLE                                                                                                                           542
#define DEVICE_WIFI_ENDPOINT_STATUS                                                                                                                           543
#define DEVICE_WIFI_ENDPOINT_ALIAS                                                                                                                            544
#define DEVICE_WIFI_ENDPOINT_PROFILEREFERENCE                                                                                                                 545
#define DEVICE_WIFI_ENDPOINT_SSIDREFERENCE                                                                                                                    546
#define DEVICE_WIFI_ENDPOINT_PROFILENUMBEROFENTRIES                                                                                                           547
#define DEVICE_WIFI_ENDPOINT_X_LANTIQ_COM_VENDOR_SCANSTATUS                                                                                                   548
#define DEVICE_WIFI_ENDPOINT_X_LANTIQ_COM_VENDOR_CONNECTIONSTATUS                                                                                             549
#define DEVICE_WIFI_ENDPOINT_X_LANTIQ_COM_VENDOR_WAVEENDPOINTWDS                                                                                              550
#define DEVICE_WIFI_ENDPOINT_STATS                                                                                                                            551
#define DEVICE_WIFI_ENDPOINT_STATS_LASTDATADOWNLINKRATE                                                                                                       552
#define DEVICE_WIFI_ENDPOINT_STATS_LASTDATAUPLINKRATE                                                                                                         553
#define DEVICE_WIFI_ENDPOINT_STATS_SIGNALSTRENGTH                                                                                                             554
#define DEVICE_WIFI_ENDPOINT_STATS_RETRANSMISSIONS                                                                                                            555
#define DEVICE_WIFI_ENDPOINT_SECURITY                                                                                                                         556
#define DEVICE_WIFI_ENDPOINT_SECURITY_MODESSUPPORTED                                                                                                          557
#define DEVICE_WIFI_ENDPOINT_PROFILE                                                                                                                          558
#define DEVICE_WIFI_ENDPOINT_PROFILE_ENABLE                                                                                                                   559
#define DEVICE_WIFI_ENDPOINT_PROFILE_STATUS                                                                                                                   560
#define DEVICE_WIFI_ENDPOINT_PROFILE_ALIAS                                                                                                                    561
#define DEVICE_WIFI_ENDPOINT_PROFILE_SSID                                                                                                                     562
#define DEVICE_WIFI_ENDPOINT_PROFILE_LOCATION                                                                                                                 563
#define DEVICE_WIFI_ENDPOINT_PROFILE_PRIORITY                                                                                                                 564
#define DEVICE_WIFI_ENDPOINT_PROFILE_X_LANTIQ_COM_VENDOR_BSSID                                                                                                565
#define DEVICE_WIFI_ENDPOINT_PROFILE_X_LANTIQ_COM_VENDOR_CHANNEL                                                                                              566
#define DEVICE_WIFI_ENDPOINT_PROFILE_X_LANTIQ_COM_VENDOR_SIGNALSTRENGTH                                                                                       567
#define DEVICE_WIFI_ENDPOINT_PROFILE_X_LANTIQ_COM_VENDOR_ISHIDDENSSID                                                                                         568
#define DEVICE_WIFI_ENDPOINT_PROFILE_SECURITY                                                                                                                 569
#define DEVICE_WIFI_ENDPOINT_PROFILE_SECURITY_RESET                                                                                                           570
#define DEVICE_WIFI_ENDPOINT_PROFILE_SECURITY_MODEENABLED                                                                                                     571
#define DEVICE_WIFI_ENDPOINT_PROFILE_SECURITY_WEPKEY                                                                                                          572
#define DEVICE_WIFI_ENDPOINT_PROFILE_SECURITY_PRESHAREDKEY                                                                                                    573
#define DEVICE_WIFI_ENDPOINT_PROFILE_SECURITY_KEYPASSPHRASE                                                                                                   574
#define DEVICE_WIFI_ENDPOINT_WPS                                                                                                                              575
#define DEVICE_WIFI_ENDPOINT_WPS_ENABLE                                                                                                                       576
#define DEVICE_WIFI_ENDPOINT_WPS_CONFIGMETHODSSUPPORTED                                                                                                       577
#define DEVICE_WIFI_ENDPOINT_WPS_CONFIGMETHODSENABLED                                                                                                         578
#define DEVICE_WIFI_ENDPOINT_WPS_X_LANTIQ_COM_VENDOR_WPSSTATUS                                                                                                579
#define DEVICE_WIFI_ENDPOINT_WPS_X_LANTIQ_COM_VENDOR_WPSACTION                                                                                                580
#define DEVICE_WIFI_ENDPOINT_WPS_X_LANTIQ_COM_VENDOR_ENDPOINTPIN                                                                                              581
#define DEVICE_WIFI_ENDPOINT_AC                                                                                                                               582
#define DEVICE_WIFI_ENDPOINT_AC_ACCESSCATEGORY                                                                                                                583
#define DEVICE_WIFI_ENDPOINT_AC_ALIAS                                                                                                                         584
#define DEVICE_WIFI_ENDPOINT_AC_AIFSN                                                                                                                         585
#define DEVICE_WIFI_ENDPOINT_AC_ECWMIN                                                                                                                        586
#define DEVICE_WIFI_ENDPOINT_AC_ECWMAX                                                                                                                        587
#define DEVICE_WIFI_ENDPOINT_AC_TXOPMAX                                                                                                                       588
#define DEVICE_WIFI_ENDPOINT_AC_ACKPOLICY                                                                                                                     589
#define DEVICE_WIFI_ENDPOINT_AC_OUTQLENHISTOGRAMINTERVALS                                                                                                     590
#define DEVICE_WIFI_ENDPOINT_AC_OUTQLENHISTOGRAMSAMPLEINTERVAL                                                                                                591
#define DEVICE_WIFI_ENDPOINT_AC_STATS                                                                                                                         592
#define DEVICE_WIFI_ENDPOINT_AC_STATS_BYTESSENT                                                                                                               593
#define DEVICE_WIFI_ENDPOINT_AC_STATS_BYTESRECEIVED                                                                                                           594
#define DEVICE_WIFI_ENDPOINT_AC_STATS_PACKETSSENT                                                                                                             595
#define DEVICE_WIFI_ENDPOINT_AC_STATS_PACKETSRECEIVED                                                                                                         596
#define DEVICE_WIFI_ENDPOINT_AC_STATS_ERRORSSENT                                                                                                              597
#define DEVICE_WIFI_ENDPOINT_AC_STATS_ERRORSRECEIVED                                                                                                          598
#define DEVICE_WIFI_ENDPOINT_AC_STATS_DISCARDPACKETSSENT                                                                                                      599
#define DEVICE_WIFI_ENDPOINT_AC_STATS_DISCARDPACKETSRECEIVED                                                                                                  600
#define DEVICE_WIFI_ENDPOINT_AC_STATS_RETRANSCOUNT                                                                                                            601
#define DEVICE_WIFI_ENDPOINT_AC_STATS_OUTQLENHISTOGRAM                                                                                                        602

OBJS_SUPPORTED = {
	"Device.WiFi",
	"Device.WiFi.Radio",
	"Device.WiFi.Radio.X_LANTIQ_COM_Vendor",
	"Device.WiFi.Radio.X_LANTIQ_COM_Vendor.WaveDriverStream",
	"Device.WiFi.Radio.X_LANTIQ_COM_Vendor.WaveConfigurationStream",
	"Device.WiFi.Radio.X_LANTIQ_COM_Vendor.WaveHostapdStream",
	"Device.WiFi.Radio.X_LANTIQ_COM_Vendor.WaveFwStream",
	"Device.WiFi.Radio.X_LANTIQ_COM_Vendor.WPS",
	"Device.WiFi.Radio.Stats",
	"Device.WiFi.NeighboringWiFiDiagnostic",
	"Device.WiFi.NeighboringWiFiDiagnostic.Result",
	"Device.WiFi.SSID",
	"Device.WiFi.SSID.Stats",
	"Device.WiFi.AccessPoint",
	"Device.WiFi.AccessPoint.Security",
	"Device.WiFi.AccessPoint.WPS",
	"Device.WiFi.AccessPoint.AssociatedDevice",
	"Device.WiFi.AccessPoint.AssociatedDevice.Stats",
	"Device.WiFi.AccessPoint.AC",
	"Device.WiFi.AccessPoint.AC.Stats",
	"Device.WiFi.AccessPoint.X_LANTIQ_COM_Vendor",
	"Device.WiFi.AccessPoint.X_LANTIQ_COM_Vendor.Security",
	"Device.WiFi.AccessPoint.X_LANTIQ_COM_Vendor.AC",
	"Device.WiFi.AccessPoint.X_LANTIQ_COM_Vendor.HS20",
	"Device.WiFi.AccessPoint.X_LANTIQ_COM_Vendor.HS20.OperatorFriendlyName",
	"Device.WiFi.AccessPoint.X_LANTIQ_COM_Vendor.HS20.VenueName",
	"Device.WiFi.AccessPoint.X_LANTIQ_COM_Vendor.HS20.RoamingConsortium",
	"Device.WiFi.AccessPoint.X_LANTIQ_COM_Vendor.HS20.ConnectionCapability",
	"Device.WiFi.AccessPoint.X_LANTIQ_COM_Vendor.HS20.NAIrealm",
	"Device.WiFi.AccessPoint.X_LANTIQ_COM_Vendor.HS20.OSUicons",
	"Device.WiFi.AccessPoint.X_LANTIQ_COM_Vendor.HS20.OSUproviders",
	"Device.WiFi.AccessPoint.X_LANTIQ_COM_Vendor.HS20.L2Firewall",
	"Device.WiFi.EndPoint",
	"Device.WiFi.EndPoint.Stats",
	"Device.WiFi.EndPoint.Security",
	"Device.WiFi.EndPoint.Profile",
	"Device.WiFi.EndPoint.Profile.Security",
	"Device.WiFi.EndPoint.WPS",
	"Device.WiFi.EndPoint.AC",
	"Device.WiFi.EndPoint.AC.Stats",
};