#!/bin/sh

script_name="wave_wlan_get_sta_advanced_stats"

[ ! "$LIB_COMMON_SOURCED" ] && . /tmp/wave_wlan_lib_common.sh
[ ! "$RC_CONF_SOURCED" ] && rc_conf_source

# Define local parameters
local ap_index interface_name
local sta_mac_address interface ifname_list

ap_index=$1
sta_mac_address=$2

timestamp $ap_index "$script_name:$ap_index:begin"
print2log $ap_index DEBUG "$script_name $*"

# function that prints station statistics
# [ IN ]	- wlan interface , station mac address
# [ OUT ]	- print mtdum statistics
# [ TODO ]	- Align what fields we want to add to this function
station_mtdump() {
	local interface_name sta
	interface_name=$1
	sta=$2
	
	echo "STATISTICS FOR STATION $sta, INTERFACE $interface_name"
	mtdump $interface_name PeerFlowStatus $sta
}

# function that returns all connected station
# [ IN ]	- wlan interface
# [ OUT ]	- Call to mtdump station function
echo_station_stats() {
	local sta mac_list interface_name
	interface_name=$1
	
	mac_list=`mtdump $interface_name PeerList | grep ":..:..:..:..:"`
	for sta in $mac_list
	do
		station_mtdump $interface_name $sta
	done
}

if [ -z "$ap_index" ]
then
	if [ -z "$sta_mac_address" ]
	then
		ifname_list=`ifconfig | grep wlan | awk -F " " '{print $1}'`
		for interface in $ifname_list
		do
			echo_station_stats $interface
		done
	fi
else
	eval interface_name=\${wlmnwave_${ap_index}_interfaceName}
	if [ -z "$sta_mac_address" ]
	then
		echo_station_stats $interface_name
	else
		station_mtdump $interface_name $sta_mac_address
	fi
fi

print2log $ap_index DEBUG "$script_name done"
timestamp "$script_name:$ap_index:done"
