#!/bin/sh

script_name="wave_wlan_logger_flush_buffers"

[ ! "$LIB_COMMON_SOURCED" ] && . /tmp/wave_wlan_lib_common.sh
[ ! "$RC_CONF_SOURCED" ] && rc_conf_source


timestamp 0 "$script_name:begin"
print2log 0 DEBUG "$script_name $*"

# Write to the proc the command to flush the buffers
echo LogFlushBuffers > $LOGGER_PROC

print2log 0 DEBUG "$script_name done"
timestamp 0 "$script_name:done"
