#!/bin/sh

script_name="wave_wlan_get_wps_dyn_info"

[ ! "$LIB_COMMON_SOURCED" ] && . /tmp/wave_wlan_lib_common.sh
[ ! "$RC_CONF_SOURCED" ] && rc_conf_source

# Define local parameters
local ap_index
local cpeid uuid

ap_index=$1
[ -z "$ap_index" ] && print2log 0 ERROR "$script_name is missing the ap index, aborting" && return

eval cpeid=\${wlmn_${ap_index}_cpeId}

timestamp $ap_index "$script_name:$ap_index:begin"
print2log $ap_index DEBUG "$script_name $*"

eval uuid=\${wlwps${cpeid}_0_uuid}
echo "UUID=\"$uuid\""

print2log $ap_index DEBUG "$script_name done"
timestamp "$script_name:$ap_index:done"
