#!/bin/sh

script_name="wave_wlan_wps_generate_pin"

[ ! "$LIB_COMMON_SOURCED" ] && . /tmp/wave_wlan_lib_common.sh
[ ! "$RC_CONF_SOURCED" ] && rc_conf_source

# Define local parameters
local ap_index interface_name
local cpeid wps_enable new_pin

ap_index=$1
[ -z "$ap_index" ] && print2log 0 ERROR "$script_name is missing the ap index, aborting" && return

timestamp $ap_index "$script_name:$ap_index:begin"
print2log $ap_index DEBUG "$script_name $*"

# Verify WPS is enabled before executing hostapd_cli command
eval cpeid=\${wlmn_${ap_index}_cpeId}
eval wps_enable=\${wlwps${cpeid}_0_enable}
[ "$wps_enable" = "0" ] && print2log $ap_index ERROR "$script_name can't run: WPS disabled" && return

eval interface_name=\${wlmnwave_${ap_index}_interfaceName}

new_pin=`hostapd_cli -i$interface_name wps_ap_pin random`

echo "pin=\"$new_pin\""

print2log $ap_index DEBUG "$script_name done"
timestamp $ap_index "$script_name:$ap_index:done"
