#!/bin/sh

script_name="wave_wlan_wps_trigger_pbc"

[ ! "$LIB_COMMON_SOURCED" ] && . /tmp/wave_wlan_lib_common.sh
[ ! "$LIB_WPS_SOURCED" ] && . /tmp/wave_wlan_lib_wps.sh
[ ! "$RC_CONF_SOURCED" ] && rc_conf_source

# Define local parameters
local ap_index interface_name

ap_index=$1
[ -z "$ap_index" ] && print2log 0 ERROR "$script_name is missing the ap index, aborting" && return

timestamp $ap_index "$script_name:$ap_index:begin"
print2log $ap_index DEBUG "$script_name $*"

eval interface_name=\${wlmnwave_${ap_index}_interfaceName}

print2log $ap_index WPS "The button 'Start PBC' was activated for $interface_name"
# send WPS-SESSION-START event to the WLAN events script
( . $HOSTAPD_EVENTS_SCRIPT $interface_name WPS-SESSION-START )
# Set AP to configured mode.
wps_set_ap_configured $ap_index
# Start the PBC session
$BINDIR/hostapd_cli -i $interface_name wps_pbc

print2log $ap_index DEBUG "$script_name done"
timestamp $ap_index "$script_name:$ap_index:done"
