#!/bin/sh

script_name="wave_wlan_get_radio_advanced_stats"

[ ! "$LIB_COMMON_SOURCED" ] && . /tmp/wave_wlan_lib_common.sh
[ ! "$RC_CONF_SOURCED" ] && rc_conf_source

# Define local parameters
local ap_index interface_name
local interface ifname_list

ap_index=$1

timestamp $ap_index "$script_name:$ap_index:begin"
print2log $ap_index DEBUG "$script_name $*"

# function that prints advanced radio statistics
# [ IN ]	- wlan interface
# [ OUT ]	- print mtdump statistics
# [ TODO ]	- Align what fields we want to add to this function
echo_advanced_radio_stats() {
	local interface_name
	interface_name=$1
	
	echo "STATISTICS FOR $interface_name INTERFACE"
	mtdump $interface_name HWFlowStatus
}

if [ -z "$ap_index" ]
then
		# Grep only for main interfaces
		ifname_list=`ifconfig | grep "wlan. " | awk -F " " '{print $1}'`
		for interface in $ifname_list
		do
			echo_advanced_radio_stats $interface
		done
else
	eval interface_name=\${wlmnwave_${ap_index}_interfaceName}
	echo_advanced_radio_stats $interface_name
fi

print2log $ap_index DEBUG "$script_name done"
timestamp "$script_name:$ap_index:done"
