#!/bin/sh

script_name="wave_wlan_get_wan_dyn_info"

[ ! "$LIB_COMMON_SOURCED" ] && . /tmp/wave_wlan_lib_common.sh
[ ! "$RC_CONF_SOURCED" ] && rc_conf_source

# Define local parameters
local ap_index interface_name
local wan_info

ap_index=$1
[ -z "$ap_index" ] && print2log 0 ERROR "$script_name is missing the ap index, aborting" && return

timestamp $ap_index "$script_name:$ap_index:begin"
print2log $ap_index DEBUG "$script_name $*"

eval interface_name=\${wlmnwave_${ap_index}_interfaceName}

wan_info=`$ETC_PATH/wmdctrl.sh $interface_name get`
echo "$wan_info"

print2log $ap_index DEBUG "$script_name done"
timestamp $ap_index "$script_name:$ap_index:done"
