#!/bin/sh

script_name="wave_wlan_fw_trigger_recovery"

[ ! "$LIB_COMMON_SOURCED" ] && . /tmp/wave_wlan_lib_common.sh
[ ! "$RC_CONF_SOURCED" ] && rc_conf_source

# Define local parameters
local ap_index interface_name
local time assert_type

ap_index=$1
time=$2
iteration=$3
assert_type=$4

eval interface_name=\${wlmnwave_${ap_index}_interfaceName}

# increment iteration by 1 in order to get into the loop
if [ "$iteration" = "0" ]
then
	let iteration=$iteration+1
fi
# assert_type may be missing in script call:
if [ -z $assert_type ]; then assert_type=0; fi

while [ "$iteration" -gt "0" ]
do
   sleep $time
   iwpriv $interface_name sDoFwDebug 1 $assert_type
   let iteration=$iteration-1
done 
